// The command that produces this file, since nothing here re-derives it:
//
//   nts bind-c --module c:netinet/ip --header netinet/ip.h --define _GNU_SOURCE=1 \
//     --record iphdr --alias iphdr=IpHeader \
//     --out compiler/codegen/common/test-support/native-bitfields/ip.d.ts
//
// Generated by `nts bind-c`. Edit the command, not this file.
//
// Derived from one compiler's reading of these headers under these macros,
// which makes it a claim like any hand-written binding. `native_witness.c`
// is what proves it against the headers a consumer actually compiles with.
/**
 * @ntsHeader netinet/ip.h
 * @ntsDefine _GNU_SOURCE=1
 */
declare module "c:netinet/ip" {
  import type { Bits, Struct, c_uint, c_uint16, c_uint32, c_uint8 } from "c:types";
  export type IpHeader = Struct<{
    ihl: Bits<c_uint, 4>;
    version: Bits<c_uint, 4>;
    tos: c_uint8;
    tot_len: c_uint16;
    id: c_uint16;
    frag_off: c_uint16;
    ttl: c_uint8;
    protocol: c_uint8;
    check: c_uint16;
    saddr: c_uint32;
    daddr: c_uint32;
  }, "iphdr">;
}
