// Generated by `nts bind-objc` beside the binding of `objc:AppKit`. Do not edit: regenerate.
//
// Swift's `async` imports: each method taking a completion handler, as a
// function returning a promise the handler settles, which the binding's
// `@ntsCall` overload names.
import { NSAnimationContext, NSWindow } from "objc:AppKit";
import { nts_pending_begin, nts_pending_end } from "c:pending";
import type { Int } from "objc:types";

export function nts_async_NSWindow_beginSheet(self: NSWindow, sheetWindow: NSWindow): Promise<Int> {
  return new Promise((resolve) => {
    nts_pending_begin();
    self.beginSheet(sheetWindow, (value: Int) => {
      nts_pending_end();
      resolve(value);
    });
  });
}

export function nts_async_NSWindow_beginCriticalSheet(self: NSWindow, sheetWindow: NSWindow): Promise<Int> {
  return new Promise((resolve) => {
    nts_pending_begin();
    self.beginCriticalSheet(sheetWindow, (value: Int) => {
      nts_pending_end();
      resolve(value);
    });
  });
}

export function nts_async_NSAnimationContext_runAnimationGroup(changes: (arg0: NSAnimationContext) => void): Promise<void> {
  return new Promise((resolve) => {
    nts_pending_begin();
    NSAnimationContext.runAnimationGroup(changes, () => {
      nts_pending_end();
      resolve();
    });
  });
}
