// Hand-written: the class this program defines at run time, which no header
// declares. Everything else is `appkit.d.ts`, generated by `nts bind-objc`.
declare module "objc:Controller" {
  import type { ObjcClass, ObjcMeta } from "objc:types";
  import type { NSObject, NSObjectOwnMethods } from "objc:AppKit";
  export type NtsWindowController = ObjcClass<"NtsWindowController", NSObject> & NSObjectOwnMethods;
  export interface NtsWindowControllerStatics {
    /** @ntsSelector new */
    "new"(this: NtsWindowControllerMeta): NtsWindowController;
  }
  export type NtsWindowControllerMeta = ObjcMeta<"NtsWindowController"> & NtsWindowControllerStatics;
  export const NtsWindowController: NtsWindowControllerMeta;
}
