// Hand-written: the class this program defines at run time, which no header
// declares. Everything else is `appkit.d.ts`, generated by `nts bind-objc`.
declare module "objc:Controller" {
  import { NSObject } from "objc:AppKit";
  /** @ntsClass NtsWindowController */
  export class NtsWindowController extends NSObject {}
}
