/** Generate the portable regexp database from the existing QuickJS-ng pin.
 * --check compares in memory; C is needed only when regenerating the data.
 * Delta varints, payload interning and composite string properties keep the
 * generated module small and avoid large JVM method initializers.
 */
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const upstream = resolve(packageRoot, "../c/quickjs");
const pin = "776150276b3657b90b0719755d5e111fa56a1a6d";
if (readFileSync(join(upstream, "REVISION"), "utf8").split(" ")[0] !== pin) {
  throw new Error("Unicode pin changed; review the regexp port before regenerating");
}

const scratch = mkdtempSync(join(tmpdir(), "nts-regexp-unicode-"));
let rows: string[];
try {
  const executable = join(scratch, "export");
  execFileSync(process.env.CC ?? "cc", [
    "-O2",
    join(packageRoot, "tools/unicode-export.c"),
    "-o",
    executable,
  ]);
  rows = execFileSync(executable, { encoding: "utf8", maxBuffer: 16 * 1024 * 1024 })
    .trimEnd()
    .split("\n");
} finally {
  rmSync(scratch, { recursive: true, force: true });
}

interface Table {
  kind: number;
  aliases: string;
  values: number[];
}
const tables: Table[] = [];
const sequences = new Map<string, number[][]>();
const folds: number[][] = [[], []];
for (const row of rows) {
  const fields = row.split("\t");
  if (fields[0] === "Q") {
    const name = fields[1]!;
    const entries = sequences.get(name) ?? [];
    entries.push(fields[2]!.split(",").map(Number));
    sequences.set(name, entries);
  } else if (fields[0] === "P") {
    const raw = fields[3]!.split(",").filter(Boolean).map(Number);
    const values: number[] = [];
    // QuickJS's CharRange complement covers uint32_t, not just Unicode.
    // Discard its out-of-universe intervals and clip the final endpoint.
    for (let i = 0; i < raw.length; i += 2) {
      const first = raw[i]!;
      const end = Math.min(raw[i + 1]!, 0x110000);
      if (first < end) {
        if (values.length > 0 && first <= values[values.length - 1]!) {
          values[values.length - 1] = Math.max(values[values.length - 1]!, end);
        } else values.push(first, end);
      }
    }
    for (let i = 0; i < values.length; i++) {
      if (values[i]! < 0 || values[i]! > 0x110000 || (i > 0 && values[i]! <= values[i - 1]!)) {
        throw new Error("Invalid normalized Unicode ranges: " + fields[2]);
      }
    }
    tables.push({ kind: Number(fields[1]), aliases: fields[2]!, values });
  } else if (fields[0] === "F")
    folds[Number(fields[1])]!.push(Number(fields[2]), Number(fields[3]));
}

const lines = [
  "// Generated by tools/generate-unicode.ts; do not edit.",
  `// QuickJS-ng ${pin}. MIT and Unicode License V3; see third_party/.`,
  "// Base64 unsigned varints: count, then delta ranges / absolute sequences / delta fold keys.",
];
for (const name of ["libunicode.c", "libunicode.h", "libunicode-table.h"]) {
  lines.push(
    `// ${name}: sha256 ${createHash("sha256")
      .update(readFileSync(join(upstream, name)))
      .digest("hex")}`,
  );
}

function varint(output: number[], value: number): void {
  while (value >= 128) {
    output.push((value & 127) | 128);
    value = Math.floor(value / 128);
  }
  output.push(value);
}

const payloads: string[] = [];
const storage = new Map<string, number>();
const modes: number[] = [];
const references: number[] = [];
function encoded(values: readonly number[], mode: number): void {
  const packed: number[] = [];
  varint(packed, values.length);
  let previous = 0;
  for (let i = 0; i < values.length; i++) {
    const value = values[i]!;
    const delta = mode === 1 || (mode === 2 && i % 2 === 0);
    varint(packed, delta ? value - previous : value);
    if (delta) previous = value;
  }
  const payload = Buffer.from(packed).toString("base64");
  let id = storage.get(payload);
  if (id === undefined) {
    id = payloads.length;
    storage.set(payload, id);
    payloads.push(payload);
  }
  references.push(id);
  modes.push(mode);
}

const sequenceIds: number[] = [];
let composite = -1;
for (let i = 0; i < tables.length; i++) {
  const table = tables[i]!;
  let values = table.values;
  if (table.kind === 4) {
    values = [];
    if (table.aliases === "RGI_Emoji") composite = i;
    else {
      sequenceIds.push(i);
      const entries = sequences.get(table.aliases.split(",")[0]!)!;
      const points = [
        ...new Set(
          entries.filter((sequence) => sequence.length === 1).map((sequence) => sequence[0]!),
        ),
      ].sort((a, b) => a - b);
      const ranges: number[] = [];
      for (const point of points) {
        if (ranges.length > 0 && ranges[ranges.length - 1] === point)
          ranges[ranges.length - 1] = point + 1;
        else ranges.push(point, point + 1);
      }
      values = [ranges.length, ...ranges];
      for (const sequence of entries)
        if (sequence.length !== 1) values.push(sequence.length, ...sequence);
    }
  }
  encoded(values, table.kind === 4 ? 0 : 1);
}
for (const fold of folds) encoded(fold, 2);
for (let i = 0; i < payloads.length; i++) {
  const payload = payloads[i]!;
  const chunks: string[] = [];
  for (let j = 0; j < payload.length; j += 4096)
    chunks.push(JSON.stringify(payload.slice(j, j + 4096)));
  lines.push(`function payload${i}(): string {`, `  return ${chunks.join(" +\n    ")};`, "}");
}
lines.push(
  "export function foldingId(unicode: boolean): number {",
  `  return unicode ? ${tables.length + 1} : ${tables.length};`,
  "}",
  "export function propertyParts(id: number): number[] {",
  `  return id === ${composite} ? [${sequenceIds.join(", ")}] : [id];`,
  "}",
  "export function propertyId(kind: number, name: string): number {",
);
for (let i = 0; i < tables.length; i++) {
  const table = tables[i]!;
  const tests = table.aliases
    .split(",")
    .map((alias) => `name === ${JSON.stringify(alias)}`)
    .join(" || ");
  lines.push(`  if (kind === ${table.kind} && (${tests})) return ${i};`);
}
lines.push("  return -1;", "}", "export function encodedTable(id: number): string {");
for (let i = 0; i < references.length; i++)
  lines.push(`  if (id === ${i}) return payload${references[i]}();`);
lines.push(
  '  throw new Error("Unknown internal Unicode table");',
  "}",
  "export function tableMode(id: number): number {",
  `  if (id >= ${tables.length}) return 2;`,
  `  return ${modes
    .slice(0, tables.length)
    .flatMap((mode, id) => (mode === 0 ? [`id === ${id}`] : []))
    .join(" || ")} ? 0 : 1;`,
  "}",
  "",
);
const content = lines.join("\n");
const target = join(packageRoot, "src/regexp/unicode-data.ts");
if (process.argv.includes("--check")) {
  if (readFileSync(target, "utf8") !== content) throw new Error("Unicode tables are stale");
} else writeFileSync(target, content);
console.log(
  `Unicode tables ${process.argv.includes("--check") ? "checked" : "generated"}: ${Buffer.byteLength(content)} bytes, ${payloads.length} shared payloads`,
);
