//! Assembling and serializing a class file.
//!
//! # The order the file wants and the order we can build in
//!
//! The constant pool is written first and everything after it is indices into
//! it -- but those indices only exist once the fields, methods and attributes
//! have asked for them. So the body is serialized into a buffer first, which is
//! what populates the pool, and only then is the pool written in front of it.
//!
//! # Line numbers are synthetic, and that is the design rather than a shortcut
//!
//! A `LineNumberTable` maps a bytecode offset to a line "in the source file",
//! and there is no Java source file here. RFC §21.3 answers this with
//! `SourceDebugExtension`: the class declares a synthetic line space of its
//! own, and an SMAP maps those lines back to TypeScript files and lines. So the
//! table written here numbers *distinct origins*, one line each, and
//! [`Class::lines`] hands the origins back in that order for whoever builds the
//! SMAP and the debug sidecar. Nothing here needs to read a source file.

use nts_semantic_schema::Origin;

use crate::code::{Body, Error};
use crate::frames;
use crate::pool::Pool;

pub mod access {
    pub const PUBLIC: u16 = 0x0001;
    pub const PRIVATE: u16 = 0x0002;
    pub const STATIC: u16 = 0x0008;
    pub const FINAL: u16 = 0x0010;
    /// A method the compiler generated to make a covariant override dispatch.
    /// Same bit as `ACC_VOLATILE`, which is a field flag, so the two never
    /// meet.
    pub const BRIDGE: u16 = 0x0040;
    /// On a class, and always set: without it `invokespecial` uses the pre-1.0
    /// lookup rule that no compiler has wanted since 1997.
    pub const SUPER: u16 = 0x0020;
    pub const ABSTRACT: u16 = 0x0400;
    /// Generated by a compiler and absent from any source. Debuggers and
    /// decompilers use it to decide what to show a human.
    pub const SYNTHETIC: u16 = 0x1000;
}

/// Java 8. The floor `d8` and every current JVM accept, and old enough that
/// nothing here can accidentally depend on a feature Android has not got.
pub const MAJOR_JAVA_8: u16 = 52;

/// Java 5, the last version whose verifier infers types rather than checking
/// supplied frames.
///
/// A bisection tool and not a shipping mode: when a class is rejected, emitting
/// it again at this version answers "is it the frames or the code" in one run.
/// It must never ship -- ART does not honour the old verifier, so a lane that
/// depended on this could never become Android.
pub const MAJOR_JAVA_5: u16 = 49;

#[derive(Debug, Clone)]
pub struct Field {
    pub access: u16,
    pub name: String,
    pub descriptor: String,
}

#[derive(Debug)]
pub struct Method {
    pub access: u16,
    pub name: String,
    pub descriptor: String,
    /// Absent for an abstract method, which is the only kind that has none.
    pub body: Option<Body>,
}

/// Which origin each synthetic line of one method stands for.
#[derive(Debug)]
pub struct MethodLines {
    pub name: String,
    pub descriptor: String,
    /// `origins[n]` is synthetic line `n + 1`.
    pub origins: Vec<Origin>,
}

/// A serialized class, and the debug information that describes it.
#[derive(Debug)]
pub struct Class {
    /// `nts/gen/Point` -- slashes, no `L`, no `;`.
    pub binary_name: String,
    pub bytes: Vec<u8>,
    pub lines: Vec<MethodLines>,
}

impl Class {
    /// The path this class must be written to, relative to an output root.
    #[must_use]
    pub fn path(&self) -> String {
        format!("{}.class", self.binary_name)
    }
}

#[derive(Debug)]
pub struct ClassBuilder {
    pub access: u16,
    pub name: String,
    pub super_name: String,
    pub interfaces: Vec<String>,
    pub fields: Vec<Field>,
    pub methods: Vec<Method>,
    /// What a stack trace calls this class's source.
    pub source_file: Option<String>,
    pub major: u16,
}

impl ClassBuilder {
    #[must_use]
    pub fn new(name: impl Into<String>, super_name: impl Into<String>) -> Self {
        Self {
            access: access::PUBLIC | access::SUPER,
            name: name.into(),
            super_name: super_name.into(),
            interfaces: Vec::new(),
            fields: Vec::new(),
            methods: Vec::new(),
            source_file: None,
            major: MAJOR_JAVA_8,
        }
    }

    pub fn field(&mut self, access: u16, name: impl Into<String>, descriptor: impl Into<String>) {
        self.fields.push(Field {
            access,
            name: name.into(),
            descriptor: descriptor.into(),
        });
    }

    pub fn method(&mut self, access: u16, name: impl Into<String>, descriptor: impl Into<String>, body: Option<Body>) {
        self.methods.push(Method {
            access,
            name: name.into(),
            descriptor: descriptor.into(),
            body,
        });
    }

    /// The no-argument constructor every generated class gets.
    ///
    /// Deliberately trivial. A TypeScript constructor is emitted as an ordinary
    /// method called after `new`, rather than as this one's body, because a
    /// real `<init>` puts the verifier into its `uninitializedThis` state --
    /// the most error-prone corner of the specification, and one that would
    /// otherwise reach into the stack map design. The JVM zeroes fields, which
    /// is exactly what `Func::initializes_receiver` already promises.
    pub fn default_constructor(&mut self, origin: &Origin, pool: &mut Pool) -> Result<(), Error> {
        let mut code = crate::code::Code::new(
            vec![frames::VType::Object(self.name.clone())],
            1,
        );
        code.load(origin, crate::insn::Kind::Ref, 0);
        code.invoke_special(origin, pool, &self.super_name, "<init>", "()V");
        code.ret(origin, None);
        let body = code.finish(pool)?;
        self.method(access::PUBLIC, "<init>", "()V", Some(body));
        Ok(())
    }

    /// Serialize. The pool is consumed because the indices it hands out are
    /// only meaningful inside the bytes this returns.
    pub fn build(self, mut pool: Pool) -> Result<Class, Error> {
        let mut tail = Vec::new();
        let this_index = pool.class(&self.name);
        let super_index = pool.class(&self.super_name);
        let interface_indices: Vec<u16> = self
            .interfaces
            .iter()
            .map(|name| pool.class(name))
            .collect();

        tail.extend_from_slice(&self.access.to_be_bytes());
        tail.extend_from_slice(&this_index.to_be_bytes());
        tail.extend_from_slice(&super_index.to_be_bytes());
        write_count(&mut tail, interface_indices.len());
        for index in interface_indices {
            tail.extend_from_slice(&index.to_be_bytes());
        }

        write_count(&mut tail, self.fields.len());
        for field in &self.fields {
            let name = pool.utf8(&field.name);
            let descriptor = pool.utf8(&field.descriptor);
            tail.extend_from_slice(&field.access.to_be_bytes());
            tail.extend_from_slice(&name.to_be_bytes());
            tail.extend_from_slice(&descriptor.to_be_bytes());
            write_count(&mut tail, 0); // no field attributes yet
        }

        let mut lines = Vec::with_capacity(self.methods.len());
        write_count(&mut tail, self.methods.len());
        for method in self.methods {
            let name = pool.utf8(&method.name);
            let descriptor = pool.utf8(&method.descriptor);
            tail.extend_from_slice(&method.access.to_be_bytes());
            tail.extend_from_slice(&name.to_be_bytes());
            tail.extend_from_slice(&descriptor.to_be_bytes());
            if let Some(body) = method.body {
                write_count(&mut tail, 1);
                let (attribute, origins) = code_attribute(&mut pool, &body);
                tail.extend_from_slice(&attribute);
                lines.push(MethodLines {
                    name: method.name,
                    descriptor: method.descriptor,
                    origins,
                });
            } else {
                write_count(&mut tail, 0);
            }
        }

        // Class attributes: `SourceFile`, when there is one to name.
        if let Some(file) = &self.source_file {
            write_count(&mut tail, 1);
            let name = pool.utf8("SourceFile");
            let value = pool.utf8(file);
            tail.extend_from_slice(&name.to_be_bytes());
            tail.extend_from_slice(&2u32.to_be_bytes());
            tail.extend_from_slice(&value.to_be_bytes());
        } else {
            write_count(&mut tail, 0);
        }

        if pool.overflowed() {
            return Err(Error::PoolOverflow);
        }

        let mut bytes = Vec::with_capacity(tail.len() + 256);
        bytes.extend_from_slice(&0xCAFE_BABEu32.to_be_bytes());
        bytes.extend_from_slice(&0u16.to_be_bytes()); // minor
        bytes.extend_from_slice(&self.major.to_be_bytes());
        bytes.extend_from_slice(&pool.count().to_be_bytes());
        pool.write(&mut bytes);
        bytes.extend_from_slice(&tail);

        Ok(Class {
            binary_name: self.name,
            bytes,
            lines,
        })
    }
}

fn write_count(out: &mut Vec<u8>, count: usize) {
    let count = u16::try_from(count).unwrap_or(u16::MAX);
    out.extend_from_slice(&count.to_be_bytes());
}

/// The `Code` attribute, and the origins its synthetic line numbers stand for.
fn code_attribute(pool: &mut Pool, body: &Body) -> (Vec<u8>, Vec<Origin>) {
    // Distinct origins, in first-appearance order. Consecutive instructions
    // from one source construct share a line, which is what makes a
    // LineNumberTable smaller than the instruction count and what a debugger
    // expects to see.
    let mut origins: Vec<Origin> = Vec::new();
    let mut table: Vec<(u16, u16)> = Vec::new();
    for (at, origin) in &body.origins {
        let line = if let Some(found) = origins.iter().position(|seen| seen == origin) {
            found + 1
        } else {
            origins.push(origin.clone());
            origins.len()
        };
        let line = u16::try_from(line).unwrap_or(u16::MAX);
        if table.last().is_none_or(|&(_, last)| last != line) {
            table.push((*at, line));
        }
    }

    let mut attributes = Vec::new();

    let name = pool.utf8("LineNumberTable");
    let mut line_body = Vec::new();
    write_count(&mut line_body, table.len());
    for (at, line) in &table {
        line_body.extend_from_slice(&at.to_be_bytes());
        line_body.extend_from_slice(&line.to_be_bytes());
    }
    attributes.extend_from_slice(&name.to_be_bytes());
    attributes.extend_from_slice(&u32::try_from(line_body.len()).unwrap_or(u32::MAX).to_be_bytes());
    attributes.extend_from_slice(&line_body);

    let mut attribute_count = 1;
    if let Some(frames) = frames::stack_map_table(pool, &body.locals, &body.frame_offsets) {
        let name = pool.utf8("StackMapTable");
        attributes.extend_from_slice(&name.to_be_bytes());
        attributes.extend_from_slice(&u32::try_from(frames.len()).unwrap_or(u32::MAX).to_be_bytes());
        attributes.extend_from_slice(&frames);
        attribute_count += 1;
    }

    let mut inner = Vec::new();
    inner.extend_from_slice(&body.max_stack.to_be_bytes());
    inner.extend_from_slice(&body.max_locals.to_be_bytes());
    inner.extend_from_slice(&u32::try_from(body.code.len()).unwrap_or(u32::MAX).to_be_bytes());
    inner.extend_from_slice(&body.code);
    write_count(&mut inner, 0); // exception table -- see the plan on handlers
    write_count(&mut inner, attribute_count);
    inner.extend_from_slice(&attributes);

    let name = pool.utf8("Code");
    let mut out = Vec::with_capacity(inner.len() + 6);
    out.extend_from_slice(&name.to_be_bytes());
    out.extend_from_slice(&u32::try_from(inner.len()).unwrap_or(u32::MAX).to_be_bytes());
    out.extend_from_slice(&inner);
    (out, origins)
}
