//! Every declaration a binding keeps has compiled against the real headers.
//!
//! GIR is a claim about a library, generated by a scanner that read the same
//! headers and can be wrong about them, and the mapping is a claim about GIR.
//! The build's witness would catch a wrong prototype -- but only for the
//! functions a program happens to call, and only by failing that program's
//! build. So the binder asks first: each function it would emit is declared,
//! in the compiler's own C spelling, after the headers that declare it, and
//! clang compiles the lot. Whatever clang rejects is dropped with clang's own
//! words as the reason, and the rest is asked again until nothing is rejected.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

use anyhow::{Context, Result, bail};
use nts_core::hir::native::{Pointee, Type};

use super::map::{Binding, Reason};

/// Remove from `binding` every function the headers disagree with.
pub(crate) fn against_headers(binding: &mut Binding, cflags: &[String]) -> Result<()> {
    // One directory per module, since namespaces are checked at once.
    let dir = std::env::temp_dir().join(format!(
        "nts-bind-gir-{}-{}",
        std::process::id(),
        binding.module.replace([':', '.', '-'], "_")
    ));
    std::fs::create_dir_all(&dir).with_context(|| format!("creating {}", dir.display()))?;
    let probe = dir.join(format!("{}.c", binding.module.replace([':', '.', '-'], "_")));
    // Each round drops what clang reported; a round that reports errors on no
    // declaration line has found something else wrong, and says so.
    loop {
        let (text, lines) = probe_text(binding);
        std::fs::write(&probe, &text).with_context(|| format!("writing {}", probe.display()))?;
        let output = std::process::Command::new(std::env::var("CC").unwrap_or_else(|_| "clang".to_owned()))
            .args(["-std=c11", "-fsyntax-only", "-ferror-limit=0", "-w"])
            .args(cflags)
            .arg(&probe)
            .output()
            .context("running clang on the binding's self-check")?;
        if output.status.success() {
            break;
        }
        let stderr = String::from_utf8_lossy(&output.stderr);
        let name = probe.file_name().and_then(|n| n.to_str()).unwrap_or_default();
        let declared: BTreeMap<&str, &str> =
            lines.iter().filter_map(|(n, symbol)| Some((symbol.as_str(), text_line(&text, *n)?))).collect();
        let mut rejected: BTreeMap<String, String> = BTreeMap::new();
        for line in stderr.lines() {
            // `<probe>:<line>:<col>: error: <message>`
            let Some(rest) = line.split_once(name).map(|(_, rest)| rest) else { continue };
            let mut fields = rest.trim_start_matches(':').splitn(3, ':');
            let (Some(number), _, Some(message)) = (fields.next(), fields.next(), fields.next()) else {
                continue;
            };
            let Some(message) = message.trim().strip_prefix("error:") else { continue };
            if let Some(symbol) = number.parse::<usize>().ok().and_then(|n| lines.get(&n)) {
                // Clang's words and the prototype they were about, so a
                // report line says what was declared and not only that it
                // was wrong.
                let prototype = declared.get(symbol.as_str()).copied().unwrap_or_default();
                rejected
                    .entry(symbol.clone())
                    .or_insert_with(|| format!("{} -- declared `{prototype}`", message.trim()));
            }
        }
        if rejected.is_empty() {
            bail!(
                "the self-check of `{}` failed outside any declaration, so the headers \
                 themselves did not compile with these flags:\n{stderr}",
                binding.module
            );
        }
        binding.functions.retain(|f| !rejected.contains_key(&f.name));
        binding
            .refused
            .extend(rejected.into_iter().map(|(symbol, why)| (symbol, Reason::Header(why))));
    }
    let _ = std::fs::remove_dir_all(&dir);
    Ok(())
}

/// The probe, and which function each of its lines declares.
fn probe_text(binding: &Binding) -> (String, BTreeMap<usize, String>) {
    let mut out = String::new();
    for header in &binding.headers {
        let _ = writeln!(out, "#include <{header}>");
    }
    // Every tag a prototype names, declared first: a tag first seen inside a
    // parameter list is scoped to it and would name a different struct.
    let mut tags = BTreeSet::new();
    for function in &binding.functions {
        for ty in function.c_parameters.iter().chain(std::iter::once(&function.result.c)) {
            collect_tags(ty, &mut tags);
        }
    }
    for tag in &tags {
        let _ = writeln!(out, "struct {tag};");
    }
    let mut lines = BTreeMap::new();
    for function in &binding.functions {
        let parameters = if function.c_parameters.is_empty() {
            "void".to_owned()
        } else {
            function.c_parameters.iter().map(Type::c_type_expanded).collect::<Vec<_>>().join(", ")
        };
        // The declarator in parentheses, as the build's witness writes it: a
        // header may define the function as a function-like macro too --
        // GLib's `g_free` -- which a bare `g_free(` would expand.
        let _ = writeln!(
            out,
            "extern {} ({})({parameters});",
            function.result.c.c_type_expanded(),
            function.symbol
        );
        lines.insert(out.lines().count(), function.name.clone());
    }
    (out, lines)
}

fn collect_tags(ty: &Type, into: &mut BTreeSet<String>) {
    match ty {
        Type::Pointer(pointee) => collect_pointee(pointee, into),
        Type::FnPointer(signature) => {
            for ty in signature.parameters.iter().chain(std::iter::once(&*signature.result)) {
                collect_tags(ty, into);
            }
        }
        _ => {}
    }
}

fn collect_pointee(pointee: &Pointee, into: &mut BTreeSet<String>) {
    match pointee {
        Pointee::Opaque(handle) => {
            into.insert(handle.tag.clone());
        }
        Pointee::Const(inner) | Pointee::Pointer(inner) => collect_pointee(inner, into),
        _ => {}
    }
}

/// The probe's `number`th line, counting from one as clang does.
fn text_line(text: &str, number: usize) -> Option<&str> {
    text.lines().nth(number.checked_sub(1)?)
}
