//! A [`Binding`] as text: the `.d.ts` module, and the `.ts` companion with
//! the values a declaration file cannot carry.

use std::fmt::Write;

use super::map::{Binding, Function, Mapped, Shape, TypeDecl};

/// The module's head: what wrote it, its headers, and the types it imports.
fn preamble(binding: &Binding, command: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// Generated by `{command}`. Edit the command, not this file.");
    out.push_str(
        "//\n\
         // Read from GObject introspection data, with every declaration compiled\n\
         // against the headers below before it was written. `c:type` decides the\n\
         // C spelling; GIR's annotations decide ownership, nullability and which\n\
         // parameters carry a callback's context.\n",
    );
    out.push_str("/**\n");
    for header in &binding.headers {
        let _ = writeln!(out, " * @ntsHeader {header}");
    }
    out.push_str(" */\n");
    let _ = writeln!(out, "declare module \"{}\" {{", binding.module);
    if !binding.brands.is_empty() {
        let _ = writeln!(
            out,
            "  import type {{ {} }} from \"c:types\";",
            binding.brands.iter().copied().collect::<Vec<_>>().join(", ")
        );
    }
    for (module, names) in &binding.imports {
        let _ = writeln!(
            out,
            "  import type {{ {} }} from \"{module}\";",
            names.iter().cloned().collect::<Vec<_>>().join(", ")
        );
    }
    out
}

/// The declaration module: types, then functions, in a stable order.
#[must_use]
pub(crate) fn declarations(binding: &Binding, command: &str) -> String {
    let mut out = preamble(binding, command);
    out.push('\n');
    enums(&mut out, binding);
    // The methods of each class, from the functions the self-check kept.
    let promises: std::collections::BTreeMap<&str, &Function> =
        promise_forms(binding).into_iter().map(|(start, finish)| (start.symbol.as_str(), finish)).collect();
    let outs: std::collections::BTreeSet<&str> = values_forms(binding).into_iter().map(|f| f.symbol.as_str()).collect();
    let mut methods: std::collections::BTreeMap<&str, Vec<&Function>> = std::collections::BTreeMap::new();
    for function in &binding.functions {
        if let Some((class, _)) = &function.method {
            methods.entry(class.as_str()).or_default().push(function);
        }
    }
    for decl in &binding.types {
        match decl {
            TypeDecl::Class { name, tag, parent, counted, interface, implements, boxed } => {
                let class = if *counted { "GObjectClass" } else { "Class" };
                // `button.set_label(text)`: each method is the C function it
                // names, with the receiver as its `this`. Intersected rather
                // than extended, so a subclass method that shares a name with
                // an ancestor's is an overload and not a conflicting redeclaration.
                let _ = writeln!(out, "  export interface {name}OwnMethods {{");
                let own: Vec<&Function> = methods.get(name.as_str()).into_iter().flatten().copied().collect();
                for function in &own {
                    if outs.contains(function.symbol.as_str()) {
                        values_method(&mut out, function);
                    }
                    method(&mut out, function);
                    if let Some(finish) = promises.get(function.symbol.as_str()) {
                        promise_method(&mut out, function, finish);
                    }
                }
                for property in binding.properties.get(name.as_str()).into_iter().flatten() {
                    accessor(&mut out, &own, &property.name, property.getter.as_deref(), property.setter.as_deref());
                }
                out.push_str("  }\n");
                // An interface's methods are its implementers' too:
                // `entry.get_text()` is `gtk_editable_get_text`.
                let merged = implements.iter().fold(String::new(), |mut merged, (interface, _)| {
                    let _ = write!(merged, " & {interface}Methods");
                    merged
                });
                let tags = implements.iter().map(|(_, tag)| format!("\"{tag}\"")).collect::<Vec<_>>().join(" | ");
                if let Some((_, parent)) = parent {
                    let _ = writeln!(out, "  export type {name}Methods = {name}OwnMethods & {parent}Methods{merged};");
                    if *interface && implements.is_empty() {
                        let _ = writeln!(out, "  export type {name} = GObjectInterface<\"{tag}\", {parent}> & {name}Methods;");
                    } else if *interface {
                        let _ = writeln!(out, "  export type {name} = GObjectInterface<\"{tag}\", {parent}, {tags}> & {name}Methods;");
                    } else if implements.is_empty() {
                        let _ = writeln!(out, "  export type {name} = {class}<\"{tag}\", {parent}> & {name}Methods;");
                    } else {
                        let _ = writeln!(out, "  export type {name} = {class}<\"{tag}\", {parent}, {tags}> & {name}Methods;");
                    }
                } else if !implements.is_empty() {
                    let _ = writeln!(out, "  export type {name}Methods = {name}OwnMethods{merged};");
                    let _ = writeln!(out, "  export type {name} = {class}<\"{tag}\", null, {tags}> & {name}Methods;");
                } else if let Some((get_type, size)) = boxed {
                    // A boxed record: held in a box of the program's, freed
                    // by its `GType`; `new GtkTextIter()` makes a zeroed one.
                    let _ = writeln!(out, "  export type {name}Methods = {name}OwnMethods;");
                    let _ = writeln!(out, "  export type {name} = Boxed<\"{tag}\", \"{get_type}\", {size}> & {name}Methods;");
                    boxed_value(&mut out, binding, name, *size);
                    continue;
                } else {
                    let _ = writeln!(out, "  export type {name}Methods = {name}OwnMethods;");
                    let _ = writeln!(out, "  export type {name} = {class}<\"{tag}\"> & {name}Methods;");
                }
                // A GObject class a program may subclass: its `GType`'s
                // function, which the subclass registers under.
                let gtype = (*counted && !*interface)
                    .then(|| binding.casts.iter().find(|cast| cast.class == *name).map(|cast| cast.get_type.as_str()))
                    .flatten();
                construction(&mut out, binding, &own, name, parent.as_ref().map(|(_, parent)| parent.as_str()), implements, gtype);
            }
        }
    }
    out.push('\n');
    for function in binding.functions.iter().filter(|function| !function.method_only) {
        let defaulted = defaults(function, &function.parameters);
        notes(&mut out, function, function.name != function.symbol, &defaulted, "  ");
        let parameters = function
            .parameters
            .iter()
            .map(|(name, mapped)| parameter(function, &defaulted, name, &mapped.ts))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(
            out,
            "  export function {}({parameters}): {};",
            function.name, function.result.ts
        );
    }
    out.push_str("}\n");
    out
}

/// A property of the class's methods, read and written through the methods
/// GIR names for it (`@ntsGet`/`@ntsSet`), where the self-check kept them:
/// `label.label = "Hi"`. Typed by what the getter returns; the setter joins
/// only where it takes exactly that, since a getter answering `string | null`
/// beside a setter taking `string` would let `null` be assigned -- such a
/// property is read-only, and `set_label` is still there. Its `@ntsSet` stays:
/// `new GtkButton({ label })` writes it through the setter at the setter's own
/// type, which `readonly` does not stop and should not. A property whose
/// name a method of the class already has, or that no kept method serves, is
/// left out.
fn accessor(out: &mut String, own: &[&Function], property: &str, getter: Option<&str>, setter: Option<&str>) {
    let Some(Decided { ts, get, set, assignable }) = decide(own, property, getter, setter) else { return };
    let mut tags = Vec::new();
    if let Some((_, name)) = get.and_then(|f| f.method.as_ref()) {
        tags.push(format!("@ntsGet {name}"));
    }
    if let Some((_, name)) = set.and_then(|f| f.method.as_ref()) {
        tags.push(format!("@ntsSet {name}"));
    }
    let _ = writeln!(out, "    /**");
    for tag in tags {
        let _ = writeln!(out, "     * {tag}");
    }
    let _ = writeln!(out, "     */");
    let readonly = if assignable { "" } else { "readonly " };
    let _ = writeln!(out, "    {readonly}{property}: {ts};");
}

/// What a property is on its class, once its methods are known: its type, the
/// methods it is read and written through, and whether an assignment may write
/// it -- only where the setter takes what the getter answers. `None` where it
/// is left out.
struct Decided<'f> {
    ts: String,
    get: Option<&'f Function>,
    set: Option<&'f Function>,
    assignable: bool,
}

fn decide<'f>(own: &[&'f Function], property: &str, getter: Option<&str>, setter: Option<&str>) -> Option<Decided<'f>> {
    if own_method(own, Some(property)).is_some() {
        return None;
    }
    let get = own_method(own, getter)
        .filter(|f| f.parameters.len() == 1 && f.result.ts != "void" && f.throws.is_none());
    let set = settable(own, property, setter);
    let (ts, assignable) = match (get, set) {
        (Some(get), Some(set)) => (get.result.ts.clone(), set.parameters[1].1.ts == get.result.ts),
        (Some(get), None) => (get.result.ts.clone(), false),
        (None, Some(set)) => (set.parameters[1].1.ts.clone(), true),
        (None, None) => return None,
    };
    Some(Decided { ts, get, set, assignable })
}

/// The method a property is written through, where there is one a plain
/// assignment can call: it takes the instance and the value, answers nothing
/// and throws nothing, and no method of the class takes the property's name.
fn settable<'f>(own: &[&'f Function], property: &str, setter: Option<&str>) -> Option<&'f Function> {
    if own_method(own, Some(property)).is_some() {
        return None;
    }
    own_method(own, setter).filter(|f| f.parameters.len() == 2 && f.result.ts == "void" && f.throws.is_none())
}

fn own_method<'f>(own: &[&'f Function], method: Option<&str>) -> Option<&'f Function> {
    let method = method?;
    own.iter().copied().find(|f| f.method.as_ref().is_some_and(|(_, name)| name == method))
}

/// GJS's construction: `…Props`, the class's writable properties -- each
/// optional, typed as its setter takes it -- extending the parent's; and a
/// value of the class's name to construct it with, `new GtkButton({ label })`,
/// which makes one with every property at its default and then calls the
/// setter of each property the literal writes (`@ntsConstruct`). It is made
/// by the class's `new` where that takes nothing, and by its `GType` through
/// `g_object_new_with_properties` otherwise (`GtkLabel_construct`). An
/// abstract class, or one whose constructor the self-check refused, has the
/// interface and not the value.
fn construction(
    out: &mut String,
    binding: &Binding,
    own: &[&Function],
    name: &str,
    parent: Option<&str>,
    implements: &[(String, String)],
    gtype: Option<&str>,
) {
    // The parent's, and each implemented interface's: `new GtkBox({
    // orientation })` sets `GtkOrientable`'s.
    let bases: Vec<String> = parent
        .into_iter()
        .map(str::to_owned)
        .chain(implements.iter().map(|(interface, _)| interface.clone()))
        .map(|base| format!("{base}Props"))
        .collect();
    let extends = if bases.is_empty() { String::new() } else { format!(" extends {}", bases.join(", ")) };
    let _ = writeln!(out, "  export interface {name}Props{extends} {{");
    // A root's one member, which nothing sets: an interface with none accepts
    // any object literal, so `new GListStore({ item_type })` -- a property no
    // setter writes -- typechecked and was refused only by lowering. With it
    // every `…Props` in the chain has a member, and an unknown key is the
    // checker's error.
    if bases.is_empty() {
        out.push_str("    readonly __c_props?: never;\n");
    }
    // What the constructor takes, required, at its parameter's type; and
    // every other property a setter writes, optional.
    let constructor = binding.constructors.get(name);
    let from = constructor.map(|c| c.from.as_slice()).unwrap_or_default();
    let taking = constructor.and_then(|c| binding.functions.iter().find(|f| f.name == c.function));
    if let Some(taking) = taking {
        for property in from {
            if let Some((_, mapped)) = taking.parameters.iter().find(|(given, _)| given == property) {
                let _ = writeln!(out, "    {property}: {};", mapped.ts);
            }
        }
    }
    for property in binding.properties.get(name).into_iter().flatten() {
        if from.contains(&property.name) {
            continue;
        }
        let Some(set) = settable(own, &property.name, property.setter.as_deref()) else { continue };
        // **A nullable property is given or not.** Absent is the NULL a
        // construction starts from, so its props type has no `| null`: a
        // subclass that redeclares a property as nullable (`AdwPreferencesPage`
        // `name`, a `string` on `GtkWidget`) then still extends its parent's
        // props, which TypeScript otherwise refuses (TS2430) -- and a handle
        // beside both absences has no representation. Tagged, so the folded
        // set can be counted and undone.
        let ts = &set.parameters[1].1.ts;
        let ts = match ts.strip_suffix(" | null") {
            Some(given) => {
                let _ = writeln!(
                    out,
                    "    /**\n     * @ntsNullable GIR's `{}` is nullable, and absent is the NULL a construction starts from.\n     * So a props object cannot clear it to NULL: it is for construction only.\n     */",
                    property.name
                );
                given
            }
            None => ts.as_str(),
        };
        let _ = writeln!(out, "    {}?: {ts};", property.name);
    }
    out.push_str("  }\n");
    let kept = |function: &str| binding.functions.iter().find(|f| f.name == function && f.throws.is_none());
    let construct = binding.constructors.get(name).and_then(|constructor| {
        let tag = match (kept(&constructor.function), &constructor.get_type) {
            (Some(_), None) if !constructor.from.is_empty() => format!("{}({})", constructor.function, constructor.from.join(", ")),
            (Some(new), None) if new.parameters.is_empty() => constructor.function.clone(),
            (Some(_), Some(get_type)) if kept(get_type).is_some() => format!("{} {get_type}", constructor.function),
            _ => return None,
        };
        let optional = if constructor.from.is_empty() { "?" } else { "" };
        let (generic, made) = made_by(name, gtype.is_some());
        Some(format!("    /**\n     * @ntsConstruct {tag}\n     */\n    new {generic}(props{optional}: {name}Props): {made};\n"))
    });
    // The class's constructors and functions, as GJS has them on the class:
    // `GtkStringObject.new("x")`, `GtkButton.new_with_label("Add")`.
    let statics: Vec<&Function> = binding
        .functions
        .iter()
        .filter(|f| f.statics.as_ref().is_some_and(|(class, _)| class == name))
        .collect();
    if construct.is_none() && statics.is_empty() && gtype.is_none() {
        return;
    }
    // `class Counter extends GtkButton`: the value names the class's `GType`
    // function (`@ntsGType`) on a phantom member, whose declaration carries
    // the tag where a `const` could not -- and a class with no construct
    // signature of its own (`GtkWidget`, abstract) gets an abstract one, so it
    // can be extended and still not constructed.
    let abstract_construct = if construct.is_none() && gtype.is_some() {
        let (generic, made) = made_by(name, true);
        format!("(abstract new {generic}(props?: {name}Props) => {made}) & ")
    } else {
        String::new()
    };
    let _ = writeln!(out, "  export const {name}: {abstract_construct}{{");
    if let Some(gtype) = gtype {
        let _ = writeln!(out, "    /**\n     * @ntsGType {gtype}\n     */\n    readonly __c_gtype?: never;");
        // GJS's name for the class's `GType`, which a class the program
        // writes over this one inherits as a static: `Task.$gtype` for a
        // `GListStore`'s `item_type`. The compiler answers it with the
        // `GType` function of the class it is read from.
        out.push_str("    readonly $gtype: c_size_t;\n");
    }
    out.push_str(construct.as_deref().unwrap_or_default());
    for function in statics {
        static_member(out, function);
    }
    out.push_str("  };\n");
}

/// What a `GObject` class's `new` makes: generic in the signals a subclass the
/// program writes declares (`extends GtkButton<{ incremented: [by: number] }>`,
/// see `Signalled` in `c:types`), and the class itself for anything else.
fn made_by(name: &str, gobject: bool) -> (&'static str, String) {
    if gobject {
        ("<Sig extends SignalMap = {}>", format!("Signalled<{name}, Sig>"))
    } else {
        ("", name.to_owned())
    }
}

/// A boxed record's value: `new GtkTextIter()`, a zeroed record of the
/// headers' size for C to fill (the compiler allocates it by the record's
/// `GType`), and the record's constructors and functions as statics, as a
/// class's are. No `new` for a record the headers keep opaque.
fn boxed_value(out: &mut String, binding: &Binding, name: &str, size: u64) {
    let statics: Vec<&Function> =
        binding.functions.iter().filter(|f| f.statics.as_ref().is_some_and(|(class, _)| class == name)).collect();
    if size == 0 && statics.is_empty() {
        return;
    }
    let _ = writeln!(out, "  export const {name}: {{");
    if size > 0 {
        let _ = writeln!(out, "    new (): {name};");
    }
    for function in statics {
        static_member(out, function);
    }
    out.push_str("  };\n");
}

/// A constructor or function of a class as a member of the class's value.
/// `new` is quoted, since a bare `new(…)` in a type is a construct signature.
fn static_member(out: &mut String, function: &Function) {
    let Some((_, name)) = &function.statics else { return };
    let defaulted = defaults(function, &function.parameters);
    notes(out, function, true, &defaulted, "    ");
    let parameters: Vec<String> =
        function.parameters.iter().map(|(given, mapped)| parameter(function, &defaulted, given, &mapped.ts)).collect();
    let name = if name == "new" { "\"new\"".to_owned() } else { name.clone() };
    let _ = writeln!(out, "    {name}({}): {};", parameters.join(", "), function.result.ts);
}

/// A function as a method of its class: `this` is its instance.
fn method(out: &mut String, function: &Function) {
    let Some((_, name)) = &function.method else { return };
    let defaulted = defaults(function, &function.parameters);
    let mut parameters = function.parameters.iter();
    let Some((_, instance)) = parameters.next() else { return };
    notes(out, function, true, &defaulted, "    ");
    let rest: Vec<String> =
        parameters.map(|(name, mapped)| parameter(function, &defaulted, name, &mapped.ts)).collect();
    let this = std::iter::once(format!("this: {}", instance.ts)).chain(rest).collect::<Vec<_>>().join(", ");
    let _ = writeln!(out, "    {name}({this}): {};", function.result.ts);
}

/// The `_async` methods with a `_finish` that reads only their result: each
/// pair a Promise can be made of. Only from functions the self-check kept,
/// and only where the `_async` ends in its `OnceClosure` and the `_finish`
/// takes the instance and the `GAsyncResult` -- and at most the error slot --
/// so that the Promise settles with exactly what the `_finish` returns.
pub(crate) fn promise_forms(binding: &Binding) -> Vec<(&Function, &Function)> {
    binding
        .functions
        .iter()
        .filter(|start| start.vfunc.is_none())
        .filter_map(|start| {
            let (class, _) = start.method.as_ref()?;
            let finish_name = start.finish.as_ref()?;
            let (_, callback) = start.parameters.last()?;
            if callback.shape != Shape::Once {
                return None;
            }
            let finish = binding
                .functions
                .iter()
                .find(|f| f.method.as_ref().is_some_and(|(c, n)| c == class && n == finish_name))?;
            (read(finish) == 2 && settles(&finish.result)).then_some((start, finish))
        })
        .collect()
}

/// The methods whose out parameters a GJS-style form returns instead of
/// taking: `const [width, height] = widget.get_size_request()`. Every slot
/// the caller would pass is a scalar one ([`Shape::Out`]) -- a string or a
/// handle read out of a slot has an ownership a number does not -- and the
/// error slot, if any, is last, so leaving it out of the call throws.
pub(crate) fn values_forms(binding: &Binding) -> Vec<&Function> {
    binding
        .functions
        .iter()
        .filter(|function| {
            function.method.is_some()
                && function.vfunc.is_none()
                && function.parameters.iter().any(|(_, mapped)| matches!(mapped.shape, Shape::Out { .. } | Shape::Filled { .. }))
                && function.parameters.iter().all(|(name, mapped)| {
                    function.throws.as_deref() == Some(name.as_str())
                        || matches!(mapped.shape, Shape::Out { .. } | Shape::Filled { .. } | Shape::Handle { .. } | Shape::Lent { .. })
                        || (mapped.shape == Shape::Other && !mapped.ts.starts_with("Ptr<") && !mapped.ts.contains("Closure<"))
                })
                && function.throws.as_ref().is_none_or(|slot| function.parameters.last().is_some_and(|(name, _)| name == slot))
        })
        .collect()
}

/// What a values form returns: the function's own result, if it has one,
/// then each out value, in order -- GJS's shape -- and a lone value unwrapped.
fn values_result(function: &Function) -> String {
    let result = (function.result.ts != "void").then(|| function.result.ts.clone());
    let values: Vec<String> = result
        .into_iter()
        .chain(function.parameters.iter().filter_map(|(_, mapped)| match &mapped.shape {
            Shape::Out { value } => Some(value.clone()),
            Shape::Filled { class } => Some(class.clone()),
            _ => None,
        }))
        .collect();
    if values.len() == 1 { values[0].clone() } else { format!("[{}]", values.join(", ")) }
}

/// The parameters a values form takes: all but the out slots, the storage it
/// makes, and the error slot.
fn values_taken(function: &Function) -> Vec<(String, Mapped)> {
    function
        .parameters
        .iter()
        .filter(|(name, mapped)| {
            !matches!(mapped.shape, Shape::Out { .. } | Shape::Filled { .. }) && function.throws.as_deref() != Some(name.as_str())
        })
        .cloned()
        .collect()
}

/// The overload of a method that returns its out values, bodied by the
/// wrapper `values_wrapper` writes (`@ntsCall`). Declared before the method,
/// so a call leaving every slot out resolves to it.
fn values_method(out: &mut String, function: &Function) {
    let Some((_, name)) = &function.method else { return };
    let taken = values_taken(function);
    let defaulted = defaults(function, &taken);
    let mut parameters = taken.iter();
    let Some((_, instance)) = parameters.next() else { return };
    let rest: Vec<String> = parameters.map(|(name, mapped)| parameter(function, &defaulted, name, &mapped.ts)).collect();
    let this = std::iter::once(format!("this: {}", instance.ts)).chain(rest).collect::<Vec<_>>().join(", ");
    let _ = writeln!(out, "    /**\n     * @ntsCall {}_values\n     */", function.symbol);
    let _ = writeln!(out, "    {name}({this}): {};", values_result(function));
}

/// The parameters a promise's `_finish` call has to write: all but the error
/// slot, which a leaving-out throws, and the trailing ones the binding
/// defaults -- `etag_out` on every GIO `_finish`. Two is the instance and the
/// result.
fn read(finish: &Function) -> usize {
    let defaulted = defaults(finish, &finish.parameters);
    finish
        .parameters
        .iter()
        .filter(|(name, _)| finish.throws.as_deref() != Some(name.as_str()) && !defaulted.iter().any(|(given, _)| given == name))
        .count()
}

/// Every `_async` method the binding kept, and whether it has a Promise form
/// -- and if not, why not. An absent overload fails nothing, so the ones
/// without one are counted here rather than left to be found by a call that
/// does not typecheck: the before-number for whatever makes them possible.
pub(crate) fn promise_census(binding: &Binding) -> Vec<(String, &'static str)> {
    let made: std::collections::BTreeSet<&str> = promise_forms(binding).into_iter().map(|(start, _)| start.symbol.as_str()).collect();
    binding
        .functions
        .iter()
        .filter(|start| {
            start.method.is_some()
                && start.finish.is_some()
                && start.parameters.last().is_some_and(|(_, callback)| callback.shape == Shape::Once)
        })
        .map(|start| {
            let outcome = if made.contains(start.symbol.as_str()) {
                "promise"
            } else {
                why_no_promise(binding, start)
            };
            (start.symbol.clone(), outcome)
        })
        .collect()
}

/// Why an `_async` method has no Promise form.
fn why_no_promise(binding: &Binding, start: &Function) -> &'static str {
    let (class, _) = start.method.as_ref().expect("a method");
    let finish_name = start.finish.as_ref().expect("a finish");
    let Some(finish) = binding
        .functions
        .iter()
        .find(|f| f.method.as_ref().is_some_and(|(c, n)| c == class && n == finish_name))
    else {
        return "no Promise form: its `_finish` is not bound";
    };
    if read(finish) != 2 {
        return "no Promise form: its `_finish` takes more than the result";
    }
    match &finish.result.c {
        nts_core::hir::native::Type::Scalar(_) => "no Promise form: its `_finish` returns a 64-bit integer",
        nts_core::hir::native::Type::Pointer(_) => "no Promise form: its `_finish` returns an untyped pointer",
        _ => "no Promise form: its `_finish` returns what a promise cannot carry",
    }
}

/// Whether a promise can carry what a `_finish` returns: nothing, a number,
/// a boolean, a string, or a handle -- which the promise holds in a slot of
/// its own, outside its value. Not a 64-bit integer, which a number cannot
/// hold; those `_async` methods keep only their callback form.
fn settles(result: &super::map::Mapped) -> bool {
    use nts_core::hir::native::{Pointee, Type};
    match &result.c {
        Type::Void | Type::Bool | Type::Pointer(_) if !matches!(result.c, Type::Pointer(Pointee::Void)) => true,
        // A number the program reads as a `number` (`CNumber`), whatever C's
        // width; not a `bigint`, which a promise's payload cannot carry.
        Type::Scalar(scalar) => !scalar.needs_exact_integer() || result.ts.starts_with("CNumber<"),
        _ => false,
    }
}

/// An `_async` method's Promise form: the same method without its callback,
/// answering what the `_finish` returns -- `await file.query_info_async(…)`.
/// An overload of the C one, told apart by arity, and bodied by the wrapper
/// the companion module defines (`@ntsCall`).
fn promise_method(out: &mut String, start: &Function, finish: &Function) {
    let Some((_, name)) = &start.method else { return };
    // Without the callback, which the Promise stands in for.
    let taken = &start.parameters[..start.parameters.len().saturating_sub(1)];
    let defaulted = defaults(start, taken);
    let mut parameters = taken.iter();
    let Some((_, instance)) = parameters.next() else { return };
    let rest: Vec<String> = parameters.map(|(name, mapped)| parameter(start, &defaulted, name, &mapped.ts)).collect();
    let this = std::iter::once(format!("this: {}", instance.ts)).chain(rest).collect::<Vec<_>>().join(", ");
    let _ = writeln!(out, "    /**\n     * @ntsCall {}_promise\n     */", start.symbol);
    let _ = writeln!(out, "    {name}({this}): Promise<{}>;", finish.result.ts);
}

/// The parameters a caller may leave out of `parameters`, and what stands for
/// each: the longest run at the end that `omissible` covers, stepping over
/// the `@ntsThrows` slot, which is optional already. Only a run at the end,
/// since TypeScript lets no required parameter follow an optional one.
fn defaults<'f>(function: &'f Function, parameters: &'f [(String, Mapped)]) -> Vec<(&'f str, &'static str)> {
    let mut run = Vec::new();
    for (name, _) in parameters.iter().rev() {
        if function.throws.as_deref() == Some(name.as_str()) {
            continue;
        }
        match function.omissible.get(name) {
            Some(value) => run.push((name.as_str(), *value)),
            None => break,
        }
    }
    run.reverse();
    run
}

/// One parameter as TypeScript writes it: the `@ntsThrows` one optional, so a
/// caller that leaves it out has the failure thrown, and so is each of
/// `defaulted`, whose value the compiler passes instead (`@ntsDefault`).
fn parameter(function: &Function, defaulted: &[(&str, &str)], name: &str, ts: &str) -> String {
    let optional = function.throws.as_deref() == Some(name) || defaulted.iter().any(|(given, _)| *given == name);
    format!("{name}{}: {ts}", if optional { "?" } else { "" })
}

/// The tags a declaration carries: one per line, since a tag's value runs to
/// the end of its line. `symbol` when its name is not the C function's.
fn notes(out: &mut String, function: &Function, symbol: bool, defaulted: &[(&str, &str)], indent: &str) {
    let mut notes = Vec::new();
    if function.deprecated {
        notes.push("@deprecated".to_owned());
    }
    if let Some(returns) = &function.returns {
        notes.push(format!("GIR: returns a `{returns}`."));
    }
    if let Some(free) = &function.free {
        notes.push(format!("@ntsFree {free}"));
    }
    for name in &function.no_escape {
        notes.push(format!("@ntsNoEscape {name}"));
    }
    // A virtual function names its slot, and has no symbol to name.
    if let Some((class_struct, member, offset)) = &function.vfunc {
        notes.push(format!("@ntsVfunc {class_struct} {member} {offset}"));
    } else if symbol {
        notes.push(format!("@ntsSymbol {}", function.symbol));
    }
    if let Some(slot) = &function.throws {
        notes.push(format!("@ntsThrows {slot} nts_gerror_take_message"));
    }
    if !defaulted.is_empty() {
        let given: Vec<String> = defaulted.iter().map(|(name, value)| format!("{name}={value}")).collect();
        notes.push(format!("@ntsDefault {}", given.join(" ")));
    }
    if !notes.is_empty() {
        let _ = writeln!(out, "{indent}/**");
        for note in notes {
            let _ = writeln!(out, "{indent} * {note}");
        }
        let _ = writeln!(out, "{indent} */");
    }
}

/// The enums, as `const enum`s in the module itself, so a program imports
/// `Orientation` from `c:Gtk-4.0` beside the functions taking one, and a
/// member read is a literal where it is used -- no object, no global, no
/// load. Named as GIR names them (`Align.FILL`), and each also by its C name
/// (`GtkAlign`), which is the one signatures spell (`CEnum<GtkAlign,
/// c_uint>`): two namespaces can share a short name, never a C one.
fn enums(out: &mut String, binding: &Binding) {
    for decl in &binding.enums {
        let _ = writeln!(out, "  export const enum {} {{", decl.name);
        for (name, value, c_identifier) in &decl.members {
            // A member name may start with a digit (`2BUTTON_PRESS`), which
            // TypeScript does not allow unquoted.
            let key = if name.starts_with(|c: char| c.is_ascii_digit()) { format!("_{name}") } else { name.clone() };
            let _ = writeln!(out, "    /** `{c_identifier}` */\n    {key} = {value},");
        }
        out.push_str("  }\n");
        if let Some(c_type) = &decl.c_type {
            let _ = writeln!(out, "  export type {c_type} = {};", decl.name);
        }
    }
    if !binding.enums.is_empty() {
        out.push('\n');
    }
}

/// The companion module: what a declaration file cannot carry.
///
/// A `.ts` rather than a `.d.ts`, because what it holds are values:
///
/// - **A checked downcast per class**, `asGtkBox(value)`: the one intended
///   caller of `unsafeDowncast`, which is safe here because the check is the
///   type system's own -- `g_type_check_instance_is_a` against the class's
///   `GType` -- and not the caller's word. Every GTK constructor returns a
///   `GtkWidget *`, so this is how a program gets the box it made.
#[must_use]
pub(crate) fn companion(binding: &Binding, command: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// Generated by `{command}`. Edit the command, not this file.");
    out.push_str("//\n// The values that go with the declarations in the module of the same name.\n");
    // One import line per module, merged, since the checker lives in
    // `GObject-2.0` and so do that module's own classes.
    let mut imports: std::collections::BTreeMap<String, Vec<String>> = std::collections::BTreeMap::new();
    if !binding.casts.is_empty() {
        imports.entry("c:GObject-2.0".to_owned()).or_default().extend([
            "g_type_check_instance_is_a".to_owned(),
            "type GTypeInstance".to_owned(),
        ]);
        let own = imports.entry(binding.module.clone()).or_default();
        for cast in &binding.casts {
            own.push(cast.get_type.clone());
            own.push(format!("type {}", cast.class));
        }
    }
    let promises = promise_forms(binding);
    for (start, finish) in &promises {
        let own = imports.entry(binding.module.clone()).or_default();
        own.push(start.symbol.clone());
        own.push(finish.symbol.clone());
        // Every name the wrapper's signature prints, to import from where it
        // is declared: read from the spelling, since the spelling is exactly
        // what has to resolve, and a `Declared<GtkBox, GtkWidget>` names two.
        let spellings = start.parameters.iter().map(|(_, mapped)| mapped.ts.as_str()).chain([finish.result.ts.as_str()]);
        for name in spellings.flat_map(|ts| ts.split(|c: char| !(c.is_ascii_alphanumeric() || c == '_'))) {
            if let Some(module) = module_of_type(binding, name) {
                imports.entry(module).or_default().push(format!("type {name}"));
            }
        }
    }
    let values = values_forms(binding);
    for function in &values {
        imports.entry(binding.module.clone()).or_default().push(function.symbol.clone());
        // A record the wrapper makes is a value it imports, `new GtkTextIter()`.
        for (_, mapped) in &function.parameters {
            if let Shape::Filled { class } = &mapped.shape
                && let Some(module) = module_of_type(binding, class)
            {
                imports.entry(module).or_default().push(class.clone());
            }
        }
        let spellings = function.parameters.iter().map(|(_, mapped)| mapped.ts.as_str()).chain([function.result.ts.as_str()]);
        for name in spellings.flat_map(|ts| ts.split(|c: char| !(c.is_ascii_alphanumeric() || c == '_'))) {
            if let Some(module) = module_of_type(binding, name) {
                imports.entry(module).or_default().push(format!("type {name}"));
            }
        }
    }
    let memory: Vec<&str> = [(!binding.casts.is_empty()).then_some("unsafeDowncast"), values
            .iter()
            .any(|function| function.parameters.iter().any(|(_, mapped)| matches!(mapped.shape, Shape::Out { .. })))
            .then_some("local")]
        .into_iter()
        .flatten()
        .collect();
    if !memory.is_empty() {
        let _ = writeln!(out, "\nimport {{ {} }} from \"c:memory\";", memory.join(", "));
    } else if !imports.is_empty() {
        out.push('\n');
    }
    for (module, mut names) in imports {
        names.sort();
        names.dedup();
        // A value import brings its type along, and naming both is an error.
        let values: Vec<String> = names.iter().filter(|name| !name.starts_with("type ")).cloned().collect();
        names.retain(|name| name.strip_prefix("type ").is_none_or(|ty| !values.iter().any(|value| value == ty)));
        let _ = writeln!(out, "import {{ {} }} from \"{module}\";", names.join(", "));
    }
    for cast in &binding.casts {
        let _ = writeln!(
            out,
            "\n/** `{class}` if `value` is one, and `null` otherwise. */\n\
             export function as{class}(value: GTypeInstance | null): {class} | null {{\n\
             \x20 return unsafeDowncast<{class}>(\n\
             \x20   value,\n\
             \x20   value !== null && g_type_check_instance_is_a(value, {get_type}()),\n\
             \x20 );\n\
             }}",
            class = cast.class,
            get_type = cast.get_type,
        );
    }
    for (start, finish) in &promises {
        promise_wrapper(&mut out, start, finish);
    }
    for function in &values {
        values_wrapper(&mut out, function);
    }
    out
}

/// `function` with its out slots as locals, read once it returns and handed
/// back as `values_result` says. The error slot is left out of the call, so a
/// failure is thrown here and propagates.
fn values_wrapper(out: &mut String, function: &Function) {
    let taken = values_taken(function);
    let defaulted = defaults(function, &taken);
    let declared = declared_parameters(&taken, &defaulted);
    let mut body = String::new();
    let mut read = Vec::new();
    if function.result.ts != "void" {
        read.push("nts_result".to_owned());
    }
    for (name, mapped) in &function.parameters {
        match &mapped.shape {
            Shape::Out { value } => {
                let _ = writeln!(body, "  const {name} = local<{value}>();");
                read.push(format!("{name}[0]"));
            }
            Shape::Filled { class } => {
                let _ = writeln!(body, "  const {name} = new {class}();");
                read.push(name.clone());
            }
            _ => {}
        }
    }
    let passed = function
        .parameters
        .iter()
        .filter(|(name, _)| function.throws.as_deref() != Some(name.as_str()))
        .map(|(name, _)| name.as_str())
        .collect::<Vec<_>>()
        .join(", ");
    let call = format!("{}({passed})", function.symbol);
    let _ = if function.result.ts == "void" { writeln!(body, "  {call};") } else { writeln!(body, "  const nts_result = {call};") };
    let returned = if read.len() == 1 { read[0].clone() } else { format!("[{}]", read.join(", ")) };
    let _ = writeln!(
        out,
        "\n/** `{symbol}`, returning its out values. */\n\
         export function {symbol}_values({declared}): {result} {{\n\
         {body}\x20 return {returned};\n\
         }}",
        symbol = function.symbol,
        result = values_result(function),
    );
}

/// A wrapper's own parameters, as it declares them: the trailing defaulted
/// ones as default parameters, and a lent array as the program holds it,
/// since it is lent at the call inside.
fn declared_parameters(taken: &[(String, Mapped)], defaulted: &[(&str, &str)]) -> String {
    let program = |mapped: &Mapped| match &mapped.shape {
        Shape::Lent { program } => program.clone(),
        _ => mapped.ts.clone(),
    };
    taken
        .iter()
        .map(|(name, mapped)| match defaulted.iter().find(|(given, _)| *given == name.as_str()) {
            Some((_, "null")) => format!("{name}: {} = null", program(mapped)),
            Some((_, value)) => format!("{name}: {ts} = {value} as {ts}", ts = program(mapped)),
            None => format!("{name}: {}", program(mapped)),
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// Where a type name a spelling uses is declared: this module, the module it
/// was imported from, or `c:types` for a brand. `None` for anything else --
/// `string`, `null`, a keyword.
fn module_of_type(binding: &Binding, name: &str) -> Option<String> {
    if binding.types.iter().any(|decl| matches!(decl, super::map::TypeDecl::Class { name: n, .. } if n == name))
        || binding.enums.iter().any(|decl| decl.c_type.as_deref() == Some(name))
    {
        return Some(binding.module.clone());
    }
    if let Some((module, _)) = binding.imports.iter().find(|(_, names)| names.contains(name)) {
        return Some(module.clone());
    }
    binding.brands.contains(name).then(|| "c:types".to_owned())
}

/// `start` as a Promise, settled by `finish`: what `finish` returns, or the
/// `GError` it reports, thrown there and rejected here. The method overload
/// `promise_method` declares is bodied by this (`@ntsCall`).
fn promise_wrapper(out: &mut String, start: &Function, finish: &Function) {
    let taken = &start.parameters[..start.parameters.len().saturating_sub(1)];
    let Some((instance, _)) = taken.first() else { return };
    // The method leaves these out as the C one would; here they are ordinary
    // default parameters, since this is the program's own function.
    let defaulted = defaults(start, taken);
    let declared = declared_parameters(taken, &defaulted);
    let passed = taken.iter().map(|(name, _)| name.as_str()).collect::<Vec<_>>().join(", ");
    // **A lent array lives until `finish`, not until `start` returns.** The
    // call lends it for its own duration, which for an `_async` method is
    // the time it takes to queue the work: GIO writes `contents` from a
    // pool thread afterwards. Named in the callback, each is held by the
    // closure, which GIO keeps until it has called it.
    let kept = taken.iter().filter(|(_, mapped)| matches!(mapped.shape, Shape::Lent { .. })).fold(String::new(), |mut kept, (name, _)| {
        let _ = writeln!(kept, "      void {name};");
        kept
    });
    let _ = writeln!(
        out,
        "\n/** `{start}` as a Promise, settled by `{finish}`. */\n\
         export function {start}_promise({declared}): Promise<{result}> {{\n\
         \x20 return new Promise((nts_resolve, nts_reject) => {{\n\
         \x20   {start}({passed}, (_source, nts_result) => {{\n\
         {kept}\
         \x20     try {{\n\
         \x20       nts_resolve({finish}({instance}, nts_result));\n\
         \x20     }} catch (nts_error) {{\n\
         \x20       nts_reject(nts_error);\n\
         \x20     }}\n\
         \x20   }});\n\
         \x20 }});\n\
         }}",
        start = start.symbol,
        finish = finish.symbol,
        result = finish.result.ts,
    );
}

#[cfg(test)]
mod tests {
    use super::super::map::{Function, Mapped, Shape};
    use nts_core::hir::native::{Scalar, Type};

    fn mapped(ts: &str, shape: Shape) -> Mapped {
        Mapped { shape, ts: ts.to_owned(), c: Type::Scalar(Scalar::Size) }
    }

    fn function(symbol: &str, parameters: Vec<(&str, Mapped)>, result: &str) -> Function {
        Function {
            name: symbol.to_owned(),
            symbol: symbol.to_owned(),
            parameters: parameters.into_iter().map(|(name, mapped)| (name.to_owned(), mapped)).collect(),
            result: mapped(result, Shape::Other),
            c_parameters: Vec::new(),
            deprecated: false,
            free: None,
            no_escape: Vec::new(),
            returns: None,
            method: None,
            throws: None,
            finish: None,
            omissible: std::collections::BTreeMap::new(),
            method_only: false,
            statics: None,
            vfunc: None,
        }
    }

    /// An `_async` method's work outlives its call -- GIO writes `contents`
    /// from a pool thread after `start` has returned -- so the Promise form's
    /// callback names each array the call lends, and the closure holds it
    /// until `finish`. Without it, `--rc` freed the bytes before the write
    /// (valgrind: "Syscall param write(buf) points to unaddressable byte(s)").
    #[test]
    fn a_promise_form_keeps_what_its_call_lends_until_finish() {
        let start = function(
            "g_file_replace_contents_async",
            vec![
                ("file", mapped("GFile", Shape::Other)),
                ("contents", mapped("CBytes", Shape::Lent { program: "Uint8Array".to_owned() })),
                ("callback", mapped("GAsyncReadyCallback", Shape::Other)),
            ],
            "void",
        );
        let finish = function("g_file_replace_contents_finish", vec![("file", mapped("GFile", Shape::Other))], "boolean");
        let mut out = String::new();
        super::promise_wrapper(&mut out, &start, &finish);
        let callback = out.split("(_source, nts_result) => {").nth(1).expect("a callback");
        assert!(callback.contains("void contents;"), "{out}");
        assert!(!callback.contains("void file;"), "{out}");
    }
}
