//! A [`Binding`] as text: the `.d.ts` module, and the `.ts` companion with
//! the values a declaration file cannot carry.

use std::fmt::Write;

use super::map::{Binding, Function, Mapped, Shape, TypeDecl};

/// The declaration module: types, then functions, in a stable order.
#[must_use]
pub(crate) fn declarations(binding: &Binding, command: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// Generated by `{command}`. Edit the command, not this file.");
    out.push_str(
        "//\n\
         // Read from GObject introspection data, with every declaration compiled\n\
         // against the headers below before it was written. `c:type` decides the\n\
         // C spelling; GIR's annotations decide ownership, nullability and which\n\
         // parameters carry a callback's context.\n",
    );
    out.push_str("/**\n");
    for header in &binding.headers {
        let _ = writeln!(out, " * @ntsHeader {header}");
    }
    out.push_str(" */\n");
    let _ = writeln!(out, "declare module \"{}\" {{", binding.module);
    if !binding.brands.is_empty() {
        let _ = writeln!(
            out,
            "  import type {{ {} }} from \"c:types\";",
            binding.brands.iter().copied().collect::<Vec<_>>().join(", ")
        );
    }
    for (module, names) in &binding.imports {
        let _ = writeln!(
            out,
            "  import type {{ {} }} from \"{module}\";",
            names.iter().cloned().collect::<Vec<_>>().join(", ")
        );
    }
    out.push('\n');
    enums(&mut out, binding);
    // The methods of each class, from the functions the self-check kept.
    let promises: std::collections::BTreeMap<&str, &Function> =
        promise_forms(binding).into_iter().map(|(start, finish)| (start.symbol.as_str(), finish)).collect();
    let mut methods: std::collections::BTreeMap<&str, Vec<&Function>> = std::collections::BTreeMap::new();
    for function in &binding.functions {
        if let Some((class, _)) = &function.method {
            methods.entry(class.as_str()).or_default().push(function);
        }
    }
    for decl in &binding.types {
        match decl {
            TypeDecl::Class { name, tag, parent, counted } => {
                let class = if *counted { "GObjectClass" } else { "Class" };
                // `button.set_label(text)`: each method is the C function it
                // names, with the receiver as its `this`. Intersected rather
                // than extended, so a subclass method that shares a name with
                // an ancestor's is an overload and not a conflicting redeclaration.
                let _ = writeln!(out, "  export interface {name}OwnMethods {{");
                let own: Vec<&Function> = methods.get(name.as_str()).into_iter().flatten().copied().collect();
                for function in &own {
                    method(&mut out, function);
                    if let Some(finish) = promises.get(function.symbol.as_str()) {
                        promise_method(&mut out, function, finish);
                    }
                }
                for property in binding.properties.get(name.as_str()).into_iter().flatten() {
                    accessor(&mut out, &own, &property.name, property.getter.as_deref(), property.setter.as_deref());
                }
                out.push_str("  }\n");
                if let Some((_, parent)) = parent {
                    let _ = writeln!(out, "  export type {name}Methods = {name}OwnMethods & {parent}Methods;");
                    let _ = writeln!(out, "  export type {name} = {class}<\"{tag}\", {parent}> & {name}Methods;");
                } else {
                    let _ = writeln!(out, "  export type {name}Methods = {name}OwnMethods;");
                    let _ = writeln!(out, "  export type {name} = {class}<\"{tag}\"> & {name}Methods;");
                }
                construction(&mut out, binding, &own, name, parent.as_ref().map(|(_, parent)| parent.as_str()));
            }
        }
    }
    out.push('\n');
    for function in binding.functions.iter().filter(|function| !function.method_only) {
        let defaulted = defaults(function, &function.parameters);
        notes(&mut out, function, function.name != function.symbol, &defaulted, "  ");
        let parameters = function
            .parameters
            .iter()
            .map(|(name, mapped)| parameter(function, &defaulted, name, &mapped.ts))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(
            out,
            "  export function {}({parameters}): {};",
            function.name, function.result.ts
        );
    }
    out.push_str("}\n");
    out
}

/// A property of the class's methods, read and written through the methods
/// GIR names for it (`@ntsGet`/`@ntsSet`), where the self-check kept them:
/// `label.label = "Hi"`. Typed by what the getter returns; the setter joins
/// only where it takes exactly that, since a getter answering `string | null`
/// beside a setter taking `string` would let `null` be assigned -- such a
/// property is read-only, and `set_label` is still there. Its `@ntsSet` stays:
/// `new GtkButton({ label })` writes it through the setter at the setter's own
/// type, which `readonly` does not stop and should not. A property whose
/// name a method of the class already has, or that no kept method serves, is
/// left out.
fn accessor(out: &mut String, own: &[&Function], property: &str, getter: Option<&str>, setter: Option<&str>) {
    let Some(Decided { ts, get, set, assignable }) = decide(own, property, getter, setter) else { return };
    let mut tags = Vec::new();
    if let Some((_, name)) = get.and_then(|f| f.method.as_ref()) {
        tags.push(format!("@ntsGet {name}"));
    }
    if let Some((_, name)) = set.and_then(|f| f.method.as_ref()) {
        tags.push(format!("@ntsSet {name}"));
    }
    let _ = writeln!(out, "    /**");
    for tag in tags {
        let _ = writeln!(out, "     * {tag}");
    }
    let _ = writeln!(out, "     */");
    let readonly = if assignable { "" } else { "readonly " };
    let _ = writeln!(out, "    {readonly}{property}: {ts};");
}

/// What a property is on its class, once its methods are known: its type, the
/// methods it is read and written through, and whether an assignment may write
/// it -- only where the setter takes what the getter answers. `None` where it
/// is left out.
struct Decided<'f> {
    ts: String,
    get: Option<&'f Function>,
    set: Option<&'f Function>,
    assignable: bool,
}

fn decide<'f>(own: &[&'f Function], property: &str, getter: Option<&str>, setter: Option<&str>) -> Option<Decided<'f>> {
    if own_method(own, Some(property)).is_some() {
        return None;
    }
    let get = own_method(own, getter)
        .filter(|f| f.parameters.len() == 1 && f.result.ts != "void" && f.throws.is_none());
    let set = settable(own, property, setter);
    let (ts, assignable) = match (get, set) {
        (Some(get), Some(set)) => (get.result.ts.clone(), set.parameters[1].1.ts == get.result.ts),
        (Some(get), None) => (get.result.ts.clone(), false),
        (None, Some(set)) => (set.parameters[1].1.ts.clone(), true),
        (None, None) => return None,
    };
    Some(Decided { ts, get, set, assignable })
}

/// The method a property is written through, where there is one a plain
/// assignment can call: it takes the instance and the value, answers nothing
/// and throws nothing, and no method of the class takes the property's name.
fn settable<'f>(own: &[&'f Function], property: &str, setter: Option<&str>) -> Option<&'f Function> {
    if own_method(own, Some(property)).is_some() {
        return None;
    }
    own_method(own, setter).filter(|f| f.parameters.len() == 2 && f.result.ts == "void" && f.throws.is_none())
}

fn own_method<'f>(own: &[&'f Function], method: Option<&str>) -> Option<&'f Function> {
    let method = method?;
    own.iter().copied().find(|f| f.method.as_ref().is_some_and(|(_, name)| name == method))
}

/// GJS's construction: `…Props`, the class's writable properties -- each
/// optional, typed as its setter takes it -- extending the parent's; and a
/// value of the class's name to construct it with, `new GtkButton({ label })`,
/// which makes one with every property at its default and then calls the
/// setter of each property the literal writes (`@ntsConstruct`). It is made
/// by the class's `new` where that takes nothing, and by its `GType` through
/// `g_object_new_with_properties` otherwise (`GtkLabel_construct`). An
/// abstract class, or one whose constructor the self-check refused, has the
/// interface and not the value.
fn construction(out: &mut String, binding: &Binding, own: &[&Function], name: &str, parent: Option<&str>) {
    let extends = parent.map(|parent| format!(" extends {parent}Props")).unwrap_or_default();
    let _ = writeln!(out, "  export interface {name}Props{extends} {{");
    for property in binding.properties.get(name).into_iter().flatten() {
        let Some(set) = settable(own, &property.name, property.setter.as_deref()) else { continue };
        let _ = writeln!(out, "    {}?: {};", property.name, set.parameters[1].1.ts);
    }
    out.push_str("  }\n");
    let kept = |function: &str| binding.functions.iter().find(|f| f.name == function && f.throws.is_none());
    let Some(constructor) = binding.constructors.get(name) else { return };
    let tag = match (kept(&constructor.function), &constructor.get_type) {
        (Some(new), None) if new.parameters.is_empty() => constructor.function.clone(),
        (Some(_), Some(get_type)) if kept(get_type).is_some() => format!("{} {get_type}", constructor.function),
        _ => return,
    };
    let _ = writeln!(
        out,
        "  export const {name}: {{\n    /**\n     * @ntsConstruct {tag}\n     */\n    new (props?: {name}Props): {name};\n  }};",
    );
}

/// A function as a method of its class: `this` is its instance.
fn method(out: &mut String, function: &Function) {
    let Some((_, name)) = &function.method else { return };
    let defaulted = defaults(function, &function.parameters);
    let mut parameters = function.parameters.iter();
    let Some((_, instance)) = parameters.next() else { return };
    notes(out, function, true, &defaulted, "    ");
    let rest: Vec<String> =
        parameters.map(|(name, mapped)| parameter(function, &defaulted, name, &mapped.ts)).collect();
    let this = std::iter::once(format!("this: {}", instance.ts)).chain(rest).collect::<Vec<_>>().join(", ");
    let _ = writeln!(out, "    {name}({this}): {};", function.result.ts);
}

/// The `_async` methods with a `_finish` that reads only their result: each
/// pair a Promise can be made of. Only from functions the self-check kept,
/// and only where the `_async` ends in its `OnceClosure` and the `_finish`
/// takes the instance and the `GAsyncResult` -- and at most the error slot --
/// so that the Promise settles with exactly what the `_finish` returns.
pub(crate) fn promise_forms(binding: &Binding) -> Vec<(&Function, &Function)> {
    binding
        .functions
        .iter()
        .filter_map(|start| {
            let (class, _) = start.method.as_ref()?;
            let finish_name = start.finish.as_ref()?;
            let (_, callback) = start.parameters.last()?;
            if callback.shape != Shape::Once {
                return None;
            }
            let finish = binding
                .functions
                .iter()
                .find(|f| f.method.as_ref().is_some_and(|(c, n)| c == class && n == finish_name))?;
            let read = finish.parameters.iter().filter(|(name, _)| finish.throws.as_deref() != Some(name.as_str())).count();
            (read == 2 && settles(&finish.result)).then_some((start, finish))
        })
        .collect()
}

/// Every `_async` method the binding kept, and whether it has a Promise form
/// -- and if not, why not. An absent overload fails nothing, so the ones
/// without one are counted here rather than left to be found by a call that
/// does not typecheck: the before-number for whatever makes them possible.
pub(crate) fn promise_census(binding: &Binding) -> Vec<(String, &'static str)> {
    let made: std::collections::BTreeSet<&str> = promise_forms(binding).into_iter().map(|(start, _)| start.symbol.as_str()).collect();
    binding
        .functions
        .iter()
        .filter(|start| {
            start.method.is_some()
                && start.finish.is_some()
                && start.parameters.last().is_some_and(|(_, callback)| callback.shape == Shape::Once)
        })
        .map(|start| {
            let outcome = if made.contains(start.symbol.as_str()) {
                "promise"
            } else {
                why_no_promise(binding, start)
            };
            (start.symbol.clone(), outcome)
        })
        .collect()
}

/// Why an `_async` method has no Promise form.
fn why_no_promise(binding: &Binding, start: &Function) -> &'static str {
    let (class, _) = start.method.as_ref().expect("a method");
    let finish_name = start.finish.as_ref().expect("a finish");
    let Some(finish) = binding
        .functions
        .iter()
        .find(|f| f.method.as_ref().is_some_and(|(c, n)| c == class && n == finish_name))
    else {
        return "no Promise form: its `_finish` is not bound";
    };
    let read = finish.parameters.iter().filter(|(name, _)| finish.throws.as_deref() != Some(name.as_str())).count();
    if read != 2 {
        return "no Promise form: its `_finish` takes more than the result";
    }
    match &finish.result.c {
        nts_core::hir::native::Type::Scalar(_) => "no Promise form: its `_finish` returns a 64-bit integer",
        nts_core::hir::native::Type::Pointer(_) => "no Promise form: its `_finish` returns an untyped pointer",
        _ => "no Promise form: its `_finish` returns what a promise cannot carry",
    }
}

/// Whether a promise can carry what a `_finish` returns: nothing, a number,
/// a boolean, a string, or a handle -- which the promise holds in a slot of
/// its own, outside its value. Not a 64-bit integer, which a number cannot
/// hold; those `_async` methods keep only their callback form.
fn settles(result: &super::map::Mapped) -> bool {
    use nts_core::hir::native::{Pointee, Type};
    match &result.c {
        Type::Void | Type::Bool | Type::Pointer(_) if !matches!(result.c, Type::Pointer(Pointee::Void)) => true,
        Type::Scalar(scalar) => !scalar.needs_exact_integer(),
        _ => false,
    }
}

/// An `_async` method's Promise form: the same method without its callback,
/// answering what the `_finish` returns -- `await file.query_info_async(…)`.
/// An overload of the C one, told apart by arity, and bodied by the wrapper
/// the companion module defines (`@ntsCall`).
fn promise_method(out: &mut String, start: &Function, finish: &Function) {
    let Some((_, name)) = &start.method else { return };
    // Without the callback, which the Promise stands in for.
    let taken = &start.parameters[..start.parameters.len().saturating_sub(1)];
    let defaulted = defaults(start, taken);
    let mut parameters = taken.iter();
    let Some((_, instance)) = parameters.next() else { return };
    let rest: Vec<String> = parameters.map(|(name, mapped)| parameter(start, &defaulted, name, &mapped.ts)).collect();
    let this = std::iter::once(format!("this: {}", instance.ts)).chain(rest).collect::<Vec<_>>().join(", ");
    let _ = writeln!(out, "    /**\n     * @ntsCall {}_promise\n     */", start.symbol);
    let _ = writeln!(out, "    {name}({this}): Promise<{}>;", finish.result.ts);
}

/// The parameters a caller may leave out of `parameters`, and what stands for
/// each: the longest run at the end that `omissible` covers, stepping over
/// the `@ntsThrows` slot, which is optional already. Only a run at the end,
/// since TypeScript lets no required parameter follow an optional one.
fn defaults<'f>(function: &'f Function, parameters: &'f [(String, Mapped)]) -> Vec<(&'f str, &'static str)> {
    let mut run = Vec::new();
    for (name, _) in parameters.iter().rev() {
        if function.throws.as_deref() == Some(name.as_str()) {
            continue;
        }
        match function.omissible.get(name) {
            Some(value) => run.push((name.as_str(), *value)),
            None => break,
        }
    }
    run.reverse();
    run
}

/// One parameter as TypeScript writes it: the `@ntsThrows` one optional, so a
/// caller that leaves it out has the failure thrown, and so is each of
/// `defaulted`, whose value the compiler passes instead (`@ntsDefault`).
fn parameter(function: &Function, defaulted: &[(&str, &str)], name: &str, ts: &str) -> String {
    let optional = function.throws.as_deref() == Some(name) || defaulted.iter().any(|(given, _)| *given == name);
    format!("{name}{}: {ts}", if optional { "?" } else { "" })
}

/// The tags a declaration carries: one per line, since a tag's value runs to
/// the end of its line. `symbol` when its name is not the C function's.
fn notes(out: &mut String, function: &Function, symbol: bool, defaulted: &[(&str, &str)], indent: &str) {
    let mut notes = Vec::new();
    if function.deprecated {
        notes.push("@deprecated".to_owned());
    }
    if let Some(returns) = &function.returns {
        notes.push(format!("GIR: returns a `{returns}`."));
    }
    if let Some(free) = &function.free {
        notes.push(format!("@ntsFree {free}"));
    }
    for name in &function.no_escape {
        notes.push(format!("@ntsNoEscape {name}"));
    }
    if symbol {
        notes.push(format!("@ntsSymbol {}", function.symbol));
    }
    if let Some(slot) = &function.throws {
        notes.push(format!("@ntsThrows {slot} nts_gerror_take_message"));
    }
    if !defaulted.is_empty() {
        let given: Vec<String> = defaulted.iter().map(|(name, value)| format!("{name}={value}")).collect();
        notes.push(format!("@ntsDefault {}", given.join(" ")));
    }
    if !notes.is_empty() {
        let _ = writeln!(out, "{indent}/**");
        for note in notes {
            let _ = writeln!(out, "{indent} * {note}");
        }
        let _ = writeln!(out, "{indent} */");
    }
}

/// The enums, as `const enum`s in the module itself, so a program imports
/// `Orientation` from `c:Gtk-4.0` beside the functions taking one, and a
/// member read is a literal where it is used -- no object, no global, no
/// load. Named as GIR names them (`Align.FILL`), and each also by its C name
/// (`GtkAlign`), which is the one signatures spell (`CEnum<GtkAlign,
/// c_uint>`): two namespaces can share a short name, never a C one.
fn enums(out: &mut String, binding: &Binding) {
    for decl in &binding.enums {
        let _ = writeln!(out, "  export const enum {} {{", decl.name);
        for (name, value, c_identifier) in &decl.members {
            // A member name may start with a digit (`2BUTTON_PRESS`), which
            // TypeScript does not allow unquoted.
            let key = if name.starts_with(|c: char| c.is_ascii_digit()) { format!("_{name}") } else { name.clone() };
            let _ = writeln!(out, "    /** `{c_identifier}` */\n    {key} = {value},");
        }
        out.push_str("  }\n");
        if let Some(c_type) = &decl.c_type {
            let _ = writeln!(out, "  export type {c_type} = {};", decl.name);
        }
    }
    if !binding.enums.is_empty() {
        out.push('\n');
    }
}

/// The companion module: what a declaration file cannot carry.
///
/// A `.ts` rather than a `.d.ts`, because what it holds are values:
///
/// - **A checked downcast per class**, `asGtkBox(value)`: the one intended
///   caller of `unsafeDowncast`, which is safe here because the check is the
///   type system's own -- `g_type_check_instance_is_a` against the class's
///   `GType` -- and not the caller's word. Every GTK constructor returns a
///   `GtkWidget *`, so this is how a program gets the box it made.
#[must_use]
pub(crate) fn companion(binding: &Binding, command: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// Generated by `{command}`. Edit the command, not this file.");
    out.push_str("//\n// The values that go with the declarations in the module of the same name.\n");
    // One import line per module, merged, since the checker lives in
    // `GObject-2.0` and so do that module's own classes.
    let mut imports: std::collections::BTreeMap<String, Vec<String>> = std::collections::BTreeMap::new();
    if !binding.casts.is_empty() {
        imports.entry("c:GObject-2.0".to_owned()).or_default().extend([
            "g_type_check_instance_is_a".to_owned(),
            "type GTypeInstance".to_owned(),
        ]);
        let own = imports.entry(binding.module.clone()).or_default();
        for cast in &binding.casts {
            own.push(cast.get_type.clone());
            own.push(format!("type {}", cast.class));
        }
    }
    let promises = promise_forms(binding);
    for (start, finish) in &promises {
        let own = imports.entry(binding.module.clone()).or_default();
        own.push(start.symbol.clone());
        own.push(finish.symbol.clone());
        // Every name the wrapper's signature prints, to import from where it
        // is declared: read from the spelling, since the spelling is exactly
        // what has to resolve, and a `Declared<GtkBox, GtkWidget>` names two.
        let spellings = start.parameters.iter().map(|(_, mapped)| mapped.ts.as_str()).chain([finish.result.ts.as_str()]);
        for name in spellings.flat_map(|ts| ts.split(|c: char| !(c.is_ascii_alphanumeric() || c == '_'))) {
            if let Some(module) = module_of_type(binding, name) {
                imports.entry(module).or_default().push(format!("type {name}"));
            }
        }
    }
    if !binding.casts.is_empty() {
        out.push_str("\nimport { unsafeDowncast } from \"c:memory\";\n");
    } else if !imports.is_empty() {
        out.push('\n');
    }
    for (module, mut names) in imports {
        names.sort();
        names.dedup();
        let _ = writeln!(out, "import {{ {} }} from \"{module}\";", names.join(", "));
    }
    for cast in &binding.casts {
        let _ = writeln!(
            out,
            "\n/** `{class}` if `value` is one, and `null` otherwise. */\n\
             export function as{class}(value: GTypeInstance | null): {class} | null {{\n\
             \x20 return unsafeDowncast<{class}>(\n\
             \x20   value,\n\
             \x20   value !== null && g_type_check_instance_is_a(value, {get_type}()),\n\
             \x20 );\n\
             }}",
            class = cast.class,
            get_type = cast.get_type,
        );
    }
    for (start, finish) in &promises {
        promise_wrapper(&mut out, start, finish);
    }
    out
}

/// Where a type name a spelling uses is declared: this module, the module it
/// was imported from, or `c:types` for a brand. `None` for anything else --
/// `string`, `null`, a keyword.
fn module_of_type(binding: &Binding, name: &str) -> Option<String> {
    if binding.types.iter().any(|decl| matches!(decl, super::map::TypeDecl::Class { name: n, .. } if n == name))
        || binding.enums.iter().any(|decl| decl.c_type.as_deref() == Some(name))
    {
        return Some(binding.module.clone());
    }
    if let Some((module, _)) = binding.imports.iter().find(|(_, names)| names.contains(name)) {
        return Some(module.clone());
    }
    binding.brands.contains(name).then(|| "c:types".to_owned())
}

/// `start` as a Promise, settled by `finish`: what `finish` returns, or the
/// `GError` it reports, thrown there and rejected here. The method overload
/// `promise_method` declares is bodied by this (`@ntsCall`).
fn promise_wrapper(out: &mut String, start: &Function, finish: &Function) {
    let taken = &start.parameters[..start.parameters.len().saturating_sub(1)];
    let Some((instance, _)) = taken.first() else { return };
    // The method leaves these out as the C one would; here they are ordinary
    // default parameters, since this is the program's own function.
    let defaulted = defaults(start, taken);
    let declared = taken
        .iter()
        .map(|(name, mapped)| match defaulted.iter().find(|(given, _)| *given == name.as_str()) {
            Some((_, "null")) => format!("{name}: {} = null", mapped.ts),
            Some((_, value)) => format!("{name}: {ts} = {value} as {ts}", ts = mapped.ts),
            None => format!("{name}: {}", mapped.ts),
        })
        .collect::<Vec<_>>()
        .join(", ");
    let passed = taken.iter().map(|(name, _)| name.as_str()).collect::<Vec<_>>().join(", ");
    let _ = writeln!(
        out,
        "\n/** `{start}` as a Promise, settled by `{finish}`. */\n\
         export function {start}_promise({declared}): Promise<{result}> {{\n\
         \x20 return new Promise((nts_resolve, nts_reject) => {{\n\
         \x20   {start}({passed}, (_source, nts_result) => {{\n\
         \x20     try {{\n\
         \x20       nts_resolve({finish}({instance}, nts_result));\n\
         \x20     }} catch (nts_error) {{\n\
         \x20       nts_reject(nts_error);\n\
         \x20     }}\n\
         \x20   }});\n\
         \x20 }});\n\
         }}",
        start = start.symbol,
        finish = finish.symbol,
        result = finish.result.ts,
    );
}
