//! A [`Binding`] as text: the `.d.ts` module, and the `.ts` companion with
//! the values a declaration file cannot carry.

use std::fmt::Write;

use super::map::{Binding, Function, TypeDecl};

/// The declaration module: types, then functions, in a stable order.
#[must_use]
pub(crate) fn declarations(binding: &Binding, command: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// Generated by `{command}`. Edit the command, not this file.");
    out.push_str(
        "//\n\
         // Read from GObject introspection data, with every declaration compiled\n\
         // against the headers below before it was written. `c:type` decides the\n\
         // C spelling; GIR's annotations decide ownership, nullability and which\n\
         // parameters carry a callback's context.\n",
    );
    out.push_str("/**\n");
    for header in &binding.headers {
        let _ = writeln!(out, " * @ntsHeader {header}");
    }
    out.push_str(" */\n");
    let _ = writeln!(out, "declare module \"{}\" {{", binding.module);
    if !binding.brands.is_empty() {
        let _ = writeln!(
            out,
            "  import type {{ {} }} from \"c:types\";",
            binding.brands.iter().copied().collect::<Vec<_>>().join(", ")
        );
    }
    for (module, names) in &binding.imports {
        let _ = writeln!(
            out,
            "  import type {{ {} }} from \"{module}\";",
            names.iter().cloned().collect::<Vec<_>>().join(", ")
        );
    }
    out.push('\n');
    // The methods of each class, from the functions the self-check kept.
    let mut methods: std::collections::BTreeMap<&str, Vec<&Function>> = std::collections::BTreeMap::new();
    for function in &binding.functions {
        if let Some((class, _)) = &function.method {
            methods.entry(class.as_str()).or_default().push(function);
        }
    }
    for decl in &binding.types {
        match decl {
            TypeDecl::Class { name, tag, parent } => {
                // `button.set_label(text)`: each method is the C function it
                // names, with the receiver as its `this`. Intersected rather
                // than extended, so a subclass method that shares a name with
                // an ancestor's is an overload and not a conflicting redeclaration.
                let _ = writeln!(out, "  export interface {name}OwnMethods {{");
                for function in methods.get(name.as_str()).into_iter().flatten() {
                    method(&mut out, function);
                }
                out.push_str("  }\n");
                if let Some((_, parent)) = parent {
                    let _ = writeln!(out, "  export type {name}Methods = {name}OwnMethods & {parent}Methods;");
                    let _ = writeln!(out, "  export type {name} = Class<\"{tag}\", {parent}> & {name}Methods;");
                } else {
                    let _ = writeln!(out, "  export type {name}Methods = {name}OwnMethods;");
                    let _ = writeln!(out, "  export type {name} = Class<\"{tag}\"> & {name}Methods;");
                }
            }
        }
    }
    out.push('\n');
    for function in &binding.functions {
        notes(&mut out, function, function.name != function.symbol, "  ");
        let parameters = function
            .parameters
            .iter()
            .map(|(name, mapped)| parameter(function, name, &mapped.ts))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(
            out,
            "  export function {}({parameters}): {};",
            function.name, function.result.ts
        );
    }
    out.push_str("}\n");
    out
}

/// A function as a method of its class: `this` is its instance.
fn method(out: &mut String, function: &Function) {
    let Some((_, name)) = &function.method else { return };
    let mut parameters = function.parameters.iter();
    let Some((_, instance)) = parameters.next() else { return };
    notes(out, function, true, "    ");
    let rest: Vec<String> = parameters.map(|(name, mapped)| parameter(function, name, &mapped.ts)).collect();
    let this = std::iter::once(format!("this: {}", instance.ts)).chain(rest).collect::<Vec<_>>().join(", ");
    let _ = writeln!(out, "    {name}({this}): {};", function.result.ts);
}

/// One parameter as TypeScript writes it: the `@ntsThrows` one optional, so a
/// caller that leaves it out has the failure thrown.
fn parameter(function: &Function, name: &str, ts: &str) -> String {
    let optional = if function.throws.as_deref() == Some(name) { "?" } else { "" };
    format!("{name}{optional}: {ts}")
}

/// The tags a declaration carries: one per line, since a tag's value runs to
/// the end of its line. `symbol` when its name is not the C function's.
fn notes(out: &mut String, function: &Function, symbol: bool, indent: &str) {
    let mut notes = Vec::new();
    if function.deprecated {
        notes.push("@deprecated".to_owned());
    }
    if let Some(returns) = &function.returns {
        notes.push(format!("GIR: returns a `{returns}`."));
    }
    if let Some(free) = &function.free {
        notes.push(format!("@ntsFree {free}"));
    }
    for name in &function.no_escape {
        notes.push(format!("@ntsNoEscape {name}"));
    }
    if symbol {
        notes.push(format!("@ntsSymbol {}", function.symbol));
    }
    if let Some(slot) = &function.throws {
        notes.push(format!("@ntsThrows {slot} nts_gerror_take_message"));
    }
    if !notes.is_empty() {
        let _ = writeln!(out, "{indent}/**");
        for note in notes {
            let _ = writeln!(out, "{indent} * {note}");
        }
        let _ = writeln!(out, "{indent} */");
    }
}

/// The companion module: what a declaration file cannot carry.
///
/// A `.ts` rather than a `.d.ts`, because both halves are values:
///
/// - **The enums, as `const enum`s**, so that a member read is a literal
///   where it is used -- no object, no global, no load. Named as GIR names them
///   (`Align.FILL`); the C names would collide with the enumerators
///   `program.c` sees through the header.
/// - **A checked downcast per class**, `asGtkBox(value)`: the one intended
///   caller of `unsafeDowncast`, which is safe here because the check is the
///   type system's own -- `g_type_check_instance_is_a` against the class's
///   `GType` -- and not the caller's word. Every GTK constructor returns a
///   `GtkWidget *`, so this is how a program gets the box it made.
#[must_use]
pub(crate) fn companion(binding: &Binding, command: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// Generated by `{command}`. Edit the command, not this file.");
    out.push_str("//\n// The values that go with the declarations in the module of the same name.\n");
    if !binding.casts.is_empty() {
        // One import line per module, merged, since the checker lives in
        // `GObject-2.0` and so do that module's own classes.
        let mut imports: std::collections::BTreeMap<&str, Vec<String>> = std::collections::BTreeMap::new();
        let objects = "c:GObject-2.0";
        imports.entry(objects).or_default().extend([
            "g_type_check_instance_is_a".to_owned(),
            "type GTypeInstance".to_owned(),
        ]);
        let own = imports.entry(binding.module.as_str()).or_default();
        for cast in &binding.casts {
            own.push(cast.get_type.clone());
            own.push(format!("type {}", cast.class));
        }
        out.push_str("\nimport { unsafeDowncast } from \"c:memory\";\n");
        for (module, mut names) in imports {
            names.sort();
            names.dedup();
            let _ = writeln!(out, "import {{ {} }} from \"{module}\";", names.join(", "));
        }
    }
    for decl in &binding.enums {
        let _ = writeln!(out, "\nexport const enum {} {{", decl.name);
        for (name, value, c_identifier) in &decl.members {
            // A member name may start with a digit (`2BUTTON_PRESS`), which
            // TypeScript does not allow unquoted.
            let key = if name.starts_with(|c: char| c.is_ascii_digit()) {
                format!("_{name}")
            } else {
                name.clone()
            };
            let _ = writeln!(out, "  /** `{c_identifier}` */\n  {key} = {value},");
        }
        out.push_str("}\n");
    }
    for cast in &binding.casts {
        let _ = writeln!(
            out,
            "\n/** `{class}` if `value` is one, and `null` otherwise. */\n\
             export function as{class}(value: GTypeInstance | null): {class} | null {{\n\
             \x20 return unsafeDowncast<{class}>(\n\
             \x20   value,\n\
             \x20   value !== null && g_type_check_instance_is_a(value, {get_type}()) !== 0,\n\
             \x20 );\n\
             }}",
            class = cast.class,
            get_type = cast.get_type,
        );
    }
    out
}
