// Generated by tooling/chromium/bindgen/generate.py from Blink's IDL at Chromium b510e9d7cd3a2fbd78d0ddc42234103206c5f78d.
// Do not edit; regenerate.
//
// What implements lib.dom.d.ts's declarations natively: each names the
// nts:dom declaration a use of it lowers to (docs/lib-dom.md). Declarations
// only -- lib.dom.d.ts types the program; nothing here changes a type.

/**
 * @ntsBoundBy "nts:dom" AbortController
 * @ntsIs nts_dom_is 0
 */
interface AbortController {}
/**
 * @ntsBoundBy "nts:dom" AbortSignal
 * @ntsIs nts_dom_is 1
 */
interface AbortSignal {}
/**
 * @ntsIs nts_dom_is 2
 */
interface AbstractRange {}
/**
 * @ntsBoundBy "nts:dom" EventTarget
 * @ntsIs nts_dom_is 3
 */
interface Animation {}
/**
 * @ntsIs nts_dom_is 4
 */
interface AnimationEffect {}
/**
 * @ntsBoundBy "nts:dom" Event
 * @ntsIs nts_dom_is 5
 */
interface AnimationEvent {}
/**
 * @ntsBoundBy "nts:dom" Event
 * @ntsIs nts_dom_is 6
 */
interface AnimationPlaybackEvent {}
/**
 * @ntsIs nts_dom_is 7
 */
interface AnimationTimeline {}
/**
 * @ntsBoundBy "nts:dom" Node
 * @ntsIs nts_dom_is 9
 */
interface Attr {}
/**
 * @ntsIs nts_dom_is 14
 */
interface BarProp {}
/**
 * @ntsBoundBy "nts:dom" Event
 * @ntsIs nts_dom_is 15
 */
interface BeforeUnloadEvent {}
/**
 * @ntsIs nts_dom_is 16
 */
interface Blob {}
/**
 * @ntsIs nts_dom_is 17
 */
interface ByteLengthQueuingStrategy {}
/**
 * @ntsBoundBy "nts:dom" Text
 * @ntsIs nts_dom_is 18
 */
interface CDATASection {}
/**
 * @ntsBoundBy "nts:dom" EventTarget
 * @ntsIs nts_dom_is 20
 */
interface CSSAnimation {}
/**
 * @ntsIs nts_dom_is 23
 */
interface CSSConditionRule {}
/**
 * @ntsIs nts_dom_is 24
 */
interface CSSContainerRule {}
/**
 * @ntsIs nts_dom_is 26
 */
interface CSSCounterStyleRule {}
/**
 * @ntsIs nts_dom_is 28
 */
interface CSSFontFaceRule {}
/**
 * @ntsIs nts_dom_is 30
 */
interface CSSFontFeatureValuesRule {}
/**
 * @ntsIs nts_dom_is 31
 */
interface CSSFontPaletteValuesRule {}
/**
 * @ntsIs nts_dom_is 35
 */
interface CSSGroupingRule {}
/**
 * @ntsIs nts_dom_is 38
 */
interface CSSImageValue {}
/**
 * @ntsIs nts_dom_is 39
 */
interface CSSImportRule {}
/**
 * @ntsIs nts_dom_is 40
 */
interface CSSKeyframeRule {}
/**
 * @ntsIs nts_dom_is 41
 */
interface CSSKeyframesRule {}
/**
 * @ntsIs nts_dom_is 42
 */
interface CSSKeywordValue {}
/**
 * @ntsIs nts_dom_is 43
 */
interface CSSLayerBlockRule {}
/**
 * @ntsIs nts_dom_is 44
 */
interface CSSLayerStatementRule {}
/**
 * @ntsIs nts_dom_is 47
 */
interface CSSMathClamp {}
/**
 * @ntsIs nts_dom_is 48
 */
interface CSSMathInvert {}
/**
 * @ntsIs nts_dom_is 49
 */
interface CSSMathMax {}
/**
 * @ntsIs nts_dom_is 50
 */
interface CSSMathMin {}
/**
 * @ntsIs nts_dom_is 51
 */
interface CSSMathNegate {}
/**
 * @ntsIs nts_dom_is 52
 */
interface CSSMathProduct {}
/**
 * @ntsIs nts_dom_is 54
 */
interface CSSMathSum {}
/**
 * @ntsIs nts_dom_is 55
 */
interface CSSMathValue {}
/**
 * @ntsIs nts_dom_is 56
 */
interface CSSMatrixComponent {}
/**
 * @ntsIs nts_dom_is 57
 */
interface CSSMediaRule {}
/**
 * @ntsIs nts_dom_is 59
 */
interface CSSNamespaceRule {}
/**
 * @ntsIs nts_dom_is 61
 */
interface CSSNestedDeclarations {}
/**
 * @ntsIs nts_dom_is 62
 */
interface CSSNumericArray {}
/**
 * @ntsIs nts_dom_is 63
 */
interface CSSNumericValue {}
/**
 * @ntsIs nts_dom_is 64
 */
interface CSSPageRule {}
/**
 * @ntsIs nts_dom_is 65
 */
interface CSSPerspective {}
/**
 * @ntsBoundBy "nts:dom" CSSStyleDeclaration
 * @ntsIs nts_dom_is 66
 */
interface CSSPositionTryDescriptors {}
/**
 * @ntsIs nts_dom_is 67
 */
interface CSSPositionTryRule {}
/**
 * @ntsIs nts_dom_is 70
 */
interface CSSPropertyRule {}
/**
 * @ntsIs nts_dom_is 74
 */
interface CSSRotate {}
/**
 * @ntsIs nts_dom_is 75
 */
interface CSSRule {}
/**
 * @ntsIs nts_dom_is 76
 */
interface CSSRuleList {}
/**
 * @ntsIs nts_dom_is 77
 */
interface CSSScale {}
/**
 * @ntsIs nts_dom_is 78
 */
interface CSSScopeRule {}
/**
 * @ntsIs nts_dom_is 79
 */
interface CSSSkew {}
/**
 * @ntsIs nts_dom_is 80
 */
interface CSSSkewX {}
/**
 * @ntsIs nts_dom_is 81
 */
interface CSSSkewY {}
/**
 * @ntsIs nts_dom_is 82
 */
interface CSSStartingStyleRule {}
/**
 * @ntsBoundBy "nts:dom" CSSStyleDeclaration
 * @ntsIs nts_dom_is 83
 */
interface CSSStyleDeclaration {}
/**
 * @ntsIs nts_dom_is 84
 */
interface CSSStyleRule {}
/**
 * @ntsIs nts_dom_is 85
 */
interface CSSStyleSheet {}
/**
 * @ntsIs nts_dom_is 86
 */
interface CSSStyleValue {}
/**
 * @ntsIs nts_dom_is 87
 */
interface CSSSupportsRule {}
/**
 * @ntsIs nts_dom_is 88
 */
interface CSSTransformComponent {}
/**
 * @ntsIs nts_dom_is 89
 */
interface CSSTransformValue {}
/**
 * @ntsBoundBy "nts:dom" EventTarget
 * @ntsIs nts_dom_is 90
 */
interface CSSTransition {}
/**
 * @ntsIs nts_dom_is 91
 */
interface CSSTranslate {}
/**
 * @ntsIs nts_dom_is 92
 */
interface CSSUnitValue {}
/**
 * @ntsIs nts_dom_is 93
 */
interface CSSUnparsedValue {}
/**
 * @ntsIs nts_dom_is 94
 */
interface CSSVariableReferenceValue {}
/**
 * @ntsIs nts_dom_is 95
 */
interface CSSViewTransitionRule {}
/**
 * @ntsIs nts_dom_is 98
 */
interface CaretPosition {}
/**
 * @ntsBoundBy "nts:dom" CharacterData
 * @ntsIs nts_dom_is 100
 */
interface CharacterData {}
/**
 * @ntsBoundBy "nts:dom" Event
 * @ntsIs nts_dom_is 101
 */
interface ClipboardEvent {}
/**
 * @ntsBoundBy "nts:dom" Event
 * @ntsIs nts_dom_is 104
 */
interface CommandEvent {}
/**
 * @ntsBoundBy "nts:dom" Comment
 * @ntsIs nts_dom_is 105
 */
interface Comment {}
/**
 * @ntsBoundBy "nts:dom" UIEvent
 * @ntsIs nts_dom_is 106
 */
interface CompositionEvent {}
/**
 * @ntsBoundBy "nts:dom" Event
 * @ntsIs nts_dom_is 109
 */
interface ContentVisibilityAutoStateChangeEvent {}
/**
 * @ntsIs nts_dom_is 111
 */
interface CountQueuingStrategy {}
/**
 * @ntsIs nts_dom_is 113
 */
interface CustomElementRegistry {}
/**
 * @ntsBoundBy "nts:dom" CustomEvent
 * @ntsIs nts_dom_is 114
 */
interface CustomEvent {}
/**
 * @ntsIs nts_dom_is 115
 */
interface CustomStateSet {}
/**
 * @ntsIs nts_dom_is 116
 */
interface DOMException {}
/**
 * @ntsIs nts_dom_is 117
 */
interface DOMImplementation {}
/**
 * @ntsIs nts_dom_is 118
 */
interface DOMMatrix {}
/**
 * @ntsIs nts_dom_is 119
 */
interface DOMMatrixReadOnly {}
/**
 * @ntsIs nts_dom_is 120
 */
interface DOMParser {}
/**
 * @ntsIs nts_dom_is 121
 */
interface DOMPoint {}
/**
 * @ntsIs nts_dom_is 122
 */
interface DOMPointReadOnly {}
/**
 * @ntsIs nts_dom_is 123
 */
interface DOMQuad {}
/**
 * @ntsBoundBy "nts:dom" DOMRect
 * @ntsIs nts_dom_is 124
 */
interface DOMRect {}
/**
 * @ntsIs nts_dom_is 125
 */
interface DOMRectList {}
/**
 * @ntsBoundBy "nts:dom" DOMRectReadOnly
 * @ntsIs nts_dom_is 126
 */
interface DOMRectReadOnly {}
/**
 * @ntsIs nts_dom_is 127
 */
interface DOMStringList {}
/**
 * @ntsBoundBy "nts:dom" DOMStringMap
 * @ntsIs nts_dom_is 128
 */
interface DOMStringMap {}
/**
 * @ntsBoundBy "nts:dom" DOMTokenList
 * @ntsIs nts_dom_is 129
 */
interface DOMTokenList {}
/**
 * @ntsIs nts_dom_is 130
 */
interface DataTransfer {}
/**
 * @ntsIs nts_dom_is 131
 */
interface DataTransferItem {}
/**
 * @ntsIs nts_dom_is 132
 */
interface DataTransferItemList {}
/**
 * @ntsBoundBy "nts:dom" Document
 * @ntsIs nts_dom_is 138
 */
interface Document {}
/**
 * @ntsBoundBy "nts:dom" DocumentFragment
 * @ntsIs nts_dom_is 139
 */
interface DocumentFragment {}
/**
 * @ntsIs nts_dom_is 141
 */
interface DocumentTimeline {}
/**
 * @ntsBoundBy "nts:dom" Node
 * @ntsIs nts_dom_is 142
 */
interface DocumentType {}
/**
 * @ntsBoundBy "nts:dom" MouseEvent
 * @ntsIs nts_dom_is 143
 */
interface DragEvent {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 145
 */
interface Element {}
/**
 * @ntsIs nts_dom_is 148
 */
interface ElementInternals {}
/**
 * @ntsBoundBy "nts:dom" Event
 * @ntsIs nts_dom_is 149
 */
interface ErrorEvent {}
/**
 * @ntsBoundBy "nts:dom" Event
 * @ntsIs nts_dom_is 150
 */
interface Event {}
/**
 * @ntsIs nts_dom_is 151
 */
interface EventCounts {}
/**
 * @ntsBoundBy "nts:dom" EventTarget
 * @ntsIs nts_dom_is 152
 */
interface EventTarget {}
/**
 * @ntsIs nts_dom_is 154
 */
interface External {}
/**
 * @ntsIs nts_dom_is 158
 */
interface File {}
/**
 * @ntsIs nts_dom_is 159
 */
interface FileList {}
/**
 * @ntsBoundBy "nts:dom" EventTarget
 * @ntsIs nts_dom_is 160
 */
interface FileReader {}
/**
 * @ntsBoundBy "nts:dom" FocusEvent
 * @ntsIs nts_dom_is 162
 */
interface FocusEvent {}
/**
 * @ntsIs nts_dom_is 163
 */
interface FontFace {}
/**
 * @ntsBoundBy "nts:dom" EventTarget
 * @ntsIs nts_dom_is 164
 */
interface FontFaceSet {}
/**
 * @ntsBoundBy "nts:dom" Event
 * @ntsIs nts_dom_is 165
 */
interface FontFaceSetLoadEvent {}
/**
 * @ntsIs nts_dom_is 166
 */
interface FormData {}
/**
 * @ntsBoundBy "nts:dom" Event
 * @ntsIs nts_dom_is 167
 */
interface FormDataEvent {}
/**
 * @ntsIs nts_dom_is 168
 */
interface FragmentDirective {}
/**
 * @ntsIs nts_dom_is 171
 */
interface Geolocation {}
/**
 * @ntsIs nts_dom_is 172
 */
interface GeolocationCoordinates {}
/**
 * @ntsIs nts_dom_is 173
 */
interface GeolocationPosition {}
/**
 * @ntsIs nts_dom_is 174
 */
interface GeolocationPositionError {}
/**
 * @ntsIs nts_dom_is 175
 */
interface HTMLAllCollection {}
/**
 * @ntsBoundBy "nts:dom" HTMLAnchorElement
 * @ntsIs nts_dom_is 176
 */
interface HTMLAnchorElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 177
 */
interface HTMLAreaElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 178
 */
interface HTMLAudioElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 179
 */
interface HTMLBRElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 180
 */
interface HTMLBaseElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 181
 */
interface HTMLBodyElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLButtonElement
 * @ntsIs nts_dom_is 182
 */
interface HTMLButtonElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLCanvasElement
 * @ntsIs nts_dom_is 184
 */
interface HTMLCanvasElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLCollection
 * @ntsIs nts_dom_is 185
 */
interface HTMLCollection {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 187
 */
interface HTMLDListElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 188
 */
interface HTMLDataElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 189
 */
interface HTMLDataListElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 190
 */
interface HTMLDetailsElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 191
 */
interface HTMLDialogElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 192
 */
interface HTMLDirectoryElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLDivElement
 * @ntsIs nts_dom_is 193
 */
interface HTMLDivElement {}
/**
 * @ntsBoundBy "nts:dom" Document
 * @ntsIs nts_dom_is 194
 */
interface HTMLDocument {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 195
 */
interface HTMLElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 196
 */
interface HTMLEmbedElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 198
 */
interface HTMLFieldSetElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 199
 */
interface HTMLFontElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLCollection
 * @ntsIs nts_dom_is 200
 */
interface HTMLFormControlsCollection {}
/**
 * @ntsBoundBy "nts:dom" HTMLFormElement
 * @ntsIs nts_dom_is 201
 */
interface HTMLFormElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 202
 */
interface HTMLFrameElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 203
 */
interface HTMLFrameSetElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 205
 */
interface HTMLHRElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 206
 */
interface HTMLHeadElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 207
 */
interface HTMLHeadingElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 208
 */
interface HTMLHtmlElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 209
 */
interface HTMLIFrameElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLImageElement
 * @ntsIs nts_dom_is 210
 */
interface HTMLImageElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLInputElement
 * @ntsIs nts_dom_is 211
 */
interface HTMLInputElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLLIElement
 * @ntsIs nts_dom_is 213
 */
interface HTMLLIElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLLabelElement
 * @ntsIs nts_dom_is 214
 */
interface HTMLLabelElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 215
 */
interface HTMLLegendElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 216
 */
interface HTMLLinkElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 218
 */
interface HTMLMapElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 219
 */
interface HTMLMarqueeElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 220
 */
interface HTMLMediaElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 222
 */
interface HTMLMenuElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 225
 */
interface HTMLMetaElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 226
 */
interface HTMLMeterElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 228
 */
interface HTMLModElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLOListElement
 * @ntsIs nts_dom_is 229
 */
interface HTMLOListElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 230
 */
interface HTMLObjectElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 231
 */
interface HTMLOptGroupElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLOptionElement
 * @ntsIs nts_dom_is 232
 */
interface HTMLOptionElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLCollection
 * @ntsIs nts_dom_is 233
 */
interface HTMLOptionsCollection {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 234
 */
interface HTMLOutputElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLParagraphElement
 * @ntsIs nts_dom_is 235
 */
interface HTMLParagraphElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 236
 */
interface HTMLParamElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 237
 */
interface HTMLPictureElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 238
 */
interface HTMLPreElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 239
 */
interface HTMLProgressElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 240
 */
interface HTMLQuoteElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 241
 */
interface HTMLScriptElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLSelectElement
 * @ntsIs nts_dom_is 242
 */
interface HTMLSelectElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 244
 */
interface HTMLSlotElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 245
 */
interface HTMLSourceElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLSpanElement
 * @ntsIs nts_dom_is 246
 */
interface HTMLSpanElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 247
 */
interface HTMLStyleElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 250
 */
interface HTMLTableCaptionElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLTableCellElement
 * @ntsIs nts_dom_is 251
 */
interface HTMLTableCellElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 252
 */
interface HTMLTableColElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLTableElement
 * @ntsIs nts_dom_is 253
 */
interface HTMLTableElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLTableRowElement
 * @ntsIs nts_dom_is 254
 */
interface HTMLTableRowElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLTableSectionElement
 * @ntsIs nts_dom_is 255
 */
interface HTMLTableSectionElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLTemplateElement
 * @ntsIs nts_dom_is 256
 */
interface HTMLTemplateElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLTextAreaElement
 * @ntsIs nts_dom_is 257
 */
interface HTMLTextAreaElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 258
 */
interface HTMLTimeElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 259
 */
interface HTMLTitleElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 260
 */
interface HTMLTrackElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLUListElement
 * @ntsIs nts_dom_is 261
 */
interface HTMLUListElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 262
 */
interface HTMLUnknownElement {}
/**
 * @ntsBoundBy "nts:dom" HTMLElement
 * @ntsIs nts_dom_is 264
 */
interface HTMLVideoElement {}
/**
 * @ntsBoundBy "nts:dom" Event
 * @ntsIs nts_dom_is 265
 */
interface HashChangeEvent {}
/**
 * @ntsIs nts_dom_is 266
 */
interface Headers {}
/**
 * @ntsIs nts_dom_is 267
 */
interface Highlight {}
/**
 * @ntsIs nts_dom_is 268
 */
interface HighlightRegistry {}
/**
 * @ntsBoundBy "nts:dom" History
 * @ntsIs nts_dom_is 269
 */
interface History {}
/**
 * @ntsIs nts_dom_is 272
 */
interface IdleDeadline {}
/**
 * @ntsIs nts_dom_is 273
 */
interface ImageBitmap {}
/**
 * @ntsIs nts_dom_is 274
 */
interface ImageData {}
/**
 * @ntsBoundBy "nts:dom" InputEvent
 * @ntsIs nts_dom_is 276
 */
interface InputEvent {}
/**
 * @ntsIs nts_dom_is 287
 */
interface IntersectionObserver {}
/**
 * @ntsIs nts_dom_is 288
 */
interface IntersectionObserverEntry {}
/**
 * @ntsBoundBy "nts:dom" KeyboardEvent
 * @ntsIs nts_dom_is 291
 */
interface KeyboardEvent {}
/**
 * @ntsIs nts_dom_is 292
 */
interface KeyframeEffect {}
/**
 * @ntsIs nts_dom_is 293
 */
interface LargestContentfulPaint {}
/**
 * @ntsBoundBy "nts:dom" Location
 * @ntsIs nts_dom_is 301
 */
interface Location {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 303
 */
interface MathMLElement {}
/**
 * @ntsIs nts_dom_is 304
 */
interface MediaError {}
/**
 * @ntsIs nts_dom_is 305
 */
interface MediaList {}
/**
 * @ntsBoundBy "nts:dom" MediaQueryList
 * @ntsIs nts_dom_is 306
 */
interface MediaQueryList {}
/**
 * @ntsBoundBy "nts:dom" Event
 * @ntsIs nts_dom_is 307
 */
interface MediaQueryListEvent {}
/**
 * @ntsIs nts_dom_is 309
 */
interface MessageChannel {}
/**
 * @ntsBoundBy "nts:dom" Event
 * @ntsIs nts_dom_is 310
 */
interface MessageEvent {}
/**
 * @ntsBoundBy "nts:dom" EventTarget
 * @ntsIs nts_dom_is 311
 */
interface MessagePort {}
/**
 * @ntsBoundBy "nts:dom" MouseEvent
 * @ntsIs nts_dom_is 318
 */
interface MouseEvent {}
/**
 * @ntsIs nts_dom_is 319
 */
interface MutationObserver {}
/**
 * @ntsIs nts_dom_is 320
 */
interface MutationRecord {}
/**
 * @ntsIs nts_dom_is 322
 */
interface NamedNodeMap {}
/**
 * @ntsBoundBy "nts:dom" Event
 * @ntsIs nts_dom_is 323
 */
interface NavigateEvent {}
/**
 * @ntsBoundBy "nts:dom" EventTarget
 * @ntsIs nts_dom_is 324
 */
interface Navigation {}
/**
 * @ntsIs nts_dom_is 325
 */
interface NavigationActivation {}
/**
 * @ntsBoundBy "nts:dom" Event
 * @ntsIs nts_dom_is 326
 */
interface NavigationCurrentEntryChangeEvent {}
/**
 * @ntsIs nts_dom_is 328
 */
interface NavigationDestination {}
/**
 * @ntsBoundBy "nts:dom" EventTarget
 * @ntsIs nts_dom_is 329
 */
interface NavigationHistoryEntry {}
/**
 * @ntsIs nts_dom_is 330
 */
interface NavigationPrecommitController {}
/**
 * @ntsIs nts_dom_is 331
 */
interface NavigationTransition {}
/**
 * @ntsIs nts_dom_is 332
 */
interface Navigator {}
/**
 * @ntsBoundBy "nts:dom" Node
 * @ntsIs nts_dom_is 334
 */
interface Node {}
/**
 * @ntsIs nts_dom_is 335
 */
interface NodeIterator {}
/**
 * @ntsBoundBy "nts:dom" NodeList
 * @ntsIs nts_dom_is 336
 */
interface NodeList {}
/**
 * @ntsBoundBy "nts:dom" EventTarget
 * @ntsIs nts_dom_is 341
 */
interface OffscreenCanvas {}
/**
 * @ntsBoundBy "nts:dom" Event
 * @ntsIs nts_dom_is 347
 */
interface PageRevealEvent {}
/**
 * @ntsBoundBy "nts:dom" Event
 * @ntsIs nts_dom_is 348
 */
interface PageSwapEvent {}
/**
 * @ntsBoundBy "nts:dom" Event
 * @ntsIs nts_dom_is 349
 */
interface PageTransitionEvent {}
/**
 * @ntsBoundBy "nts:dom" Performance
 * @ntsIs nts_dom_is 350
 */
interface Performance {}
/**
 * @ntsIs nts_dom_is 353
 */
interface PerformanceEntry {}
/**
 * @ntsIs nts_dom_is 354
 */
interface PerformanceEventTiming {}
/**
 * @ntsIs nts_dom_is 357
 */
interface PerformanceMark {}
/**
 * @ntsIs nts_dom_is 359
 */
interface PerformanceMeasure {}
/**
 * @ntsIs nts_dom_is 361
 */
interface PerformanceNavigation {}
/**
 * @ntsIs nts_dom_is 362
 */
interface PerformanceNavigationTiming {}
/**
 * @ntsIs nts_dom_is 363
 */
interface PerformanceObserver {}
/**
 * @ntsIs nts_dom_is 364
 */
interface PerformanceObserverEntryList {}
/**
 * @ntsIs nts_dom_is 365
 */
interface PerformancePaintTiming {}
/**
 * @ntsIs nts_dom_is 366
 */
interface PerformanceResourceTiming {}
/**
 * @ntsIs nts_dom_is 369
 */
interface PerformanceServerTiming {}
/**
 * @ntsIs nts_dom_is 371
 */
interface PerformanceTiming {}
/**
 * @ntsBoundBy "nts:dom" PointerEvent
 * @ntsIs nts_dom_is 375
 */
interface PointerEvent {}
/**
 * @ntsBoundBy "nts:dom" Event
 * @ntsIs nts_dom_is 376
 */
interface PopStateEvent {}
/**
 * @ntsBoundBy "nts:dom" CharacterData
 * @ntsIs nts_dom_is 381
 */
interface ProcessingInstruction {}
/**
 * @ntsBoundBy "nts:dom" Event
 * @ntsIs nts_dom_is 383
 */
interface ProgressEvent {}
/**
 * @ntsBoundBy "nts:dom" Event
 * @ntsIs nts_dom_is 384
 */
interface PromiseRejectionEvent {}
/**
 * @ntsBoundBy "nts:dom" NodeList
 * @ntsIs nts_dom_is 386
 */
interface RadioNodeList {}
/**
 * @ntsIs nts_dom_is 387
 */
interface Range {}
/**
 * @ntsIs nts_dom_is 388
 */
interface ReadableByteStreamController {}
/**
 * @ntsIs nts_dom_is 389
 */
interface ReadableStream {}
/**
 * @ntsIs nts_dom_is 390
 */
interface ReadableStreamBYOBReader {}
/**
 * @ntsIs nts_dom_is 391
 */
interface ReadableStreamBYOBRequest {}
/**
 * @ntsIs nts_dom_is 392
 */
interface ReadableStreamDefaultController {}
/**
 * @ntsIs nts_dom_is 393
 */
interface ReadableStreamDefaultReader {}
/**
 * @ntsIs nts_dom_is 395
 */
interface Report {}
/**
 * @ntsIs nts_dom_is 396
 */
interface ReportBody {}
/**
 * @ntsIs nts_dom_is 397
 */
interface ReportingObserver {}
/**
 * @ntsIs nts_dom_is 398
 */
interface Request {}
/**
 * @ntsIs nts_dom_is 399
 */
interface ResizeObserver {}
/**
 * @ntsIs nts_dom_is 400
 */
interface ResizeObserverEntry {}
/**
 * @ntsIs nts_dom_is 401
 */
interface ResizeObserverSize {}
/**
 * @ntsIs nts_dom_is 403
 */
interface Response {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 404
 */
interface SVGAElement {}
/**
 * @ntsIs nts_dom_is 405
 */
interface SVGAngle {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 406
 */
interface SVGAnimateElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 407
 */
interface SVGAnimateMotionElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 408
 */
interface SVGAnimateTransformElement {}
/**
 * @ntsIs nts_dom_is 409
 */
interface SVGAnimatedAngle {}
/**
 * @ntsIs nts_dom_is 410
 */
interface SVGAnimatedBoolean {}
/**
 * @ntsIs nts_dom_is 411
 */
interface SVGAnimatedEnumeration {}
/**
 * @ntsIs nts_dom_is 412
 */
interface SVGAnimatedInteger {}
/**
 * @ntsIs nts_dom_is 413
 */
interface SVGAnimatedLength {}
/**
 * @ntsIs nts_dom_is 414
 */
interface SVGAnimatedLengthList {}
/**
 * @ntsIs nts_dom_is 415
 */
interface SVGAnimatedNumber {}
/**
 * @ntsIs nts_dom_is 416
 */
interface SVGAnimatedNumberList {}
/**
 * @ntsIs nts_dom_is 417
 */
interface SVGAnimatedPreserveAspectRatio {}
/**
 * @ntsIs nts_dom_is 418
 */
interface SVGAnimatedRect {}
/**
 * @ntsIs nts_dom_is 419
 */
interface SVGAnimatedString {}
/**
 * @ntsIs nts_dom_is 420
 */
interface SVGAnimatedTransformList {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 421
 */
interface SVGAnimationElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 422
 */
interface SVGCircleElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 423
 */
interface SVGClipPathElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 424
 */
interface SVGComponentTransferFunctionElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 425
 */
interface SVGDefsElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 426
 */
interface SVGDescElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 427
 */
interface SVGElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 428
 */
interface SVGEllipseElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 429
 */
interface SVGFEBlendElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 430
 */
interface SVGFEColorMatrixElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 431
 */
interface SVGFEComponentTransferElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 432
 */
interface SVGFECompositeElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 433
 */
interface SVGFEConvolveMatrixElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 434
 */
interface SVGFEDiffuseLightingElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 435
 */
interface SVGFEDisplacementMapElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 436
 */
interface SVGFEDistantLightElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 437
 */
interface SVGFEDropShadowElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 438
 */
interface SVGFEFloodElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 439
 */
interface SVGFEFuncAElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 440
 */
interface SVGFEFuncBElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 441
 */
interface SVGFEFuncGElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 442
 */
interface SVGFEFuncRElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 443
 */
interface SVGFEGaussianBlurElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 444
 */
interface SVGFEImageElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 445
 */
interface SVGFEMergeElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 446
 */
interface SVGFEMergeNodeElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 447
 */
interface SVGFEMorphologyElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 448
 */
interface SVGFEOffsetElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 449
 */
interface SVGFEPointLightElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 450
 */
interface SVGFESpecularLightingElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 451
 */
interface SVGFESpotLightElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 452
 */
interface SVGFETileElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 453
 */
interface SVGFETurbulenceElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 454
 */
interface SVGFilterElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 455
 */
interface SVGForeignObjectElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 456
 */
interface SVGGElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 457
 */
interface SVGGeometryElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 458
 */
interface SVGGradientElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 459
 */
interface SVGGraphicsElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 460
 */
interface SVGImageElement {}
/**
 * @ntsIs nts_dom_is 461
 */
interface SVGLength {}
/**
 * @ntsIs nts_dom_is 462
 */
interface SVGLengthList {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 463
 */
interface SVGLineElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 464
 */
interface SVGLinearGradientElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 465
 */
interface SVGMPathElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 466
 */
interface SVGMarkerElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 467
 */
interface SVGMaskElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 469
 */
interface SVGMetadataElement {}
/**
 * @ntsIs nts_dom_is 470
 */
interface SVGNumber {}
/**
 * @ntsIs nts_dom_is 471
 */
interface SVGNumberList {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 472
 */
interface SVGPathElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 473
 */
interface SVGPatternElement {}
/**
 * @ntsIs nts_dom_is 475
 */
interface SVGPointList {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 476
 */
interface SVGPolygonElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 477
 */
interface SVGPolylineElement {}
/**
 * @ntsIs nts_dom_is 478
 */
interface SVGPreserveAspectRatio {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 479
 */
interface SVGRadialGradientElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 481
 */
interface SVGRectElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 482
 */
interface SVGSVGElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 483
 */
interface SVGScriptElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 484
 */
interface SVGSetElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 485
 */
interface SVGStopElement {}
/**
 * @ntsIs nts_dom_is 486
 */
interface SVGStringList {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 487
 */
interface SVGStyleElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 488
 */
interface SVGSwitchElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 489
 */
interface SVGSymbolElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 490
 */
interface SVGTSpanElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 491
 */
interface SVGTextContentElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 492
 */
interface SVGTextElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 493
 */
interface SVGTextPathElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 494
 */
interface SVGTextPositioningElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 495
 */
interface SVGTitleElement {}
/**
 * @ntsIs nts_dom_is 496
 */
interface SVGTransform {}
/**
 * @ntsIs nts_dom_is 497
 */
interface SVGTransformList {}
/**
 * @ntsIs nts_dom_is 498
 */
interface SVGUnitTypes {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 499
 */
interface SVGUseElement {}
/**
 * @ntsBoundBy "nts:dom" Element
 * @ntsIs nts_dom_is 500
 */
interface SVGViewElement {}
/**
 * @ntsIs nts_dom_is 501
 */
interface Sanitizer {}
/**
 * @ntsIs nts_dom_is 502
 */
interface Scheduler {}
/**
 * @ntsBoundBy "nts:dom" Screen
 * @ntsIs nts_dom_is 504
 */
interface Screen {}
/**
 * @ntsIs nts_dom_is 505
 */
interface ScrollTimeline {}
/**
 * @ntsBoundBy "nts:dom" Event
 * @ntsIs nts_dom_is 506
 */
interface SecurityPolicyViolationEvent {}
/**
 * @ntsIs nts_dom_is 507
 */
interface Selection {}
/**
 * @ntsBoundBy "nts:dom" DocumentFragment
 * @ntsIs nts_dom_is 511
 */
interface ShadowRoot {}
/**
 * @ntsBoundBy "nts:dom" EventTarget
 * @ntsIs nts_dom_is 512
 */
interface SharedWorker {}
/**
 * @ntsIs nts_dom_is 517
 */
interface StaticRange {}
/**
 * @ntsIs nts_dom_is 520
 */
interface StylePropertyMap {}
/**
 * @ntsIs nts_dom_is 521
 */
interface StylePropertyMapReadOnly {}
/**
 * @ntsIs nts_dom_is 522
 */
interface StyleSheet {}
/**
 * @ntsIs nts_dom_is 523
 */
interface StyleSheetList {}
/**
 * @ntsBoundBy "nts:dom" Event
 * @ntsIs nts_dom_is 524
 */
interface SubmitEvent {}
/**
 * @ntsBoundBy "nts:dom" AbortController
 * @ntsIs nts_dom_is 527
 */
interface TaskController {}
/**
 * @ntsBoundBy "nts:dom" Event
 * @ntsIs nts_dom_is 528
 */
interface TaskPriorityChangeEvent {}
/**
 * @ntsBoundBy "nts:dom" AbortSignal
 * @ntsIs nts_dom_is 529
 */
interface TaskSignal {}
/**
 * @ntsBoundBy "nts:dom" Text
 * @ntsIs nts_dom_is 531
 */
interface Text {}
/**
 * @ntsBoundBy "nts:dom" UIEvent
 * @ntsIs nts_dom_is 534
 */
interface TextEvent {}
/**
 * @ntsIs nts_dom_is 537
 */
interface TextMetrics {}
/**
 * @ntsBoundBy "nts:dom" EventTarget
 * @ntsIs nts_dom_is 538
 */
interface TextTrack {}
/**
 * @ntsBoundBy "nts:dom" EventTarget
 * @ntsIs nts_dom_is 539
 */
interface TextTrackCue {}
/**
 * @ntsIs nts_dom_is 540
 */
interface TextTrackCueList {}
/**
 * @ntsBoundBy "nts:dom" EventTarget
 * @ntsIs nts_dom_is 541
 */
interface TextTrackList {}
/**
 * @ntsIs nts_dom_is 543
 */
interface TimeRanges {}
/**
 * @ntsBoundBy "nts:dom" Event
 * @ntsIs nts_dom_is 547
 */
interface ToggleEvent {}
/**
 * @ntsIs nts_dom_is 548
 */
interface Touch {}
/**
 * @ntsBoundBy "nts:dom" UIEvent
 * @ntsIs nts_dom_is 549
 */
interface TouchEvent {}
/**
 * @ntsIs nts_dom_is 550
 */
interface TouchList {}
/**
 * @ntsBoundBy "nts:dom" Event
 * @ntsIs nts_dom_is 551
 */
interface TrackEvent {}
/**
 * @ntsIs nts_dom_is 552
 */
interface TransformStream {}
/**
 * @ntsIs nts_dom_is 553
 */
interface TransformStreamDefaultController {}
/**
 * @ntsBoundBy "nts:dom" Event
 * @ntsIs nts_dom_is 554
 */
interface TransitionEvent {}
/**
 * @ntsIs nts_dom_is 555
 */
interface TreeWalker {}
/**
 * @ntsBoundBy "nts:dom" UIEvent
 * @ntsIs nts_dom_is 563
 */
interface UIEvent {}
/**
 * @ntsBoundBy "nts:dom" URL
 * @ntsIs nts_dom_is 564
 */
interface URL {}
/**
 * @ntsIs nts_dom_is 565
 */
interface URLPattern {}
/**
 * @ntsBoundBy "nts:dom" URLSearchParams
 * @ntsIs nts_dom_is 566
 */
interface URLSearchParams {}
/**
 * @ntsIs nts_dom_is 568
 */
interface UserActivation {}
/**
 * @ntsBoundBy "nts:dom" EventTarget
 * @ntsIs nts_dom_is 569
 */
interface VTTCue {}
/**
 * @ntsIs nts_dom_is 570
 */
interface VTTRegion {}
/**
 * @ntsIs nts_dom_is 571
 */
interface ValidityState {}
/**
 * @ntsIs nts_dom_is 574
 */
interface ViewTimeline {}
/**
 * @ntsIs nts_dom_is 575
 */
interface ViewTransition {}
/**
 * @ntsIs nts_dom_is 576
 */
interface ViewTransitionTypeSet {}
/**
 * @ntsBoundBy "nts:dom" EventTarget
 * @ntsIs nts_dom_is 579
 */
interface VisualViewport {}
/**
 * @ntsBoundBy "nts:dom" WheelEvent
 * @ntsIs nts_dom_is 581
 */
interface WheelEvent {}
/**
 * @ntsBoundBy "nts:dom" Window
 * @ntsIs nts_dom_is 582
 */
interface Window {}
/**
 * @ntsBoundBy "nts:dom" EventTarget
 * @ntsIs nts_dom_is 584
 */
interface Worker {}
/**
 * @ntsIs nts_dom_is 589
 */
interface Worklet {}
/**
 * @ntsIs nts_dom_is 591
 */
interface WritableStream {}
/**
 * @ntsIs nts_dom_is 592
 */
interface WritableStreamDefaultController {}
/**
 * @ntsIs nts_dom_is 593
 */
interface WritableStreamDefaultWriter {}
/**
 * @ntsBoundBy "nts:dom" Document
 * @ntsIs nts_dom_is 594
 */
interface XMLDocument {}
/**
 * @ntsBoundBy "nts:dom" EventTarget
 * @ntsIs nts_dom_is 595
 */
interface XMLHttpRequest {}
/**
 * @ntsBoundBy "nts:dom" EventTarget
 * @ntsIs nts_dom_is 596
 */
interface XMLHttpRequestEventTarget {}
/**
 * @ntsBoundBy "nts:dom" EventTarget
 * @ntsIs nts_dom_is 597
 */
interface XMLHttpRequestUpload {}
/**
 * @ntsIs nts_dom_is 598
 */
interface XMLSerializer {}
/**
 * @ntsIs nts_dom_is 599
 */
interface XPathEvaluator {}
/**
 * @ntsIs nts_dom_is 600
 */
interface XPathExpression {}
/**
 * @ntsIs nts_dom_is 601
 */
interface XPathResult {}
/**
 * @ntsIs nts_dom_is 602
 */
interface XSLTProcessor {}
/** @ntsBoundBy "nts:dom" document */
declare var document: Document;
/** @ntsBoundBy "nts:dom" requestAnimationFrame */
declare function requestAnimationFrame(callback: FrameRequestCallback): number;
/** @ntsBoundBy "nts:dom" cancelAnimationFrame */
declare function cancelAnimationFrame(handle: number): void;
