[package]
name = "nts-codegen-llvm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
nts-diagnostics.workspace = true
nts-core.workspace = true
nts-codegen-common.workspace = true

[lints]
workspace = true

[dev-dependencies]
nts-frontend-ts.workspace = true
nts-codegen-c.workspace = true
camino.workspace = true
