//! A [`Binding`] as files: the declaration module, the constants as values,
//! and what was refused.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

use anyhow::{Context, Result};
use camino::Utf8Path;

use super::map::{Binding, TypeDecl};

/// Every name of `c:types` a binding may use.
const BRANDS: &[&str] = &[
    "CArray", "CEnum", "Class", "ConstPtr", "Erased", "Opaque", "Ptr", "Struct", "Typedef", "Union", "Utf16String",
    "c_char", "c_double", "c_float", "c_int", "c_int16", "c_int64", "c_int8", "c_long", "c_long32", "c_uint",
    "c_uint16", "c_uint64", "c_uint8", "c_ulong", "c_ulong32",
];

/// The identifiers `text` uses, which decides what it imports.
fn identifiers(text: &str) -> BTreeSet<&str> {
    text.split(|c: char| !(c.is_ascii_alphanumeric() || c == '_')).filter(|w| !w.is_empty()).collect()
}

fn imports(body: &str, own: &str, owners: &BTreeMap<String, String>) -> String {
    let used = identifiers(body);
    let mut out = String::new();
    let brands: Vec<&str> = BRANDS.iter().copied().filter(|brand| used.contains(brand)).collect();
    if !brands.is_empty() {
        let _ = writeln!(out, "  import type {{ {} }} from \"c:types\";", brands.join(", "));
    }
    let mut foreign: BTreeMap<&str, Vec<&str>> = BTreeMap::new();
    for name in &used {
        if let Some(namespace) = owners.get(*name)
            && namespace != own
        {
            foreign.entry(namespace.as_str()).or_default().push(name);
        }
    }
    for (namespace, names) in foreign {
        let _ = writeln!(out, "  import type {{ {} }} from \"c:{namespace}\";", names.join(", "));
    }
    out
}

/// The header a documentation page names: `.../api/winuser/nf-winuser-...`.
fn header_of(documentation: Option<&str>) -> Option<String> {
    let path = documentation?.split("/api/").nth(1)?;
    Some(format!("{}.h", path.split('/').next()?))
}

pub(crate) fn write(binding: &Binding, out: &Utf8Path, command: &str, owners: &BTreeMap<String, String>) -> Result<()> {
    let stem = &binding.namespace;
    let mut body = String::new();
    for decl in &binding.types {
        match decl {
            TypeDecl::Alias { name, ts, .. } | TypeDecl::Record { name, ts, .. } => {
                let _ = writeln!(body, "  export type {name} = {ts};");
            }
            TypeDecl::Enum { name, members } => {
                let _ = writeln!(body, "  export const enum {name} {{");
                for (member, value) in members {
                    let _ = writeln!(body, "    {member} = {value},");
                }
                body.push_str("  }\n");
            }
        }
    }
    if !binding.types.is_empty() {
        body.push('\n');
    }
    for function in &binding.functions {
        body.push_str("  /**\n");
        if let Some(page) = &function.documentation {
            let _ = writeln!(body, "   * {page}");
        }
        let header = header_of(function.documentation.as_deref()).unwrap_or_else(|| "windows.h".into());
        let _ = writeln!(body, "   * Imported from `{}`; declared in `<{header}>`.", function.library);
        // The import library mingw names after the DLL: `USER32.dll` is
        // `-luser32`. A program links it only if it calls this.
        let library = function.library.to_ascii_lowercase();
        let _ = writeln!(body, "   * @ntsLibrary {}", library.strip_suffix(".dll").unwrap_or(&library));
        for parameter in &function.no_escape {
            let _ = writeln!(body, "   * @ntsNoEscape {parameter}");
        }
        body.push_str("   */\n");
        let parameters: Vec<String> = function.parameters.iter().map(|(name, ts)| format!("{}: {ts}", safe(name))).collect();
        let _ = writeln!(body, "  export function {}({}): {};", function.name, parameters.join(", "), function.result);
    }
    let mut declarations = String::new();
    let _ = writeln!(declarations, "// Generated by `{command}`. Edit the command, not this file.");
    declarations.push_str(
        "//\n// Each declaration's meaning is from Windows metadata and its C type from the\n\
         // Windows headers, and every one compiled against those headers before it\n\
         // was written.\n/**\n * @ntsHeader <windows.h>\n */\n",
    );
    let _ = writeln!(declarations, "declare module \"{}\" {{", binding.module);
    declarations.push_str(&imports(&body, stem, owners));
    declarations.push('\n');
    declarations.push_str(&body);
    declarations.push_str("}\n");
    write_file(&out.join(format!("{stem}.d.ts")), &declarations)?;

    let mut values = String::new();
    let _ = writeln!(values, "// Generated by `{command}`. Edit the command, not this file.");
    values.push_str("//\n// The constants that go with the declarations in the module of the same name.\n");
    let mut constants = String::new();
    for constant in &binding.constants {
        let _ = writeln!(constants, "export const {} = {} as {};", constant.name, constant.value, constant.ts);
    }
    let used = identifiers(&constants);
    let brands: Vec<&str> = BRANDS.iter().copied().filter(|brand| used.contains(brand)).collect();
    if !brands.is_empty() {
        let _ = writeln!(values, "import type {{ {} }} from \"c:types\";", brands.join(", "));
    }
    values.push_str(&constants);
    write_file(&out.join(format!("{stem}.values.ts")), &values)?;

    let mut refused = String::new();
    for (name, why) in &binding.refused {
        let _ = writeln!(refused, "{name}\t{why}");
    }
    write_file(&out.join(format!("{stem}.refused.txt")), &refused)
}

/// A parameter name TypeScript reserves, renamed.
pub(crate) fn safe(name: &str) -> String {
    const RESERVED: &[&str] = &["function", "default", "in", "new", "class", "var", "this", "delete", "void", "with", "case", "enum", "export", "import", "switch", "typeof", "yield", "package", "interface", "private", "protected", "public", "static", "let"];
    if RESERVED.contains(&name) { format!("{name}_") } else { name.to_owned() }
}

fn write_file(path: &Utf8Path, text: &str) -> Result<()> {
    std::fs::write(path, text).with_context(|| format!("writing {path}"))
}
