#ifndef NTS_ICU_H
#define NTS_ICU_H
#include "nts_runtime.h"

bool nts_icu_versions_match(void);
NtsHeader *nts_icu_segment_open(NtsString *locale, double granularity);
NtsHeader *nts_icu_segment_text(NtsHeader *handle, NtsString *input);
double nts_icu_segment_boundary(NtsHeader *handle, double index, double direction);
double nts_icu_segment_status(NtsHeader *handle);
NtsHeader *nts_icu_plural_open(NtsString *locale, bool ordinal, NtsString *skeleton, NtsString *negative_skeleton);
double nts_icu_plural_categories(NtsHeader *handle);
double nts_icu_plural_select(NtsHeader *handle, double value, bool negative);
double nts_icu_plural_decimal(NtsHeader *handle, NtsString *value, bool negative);
double nts_icu_plural_range(NtsHeader *handle, NtsString *start, NtsString *end, bool negative_start, bool negative_end);
NtsHeader *nts_icu_relative_open(NtsString *locale, double style);
NtsString *nts_icu_relative_format(NtsHeader *handle, double value, double unit, bool automatic, bool fields);
double nts_icu_relative_field_count(NtsHeader *handle);
double nts_icu_relative_field(NtsHeader *handle, double index, double component);
NtsHeader *nts_icu_date_open(NtsString *locale, NtsString *pattern, NtsString *time_zone);
NtsString *nts_icu_date_format(NtsHeader *handle, double milliseconds, bool fields);
NtsString *nts_icu_date_range(NtsHeader *handle, double start, double end, bool fields);
double nts_icu_date_field_count(NtsHeader *handle);
double nts_icu_date_field(NtsHeader *handle, double index, double component);
NtsHeader *nts_icu_date_patterns_open(NtsString *locale);
NtsString *nts_icu_date_best_pattern(NtsHeader *handle, NtsString *skeleton);
NtsString *nts_icu_date_style_pattern(NtsHeader *handle, double date_style, double time_style);
NtsArray *nts_icu_date_patterns(NtsHeader *handle);
double nts_icu_collation_defaults(NtsString *locale);
NtsHeader *nts_icu_collator_open(NtsString *locale, double sensitivity, bool punctuation, bool numeric, double case_first);
double nts_icu_collator_compare(NtsHeader *handle, NtsString *one, NtsString *two);
NtsHeader *nts_icu_locale_open(void);
NtsString *nts_icu_locale_transform(NtsString *tag, double operation);
NtsString *nts_icu_locale_default(void);
double nts_icu_locale_count(NtsHeader *handle);
NtsString *nts_icu_locale_available(NtsHeader *handle, double index);
NtsString *nts_icu_locale_best_fit(NtsHeader *handle, NtsString *tag);
NtsString *nts_icu_locale_numbering(NtsString *tag);
bool nts_icu_numbering_supported(NtsString *name);
NtsString *nts_icu_locale_type(NtsString *key, NtsString *value);
NtsArray *nts_icu_locale_values(NtsString *tag, double kind);
NtsArray *nts_icu_supported_values(double category);
bool nts_icu_currency_named(NtsString *code);
NtsHeader *nts_icu_display_open(NtsString *locale, double type, double style, bool dialect);
NtsString *nts_icu_display_name(NtsHeader *handle, NtsString *code, double field);
NtsString *nts_icu_timezone_primary(NtsString *name);
NtsArray *nts_icu_timezone_primary_names(void);
double nts_icu_script_direction(NtsString *script);
bool nts_icu_script_is_hebrew(double code_point);
NtsArray *nts_icu_locale_list_samples(NtsString *locale, double type, double style, NtsArray *tokens);
NtsArray *nts_icu_locale_duration_samples(NtsString *locale);
double nts_icu_locale_week(NtsString *region);
NtsString *nts_icu_timezone_canonical(NtsString *name);
NtsString *nts_icu_timezone_default(void);
NtsHeader *nts_icu_timezone_open(NtsString *id);
NtsString *nts_icu_timezone_id(NtsHeader *handle);
double nts_icu_timezone_offset(NtsHeader *handle, double epoch_ms);
double nts_icu_timezone_local_offset(NtsHeader *handle, double local_ms, bool former);
double nts_icu_timezone_transition(NtsHeader *handle, double epoch_ms, bool forward);
NtsHeader *nts_icu_number_open(NtsString *locale, NtsString *skeleton);
double nts_icu_currency_digits(NtsString *currency);
NtsString *nts_icu_number_format(NtsHeader *handle, double value, bool fields);
NtsString *nts_icu_number_decimal(NtsHeader *handle, NtsString *value, bool fields);
NtsHeader *nts_icu_number_range_open(NtsString *locale, NtsString *start_skeleton, NtsString *end_skeleton);
NtsString *nts_icu_number_range_format(NtsHeader *handle, NtsString *start, NtsString *end, bool fields);
double nts_icu_number_range_field_count(NtsHeader *handle);
double nts_icu_number_range_field(NtsHeader *handle, double index, double component);
double nts_icu_number_field_count(NtsHeader *handle);
double nts_icu_number_field(NtsHeader *handle, double index, double component);

#endif
