// Generated by `nts bind-c`. Edit the command, not this file.
//
// Derived from one compiler's reading of these headers under these macros,
// which makes it a claim like any hand-written binding. `native_witness.c`
// is what proves it against the headers a consumer actually compiles with.
/**
 * @ntsHeader /home/akisarou/Projects/nts/examples/workspace/packages/notifications/native/linux/scheduler.h
 */
declare module "c:notifications" {
  import type { Float64, Int32 } from "@nts/scalars";
  export function schedule_at(id: Int32, delay_millis: Float64): void;
  export function cancel_by_id(id: Int32): void;
  export function set_tap_handler(handler: (arg0: Int32) => void): void;
}
