[package]
name = "nts-suite"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "nts-suite"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
camino.workspace = true
nts-core.workspace = true
nts-differential.workspace = true
nts-frontend-ts.workspace = true
rustc-hash.workspace = true

[lints]
workspace = true
