//! The second backend: textual LLVM IR.
//!
//! # Why textual, and why a second backend at all
//!
//! Textual `.ll` fed to `clang -x ir` rather than a linked `llvm-sys`. Reading
//! `program.c` diagnosed three separate bugs in one week — a struct cast to a
//! double named an unreachable narrowing on sight, and a `module__init` visibly
//! not assigning a global exposed an initializer that had been silently
//! dropped. That legibility is a working instrument, not a nicety, and it is
//! worth keeping in the backend that is meant to become primary. It also avoids
//! pinning an LLVM version into the build.
//!
//! The C backend does not go away when this one grows up. It is the *oracle*:
//! one HIR, two renderers, and the differential already knows how to ask
//! whether a compiled program agrees with node. A disagreement between the two
//! backends is a backend bug by construction, which is the only cheap way to
//! find one. scriptc gave this up — their C backend cannot express coroutines,
//! so it is debug-only — and they gave it up because their suspension lives in
//! the backend. Ours lives in `hir::suspend`, which is what makes two real
//! backends possible at all.
//!
//! # What it maps
//!
//! HIR is already backend-neutral: `Convert` is a representation change that
//! specialization decided, `frame` is a placement decision from escape
//! analysis, `checked` is a bounds proof. Each renders differently here and
//! means the same thing.
//!
//! The one structural difference is *block parameters*. HIR is SSA with
//! arguments on edges, the way MLIR and Swift's SIL are; LLVM puts the join in
//! the successor as a `phi` listing one value per predecessor. The two carry
//! the same information and the translation is mechanical — which is the whole
//! reason the lowering chose block parameters rather than phis in the first
//! place.
//!
//! # What it does not do yet
//!
//! This is the scalar slice: numbers, integers and booleans, arithmetic,
//! comparison, calls between lowered functions, and control flow. Anything
//! managed is refused by name rather than half-emitted. A backend that emits
//! *something* for every input is a backend nobody can trust the output of.

pub mod signatures;

use std::fmt::Write as _;

use nts_core::hir::{BinOp, BlockId, Callee, Func, HirType, OpKind, Program, Terminator, UnOp, ValueId};
use nts_diagnostics::Diagnostic;

/// What the backend produced, and what it declined to.
#[derive(Debug)]
pub struct Emitted {
    pub text: String,
    pub diagnostics: Vec<Diagnostic>,
}

/// Render a whole program as textual LLVM IR.
///
/// A function this cannot render is *absent* and reported, exactly as the C
/// backend does: a caller that still calls it fails at the linker with a name,
/// which is a better failure than a body that silently means something else.
#[must_use]
pub fn emit(program: &Program) -> Emitted {
    let mut text = String::new();
    let mut diagnostics = Vec::new();
    let _ = writeln!(text, "; Generated by nts. Do not edit.");
    // What the runtime offers this backend, declared up front.
    //
    // `nts_to_int32` is `static inline` in the C header, which is right for C
    // and unreadable to anything else: a header is not a contract another code
    // generator can read. The runtime exposes a linkable form beside the inline
    // for exactly this, and these two are the first things to cross the C-to-
    // LLVM boundary -- a double in, an `i32` out, the simplest ABI there is to
    // get wrong.
    let _ = writeln!(text, "declare i32 @nts_to_int32_fn(double)");
    let _ = writeln!(text, "declare i32 @nts_to_uint32_fn(double)");
    let _ = writeln!(text, "declare ptr @nts_object_new(ptr)");
    let _ = writeln!(text, "declare ptr @nts_array_new(ptr, double)");
    let _ = writeln!(text, "declare i32 @nts_check_fn(ptr, i32)");
    let _ = writeln!(text, "declare void @nts_retain(ptr)");
    let _ = writeln!(text, "declare void @nts_release(ptr)");
    let _ = writeln!(text, "declare ptr @nts_concat(ptr, ptr)");
    let _ = writeln!(
        text,
        "declare zeroext i1 @nts_value_strict_eq(i32, i64, i32, i64)"
    );
    let _ = writeln!(text, "declare zeroext i1 @nts_string_truthy(ptr)");
    let _ = writeln!(text, "declare zeroext i16 @nts_unit_fn(ptr, i32)");
    let _ = writeln!(text, "declare double @nts_str_char_code_at_fn(ptr, double)");
    let _ = writeln!(text, "declare double @llvm.fabs.f64(double)");
    let _ = writeln!(text, "declare double @llvm.sqrt.f64(double)");
    let _ = writeln!(text, "declare i32 @nts_index_fn(ptr, double)");
    let _ = writeln!(text, "declare ptr @nts_array_new_uninitialized(ptr, double)");
    // The runtime's own, shared by every array of references: each element is a
    // pointer, so they are all the same shape and one descriptor serves them.
    let _ = writeln!(text, "@nts_desc_ref = external constant %NtsDescriptor");
    for line in externals(program) {
        let _ = writeln!(text, "{line}");
    }
    let _ = writeln!(text, "\n{}", descriptors(program));
    let _ = writeln!(text, "{}", literals(program));
    // Module-scope storage. `internal` unless the program exports it, for the
    // same reason the C backend makes it `static`: a name outside the program
    // is a name something outside can collide with.
    for (at, global) in program.globals.iter().enumerate() {
        let Ok(ty) = ty_of(&global.ty, &program.funcs[0]) else {
            continue;
        };
        let linkage = if global.exported { "" } else { "internal " };
        let zero = if matches!(global.ty, HirType::Managed(_)) {
            "null".to_owned()
        } else if matches!(global.ty, HirType::Float { .. }) {
            float_literal(global.initial)
        } else {
            // A global's recorded initial value is a double whatever the
            // slot's width is, and an integer slot's is a whole number by
            // construction -- `Global::initial` is what the lowering folded,
            // not an arbitrary value.
            #[allow(
                clippy::cast_possible_truncation,
                reason = "an integer global's initial value is whole by construction"
            )]
            let whole = global.initial as i64;
            format!("{whole}")
        };
        let _ = writeln!(
            text,
            "{} = {linkage}global {ty} {zero}",
            symbol(&global_symbol(program, at))
        );
    }
    for func in &program.funcs {
        match function(program, func) {
            Ok(rendered) => {
                let _ = writeln!(text, "\n{rendered}");
            }
            Err(diagnostic) => diagnostics.push(diagnostic),
        }
    }
    Emitted { text, diagnostics }
}

/// An erased value: the tag, and the union's eightbyte as an integer.
const ERASED_TYPE: &str = "{ i32, i64 }";

/// The tags, which are `typeof`'s answers in `typeof`'s order.
///
/// Read from the middle end rather than restated: `hir::tags` is where the
/// order is decided, and the order is load-bearing -- `"object"` is the range
/// test `tag >= OBJECT`, which is why `FUNCTION` sits below it.
fn tag_of(ty: &HirType) -> Option<u32> {
    use nts_core::hir::tags;
    Some(match ty {
        HirType::Bool => tags::BOOLEAN,
        HirType::Float { .. } | HirType::Int { .. } => tags::NUMBER,
        HirType::Managed(nts_core::hir::ManagedType::String) => tags::STRING,
        HirType::Managed(_) => tags::OBJECT,
        HirType::Void => tags::UNDEFINED,
        _ => return None,
    })
}

/// `NtsHeader`, as LLVM's own struct type: the same fields in the same order,
/// so it is laid out the way clang lays out the C one.
const HEADER_TYPE: &str = "%NtsHeader = type { ptr, i64, i32, i32 }";

/// Every string literal in the program, in the order the C backend numbers
/// them -- one table, so `nts_str_3` is the same string in both outputs.
///
/// A literal is static storage with an immortal count, so nothing ever tries to
/// free it. Emitted as code *units* rather than as an LLVM string constant for
/// the reason the C backend gives: an escape rule that is not JavaScript's is a
/// different string, and a wide literal is not bytes at all.
fn literals(program: &Program) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "{HEADER_TYPE}");
    let _ = writeln!(out, "@nts_desc_string1 = external constant %NtsDescriptor");
    let _ = writeln!(out, "@nts_desc_string2 = external constant %NtsDescriptor");
    for (index, text) in literal_table(program).iter().enumerate() {
        let units: Vec<u16> = text.encode_utf16().collect();
        let wide = units.iter().any(|unit| *unit > 0xFF);
        let (element, descriptor, flags) = if wide {
            ("i16", "@nts_desc_string2", 1)
        } else {
            ("i8", "@nts_desc_string1", 0)
        };
        // One more unit than the string holds, kept at zero, so a narrow one
        // can be handed to C directly.
        let mut data: Vec<String> = units
            .iter()
            .map(|unit| format!("{element} {unit}"))
            .collect();
        data.push(format!("{element} 0"));
        let _ = writeln!(
            out,
            "@nts_str_{index} = internal constant {{ %NtsHeader, [{count} x {element}] }} \
             {{ %NtsHeader {{ ptr {descriptor}, i64 {immortal}, i32 {flags}, i32 {length} }}, \
             [{count} x {element}] [{}] }}",
            data.join(", "),
            count = data.len(),
            immortal = nts_codegen_common::layout::IMMORTAL,
            length = units.len(),
        );
    }
    out
}

/// The literals a program holds, numbered the way the C backend numbers them.
fn literal_table(program: &Program) -> Vec<String> {
    let mut table: Vec<String> = Vec::new();
    for func in &program.funcs {
        for block in &func.blocks {
            for value in &block.ops {
                if let OpKind::ConstString(text) = &func.values[value.0 as usize].kind
                    && !table.contains(text)
                {
                    table.push(text.clone());
                }
            }
        }
    }
    table
}

/// `NtsDescriptor`, as LLVM's own struct type.
///
/// The field *types* in the runtime's order, not hand-computed offsets. LLVM
/// lays a struct out with the same rules clang does, so declaring the same
/// fields in the same order matches by construction -- which is the whole
/// difference between this and deriving an ABI, and it is why there is nothing
/// here to get wrong by four bytes.
const DESCRIPTOR_TYPE: &str =
    "%NtsDescriptor = type { i32, i32, i32, i32, ptr, ptr, ptr, i32, ptr }";

/// `NTS_KIND_OBJECT`. The other kinds belong to the runtime's own types.
const KIND_OBJECT: u32 = 2;

/// Every descriptor the program needs, with the tables they point at.
///
/// What goes *in* one is already shared: `cyclic_layouts` and
/// `reference_fields` are `nts_core::hir`'s, and the offsets are the layout
/// engine's. Only the rendering is the backend's, which is what a backend is.
fn descriptors(program: &Program) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "{DESCRIPTOR_TYPE}");
    let cyclic = program.cyclic_layouts();
    for (index, layout) in program.layouts.iter().enumerate() {
        let Some(placed) = nts_codegen_common::layout::place(&layout.fields) else {
            continue;
        };
        let tag = descriptor_name(layout);
        let mut offsets = |which: &str, wanted: &[u32]| -> String {
            if wanted.is_empty() {
                return "ptr null".to_owned();
            }
            let entries: Vec<String> = wanted.iter().map(|at| format!("i32 {at}")).collect();
            let _ = writeln!(
                out,
                "@nts_{which}_{tag} = internal constant [{} x i32] [{}]",
                wanted.len(),
                entries.join(", ")
            );
            format!("ptr @nts_{which}_{tag}")
        };
        let references: Vec<u32> = layout
            .fields
            .iter()
            .enumerate()
            .filter(|(_, field)| field.ty.may_hold_a_reference())
            .filter_map(|(at, _)| placed.offsets.get(at).copied())
            .collect();
        let erased: Vec<u32> = layout
            .fields
            .iter()
            .enumerate()
            .filter(|(_, field)| field.ty == HirType::Erased)
            .filter_map(|(at, _)| placed.offsets.get(at).copied())
            .collect();
        let reference_table = offsets("refs", &references);
        let erased_table = offsets("erased", &erased);
        // The name is a C string, terminator and all: the runtime prints it.
        let bytes = layout.name.len() + 1;
        let _ = writeln!(
            out,
            "@nts_name_{tag} = internal constant [{bytes} x i8] c\"{}\\00\"",
            layout.name
        );
        let is_cyclic = u32::from(cyclic.get(index).copied().unwrap_or(true));
        let _ = writeln!(
            out,
            "@nts_desc_{tag} = internal constant %NtsDescriptor {{ i32 {KIND_OBJECT}, \
             i32 {}, i32 {}, i32 {is_cyclic}, {reference_table}, ptr null, \
             ptr @nts_name_{tag}, i32 {}, {erased_table} }}",
            placed.size,
            references.len(),
            erased.len()
        );
    }
    // One per scalar element type an array is made of. An array of references
    // uses the runtime's `nts_desc_ref`, declared above.
    let mut seen: Vec<String> = Vec::new();
    for func in &program.funcs {
        for op in &func.values {
            if !matches!(op.kind, OpKind::ArrayNew { .. }) {
                continue;
            }
            let HirType::Managed(nts_core::hir::ManagedType::Array(element)) = &op.ty else {
                continue;
            };
            if element.is_managed() {
                continue;
            }
            let Some(shape) = nts_codegen_common::layout::shape_of(element) else {
                continue;
            };
            let tag = element_tag(element);
            if seen.contains(&tag) {
                continue;
            }
            seen.push(tag.clone());
            let _ = writeln!(
                out,
                "@nts_name_arr_{tag} = internal constant [{} x i8] c\"{tag}[]\\00\"",
                tag.len() + 3
            );
            // For an array, `erased` is a fact about *every* element rather
            // than a table of offsets, exactly as `references` is. One that
                // said zero would never be walked, and a string held in it
            // would be released while something still pointed at it.
            let erased = u32::from(**element == HirType::Erased);
            let _ = writeln!(
                out,
                "@nts_desc_arr_{tag} = internal constant %NtsDescriptor {{ i32 0, i32 {}, \
                 i32 0, i32 0, ptr null, ptr null, ptr @nts_name_arr_{tag}, i32 {erased}, \
                 ptr null }}",
                shape.size
            );
        }
    }
    out
}

/// A global's symbol, which is its source name.
fn global_symbol(program: &Program, at: usize) -> String {
    program
        .globals
        .get(at)
        .map_or_else(|| format!("nts_global_{at}"), |global| global.name.clone())
}

/// The address of an array's element block, and the index into it.
///
/// Leaves `%out.blk` holding the address of the `elements` field and `%out.i`
/// holding the checked index, which the caller loads and indexes through.
fn index_lines(
    func: &Func,
    out: &str,
    array: ValueId,
    index: ValueId,
    checked: bool,
) -> Vec<String> {
    let mut lines = vec![format!(
        "{out}.blk = getelementptr i8, ptr {}, i64 {}",
        name(array),
        nts_codegen_common::layout::ELEMENTS_OFFSET
    )];
    let integral = matches!(func.values[index.0 as usize].ty, HirType::Int { .. });
    if checked {
        if integral {
            lines.push(format!(
                "{out}.i = call i32 @nts_check_fn(ptr {}, i32 {})",
                name(array),
                name(index)
            ));
        } else {
            lines.push(format!(
                "{out}.i = call i32 @nts_index_fn(ptr {}, double {})",
                name(array),
                name(index)
            ));
        }
    } else if integral {
        lines.push(format!("{out}.i = add i32 {}, 0", name(index)));
    } else {
        // Proven in range, so the conversion is exact whichever representation
        // it arrived in.
        lines.push(format!("{out}.i = fptoui double {} to i32", name(index)));
    }
    lines
}

/// A name for a scalar element type, for the descriptor it needs.
fn element_tag(ty: &HirType) -> String {
    match ty {
        HirType::Bool => "bool".to_owned(),
        HirType::Erased => "value".to_owned(),
        HirType::Float { bits } => format!("f{bits}"),
        HirType::Int { bits, signed: true } => format!("i{bits}"),
        HirType::Int { bits, signed: false } => format!("u{bits}"),
        other => format!("{other:?}"),
    }
}

/// A layout's descriptor symbol, with anything LLVM dislikes replaced.
fn descriptor_name(layout: &nts_core::hir::Layout) -> String {
    layout
        .name
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect()
}

/// One `declare` per runtime helper the program calls, from `signatures`.
///
/// Read off the *call site* at first, which is sound only where the lowering's
/// types and the runtime's already agree -- and they do not. `nts_tag_name`
/// takes a `uint32_t` and the lowering hands it a double, because C converts
/// implicitly at the call and the C backend never had to notice. The declared
/// double went into an SSE register, the callee read an integer one, and
/// `typeof v` answered "undefined" for a number. Found by the cross-backend
/// test, which is the only thing that could have.
fn externals(program: &Program) -> Vec<String> {
    let mut seen: Vec<String> = Vec::new();
    let mut lines = Vec::new();
    for func in &program.funcs {
        for op in &func.values {
            let OpKind::Call {
                callee: Callee::External(target),
                ..
            } = &op.kind
            else {
                continue;
            };
            if seen.iter().any(|name| name == target) {
                continue;
            }
            let Some(known) = signatures::signature(target) else {
                continue;
            };
            seen.push(target.clone());
            lines.push(format!(
                "declare {} {}({})",
                known.returns,
                symbol(target),
                known.params.join(", ")
            ));
        }
    }
    lines
}

/// The LLVM type a value of this HIR type lives in.
fn ty_of(ty: &HirType, func: &Func) -> Result<&'static str, Diagnostic> {
    Ok(match ty {
        HirType::Void => "void",
        HirType::Bool => "i1",
        HirType::Float { bits: 32 } => "float",
        HirType::Float { .. } => "double",
        HirType::Int { bits: 8, .. } => "i8",
        HirType::Int { bits: 16, .. } => "i16",
        HirType::Int { bits: 32, .. } => "i32",
        HirType::Int { bits: 64, .. } => "i64",
        // Exact, and 128 bits rather than arbitrary precision -- the same
        // promise the C backend makes with `__int128`, which is where LLVM's
        // `i128` is what clang lowers that to anyway.
        HirType::BigInt => "i128",
        // One opaque pointer, whatever it points at. LLVM has had no other
        // kind since 17, and it is the same fact the C backend leans on when a
        // field's type has no layout: every managed value is a pointer.
        HirType::Managed(_) => "ptr",
        // `NtsValue`: a tag beside a union of a double, a bool and a pointer.
        //
        // The *type* is easy and the **ABI** is not, which is why this was
        // refused until clang was asked. `clang -S -emit-llvm` on a function
        // taking one prints `define { i32, i64 } @f(i32 %0, i64 %1)`: System V
        // classifies the sixteen bytes as two eightbytes, and the second is
        // `i64` rather than `double` because the union holds a pointer. So an
        // erased value is this aggregate inside a function and *two scalars*
        // across a call, which `function` and the call arm below arrange.
        HirType::Erased => ERASED_TYPE,
        other => {
            return Err(refuse(
                func,
                &format!("a value of type {other:?}, which this backend does not render yet"),
            ));
        }
    })
}

/// The extension attribute a value of this type carries across a call.
///
/// Taken from clang rather than derived. A `_Bool` is passed `zeroext`, an
/// `int8_t` `signext`, a `uint16_t` `zeroext`, and anything word-sized or
/// wider nothing at all -- which is what `clang -S -emit-llvm` prints for the
/// same declarations, and the only way to be sure is to look.
///
/// On x86-64 a bare `i1` happens to work, because both ends use the low bit of
/// a register. "Happens to work" is not an ABI: the runtime is compiled by
/// clang and this has to agree with it on every target, not on the one it was
/// written on. This is the whole of the ABI story for the scalar slice --
/// `NtsValue` by value is the part that is not, and it is refused rather than
/// guessed at.
fn extension(ty: &HirType) -> &'static str {
    match ty {
        HirType::Int {
            bits: 8 | 16,
            signed: true,
        } => "signext ",
        // A `_Bool` and an unsigned narrow integer are the same case: neither
        // has a sign bit to carry into the upper half of the register.
        HirType::Bool
        | HirType::Int {
            bits: 8 | 16,
            signed: false,
        } => "zeroext ",
        _ => "",
    }
}

fn refuse(func: &Func, what: &str) -> Diagnostic {
    Diagnostic::error(
        "NTS3001",
        format!("{what} (in `{}`)", func.name),
        func.origin.location,
    )
}

/// A value's name in the emitted IR.
///
/// `%v12` for every value, including block parameters: SSA names are unique
/// per function and the HIR's are already numbered, so nothing has to be
/// invented or tracked.
fn name(value: ValueId) -> String {
    format!("%v{}", value.0)
}

fn label(block: BlockId) -> String {
    format!("b{}", block.0)
}

/// A function's symbol, mangled the way the C backend mangles it.
///
/// Not LLVM's quoted form, which was the first answer and the wrong one. An
/// exported name is an ABI a human links against, so it cannot depend on which
/// backend produced the object -- and `module#init` became `module__init` in
/// one output and `@"module#init"` in the other, so a driver could link against
/// exactly one of them. The rule lives in `nts_codegen_common::symbols` now and
/// both backends read it.
fn symbol(raw: &str) -> String {
    format!("@{}", nts_codegen_common::symbols::c_identifier(raw))
}

fn function(program: &Program, func: &Func) -> Result<String, Diagnostic> {
    let mut out = String::new();
    let returns = ty_of(&func.return_type, func)?;
    let mut params = Vec::new();
    // An erased parameter arrives as two scalars and is put back together at
    // the top of the entry block, which is what clang does for the same C.
    let mut prologue: Vec<String> = Vec::new();
    for (at, param) in func.params.iter().enumerate() {
        let ty = ty_of(&param.ty, func)?;
        // A parameter's *value* is whichever op is `Param(at)`, which is how
        // the rest of the function names it.
        let value = func
            .values
            .iter()
            .position(|op| matches!(op.kind, OpKind::Param(slot) if slot as usize == at))
            .map_or_else(
                || format!("%unused{at}"),
                |index| name(ValueId(u32::try_from(index).unwrap_or(0))),
            );
        if param.ty == HirType::Erased {
            params.push(format!("i32 {value}.tag"));
            params.push(format!("i64 {value}.bits"));
            prologue.push(format!(
                "{value}.half = insertvalue {ERASED_TYPE} undef, i32 {value}.tag, 0"
            ));
            prologue.push(format!(
                "{value} = insertvalue {ERASED_TYPE} {value}.half, i64 {value}.bits, 1"
            ));
        } else {
            params.push(format!("{ty} {}{value}", extension(&param.ty)));
        }
    }
    let linkage = if func.exported { "" } else { "internal " };
    let _ = writeln!(
        out,
        "define {linkage}{}{returns} {}({}) {{",
        extension(&func.return_type),
        symbol(&func.name),
        params.join(", ")
    );

    for (index, block) in func.blocks.iter().enumerate() {
        let id = BlockId(u32::try_from(index).unwrap_or(0));
        let _ = writeln!(out, "{}:", label(id));
        if index == 0 {
            for line in &prologue {
                let _ = writeln!(out, "  {line}");
            }
        }
        // Block parameters become `phi`, one incoming per predecessor edge.
        for (slot, param) in block.params.iter().enumerate() {
            let ty = ty_of(&func.values[param.0 as usize].ty, func)?;
            let incoming = incoming_for(func, id, slot);
            if incoming.is_empty() {
                return Err(refuse(
                    func,
                    &format!("a block parameter no edge supplies, in {}", label(id)),
                ));
            }
            let _ = writeln!(
                out,
                "  {} = phi {ty} {}",
                name(*param),
                incoming.join(", ")
            );
        }
        for value in &block.ops {
            let line = operation(program, func, *value)?;
            if !line.is_empty() {
                let _ = writeln!(out, "  {line}");
            }
        }
        let _ = writeln!(out, "  {}", terminator(func, &block.terminator)?);
    }
    let _ = writeln!(out, "}}");
    Ok(out)
}

/// Every `[value, %predecessor]` pair reaching one block parameter.
fn incoming_for(func: &Func, target: BlockId, slot: usize) -> Vec<String> {
    let mut pairs = Vec::new();
    for (index, block) in func.blocks.iter().enumerate() {
        let from = BlockId(u32::try_from(index).unwrap_or(0));
        let mut add = |to: BlockId, args: &[ValueId]| {
            if to == target && let Some(value) = args.get(slot) {
                pairs.push(format!("[ {}, %{} ]", name(*value), label(from)));
            }
        };
        match &block.terminator {
            Terminator::Jump { target: to, args } => add(*to, args),
            Terminator::Branch {
                then_target,
                then_args,
                else_target,
                else_args,
                ..
            } => {
                add(*then_target, then_args);
                add(*else_target, else_args);
            }
            _ => {}
        }
    }
    pairs
}

fn terminator(func: &Func, term: &Terminator) -> Result<String, Diagnostic> {
    Ok(match term {
        Terminator::Return(Some(value)) => {
            let ty = ty_of(&func.values[value.0 as usize].ty, func)?;
            format!("ret {ty} {}", name(*value))
        }
        Terminator::Return(None) => "ret void".to_owned(),
        Terminator::Jump { target, .. } => format!("br label %{}", label(*target)),
        Terminator::Branch {
            cond,
            then_target,
            else_target,
            ..
        } => format!(
            "br i1 {}, label %{}, label %{}",
            name(*cond),
            label(*then_target),
            label(*else_target)
        ),
        // A claim the compiler is making, and LLVM has the same word for it.
        Terminator::Unreachable => "unreachable".to_owned(),
        // Not a claim, an absence -- and the C backend's note explains what
        // rendering it as a licence cost once. Refused rather than rendered.
        Terminator::FellThrough => {
            return Err(refuse(func, "a block that falls out of the end of a function"));
        }
    })
}

/// Where a field sits, and what it holds.
///
/// The offset comes from the layout engine and the *type* from the operation
/// rather than from the layout: a field whose own type has no layout is a
/// pointer here exactly as it is in the C backend, and the operation says so.
fn field_at(
    program: &Program,
    func: &Func,
    object: ValueId,
    field: u32,
    ty: &HirType,
) -> Result<(u32, &'static str), Diagnostic> {
    let HirType::Managed(nts_core::hir::ManagedType::Object(id)) =
        &func.values[object.0 as usize].ty
    else {
        return Err(refuse(func, "a field of something that is not an object"));
    };
    let layout = program
        .layouts
        .iter()
        .find(|layout| layout.types.contains(id))
        .ok_or_else(|| refuse(func, "a field of a type with no layout"))?;
    let placed = nts_codegen_common::layout::place(&layout.fields)
        .ok_or_else(|| refuse(func, "an object whose fields cannot be placed"))?;
    let offset = *placed
        .offsets
        .get(field as usize)
        .ok_or_else(|| refuse(func, "a field index outside its layout"))?;
    Ok((offset, ty_of(ty, func)?))
}

fn operation(program: &Program, func: &Func, value: ValueId) -> Result<String, Diagnostic> {
    let op = &func.values[value.0 as usize];
    let out = name(value);
    Ok(match &op.kind {
        // Already named by the signature.
        OpKind::Param(_) | OpKind::BlockParam(_) => String::new(),
        OpKind::ConstFloat(number) => {
            // LLVM reads a float literal as a C double, and prints one back
            // exactly when it is written in full. `fadd double %x, 1.0` is the
            // shape, and a value that is not representable is written as its
            // bits so nothing is lost in the spelling.
            format!("{out} = fadd double 0.0, {}", float_literal(*number))
        }
        OpKind::ConstInt(number) => {
            let ty = ty_of(&op.ty, func)?;
            format!("{out} = add {ty} 0, {number}")
        }
        // The address of the static storage, which is what a string value is.
        OpKind::ConstString(text) => {
            let index = literal_table(program)
                .iter()
                .position(|known| known == text)
                .unwrap_or(0);
            format!("{out} = getelementptr i8, ptr @nts_str_{index}, i64 0")
        }
        OpKind::ConstBool(flag) => {
            format!("{out} = add i1 0, {}", u8::from(*flag))
        }
        OpKind::Erase { .. } | OpKind::Unerase { .. } | OpKind::TagOf { .. } => {
            return tagging(func, value, &out);
        }
        // Before the general binary arm, because it *is* a binary and the
        // general one would match it first -- and an `icmp` on a sixteen-byte
        // aggregate is not an instruction.
        OpKind::Binary {
            op: BinOp::Eq | BinOp::Ne,
            lhs,
            ..
        } if func.values[lhs.0 as usize].ty == HirType::Erased => {
            return tagging(func, value, &out);
        }
        // Two operators wear the `+` token and this is the other one. The
        // lowering already decided which, from the result type, so there is
        // nothing to work out here.
        OpKind::Binary {
            op: BinOp::Concat,
            lhs,
            rhs,
        } => format!(
            "{out} = call ptr @nts_concat(ptr {}, ptr {})",
            name(*lhs),
            name(*rhs)
        ),
        OpKind::Binary { op: bin, lhs, rhs } => {
            let ty = ty_of(&func.values[lhs.0 as usize].ty, func)?;
            let float = matches!(func.values[lhs.0 as usize].ty, HirType::Float { .. });
            let instruction = binary(*bin, float, func)?;
            format!(
                "{out} = {instruction} {ty} {}, {}",
                name(*lhs),
                name(*rhs)
            )
        }
        OpKind::Unary { op: un, operand } => unary(func, &out, *un, *operand)?,
        // A representation change specialization decided on. The C backend
        // spells it as a cast; LLVM makes the direction explicit, which is the
        // same instruction and a better record of what was meant.
        //
        // Out-of-range float to integer is undefined in C and poison here --
        // the same hazard by the same argument, and specialization only emits
        // one where the interval analysis proved the value fits.
        OpKind::Convert(operand) => {
            let from = &func.values[operand.0 as usize].ty;
            let to = &op.ty;
            let instruction = conversion(from, to, func)?;
            format!(
                "{out} = {instruction} {} {} to {}",
                ty_of(from, func)?,
                name(*operand),
                ty_of(to, func)?
            )
        }
        OpKind::Call { .. } => return call(func, value, &out),
        // A null pointer, which is what an absent reference is: the one spare
        // value a pointer has, and the whole reason `T | null` costs nothing.
        OpKind::ConstNull | OpKind::ConstUndefined if matches!(op.ty, HirType::Managed(_)) => {
            format!("{out} = inttoptr i64 0 to ptr")
        }
        // Where there are *two* absences the value is erased and each has a tag
        // of its own, which is the whole reason that union is not a pointer.
        // The payload is zero rather than undefined: a program that reads it
        // through a wrong narrowing then gets a zero rather than whatever was
        // in the register, which is the same choice `nts_value_of_undefined`
        // makes.
        OpKind::ConstNull | OpKind::ConstUndefined if op.ty == HirType::Erased => {
            let tag = if matches!(op.kind, OpKind::ConstNull) {
                nts_core::hir::tags::NULL
            } else {
                nts_core::hir::tags::UNDEFINED
            };
            format!(
                "{out}.half = insertvalue {ERASED_TYPE} undef, i32 {tag}, 0\n  \
                 {out} = insertvalue {ERASED_TYPE} {out}.half, i64 0, 1"
            )
        }
        _ => return memory_operation(program, func, value, &out),
    })
}

/// The two operations that make an object.
///
/// Both need a descriptor, which is the piece of the runtime a backend has to
/// *build* rather than call: it is data the collector reads, so it is emitted
/// here and everything in it comes from the middle end.
///
/// On the heap that is the allocator handed the descriptor; in the frame it is
/// an `alloca` and the header written out, which is what the C backend's
/// `v_frame.header.descriptor = ...` compiles to and one of the reasons escape
/// analysis is worth having.
fn allocation(
    program: &Program,
    func: &Func,
    value: ValueId,
    out: &str,
) -> Result<String, Diagnostic> {
    let op = &func.values[value.0 as usize];
    let out = out.to_owned();
    Ok(match &op.kind {
        OpKind::ArrayNew { length, zeroed } => {
            let HirType::Managed(nts_core::hir::ManagedType::Array(element)) = &op.ty else {
                return Err(refuse(func, "an array of something with no element type"));
            };
            // Two entry points rather than a flag, so the branch is taken here
            // rather than once per allocation at run time.
            let allocate = if *zeroed {
                "@nts_array_new"
            } else {
                "@nts_array_new_uninitialized"
            };
            let descriptor = if element.is_managed() {
                "@nts_desc_ref".to_owned()
            } else {
                format!("@nts_desc_arr_{}", element_tag(element))
            };
            format!(
                "{out} = call ptr {allocate}(ptr {descriptor}, double {})",
                name(*length)
            )
        }
        OpKind::ObjectNew { frame } => {
            let HirType::Managed(nts_core::hir::ManagedType::Object(id)) = &op.ty else {
                return Err(refuse(func, "an allocation of something that is not an object"));
            };
            let layout = program
                .layouts
                .iter()
                .find(|layout| layout.types.contains(id))
                .ok_or_else(|| refuse(func, "an allocation of a type with no layout"))?;
            let placed = nts_codegen_common::layout::place(&layout.fields)
                .ok_or_else(|| refuse(func, "an object whose fields cannot be placed"))?;
            let tag = descriptor_name(layout);
            if *frame {
                // `NTS_IMMORTAL` in the count word, so the counting pass's
                // release is a no-op on storage that was never allocated.
                [
                    format!("{out} = alloca i8, i64 {}, align {}", placed.size, placed.align),
                    format!("store ptr @nts_desc_{tag}, ptr {out}"),
                    format!("{out}.rc = getelementptr i8, ptr {out}, i64 8"),
                    format!(
                        "store i64 {}, ptr {out}.rc",
                        nts_codegen_common::layout::IMMORTAL
                    ),
                ]
                .join("\n  ")
            } else {
                format!("{out} = call ptr @nts_object_new(ptr @nts_desc_{tag})")
            }
        }
        other => {
            return Err(refuse(
                func,
                &format!("the operation {other:?}, which does not allocate"),
            ));
        }
    })
}

/// Reading and writing an array's elements.
///
/// The block is a separate allocation -- which is what lets an array grow
/// without the object moving -- so this is a load of the block pointer and then
/// an index into it.
fn element_access(func: &Func, value: ValueId, out: &str) -> Result<String, Diagnostic> {
    let op = &func.values[value.0 as usize];
    let out = out.to_owned();
    Ok(match &op.kind {
        OpKind::ArrayGet {
            array,
            index,
            checked,
        } => {
            let element = ty_of(&op.ty, func)?;
            let mut lines = index_lines(func, &out, *array, *index, *checked);
            lines.push(format!("{out}.block = load ptr, ptr {out}.blk"));
            lines.push(format!(
                "{out}.at = getelementptr {element}, ptr {out}.block, i32 {out}.i"
            ));
            lines.push(format!("{out} = load {element}, ptr {out}.at"));
            lines.join("\n  ")
        }
        OpKind::ArraySet {
            array,
            index,
            value,
            checked,
        } => {
            let element = ty_of(&func.values[value.0 as usize].ty, func)?;
            let mut lines = index_lines(func, &out, *array, *index, *checked);
            lines.push(format!("{out}.block = load ptr, ptr {out}.blk"));
            lines.push(format!(
                "{out}.at = getelementptr {element}, ptr {out}.block, i32 {out}.i"
            ));
            lines.push(format!("store {element} {}, ptr {out}.at", name(*value)));
            lines.join("\n  ")
        }
        other => {
            return Err(refuse(
                func,
                &format!("the operation {other:?}, which is not an element access"),
            ));
        }
    })
}

/// Counting, and module-scope storage.
///
/// The counting pass decides where a retain and a release go and both backends
/// emit one call each; under `NoGC` there are none, because the pass that would
/// have inserted them did not run. A global is `internal` unless the program
/// exports it, for the same reason the C backend makes it `static`.
fn counting_or_global(program: &Program, func: &Func, value: ValueId, out: &str)
    -> Result<String, Diagnostic>
{
    let op = &func.values[value.0 as usize];
    let out = out.to_owned();
    Ok(match &op.kind {
        // Counting, which the memory provider decides and both backends emit
        // the same way: one call each, and nothing under NoGC because the pass
        // that would have inserted them did not run.
        OpKind::Retain(object) => format!("call void @nts_retain(ptr {})", name(*object)),
        OpKind::Release(object) => format!("call void @nts_release(ptr {})", name(*object)),
        OpKind::GlobalGet(global) => {
            let ty = ty_of(&op.ty, func)?;
            format!(
                "{out} = load {ty}, ptr {}",
                symbol(&global_symbol(program, *global as usize))
            )
        }
        OpKind::GlobalSet { global, value } => {
            let ty = ty_of(&func.values[value.0 as usize].ty, func)?;
            format!(
                "store {ty} {}, ptr {}",
                name(*value),
                symbol(&global_symbol(program, *global as usize))
            )
        }
        other => {
            return Err(refuse(
                func,
                &format!("the operation {other:?}, which is neither counting nor a global"),
            ));
        }
    })
}

/// Reading a length, and reading a code unit.
///
/// Both are a load through a header, and both differ from an array's rule in
/// the same direction: a string is immutable and cannot grow, so its count is
/// the header's own and an index out of range answers NaN rather than trapping.
fn text_operation(func: &Func, value: ValueId, out: &str) -> Result<String, Diagnostic> {
    let op = &func.values[value.0 as usize];
    let out = out.to_owned();
    Ok(match &op.kind {
        // The count is the last four bytes of the header, whatever it belongs
        // to: an array reaches through its header because it can grow, and a
        // string *is* one.
        // A code unit. Checked goes through the runtime, which answers NaN out
        // of range rather than trapping -- a string's rule, and the opposite of
        // an array's.
        OpKind::StringUnitAt {
            string,
            index,
            checked,
        } => {
            if *checked {
                format!(
                    "{out} = call double @nts_str_char_code_at_fn(ptr {}, double {})",
                    name(*string),
                    name(*index)
                )
            } else {
                let raw = format!("{out}.u");
                format!(
                    "{raw} = call zeroext i16 @nts_unit_fn(ptr {}, i32 {})\n  \
                     {out} = uitofp i16 {raw} to double",
                    name(*string),
                    name(*index)
                )
            }
        }
        OpKind::Length(of) => {
            let returns = ty_of(&op.ty, func)?;
            let at = format!("{out}.at");
            let raw = format!("{out}.raw");
            let offset = nts_codegen_common::layout::LENGTH_OFFSET;
            let mut lines = vec![
                format!("{at} = getelementptr i8, ptr {}, i64 {offset}", name(*of)),
                format!("{raw} = load i32, ptr {at}"),
            ];
            lines.push(if returns == "i32" {
                format!("{out} = add i32 {raw}, 0")
            } else {
                format!("{out} = uitofp i32 {raw} to {returns}")
            });
            lines.join("\n  ")
        }
        other => {
            return Err(refuse(
                func,
                &format!("the operation {other:?}, which reads no length"),
            ));
        }
    })
}

/// Putting a value in a tagged one, taking it back out, and comparing two.
///
/// The whole of what a tag is *for*: `1 == true` and `[1] == 1` are questions
/// only a tag can answer, and the runtime answers them. The payload eightbyte
/// holds the union's first member, the `double`, so an integer is converted
/// before it is stored -- the same conversion `nts_value_of_number(x)` makes.
fn tagging(func: &Func, value: ValueId, out: &str) -> Result<String, Diagnostic> {
    let op = &func.values[value.0 as usize];
    let out = out.to_owned();
    Ok(match &op.kind {
        // Comparing two tagged values, which is the one thing carrying a tag is
        // *for*: `1 == true` and `[1] == 1` are questions only a tag can
        // answer, and the runtime answers them. Four scalars, because each
        // sixteen-byte value is two.
        OpKind::Binary {
            op: bin @ (BinOp::Eq | BinOp::Ne),
            lhs,
            rhs,
        } => {
            let parts: Vec<String> = [lhs, rhs]
                .iter()
                .enumerate()
                .flat_map(|(at, held)| {
                    [
                        format!("{out}.t{at} = extractvalue {ERASED_TYPE} {}, 0", name(**held)),
                        format!("{out}.p{at} = extractvalue {ERASED_TYPE} {}, 1", name(**held)),
                    ]
                })
                .collect();
            let same = format!("{out}.eq");
            let call = format!(
                "{same} = call zeroext i1 @nts_value_strict_eq(i32 {out}.t0, i64 {out}.p0, \
                 i32 {out}.t1, i64 {out}.p1)"
            );
            let answer = if matches!(bin, BinOp::Ne) {
                format!("{out} = xor i1 {same}, true")
            } else {
                format!("{out} = add i1 {same}, 0")
            };
            format!("{}\n  {call}\n  {answer}", parts.join("\n  "))
        }
        // Putting a value in a tagged one. The payload eightbyte holds the
        // union's first member, which is the `double` -- so an *integer* is
        // converted before it is stored, exactly as the C backend's
        // `nts_value_of_number(x)` converts it, and a bool and a pointer are
        // widened to the same eightbyte.
        OpKind::Erase { value } => {
            let from = &func.values[value.0 as usize].ty;
            let tag = tag_of(from)
                .ok_or_else(|| refuse(func, &format!("erasing a value of type {from:?}")))?;
            let bits = format!("{out}.bits");
            let widen = payload_from(func, &out, &bits, from, *value)?;
            format!(
                "{widen}\n  {out}.half = insertvalue {ERASED_TYPE} undef, i32 {tag}, 0\n  \
                 {out} = insertvalue {ERASED_TYPE} {out}.half, i64 {bits}, 1"
            )
        }
        // Reading the payload back, at the type the checker narrowed to.
        // Unchecked by construction, exactly as the C backend's union read is:
        // the licence comes from the narrowing and from nothing else.
        OpKind::Unerase { value } => {
            let bits = format!("{out}.bits");
            let read = format!("{bits} = extractvalue {ERASED_TYPE} {}, 1", name(*value));
            let narrow = payload_into(func, &out, &bits, &op.ty)?;
            format!("{read}\n  {narrow}")
        }
        OpKind::TagOf { value } => {
            format!("{out} = extractvalue {ERASED_TYPE} {}, 0", name(*value))
        }
        other => {
            return Err(refuse(
                func,
                &format!("the operation {other:?}, which reads no tag"),
            ));
        }
    })
}

/// A call, direct or into the runtime.
///
/// Two things happen here that C does silently. An erased argument becomes
/// *two* scalars, because that is how the platform passes a sixteen-byte
/// struct. And an argument whose type is not the one the runtime declares is
/// converted -- C does that at the call and says nothing, which is how
/// `nts_tag_name(uint32_t)` came to be handed a double.
fn call(func: &Func, value: ValueId, out: &str) -> Result<String, Diagnostic> {
    let op = &func.values[value.0 as usize];
    let out = out.to_owned();
    Ok(match &op.kind {
        OpKind::Call { callee, args, .. } => {
            let returns = ty_of(&op.ty, func)?;
            let target = match callee {
                Callee::Direct(target) | Callee::External(target) => target,
                // A dispatch through a method table. It needs the table, which
                // needs a descriptor, which is the next thing to build.
                Callee::Virtual { .. } | Callee::Closure { .. } => {
                    return Err(refuse(func, "a dispatched call, which needs a method table"));
                }
            };
            let mut rendered = Vec::new();
            let mut before: Vec<String> = Vec::new();
            for arg in args {
                let arg_ty = &func.values[arg.0 as usize].ty;
                // Two scalars, because that is how the platform passes a
                // sixteen-byte struct and how clang emits the same call.
                if *arg_ty == HirType::Erased {
                    let tag = format!("{}.a{}", out, arg.0);
                    let bits = format!("{}.b{}", out, arg.0);
                    before.push(format!(
                        "{tag} = extractvalue {ERASED_TYPE} {}, 0",
                        name(*arg)
                    ));
                    before.push(format!(
                        "{bits} = extractvalue {ERASED_TYPE} {}, 1",
                        name(*arg)
                    ));
                    rendered.push(format!("i32 {tag}"));
                    rendered.push(format!("i64 {bits}"));
                    continue;
                }
                let ty = ty_of(arg_ty, func)?;
                // What the runtime actually declares, where it declares one.
                // C converts at the call and says nothing; here the conversion
                // has to be written down, which is the better of the two.
                let wanted = match callee {
                    Callee::External(target) => signatures::signature(target)
                        .and_then(|known| known.params.get(rendered.len()))
                        .map(|spec| spec.split_whitespace().next().unwrap_or(spec)),
                    _ => None,
                };
                match wanted {
                    Some(target_ty) if target_ty != ty => {
                        let at = format!("{out}.c{}", arg.0);
                        before.push(converted(&at, ty, target_ty, &name(*arg), func)?);
                        rendered.push(format!("{target_ty} {at}"));
                    }
                    _ => rendered.push(format!("{ty} {}{}", extension(arg_ty), name(*arg))),
                }
            }
            let call = format!(
                "call {}{returns} {}({})",
                extension(&op.ty),
                symbol(target),
                rendered.join(", ")
            );
            let call = if returns == "void" {
                call
            } else {
                format!("{out} = {call}")
            };
            if before.is_empty() {
                call
            } else {
                before.push(call);
                before.join("\n  ")
            }
        }
        other => {
            return Err(refuse(func, &format!("the operation {other:?}, which is not a call")));
        }
    })
}

/// A concrete value, widened into the payload eightbyte.
///
/// The union's first member is the `double`, so an integer is converted to one
/// before its bits are stored -- the same conversion `nts_value_of_number(x)`
/// performs when C passes it an `int`. A bool and a pointer widen directly.
fn payload_from(
    func: &Func,
    out: &str,
    bits: &str,
    from: &HirType,
    value: ValueId,
) -> Result<String, Diagnostic> {
    Ok(match from {
        HirType::Float { .. } => format!("{bits} = bitcast double {} to i64", name(value)),
        HirType::Int { signed, .. } => {
            let wide = format!("{out}.d");
            let widen = if *signed { "sitofp" } else { "uitofp" };
            format!(
                "{wide} = {widen} {} {} to double\n  {bits} = bitcast double {wide} to i64",
                ty_of(from, func)?,
                name(value)
            )
        }
        HirType::Bool => format!("{bits} = zext i1 {} to i64", name(value)),
        HirType::Managed(_) => format!("{bits} = ptrtoint ptr {} to i64", name(value)),
        other => return Err(refuse(func, &format!("erasing a value of type {other:?}"))),
    })
}

/// The payload eightbyte, read back at the type the checker narrowed to.
///
/// Unchecked by construction, exactly as the C backend's union read is: the
/// licence comes from the narrowing and from nothing else.
fn payload_into(
    func: &Func,
    out: &str,
    bits: &str,
    want: &HirType,
) -> Result<String, Diagnostic> {
    Ok(match want {
        HirType::Float { .. } => format!("{out} = bitcast i64 {bits} to double"),
        HirType::Int { signed, .. } => {
            let wide = format!("{out}.d");
            let narrow = if *signed { "fptosi" } else { "fptoui" };
            format!(
                "{wide} = bitcast i64 {bits} to double\n  \
                 {out} = {narrow} double {wide} to {}",
                ty_of(want, func)?
            )
        }
        HirType::Bool => format!("{out} = trunc i64 {bits} to i1"),
        HirType::Managed(_) => format!("{out} = inttoptr i64 {bits} to ptr"),
        other => return Err(refuse(func, &format!("reading back a {other:?}"))),
    })
}

/// The operations that read or write memory.
///
/// Split from the rest because this is the half of the backend that depends on
/// `nts_codegen_common::layout` -- every one of these needs to know where
/// something sits, and none of the arithmetic does.
fn memory_operation(
    program: &Program,
    func: &Func,
    value: ValueId,
    out: &str,
) -> Result<String, Diagnostic> {
    let op = &func.values[value.0 as usize];
    let out = out.to_owned();
    Ok(match &op.kind {
        // Making one is next door: an allocation needs a descriptor, which is
        // data rather than code and the one piece of the runtime a backend has
        // to build.
        OpKind::ObjectNew { .. } | OpKind::ArrayNew { .. } => {
            return allocation(program, func, value, &out);
        }
        OpKind::ArrayGet { .. } | OpKind::ArraySet { .. } => {
            return element_access(func, value, &out);
        }
        OpKind::Length(_) | OpKind::StringUnitAt { .. } => {
            return text_operation(func, value, &out);
        }
        OpKind::Retain(_) | OpKind::Release(_) | OpKind::GlobalGet(_) | OpKind::GlobalSet { .. } => {
            return counting_or_global(program, func, value, &out);
        }
        // A field, at the offset this compiler computed.
        //
        // The C backend writes `p->x` and lets clang place it; there is no
        // `p->x` here, so `nts_codegen_common::layout` is not merely checked by
        // the `_Static_assert`s it emits -- it is the only thing that knows
        // where the field is. That is the whole reason the placement moved out
        // of the backend.
        //
        // `getelementptr i8` and a byte offset rather than an indexed GEP into
        // a named struct: opaque pointers mean the type is not carried by the
        // value, and a byte offset is exactly what the descriptor's reference
        // map already holds.
        //
        // Two instructions rather than one, because a *constant*
        // `getelementptr` may not name a function-local value and the object
        // always is one. The address gets a name of its own, derived from the
        // value it serves so nothing has to be counted.
        OpKind::FieldGet { object, field } => {
            let (offset, ty) = field_at(program, func, *object, *field, &op.ty)?;
            let at = format!("{out}.at");
            format!(
                "{at} = getelementptr i8, ptr {}, i64 {offset}\n  {out} = load {ty}, ptr {at}",
                name(*object)
            )
        }
        OpKind::FieldSet {
            object,
            field,
            value,
        } => {
            let stored = func.values[value.0 as usize].ty.clone();
            let (offset, ty) = field_at(program, func, *object, *field, &stored)?;
            let at = format!("{out}.at");
            format!(
                "{at} = getelementptr i8, ptr {}, i64 {offset}\n  store {ty} {}, ptr {at}",
                name(*object),
                name(*value)
            )
        }
        // Everything that touches memory is next door: it is the half of this
        // backend that depends on the layout engine, and keeping it together
        // is what makes that dependency visible.
        other => {
            return Err(refuse(
                func,
                &format!("the operation {other:?}, which this backend does not render yet"),
            ));
        }
    })
}

/// A double, written so that reading it back gives the same value.
///
/// LLVM accepts a decimal literal only when it is exactly representable, and
/// hexadecimal bits otherwise. Writing the bits always would be correct and
/// unreadable; writing decimal always would be wrong. So: decimal for the
/// whole numbers a program is mostly made of, bits for the rest.
fn float_literal(number: f64) -> String {
    if number.is_finite() && number.fract() == 0.0 && number.abs() < 1e15 {
        format!("{number:.1}")
    } else {
        format!("0x{:016X}", number.to_bits())
    }
}

fn binary(op: BinOp, float: bool, func: &Func) -> Result<&'static str, Diagnostic> {
    Ok(match (op, float) {
        (BinOp::Add, true) => "fadd",
        (BinOp::Add, false) => "add",
        (BinOp::Sub, true) => "fsub",
        (BinOp::Sub, false) => "sub",
        (BinOp::Mul, true) => "fmul",
        (BinOp::Mul, false) => "mul",
        (BinOp::Div, true) => "fdiv",
        (BinOp::Div, false) => "sdiv",
        (BinOp::Rem, true) => "frem",
        (BinOp::Rem, false) => "srem",
        // `ordered` comparisons, which answer false when either side is NaN --
        // which is what JavaScript's relational operators do.
        (BinOp::Lt, true) => "fcmp olt",
        (BinOp::Le, true) => "fcmp ole",
        (BinOp::Gt, true) => "fcmp ogt",
        (BinOp::Ge, true) => "fcmp oge",
        (BinOp::Eq, true) => "fcmp oeq",
        (BinOp::Ne, true) => "fcmp une",
        (BinOp::Lt, false) => "icmp slt",
        (BinOp::Le, false) => "icmp sle",
        (BinOp::Gt, false) => "icmp sgt",
        (BinOp::Ge, false) => "icmp sge",
        (BinOp::Eq, false) => "icmp eq",
        (BinOp::Ne, false) => "icmp ne",
        (BinOp::BitAnd, false) => "and",
        (BinOp::BitOr, false) => "or",
        (BinOp::BitXor, false) => "xor",
        (BinOp::Shl, false) => "shl",
        (BinOp::Shr, false) => "ashr",
        (BinOp::UShr, false) => "lshr",
        _ => {
            return Err(refuse(
                func,
                &format!("the operator {op:?} on this representation"),
            ));
        }
    })
}

/// One argument, at the type the runtime declares for it.
///
/// The conversions C performs silently at a call, written out. Only the pairs
/// that actually occur: a tag handed over as a double and wanted as a
/// `uint32_t`, a length the other way, an index narrowed. Anything else is
/// refused, because a silent conversion is what caused this.
fn converted(
    into: &str,
    have: &str,
    want: &str,
    from: &str,
    func: &Func,
) -> Result<String, Diagnostic> {
    let instruction = match (have, want) {
        ("double", "i32" | "i64" | "i16" | "i8") => "fptoui",
        ("i32" | "i64" | "i16" | "i8", "double") => "uitofp",
        ("i64", "i32") => "trunc",
        // A narrower unsigned value into a wider slot, `i1` included: a bool is
        // one unsigned bit and widens the way an unsigned integer does.
        ("i32" | "i1", "i64") | ("i1", "i32") => "zext",
        _ => {
            return Err(refuse(
                func,
                &format!("an argument of {have} where the runtime declares {want}"),
            ));
        }
    };
    Ok(format!("{into} = {instruction} {have} {from} to {want}"))
}

/// The instruction that turns one representation into another.
///
/// Named per direction rather than derived, because getting one of these
/// backwards is a wrong answer that compiles: `sitofp` where `uitofp` belongs
/// reads 4294967295 as -1.
fn conversion(from: &HirType, to: &HirType, func: &Func) -> Result<&'static str, Diagnostic> {
    Ok(match (from, to) {
        (HirType::Int { signed: true, .. } | HirType::BigInt, HirType::Float { .. }) => "sitofp",
        // A bool is one unsigned bit, so it converts the way an unsigned
        // integer does -- the same instruction for the same reason, not two
        // cases that happen to agree.
        (
            HirType::Int { signed: false, .. } | HirType::Bool,
            HirType::Float { .. },
        ) => "uitofp",
        (HirType::Float { .. }, HirType::Int { signed: true, .. }) => "fptosi",
        (HirType::Float { .. }, HirType::Int { signed: false, .. }) => "fptoui",
        (HirType::Float { bits: 32 }, HirType::Float { bits: 64 }) => "fpext",
        (HirType::Float { bits: 64 }, HirType::Float { bits: 32 }) => "fptrunc",
        (HirType::Bool, HirType::Int { .. }) => "zext",
        (
            HirType::Int { bits: wide, .. },
            HirType::Int {
                bits: narrow,
                signed,
            },
        ) => {
            if wide > narrow {
                "trunc"
            } else if *signed {
                "sext"
            } else {
                "zext"
            }
        }
        _ => {
            return Err(refuse(
                func,
                &format!("a conversion from {from:?} to {to:?}"),
            ));
        }
    })
}

fn unary(func: &Func, out: &str, op: UnOp, operand: ValueId) -> Result<String, Diagnostic> {
    let ty = ty_of(&func.values[operand.0 as usize].ty, func)?;
    let float = matches!(func.values[operand.0 as usize].ty, HirType::Float { .. });
    Ok(match op {
        UnOp::Neg if float => format!("{out} = fneg {ty} {}", name(operand)),
        UnOp::Neg => format!("{out} = sub {ty} 0, {}", name(operand)),
        UnOp::Not => format!("{out} = xor i1 {}, true", name(operand)),
        // An integer, a `bigint` and a reference are all "not the zero value".
        // A double additionally has to exclude NaN, which is falsy and which a
        // plain inequality would call true, since every comparison with a NaN
        // is false -- `fcmp one` is *ordered* and not equal, which is exactly
        // both conditions. And a string is falsy when absent *or* empty, which
        // is a short circuit and so a call.
        UnOp::Truthy => match &func.values[operand.0 as usize].ty {
            HirType::Managed(nts_core::hir::ManagedType::String) => format!(
                "{out} = call zeroext i1 @nts_string_truthy(ptr {})",
                name(operand)
            ),
            HirType::Managed(_) => {
                format!("{out} = icmp ne ptr {}, null", name(operand))
            }
            HirType::Int { .. } | HirType::BigInt => {
                format!("{out} = icmp ne {ty} {}, 0", name(operand))
            }
            HirType::Bool => format!("{out} = add i1 {}, 0", name(operand)),
            _ => format!("{out} = fcmp one {ty} {}, 0.0", name(operand)),
        },
        UnOp::Abs if float => format!("{out} = call double @llvm.fabs.f64(double {})", name(operand)),
        UnOp::Sqrt => format!("{out} = call double @llvm.sqrt.f64(double {})", name(operand)),
        // ToInt32 and ToUint32 on something already an integer, which is the
        // case specialization exists to produce: reduce modulo 2^32 and
        // reinterpret. The C backend writes `(int32_t)(uint32_t)x` for exactly
        // this and calls the runtime only for a genuine double -- which this
        // slice has no runtime to call, so it says so.
        // A genuine double: the ten-instruction reduction the runtime spells
        // out, called rather than reproduced. Inlining it here would be a
        // second implementation of ToInt32 to keep in step with the first, and
        // the differential would only find the difference after it shipped.
        UnOp::ToInt32 if float => format!(
            "{out} = call i32 @nts_to_int32_fn(double {})",
            name(operand)
        ),
        UnOp::ToUint32 if float => format!(
            "{out} = call i32 @nts_to_uint32_fn(double {})",
            name(operand)
        ),
        UnOp::ToInt32 | UnOp::ToUint32 if !float => {
            let HirType::Int { bits, .. } = func.values[operand.0 as usize].ty else {
                return Err(refuse(func, "a width-changing coercion of a non-integer"));
            };
            // LLVM's integer types carry no sign, so both coercions land in
            // `i32` and only the *widening* differs: `sext` keeps a negative
            // number negative, `zext` does not.
            let signed = matches!(op, UnOp::ToInt32);
            let target = "i32";
            match bits.cmp(&32) {
                std::cmp::Ordering::Greater => {
                    format!("{out} = trunc {ty} {} to {target}", name(operand))
                }
                std::cmp::Ordering::Equal => {
                    // Already thirty-two bits: the reinterpretation is free and
                    // LLVM's types carry no sign, so there is nothing to emit.
                    format!("{out} = add {ty} {}, 0", name(operand))
                }
                std::cmp::Ordering::Less if signed => {
                    format!("{out} = sext {ty} {} to {target}", name(operand))
                }
                std::cmp::Ordering::Less => {
                    format!("{out} = zext {ty} {} to {target}", name(operand))
                }
            }
        }
        other => {
            return Err(refuse(
                func,
                &format!("the unary operator {other:?}, which this backend does not render yet"),
            ));
        }
    })
}
