//! The second backend: textual LLVM IR.
//!
//! # Why textual, and why a second backend at all
//!
//! Textual `.ll` fed to `clang -x ir` rather than a linked `llvm-sys`. Reading
//! `program.c` diagnosed three separate bugs in one week — a struct cast to a
//! double named an unreachable narrowing on sight, and a `module__init` visibly
//! not assigning a global exposed an initializer that had been silently
//! dropped. That legibility is a working instrument, not a nicety, and it is
//! worth keeping in the backend that is meant to become primary. It also avoids
//! pinning an LLVM version into the build.
//!
//! The C backend does not go away when this one grows up. It is the *oracle*:
//! one HIR, two renderers, and the differential already knows how to ask
//! whether a compiled program agrees with node. A disagreement between the two
//! backends is a backend bug by construction, which is the only cheap way to
//! find one. scriptc gave this up — their C backend cannot express coroutines,
//! so it is debug-only — and they gave it up because their suspension lives in
//! the backend. Ours lives in `hir::suspend`, which is what makes two real
//! backends possible at all.
//!
//! # What it maps
//!
//! HIR is already backend-neutral: `Convert` is a representation change that
//! specialization decided, `frame` is a placement decision from escape
//! analysis, `checked` is a bounds proof. Each renders differently here and
//! means the same thing.
//!
//! The one structural difference is *block parameters*. HIR is SSA with
//! arguments on edges, the way MLIR and Swift's SIL are; LLVM puts the join in
//! the successor as a `phi` listing one value per predecessor. The two carry
//! the same information and the translation is mechanical — which is the whole
//! reason the lowering chose block parameters rather than phis in the first
//! place.
//!
//! # What it does not do yet
//!
//! This is the scalar slice: numbers, integers and booleans, arithmetic,
//! comparison, calls between lowered functions, and control flow. Anything
//! managed is refused by name rather than half-emitted. A backend that emits
//! *something* for every input is a backend nobody can trust the output of.

use std::fmt::Write as _;

use nts_core::hir::{BinOp, BlockId, Callee, Func, HirType, OpKind, Program, Terminator, UnOp, ValueId};
use nts_diagnostics::Diagnostic;

/// What the backend produced, and what it declined to.
#[derive(Debug)]
pub struct Emitted {
    pub text: String,
    pub diagnostics: Vec<Diagnostic>,
}

/// Render a whole program as textual LLVM IR.
///
/// A function this cannot render is *absent* and reported, exactly as the C
/// backend does: a caller that still calls it fails at the linker with a name,
/// which is a better failure than a body that silently means something else.
#[must_use]
pub fn emit(program: &Program) -> Emitted {
    let mut text = String::new();
    let mut diagnostics = Vec::new();
    let _ = writeln!(text, "; Generated by nts. Do not edit.");
    // What the runtime offers this backend, declared up front.
    //
    // `nts_to_int32` is `static inline` in the C header, which is right for C
    // and unreadable to anything else: a header is not a contract another code
    // generator can read. The runtime exposes a linkable form beside the inline
    // for exactly this, and these two are the first things to cross the C-to-
    // LLVM boundary -- a double in, an `i32` out, the simplest ABI there is to
    // get wrong.
    let _ = writeln!(text, "declare i32 @nts_to_int32_fn(double)");
    let _ = writeln!(text, "declare i32 @nts_to_uint32_fn(double)");
    for func in &program.funcs {
        match function(program, func) {
            Ok(rendered) => {
                let _ = writeln!(text, "\n{rendered}");
            }
            Err(diagnostic) => diagnostics.push(diagnostic),
        }
    }
    Emitted { text, diagnostics }
}

/// The LLVM type a value of this HIR type lives in.
fn ty_of(ty: &HirType, func: &Func) -> Result<&'static str, Diagnostic> {
    Ok(match ty {
        HirType::Void => "void",
        HirType::Bool => "i1",
        HirType::Float { bits: 32 } => "float",
        HirType::Float { .. } => "double",
        HirType::Int { bits: 8, .. } => "i8",
        HirType::Int { bits: 16, .. } => "i16",
        HirType::Int { bits: 32, .. } => "i32",
        HirType::Int { bits: 64, .. } => "i64",
        // One opaque pointer, whatever it points at. LLVM has had no other
        // kind since 17, and it is the same fact the C backend leans on when a
        // field's type has no layout: every managed value is a pointer.
        HirType::Managed(_) => "ptr",
        // `NtsValue` is the one that is not. A sixteen-byte struct passed by
        // value in seventeen runtime signatures, whose register classification
        // is not something to hand-derive: the signatures have to come from
        // clang. Named rather than guessed at.
        other => {
            return Err(refuse(
                func,
                &format!("a value of type {other:?}, which this backend does not render yet"),
            ));
        }
    })
}

/// The extension attribute a value of this type carries across a call.
///
/// Taken from clang rather than derived. A `_Bool` is passed `zeroext`, an
/// `int8_t` `signext`, a `uint16_t` `zeroext`, and anything word-sized or
/// wider nothing at all -- which is what `clang -S -emit-llvm` prints for the
/// same declarations, and the only way to be sure is to look.
///
/// On x86-64 a bare `i1` happens to work, because both ends use the low bit of
/// a register. "Happens to work" is not an ABI: the runtime is compiled by
/// clang and this has to agree with it on every target, not on the one it was
/// written on. This is the whole of the ABI story for the scalar slice --
/// `NtsValue` by value is the part that is not, and it is refused rather than
/// guessed at.
fn extension(ty: &HirType) -> &'static str {
    match ty {
        HirType::Int {
            bits: 8 | 16,
            signed: true,
        } => "signext ",
        // A `_Bool` and an unsigned narrow integer are the same case: neither
        // has a sign bit to carry into the upper half of the register.
        HirType::Bool
        | HirType::Int {
            bits: 8 | 16,
            signed: false,
        } => "zeroext ",
        _ => "",
    }
}

fn refuse(func: &Func, what: &str) -> Diagnostic {
    Diagnostic::error(
        "NTS3001",
        format!("{what} (in `{}`)", func.name),
        func.origin.location,
    )
}

/// A value's name in the emitted IR.
///
/// `%v12` for every value, including block parameters: SSA names are unique
/// per function and the HIR's are already numbered, so nothing has to be
/// invented or tracked.
fn name(value: ValueId) -> String {
    format!("%v{}", value.0)
}

fn label(block: BlockId) -> String {
    format!("b{}", block.0)
}

/// A function's name, quoted where LLVM needs it.
///
/// `#` is not a character an LLVM identifier may hold unquoted, and this
/// compiler puts one in every name it invents: `fib#whole` for a specialized
/// copy, `Closure3#call`, `module#init`. The character was chosen precisely
/// because TypeScript cannot produce it, so the names are not going to change
/// -- LLVM's quoted form is the place to absorb it.
fn symbol(raw: &str) -> String {
    let plain = raw
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '.' || c == '$');
    if plain {
        format!("@{raw}")
    } else {
        format!("@\"{raw}\"")
    }
}

fn function(program: &Program, func: &Func) -> Result<String, Diagnostic> {
    let mut out = String::new();
    let returns = ty_of(&func.return_type, func)?;
    let mut params = Vec::new();
    for (at, param) in func.params.iter().enumerate() {
        let ty = ty_of(&param.ty, func)?;
        // A parameter's *value* is whichever op is `Param(at)`, which is how
        // the rest of the function names it.
        let value = func
            .values
            .iter()
            .position(|op| matches!(op.kind, OpKind::Param(slot) if slot as usize == at))
            .map_or_else(
                || format!("%unused{at}"),
                |index| name(ValueId(u32::try_from(index).unwrap_or(0))),
            );
        params.push(format!("{ty} {}{value}", extension(&param.ty)));
    }
    let linkage = if func.exported { "" } else { "internal " };
    let _ = writeln!(
        out,
        "define {linkage}{}{returns} {}({}) {{",
        extension(&func.return_type),
        symbol(&func.name),
        params.join(", ")
    );

    for (index, block) in func.blocks.iter().enumerate() {
        let id = BlockId(u32::try_from(index).unwrap_or(0));
        let _ = writeln!(out, "{}:", label(id));
        // Block parameters become `phi`, one incoming per predecessor edge.
        for (slot, param) in block.params.iter().enumerate() {
            let ty = ty_of(&func.values[param.0 as usize].ty, func)?;
            let incoming = incoming_for(func, id, slot);
            if incoming.is_empty() {
                return Err(refuse(
                    func,
                    &format!("a block parameter no edge supplies, in {}", label(id)),
                ));
            }
            let _ = writeln!(
                out,
                "  {} = phi {ty} {}",
                name(*param),
                incoming.join(", ")
            );
        }
        for value in &block.ops {
            let line = operation(program, func, *value)?;
            if !line.is_empty() {
                let _ = writeln!(out, "  {line}");
            }
        }
        let _ = writeln!(out, "  {}", terminator(func, &block.terminator)?);
    }
    let _ = writeln!(out, "}}");
    Ok(out)
}

/// Every `[value, %predecessor]` pair reaching one block parameter.
fn incoming_for(func: &Func, target: BlockId, slot: usize) -> Vec<String> {
    let mut pairs = Vec::new();
    for (index, block) in func.blocks.iter().enumerate() {
        let from = BlockId(u32::try_from(index).unwrap_or(0));
        let mut add = |to: BlockId, args: &[ValueId]| {
            if to == target && let Some(value) = args.get(slot) {
                pairs.push(format!("[ {}, %{} ]", name(*value), label(from)));
            }
        };
        match &block.terminator {
            Terminator::Jump { target: to, args } => add(*to, args),
            Terminator::Branch {
                then_target,
                then_args,
                else_target,
                else_args,
                ..
            } => {
                add(*then_target, then_args);
                add(*else_target, else_args);
            }
            _ => {}
        }
    }
    pairs
}

fn terminator(func: &Func, term: &Terminator) -> Result<String, Diagnostic> {
    Ok(match term {
        Terminator::Return(Some(value)) => {
            let ty = ty_of(&func.values[value.0 as usize].ty, func)?;
            format!("ret {ty} {}", name(*value))
        }
        Terminator::Return(None) => "ret void".to_owned(),
        Terminator::Jump { target, .. } => format!("br label %{}", label(*target)),
        Terminator::Branch {
            cond,
            then_target,
            else_target,
            ..
        } => format!(
            "br i1 {}, label %{}, label %{}",
            name(*cond),
            label(*then_target),
            label(*else_target)
        ),
        // A claim the compiler is making, and LLVM has the same word for it.
        Terminator::Unreachable => "unreachable".to_owned(),
        // Not a claim, an absence -- and the C backend's note explains what
        // rendering it as a licence cost once. Refused rather than rendered.
        Terminator::FellThrough => {
            return Err(refuse(func, "a block that falls out of the end of a function"));
        }
    })
}

/// Where a field sits, and what it holds.
///
/// The offset comes from the layout engine and the *type* from the operation
/// rather than from the layout: a field whose own type has no layout is a
/// pointer here exactly as it is in the C backend, and the operation says so.
fn field_at(
    program: &Program,
    func: &Func,
    object: ValueId,
    field: u32,
    ty: &HirType,
) -> Result<(u32, &'static str), Diagnostic> {
    let HirType::Managed(nts_core::hir::ManagedType::Object(id)) =
        &func.values[object.0 as usize].ty
    else {
        return Err(refuse(func, "a field of something that is not an object"));
    };
    let layout = program
        .layouts
        .iter()
        .find(|layout| layout.types.contains(id))
        .ok_or_else(|| refuse(func, "a field of a type with no layout"))?;
    let placed = nts_codegen_common::layout::place(&layout.fields)
        .ok_or_else(|| refuse(func, "an object whose fields cannot be placed"))?;
    let offset = *placed
        .offsets
        .get(field as usize)
        .ok_or_else(|| refuse(func, "a field index outside its layout"))?;
    Ok((offset, ty_of(ty, func)?))
}

fn operation(program: &Program, func: &Func, value: ValueId) -> Result<String, Diagnostic> {
    let op = &func.values[value.0 as usize];
    let out = name(value);
    Ok(match &op.kind {
        // Already named by the signature.
        OpKind::Param(_) | OpKind::BlockParam(_) => String::new(),
        OpKind::ConstFloat(number) => {
            // LLVM reads a float literal as a C double, and prints one back
            // exactly when it is written in full. `fadd double %x, 1.0` is the
            // shape, and a value that is not representable is written as its
            // bits so nothing is lost in the spelling.
            format!("{out} = fadd double 0.0, {}", float_literal(*number))
        }
        OpKind::ConstInt(number) => {
            let ty = ty_of(&op.ty, func)?;
            format!("{out} = add {ty} 0, {number}")
        }
        OpKind::ConstBool(flag) => {
            format!("{out} = add i1 0, {}", u8::from(*flag))
        }
        OpKind::Binary { op: bin, lhs, rhs } => {
            let ty = ty_of(&func.values[lhs.0 as usize].ty, func)?;
            let float = matches!(func.values[lhs.0 as usize].ty, HirType::Float { .. });
            let instruction = binary(*bin, float, func)?;
            format!(
                "{out} = {instruction} {ty} {}, {}",
                name(*lhs),
                name(*rhs)
            )
        }
        OpKind::Unary { op: un, operand } => unary(func, &out, *un, *operand)?,
        // A field, at the offset this compiler computed.
        //
        // The C backend writes `p->x` and lets clang place it; there is no
        // `p->x` here, so `nts_codegen_common::layout` is not merely checked by
        // the `_Static_assert`s it emits -- it is the only thing that knows
        // where the field is. That is the whole reason the placement moved out
        // of the backend.
        //
        // `getelementptr i8` and a byte offset rather than an indexed GEP into
        // a named struct: opaque pointers mean the type is not carried by the
        // value, and a byte offset is exactly what the descriptor's reference
        // map already holds.
        //
        // Two instructions rather than one, because a *constant*
        // `getelementptr` may not name a function-local value and the object
        // always is one. The address gets a name of its own, derived from the
        // value it serves so nothing has to be counted.
        OpKind::FieldGet { object, field } => {
            let (offset, ty) = field_at(program, func, *object, *field, &op.ty)?;
            let at = format!("{out}.at");
            format!(
                "{at} = getelementptr i8, ptr {}, i64 {offset}\n  {out} = load {ty}, ptr {at}",
                name(*object)
            )
        }
        OpKind::FieldSet {
            object,
            field,
            value,
        } => {
            let stored = func.values[value.0 as usize].ty.clone();
            let (offset, ty) = field_at(program, func, *object, *field, &stored)?;
            let at = format!("{out}.at");
            format!(
                "{at} = getelementptr i8, ptr {}, i64 {offset}\n  store {ty} {}, ptr {at}",
                name(*object),
                name(*value)
            )
        }
        // A representation change specialization decided on. The C backend
        // spells it as a cast; LLVM makes the direction explicit, which is the
        // same instruction and a better record of what was meant.
        //
        // Out-of-range float to integer is undefined in C and poison here --
        // the same hazard by the same argument, and specialization only emits
        // one where the interval analysis proved the value fits.
        OpKind::Convert(operand) => {
            let from = &func.values[operand.0 as usize].ty;
            let to = &op.ty;
            let instruction = conversion(from, to, func)?;
            format!(
                "{out} = {instruction} {} {} to {}",
                ty_of(from, func)?,
                name(*operand),
                ty_of(to, func)?
            )
        }
        OpKind::Call { callee, args, .. } => {
            let returns = ty_of(&op.ty, func)?;
            let Callee::Direct(target) = callee else {
                return Err(refuse(func, "a call this backend does not resolve yet"));
            };
            let mut rendered = Vec::new();
            for arg in args {
                let ty = ty_of(&func.values[arg.0 as usize].ty, func)?;
                rendered.push(format!(
                    "{ty} {}{}",
                    extension(&func.values[arg.0 as usize].ty),
                    name(*arg)
                ));
            }
            let call = format!(
                "call {}{returns} {}({})",
                extension(&op.ty),
                symbol(target),
                rendered.join(", ")
            );
            if returns == "void" {
                call
            } else {
                format!("{out} = {call}")
            }
        }
        other => {
            return Err(refuse(
                func,
                &format!("the operation {other:?}, which this backend does not render yet"),
            ));
        }
    })
}

/// A double, written so that reading it back gives the same value.
///
/// LLVM accepts a decimal literal only when it is exactly representable, and
/// hexadecimal bits otherwise. Writing the bits always would be correct and
/// unreadable; writing decimal always would be wrong. So: decimal for the
/// whole numbers a program is mostly made of, bits for the rest.
fn float_literal(number: f64) -> String {
    if number.is_finite() && number.fract() == 0.0 && number.abs() < 1e15 {
        format!("{number:.1}")
    } else {
        format!("0x{:016X}", number.to_bits())
    }
}

fn binary(op: BinOp, float: bool, func: &Func) -> Result<&'static str, Diagnostic> {
    Ok(match (op, float) {
        (BinOp::Add, true) => "fadd",
        (BinOp::Add, false) => "add",
        (BinOp::Sub, true) => "fsub",
        (BinOp::Sub, false) => "sub",
        (BinOp::Mul, true) => "fmul",
        (BinOp::Mul, false) => "mul",
        (BinOp::Div, true) => "fdiv",
        (BinOp::Div, false) => "sdiv",
        (BinOp::Rem, true) => "frem",
        (BinOp::Rem, false) => "srem",
        // `ordered` comparisons, which answer false when either side is NaN --
        // which is what JavaScript's relational operators do.
        (BinOp::Lt, true) => "fcmp olt",
        (BinOp::Le, true) => "fcmp ole",
        (BinOp::Gt, true) => "fcmp ogt",
        (BinOp::Ge, true) => "fcmp oge",
        (BinOp::Eq, true) => "fcmp oeq",
        (BinOp::Ne, true) => "fcmp une",
        (BinOp::Lt, false) => "icmp slt",
        (BinOp::Le, false) => "icmp sle",
        (BinOp::Gt, false) => "icmp sgt",
        (BinOp::Ge, false) => "icmp sge",
        (BinOp::Eq, false) => "icmp eq",
        (BinOp::Ne, false) => "icmp ne",
        (BinOp::BitAnd, false) => "and",
        (BinOp::BitOr, false) => "or",
        (BinOp::BitXor, false) => "xor",
        (BinOp::Shl, false) => "shl",
        (BinOp::Shr, false) => "ashr",
        (BinOp::UShr, false) => "lshr",
        _ => {
            return Err(refuse(
                func,
                &format!("the operator {op:?} on this representation"),
            ));
        }
    })
}

/// The instruction that turns one representation into another.
///
/// Named per direction rather than derived, because getting one of these
/// backwards is a wrong answer that compiles: `sitofp` where `uitofp` belongs
/// reads 4294967295 as -1.
fn conversion(from: &HirType, to: &HirType, func: &Func) -> Result<&'static str, Diagnostic> {
    Ok(match (from, to) {
        (HirType::Int { signed: true, .. }, HirType::Float { .. }) => "sitofp",
        // A bool is one unsigned bit, so it converts the way an unsigned
        // integer does -- the same instruction for the same reason, not two
        // cases that happen to agree.
        (
            HirType::Int { signed: false, .. } | HirType::Bool,
            HirType::Float { .. },
        ) => "uitofp",
        (HirType::Float { .. }, HirType::Int { signed: true, .. }) => "fptosi",
        (HirType::Float { .. }, HirType::Int { signed: false, .. }) => "fptoui",
        (HirType::Float { bits: 32 }, HirType::Float { bits: 64 }) => "fpext",
        (HirType::Float { bits: 64 }, HirType::Float { bits: 32 }) => "fptrunc",
        (HirType::Bool, HirType::Int { .. }) => "zext",
        (
            HirType::Int { bits: wide, .. },
            HirType::Int {
                bits: narrow,
                signed,
            },
        ) => {
            if wide > narrow {
                "trunc"
            } else if *signed {
                "sext"
            } else {
                "zext"
            }
        }
        _ => {
            return Err(refuse(
                func,
                &format!("a conversion from {from:?} to {to:?}"),
            ));
        }
    })
}

fn unary(func: &Func, out: &str, op: UnOp, operand: ValueId) -> Result<String, Diagnostic> {
    let ty = ty_of(&func.values[operand.0 as usize].ty, func)?;
    let float = matches!(func.values[operand.0 as usize].ty, HirType::Float { .. });
    Ok(match op {
        UnOp::Neg if float => format!("{out} = fneg {ty} {}", name(operand)),
        UnOp::Neg => format!("{out} = sub {ty} 0, {}", name(operand)),
        UnOp::Not => format!("{out} = xor i1 {}, true", name(operand)),
        // ToInt32 and ToUint32 on something already an integer, which is the
        // case specialization exists to produce: reduce modulo 2^32 and
        // reinterpret. The C backend writes `(int32_t)(uint32_t)x` for exactly
        // this and calls the runtime only for a genuine double -- which this
        // slice has no runtime to call, so it says so.
        // A genuine double: the ten-instruction reduction the runtime spells
        // out, called rather than reproduced. Inlining it here would be a
        // second implementation of ToInt32 to keep in step with the first, and
        // the differential would only find the difference after it shipped.
        UnOp::ToInt32 if float => format!(
            "{out} = call i32 @nts_to_int32_fn(double {})",
            name(operand)
        ),
        UnOp::ToUint32 if float => format!(
            "{out} = call i32 @nts_to_uint32_fn(double {})",
            name(operand)
        ),
        UnOp::ToInt32 | UnOp::ToUint32 if !float => {
            let HirType::Int { bits, .. } = func.values[operand.0 as usize].ty else {
                return Err(refuse(func, "a width-changing coercion of a non-integer"));
            };
            // LLVM's integer types carry no sign, so both coercions land in
            // `i32` and only the *widening* differs: `sext` keeps a negative
            // number negative, `zext` does not.
            let signed = matches!(op, UnOp::ToInt32);
            let target = "i32";
            match bits.cmp(&32) {
                std::cmp::Ordering::Greater => {
                    format!("{out} = trunc {ty} {} to {target}", name(operand))
                }
                std::cmp::Ordering::Equal => {
                    // Already thirty-two bits: the reinterpretation is free and
                    // LLVM's types carry no sign, so there is nothing to emit.
                    format!("{out} = add {ty} {}, 0", name(operand))
                }
                std::cmp::Ordering::Less if signed => {
                    format!("{out} = sext {ty} {} to {target}", name(operand))
                }
                std::cmp::Ordering::Less => {
                    format!("{out} = zext {ty} {} to {target}", name(operand))
                }
            }
        }
        other => {
            return Err(refuse(
                func,
                &format!("the unary operator {other:?}, which this backend does not render yet"),
            ));
        }
    })
}
