//! The second backend: textual LLVM IR.
//!
//! # Why textual, and why a second backend at all
//!
//! Textual `.ll` fed to `clang -x ir` rather than a linked `llvm-sys`. Reading
//! `program.c` diagnosed three separate bugs in one week — a struct cast to a
//! double named an unreachable narrowing on sight, and a `module__init` visibly
//! not assigning a global exposed an initializer that had been silently
//! dropped. That legibility is a working instrument, not a nicety, and it is
//! worth keeping in the backend that is meant to become primary. It also avoids
//! pinning an LLVM version into the build.
//!
//! The C backend does not go away when this one grows up. It is the *oracle*:
//! one HIR, two renderers, and the differential already knows how to ask
//! whether a compiled program agrees with node. A disagreement between the two
//! backends is a backend bug by construction, which is the only cheap way to
//! find one. scriptc gave this up — their C backend cannot express coroutines,
//! so it is debug-only — and they gave it up because their suspension lives in
//! the backend. Ours lives in `hir::suspend`, which is what makes two real
//! backends possible at all.
//!
//! # What it maps
//!
//! HIR is already backend-neutral: `Convert` is a representation change that
//! specialization decided, `frame` is a placement decision from escape
//! analysis, `checked` is a bounds proof. Each renders differently here and
//! means the same thing.
//!
//! The one structural difference is *block parameters*. HIR is SSA with
//! arguments on edges, the way MLIR and Swift's SIL are; LLVM puts the join in
//! the successor as a `phi` listing one value per predecessor. The two carry
//! the same information and the translation is mechanical — which is the whole
//! reason the lowering chose block parameters rather than phis in the first
//! place.
//!
//! # What it does not do yet
//!
//! This is the scalar slice: numbers, integers and booleans, arithmetic,
//! comparison, calls between lowered functions, and control flow. Anything
//! managed is refused by name rather than half-emitted. A backend that emits
//! *something* for every input is a backend nobody can trust the output of.

pub mod signatures;

use std::fmt::Write as _;

use nts_core::hir::{BinOp, BlockId, Callee, Func, HirType, OpKind, Program, Terminator, UnOp, ValueId};
use nts_diagnostics::Diagnostic;

/// What the backend produced, and what it declined to.
#[derive(Debug)]
pub struct Emitted {
    pub text: String,
    pub diagnostics: Vec<Diagnostic>,
}

/// Render a whole program as textual LLVM IR.
///
/// A function this cannot render is *absent* and reported, exactly as the C
/// backend does: a caller that still calls it fails at the linker with a name,
/// which is a better failure than a body that silently means something else.
#[must_use]
pub fn emit(program: &Program) -> Emitted {
    let mut text = String::new();
    let mut diagnostics = Vec::new();
    let _ = writeln!(text, "; Generated by nts. Do not edit.");
    // What the runtime offers this backend, declared up front.
    //
    // `nts_to_int32` is `static inline` in the C header, which is right for C
    // and unreadable to anything else: a header is not a contract another code
    // generator can read. The runtime exposes a linkable form beside the inline
    // for exactly this, and these two are the first things to cross the C-to-
    // LLVM boundary -- a double in, an `i32` out, the simplest ABI there is to
    // get wrong.
    // Everything the backend may reach for, declared from the same table the
    // program's own calls use -- one source of signatures, and the attributes
    // come with them.
    for helper in ALWAYS_DECLARED {
        if let Some(line) = declaration(helper) {
            let _ = writeln!(text, "{line}");
        }
    }
    // The two intrinsics, which are LLVM's own and in no C header.
    let _ = writeln!(text, "declare double @llvm.fabs.f64(double) nounwind");
    let _ = writeln!(text, "declare double @llvm.sqrt.f64(double) nounwind");
    let _ = writeln!(text, "@nts_desc_ref = external constant %NtsDescriptor");
    for line in externals(program) {
        let _ = writeln!(text, "{line}");
    }
    let _ = writeln!(text, "\n{}", descriptors(program));
    let _ = writeln!(text, "{}", literals(program));
    // Module-scope storage. `internal` unless the program exports it, for the
    // same reason the C backend makes it `static`: a name outside the program
    // is a name something outside can collide with.
    for (at, global) in program.globals.iter().enumerate() {
        let Ok(ty) = ty_of(&global.ty, &program.funcs[0]) else {
            continue;
        };
        let linkage = if global.exported { "" } else { "internal " };
        let zero = if matches!(global.ty, HirType::Managed(_)) {
            "null".to_owned()
        } else if matches!(global.ty, HirType::Float { .. }) {
            float_literal(global.initial)
        } else {
            // A global's recorded initial value is a double whatever the
            // slot's width is, and an integer slot's is a whole number by
            // construction -- `Global::initial` is what the lowering folded,
            // not an arbitrary value.
            #[allow(
                clippy::cast_possible_truncation,
                reason = "an integer global's initial value is whole by construction"
            )]
            let whole = global.initial as i64;
            format!("{whole}")
        };
        let _ = writeln!(
            text,
            "{} = {linkage}global {ty} {zero}",
            symbol(&global_symbol(program, at))
        );
    }
    let mut bodies = String::new();
    for func in &program.funcs {
        match function(program, func) {
            Ok(rendered) => {
                let _ = writeln!(bodies, "\n{rendered}");
            }
            Err(diagnostic) => {
                diagnostics.push(diagnostic);
                // A refused function is absent, and a module that *calls* an
                // absent function is not a module: clang rejects the whole
                // thing, which turns a clean refusal into a broken build. Seven
                // benchmarks failed exactly that way -- the caller rendered,
                // the callee did not, and `@Benchmark__innerBenchmarkLoop` was
                // a name with nothing behind it.
                //
                // Declaring it makes the module valid and moves the failure to
                // the linker, which is where the C backend already puts it: C
                // emits a prototype for everything and lets `ld` say what is
                // missing. A refusal should look like a refusal.
                if let Some(line) = refused_declaration(func) {
                    let _ = writeln!(text, "{line}");
                }
            }
        }
    }
    text.push_str(&bodies);
    let _ = writeln!(text, "\n{TBAA_TREE}");
    Emitted { text, diagnostics }
}

/// What may alias what, which C tells clang and a module has to say for itself.
///
/// # Why this is here at all
///
/// The generated C gets this free. `xs[i] = ...` writes a `double` and
/// `xs.length` reads a `uint32_t`, and C's rule -- two accesses of different
/// types do not alias -- lets clang hoist the length and the element block out
/// of a loop that only writes doubles. A module carries no types at all once it
/// is written: `store double` and `load i32` are both just bytes, so every
/// store forces every later load to be done again.
///
/// Measured on `xs[i] = xs[i] * k; total += xs[i]` over four thousand doubles,
/// four hundred thousand rounds: **0.85s without this and 0.78s with it** --
/// which is exactly the C backend's 0.78s. The gap was never to clang; it was
/// to our own oracle, and this closes it.
///
/// # Why this is clang's tree and not one of ours
///
/// The first version invented a root, `!{!"nts"}`. The worry was that this
/// would be *unsound* under `-flto` -- which `tooling/bench` uses -- because
/// two trees would make claims about the same memory. It is the opposite, and
/// the experiment is worth keeping: given a loop that loads a `double` and
/// stores an `int` through an unrelated pointer, LLVM hoists the load out
/// entirely when both tags sit under clang's root, and moves *nothing* when the
/// store's tag has a root of its own. Tags from unrelated roots are treated as
/// possibly aliasing, which is the conservative answer.
///
/// So an invented root is safe and **useless across a translation unit**. Every
/// tag the runtime carries would have been opaque to every tag we emit, and
/// under LTO -- where the runtime's body is finally visible and there is most
/// to gain -- we would have gained nothing.
///
/// Metadata nodes are uniqued by content, so spelling the tree exactly as clang
/// spells it makes our `double` node *be* the runtime's `double` node. The
/// names are read off clang rather than guessed, and they are not obvious:
/// `int8_t` and `uint8_t` are character types and get the omnipotent char;
/// signed and unsigned share one node, so `uint32_t` is `"int"`; `int64_t` and
/// `uintptr_t` are both `"long"`; `_Bool` keeps its underscore.
///
/// # Why it is only types, and not fields
///
/// Clang additionally emits struct-path tags, which say `Point.x` and `Point.y`
/// do not alias. Scalar tags are strictly weaker, so mixing ours with the
/// runtime's paths is safe, and the plain type rule already recovered the whole
/// measured difference.
///
/// # What makes this sound here
///
/// Every field is accessed at exactly one LLVM type: the type comes from
/// `field_at`, off the field's HIR type, and it is the same type `emit.rs`
/// would have written in C -- so the tag agrees with the runtime's by
/// construction rather than by coincidence. An erased value is read and written
/// whole and gets the char node, because `NtsValue` is a union in C and this is
/// not the place to make a claim about one.
const TBAA_TREE: &str = "!0 = !{!\"Simple C/C++ TBAA\"}
!1 = !{!\"omnipotent char\", !0, i64 0}
!2 = !{!\"any pointer\", !1, i64 0}
!3 = !{!\"double\", !1, i64 0}
!4 = !{!\"float\", !1, i64 0}
!5 = !{!\"_Bool\", !1, i64 0}
!6 = !{!\"short\", !1, i64 0}
!7 = !{!\"int\", !1, i64 0}
!8 = !{!\"long\", !1, i64 0}
!9 = !{!\"__int128\", !1, i64 0}
!10 = !{!1, !1, i64 0}
!11 = !{!2, !2, i64 0}
!12 = !{!3, !3, i64 0}
!13 = !{!4, !4, i64 0}
!14 = !{!5, !5, i64 0}
!15 = !{!6, !6, i64 0}
!16 = !{!7, !7, i64 0}
!17 = !{!8, !8, i64 0}
!18 = !{!9, !9, i64 0}";

/// The access tag for a load or store at this LLVM type, as a suffix.
///
/// The mapping is C's, because the memory is shared with C: `i32` is `"int"`
/// whether the field was signed or not, `i64` is `"long"` because that is what
/// `int64_t` and `uintptr_t` are here, and `i8` is the omnipotent char, which
/// aliases everything.
///
/// Anything unrecognised falls to the char node too: a type this does not know
/// is a type whose memory it cannot reason about, and the conservative answer
/// is the one that is never wrong.
fn tbaa(ty: &str) -> &'static str {
    match ty {
        "ptr" => ", !tbaa !11",
        "double" => ", !tbaa !12",
        "float" => ", !tbaa !13",
        "i1" => ", !tbaa !14",
        "i16" => ", !tbaa !15",
        "i32" => ", !tbaa !16",
        "i64" => ", !tbaa !17",
        "i128" => ", !tbaa !18",
        // `i8` and `NtsValue` included: a character type aliases everything in
        // C, and a union is not something to make a claim about from here.
        _ => ", !tbaa !10",
    }
}

/// What an array holds, taken from the *array*.
///
/// Not from the value being stored, and not from the slot being filled. The
/// element type is what the descriptor was built from, so it is the only one
/// that describes the memory. `ArraySet` used the stored value's type instead:
/// a `number[]` whose descriptor says eight-byte doubles took `store i64`.
/// The width matched, so nothing crashed and nothing was diagnosed -- and every
/// later read of that element was an integer's bits read as a double.
/// `erasure-stored-typed` answered 1.3186118021857029e-314 where node answered
/// 2668900000, which is exactly the one reinterpreted as the other.
///
/// The C backend cannot make this mistake. It writes `elements[i] = value`
/// through a `double *` and C converts on the way in. Here it is written down.
fn array_element(func: &Func, array: ValueId) -> Result<&HirType, Diagnostic> {
    match &func.values[array.0 as usize].ty {
        HirType::Managed(nts_core::hir::ManagedType::Array(element)) => Ok(element),
        _ => Err(refuse(func, "an element access on something that is not an array")),
    }
}

/// One operand of a runtime helper, at the type the runtime declares for it.
///
/// C converts at the call and says nothing. Here every conversion has to be
/// written down -- and at *every* call, not only the ones `call` renders. The
/// signature table existed and exactly one code path consulted it, so a length
/// specialization had narrowed to an `i32` was handed to `nts_array_new(ptr,
/// double)` as an `i32`, an index narrowed the other way was handed to
/// `nts_unit_fn(ptr, i32)` as a `double`, and neither module assembled.
///
/// Any conversion lines go into `before`, because they have to be emitted
/// ahead of the call rather than inside its argument list.
fn helper_operand(
    func: &Func,
    out: &str,
    target: &str,
    at: usize,
    value: ValueId,
    before: &mut Vec<String>,
) -> Result<String, Diagnostic> {
    let have = ty_of(&func.values[value.0 as usize].ty, func)?;
    let want = signatures::signature(target)
        .and_then(|known| known.params.get(at))
        .map_or(have, |spec| spec.split_whitespace().next().unwrap_or(spec));
    if want == have {
        return Ok(format!("{have} {}", name(value)));
    }
    let slot = format!("{out}.a{}", value.0);
    before.push(converted(&slot, have, want, &name(value), func)?);
    Ok(format!("{want} {slot}"))
}

/// `declare` for a function this backend could not render.
///
/// Types only and no `internal`: LLVM has no such thing as an internal
/// declaration, and external is what makes the link fail with the function's
/// name in the message rather than the module fail to parse.
fn refused_declaration(func: &Func) -> Option<String> {
    let returns = ty_of(&func.return_type, func).ok()?;
    let mut params = Vec::new();
    for param in &func.params {
        if param.ty == HirType::Erased {
            // Two scalars, the same split `function` makes for a definition.
            params.push("i32".to_owned());
            params.push("i64".to_owned());
        } else {
            let ty = ty_of(&param.ty, func).ok()?;
            params.push(format!("{}{ty}", extension(&param.ty)));
        }
    }
    Some(format!(
        "declare {}{returns} {}({}) nounwind",
        extension(&func.return_type),
        symbol(&func.name),
        params.join(", ")
    ))
}

/// An erased value: the tag, and the union's eightbyte as an integer.
const ERASED_TYPE: &str = "{ i32, i64 }";

/// The tags, which are `typeof`'s answers in `typeof`'s order.
///
/// Read from the middle end rather than restated: `hir::tags` is where the
/// order is decided, and the order is load-bearing -- `"object"` is the range
/// test `tag >= OBJECT`, which is why `FUNCTION` sits below it.
fn tag_of(ty: &HirType) -> Option<u32> {
    use nts_core::hir::tags;
    Some(match ty {
        HirType::Bool => tags::BOOLEAN,
        HirType::Float { .. } | HirType::Int { .. } => tags::NUMBER,
        HirType::Managed(nts_core::hir::ManagedType::String) => tags::STRING,
        HirType::Managed(_) => tags::OBJECT,
        HirType::Void => tags::UNDEFINED,
        _ => return None,
    })
}

/// `NtsHeader`, as LLVM's own struct type: the same fields in the same order,
/// so it is laid out the way clang lays out the C one.
const HEADER_TYPE: &str = "%NtsHeader = type { ptr, i64, i32, i32 }";

/// Every string literal in the program, in the order the C backend numbers
/// them -- one table, so `nts_str_3` is the same string in both outputs.
///
/// A literal is static storage with an immortal count, so nothing ever tries to
/// free it. Emitted as code *units* rather than as an LLVM string constant for
/// the reason the C backend gives: an escape rule that is not JavaScript's is a
/// different string, and a wide literal is not bytes at all.
fn literals(program: &Program) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "{HEADER_TYPE}");
    let _ = writeln!(out, "@nts_desc_string1 = external constant %NtsDescriptor");
    let _ = writeln!(out, "@nts_desc_string2 = external constant %NtsDescriptor");
    for (index, text) in literal_table(program).iter().enumerate() {
        let units: Vec<u16> = text.encode_utf16().collect();
        let wide = units.iter().any(|unit| *unit > 0xFF);
        let (element, descriptor, flags) = if wide {
            ("i16", "@nts_desc_string2", 1)
        } else {
            ("i8", "@nts_desc_string1", 0)
        };
        // One more unit than the string holds, kept at zero, so a narrow one
        // can be handed to C directly.
        let mut data: Vec<String> = units
            .iter()
            .map(|unit| format!("{element} {unit}"))
            .collect();
        data.push(format!("{element} 0"));
        let _ = writeln!(
            out,
            "@nts_str_{index} = internal constant {{ %NtsHeader, [{count} x {element}] }} \
             {{ %NtsHeader {{ ptr {descriptor}, i64 {immortal}, i32 {flags}, i32 {length} }}, \
             [{count} x {element}] [{}] }}",
            data.join(", "),
            count = data.len(),
            immortal = nts_codegen_common::layout::IMMORTAL,
            length = units.len(),
        );
    }
    out
}

/// The literals a program holds, numbered the way the C backend numbers them.
fn literal_table(program: &Program) -> Vec<String> {
    let mut table: Vec<String> = Vec::new();
    for func in &program.funcs {
        for block in &func.blocks {
            for value in &block.ops {
                if let OpKind::ConstString(text) = &func.values[value.0 as usize].kind
                    && !table.contains(text)
                {
                    table.push(text.clone());
                }
            }
        }
    }
    table
}

/// `NtsDescriptor`, as LLVM's own struct type.
///
/// The field *types* in the runtime's order, not hand-computed offsets. LLVM
/// lays a struct out with the same rules clang does, so declaring the same
/// fields in the same order matches by construction -- which is the whole
/// difference between this and deriving an ABI, and it is why there is nothing
/// here to get wrong by four bytes.
const DESCRIPTOR_TYPE: &str =
    "%NtsDescriptor = type { i32, i32, i32, i32, ptr, ptr, ptr, i32, ptr }";

/// `NTS_KIND_OBJECT`. The other kinds belong to the runtime's own types.
const KIND_OBJECT: u32 = 2;

/// Every descriptor the program needs, with the tables they point at.
///
/// What goes *in* one is already shared: `cyclic_layouts` and
/// `reference_fields` are `nts_core::hir`'s, and the offsets are the layout
/// engine's. Only the rendering is the backend's, which is what a backend is.
fn descriptors(program: &Program) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "{DESCRIPTOR_TYPE}");
    let cyclic = program.cyclic_layouts();
    for (index, layout) in program.layouts.iter().enumerate() {
        let Some(placed) = nts_codegen_common::layout::place(&layout.fields) else {
            continue;
        };
        let tag = descriptor_name(layout);
        let mut offsets = |which: &str, wanted: &[u32]| -> String {
            if wanted.is_empty() {
                return "ptr null".to_owned();
            }
            let entries: Vec<String> = wanted.iter().map(|at| format!("i32 {at}")).collect();
            let _ = writeln!(
                out,
                "@nts_{which}_{tag} = internal constant [{} x i32] [{}]",
                wanted.len(),
                entries.join(", ")
            );
            format!("ptr @nts_{which}_{tag}")
        };
        let references: Vec<u32> = layout
            .fields
            .iter()
            .enumerate()
            .filter(|(_, field)| field.ty.may_hold_a_reference())
            .filter_map(|(at, _)| placed.offsets.get(at).copied())
            .collect();
        let erased: Vec<u32> = layout
            .fields
            .iter()
            .enumerate()
            .filter(|(_, field)| field.ty == HirType::Erased)
            .filter_map(|(at, _)| placed.offsets.get(at).copied())
            .collect();
        let reference_table = offsets("refs", &references);
        let erased_table = offsets("erased", &erased);
        // The name is a C string, terminator and all: the runtime prints it.
        let bytes = layout.name.len() + 1;
        let _ = writeln!(
            out,
            "@nts_name_{tag} = internal constant [{bytes} x i8] c\"{}\\00\"",
            layout.name
        );
        let is_cyclic = u32::from(cyclic.get(index).copied().unwrap_or(true));
        let _ = writeln!(
            out,
            "@nts_desc_{tag} = internal constant %NtsDescriptor {{ i32 {KIND_OBJECT}, \
             i32 {}, i32 {}, i32 {is_cyclic}, {reference_table}, ptr null, \
             ptr @nts_name_{tag}, i32 {}, {erased_table} }}",
            placed.size,
            references.len(),
            erased.len()
        );
    }
    // One per scalar element type an array is made of. An array of references
    // uses the runtime's `nts_desc_ref`, declared above.
    let mut seen: Vec<String> = Vec::new();
    for func in &program.funcs {
        for op in &func.values {
            if !matches!(op.kind, OpKind::ArrayNew { .. }) {
                continue;
            }
            let HirType::Managed(nts_core::hir::ManagedType::Array(element)) = &op.ty else {
                continue;
            };
            if element.is_managed() {
                continue;
            }
            let Some(shape) = nts_codegen_common::layout::shape_of(element) else {
                continue;
            };
            let tag = element_tag(element);
            if seen.contains(&tag) {
                continue;
            }
            seen.push(tag.clone());
            let _ = writeln!(
                out,
                "@nts_name_arr_{tag} = internal constant [{} x i8] c\"{tag}[]\\00\"",
                tag.len() + 3
            );
            // For an array, `erased` is a fact about *every* element rather
            // than a table of offsets, exactly as `references` is. One that
                // said zero would never be walked, and a string held in it
            // would be released while something still pointed at it.
            let erased = u32::from(**element == HirType::Erased);
            let _ = writeln!(
                out,
                "@nts_desc_arr_{tag} = internal constant %NtsDescriptor {{ i32 0, i32 {}, \
                 i32 0, i32 0, ptr null, ptr null, ptr @nts_name_arr_{tag}, i32 {erased}, \
                 ptr null }}",
                shape.size
            );
        }
    }
    out
}

/// A global's symbol, which is its source name.
fn global_symbol(program: &Program, at: usize) -> String {
    program
        .globals
        .get(at)
        .map_or_else(|| format!("nts_global_{at}"), |global| global.name.clone())
}

/// The address of an array's element block, and the index into it.
///
/// Leaves `%out.blk` holding the address of the `elements` field and `%out.i`
/// holding the checked index, which the caller loads and indexes through.
fn index_lines(
    func: &Func,
    out: &str,
    array: ValueId,
    index: ValueId,
    checked: bool,
) -> Vec<String> {
    let mut lines = vec![format!(
        "{out}.blk = getelementptr i8, ptr {}, i64 {}",
        name(array),
        nts_codegen_common::layout::ELEMENTS_OFFSET
    )];
    let integral = matches!(func.values[index.0 as usize].ty, HirType::Int { .. });
    if checked {
        if integral {
            lines.push(format!(
                "{out}.i = call i32 @nts_check_fn(ptr {}, i32 {})",
                name(array),
                name(index)
            ));
        } else {
            lines.push(format!(
                "{out}.i = call i32 @nts_index_fn(ptr {}, double {})",
                name(array),
                name(index)
            ));
        }
    } else if integral {
        lines.push(format!("{out}.i = add i32 {}, 0", name(index)));
    } else {
        // Proven in range, so the conversion is exact whichever representation
        // it arrived in.
        lines.push(format!("{out}.i = fptoui double {} to i32", name(index)));
    }
    lines
}

/// A name for a scalar element type, for the descriptor it needs.
fn element_tag(ty: &HirType) -> String {
    match ty {
        HirType::Bool => "bool".to_owned(),
        HirType::Erased => "value".to_owned(),
        HirType::Float { bits } => format!("f{bits}"),
        HirType::Int { bits, signed: true } => format!("i{bits}"),
        HirType::Int { bits, signed: false } => format!("u{bits}"),
        other => format!("{other:?}"),
    }
}

/// A layout's descriptor symbol, with anything LLVM dislikes replaced.
fn descriptor_name(layout: &nts_core::hir::Layout) -> String {
    layout
        .name
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect()
}

/// Runtime helpers this backend emits calls to without the program naming them.
///
/// A bounds check, a retain, an allocation: the lowering does not put these in
/// `Callee::External`, the backend reaches for them. Declared from the same
/// table as everything else so there is one place a signature comes from.
const ALWAYS_DECLARED: &[&str] = &[
    "nts_array_new",
    "nts_array_new_uninitialized",
    "nts_check_fn",
    "nts_concat",
    "nts_index_fn",
    "nts_object_new",
    "nts_release",
    "nts_retain",
    "nts_str_char_code_at_fn",
    "nts_string_truthy",
    "nts_to_int32_fn",
    "nts_to_uint32_fn",
    "nts_unit_fn",
    "nts_value_strict_eq",
];

/// One `declare` line for a runtime helper, from the generated table.
fn declaration(name: &str) -> Option<String> {
    let known = signatures::signature(name)?;
    // Nothing in this language unwinds -- there is no exception mechanism to
    // unwind *with* -- so every call is `nounwind` whatever else it is. Saying
    // so lets LLVM stop reasoning about paths that cannot exist.
    let mut carried: Vec<&str> = known.attributes.to_vec();
    if !carried.contains(&"nounwind") {
        carried.insert(0, "nounwind");
    }
    let attributes = carried.join(" ");
    Some(format!(
        "declare {} {}({}) {attributes}",
        known.returns,
        symbol(name),
        known.params.join(", ")
    ))
}

/// One `declare` per runtime helper the program calls, from `signatures`.
///
/// Read off the *call site* at first, which is sound only where the lowering's
/// types and the runtime's already agree -- and they do not. `nts_tag_name`
/// takes a `uint32_t` and the lowering hands it a double, because C converts
/// implicitly at the call and the C backend never had to notice. The declared
/// double went into an SSE register, the callee read an integer one, and
/// `typeof v` answered "undefined" for a number. Found by the cross-backend
/// test, which is the only thing that could have.
fn externals(program: &Program) -> Vec<String> {
    let mut seen: Vec<String> = ALWAYS_DECLARED.iter().map(|name| (*name).to_owned()).collect();
    let mut lines = Vec::new();
    for func in &program.funcs {
        for op in &func.values {
            let OpKind::Call {
                callee: Callee::External(target),
                ..
            } = &op.kind
            else {
                continue;
            };
            if seen.iter().any(|name| name == target) {
                continue;
            }
            let Some(line) = declaration(target) else {
                continue;
            };
            seen.push(target.clone());
            lines.push(line);
        }
    }
    lines
}

/// The LLVM type a value of this HIR type lives in.
fn ty_of(ty: &HirType, func: &Func) -> Result<&'static str, Diagnostic> {
    Ok(match ty {
        HirType::Void => "void",
        HirType::Bool => "i1",
        HirType::Float { bits: 32 } => "float",
        HirType::Float { .. } => "double",
        HirType::Int { bits: 8, .. } => "i8",
        HirType::Int { bits: 16, .. } => "i16",
        HirType::Int { bits: 32, .. } => "i32",
        HirType::Int { bits: 64, .. } => "i64",
        // Exact, and 128 bits rather than arbitrary precision -- the same
        // promise the C backend makes with `__int128`, which is where LLVM's
        // `i128` is what clang lowers that to anyway.
        HirType::BigInt => "i128",
        // One opaque pointer, whatever it points at. LLVM has had no other
        // kind since 17, and it is the same fact the C backend leans on when a
        // field's type has no layout: every managed value is a pointer.
        HirType::Managed(_) => "ptr",
        // `NtsValue`: a tag beside a union of a double, a bool and a pointer.
        //
        // The *type* is easy and the **ABI** is not, which is why this was
        // refused until clang was asked. `clang -S -emit-llvm` on a function
        // taking one prints `define { i32, i64 } @f(i32 %0, i64 %1)`: System V
        // classifies the sixteen bytes as two eightbytes, and the second is
        // `i64` rather than `double` because the union holds a pointer. So an
        // erased value is this aggregate inside a function and *two scalars*
        // across a call, which `function` and the call arm below arrange.
        HirType::Erased => ERASED_TYPE,
        other => {
            return Err(refuse(
                func,
                &format!("a value of type {other:?}, which this backend does not render yet"),
            ));
        }
    })
}

/// The extension attribute a value of this type carries across a call.
///
/// Taken from clang rather than derived. A `_Bool` is passed `zeroext`, an
/// `int8_t` `signext`, a `uint16_t` `zeroext`, and anything word-sized or
/// wider nothing at all -- which is what `clang -S -emit-llvm` prints for the
/// same declarations, and the only way to be sure is to look.
///
/// On x86-64 a bare `i1` happens to work, because both ends use the low bit of
/// a register. "Happens to work" is not an ABI: the runtime is compiled by
/// clang and this has to agree with it on every target, not on the one it was
/// written on. This is the whole of the ABI story for the scalar slice --
/// `NtsValue` by value is the part that is not, and it is refused rather than
/// guessed at.
fn extension(ty: &HirType) -> &'static str {
    match ty {
        HirType::Int {
            bits: 8 | 16,
            signed: true,
        } => "signext ",
        // A `_Bool` and an unsigned narrow integer are the same case: neither
        // has a sign bit to carry into the upper half of the register.
        HirType::Bool
        | HirType::Int {
            bits: 8 | 16,
            signed: false,
        } => "zeroext ",
        _ => "",
    }
}

fn refuse(func: &Func, what: &str) -> Diagnostic {
    Diagnostic::error(
        "NTS3001",
        format!("{what} (in `{}`)", func.name),
        func.origin.location,
    )
}

/// A value's name in the emitted IR.
///
/// `%v12` for every value, including block parameters: SSA names are unique
/// per function and the HIR's are already numbered, so nothing has to be
/// invented or tracked.
fn name(value: ValueId) -> String {
    format!("%v{}", value.0)
}

fn label(block: BlockId) -> String {
    format!("b{}", block.0)
}

/// A function's symbol, mangled the way the C backend mangles it.
///
/// Not LLVM's quoted form, which was the first answer and the wrong one. An
/// exported name is an ABI a human links against, so it cannot depend on which
/// backend produced the object -- and `module#init` became `module__init` in
/// one output and `@"module#init"` in the other, so a driver could link against
/// exactly one of them. The rule lives in `nts_codegen_common::symbols` now and
/// both backends read it.
fn symbol(raw: &str) -> String {
    format!("@{}", nts_codegen_common::symbols::c_identifier(raw))
}

fn function(program: &Program, func: &Func) -> Result<String, Diagnostic> {
    let mut out = String::new();
    let returns = ty_of(&func.return_type, func)?;
    let mut params = Vec::new();
    // An erased parameter arrives as two scalars and is put back together at
    // the top of the entry block, which is what clang does for the same C.
    let mut prologue: Vec<String> = Vec::new();
    for (at, param) in func.params.iter().enumerate() {
        let ty = ty_of(&param.ty, func)?;
        // A parameter's *value* is whichever op is `Param(at)`, which is how
        // the rest of the function names it.
        let value = func
            .values
            .iter()
            .position(|op| matches!(op.kind, OpKind::Param(slot) if slot as usize == at))
            .map_or_else(
                || format!("%unused{at}"),
                |index| name(ValueId(u32::try_from(index).unwrap_or(0))),
            );
        if param.ty == HirType::Erased {
            params.push(format!("i32 {value}.tag"));
            params.push(format!("i64 {value}.bits"));
            prologue.push(format!(
                "{value}.half = insertvalue {ERASED_TYPE} undef, i32 {value}.tag, 0"
            ));
            prologue.push(format!(
                "{value} = insertvalue {ERASED_TYPE} {value}.half, i64 {value}.bits, 1"
            ));
        } else {
            params.push(format!("{ty} {}{value}", extension(&param.ty)));
        }
    }
    let linkage = if func.exported { "" } else { "internal " };
    // `nounwind` on everything this compiler defines, for the reason above: the
    // language has no exceptions, so no frame here can be unwound through.
    //
    // Deliberately *not* `willreturn` or `mustprogress`. C guarantees forward
    // progress and JavaScript does not -- `while (true) {}` is a program the
    // checker accepts and this compiler compiles, and telling LLVM otherwise
    // would licence it to delete the loop.
    let _ = writeln!(
        out,
        "define {linkage}{}{returns} {}({}) nounwind {{",
        extension(&func.return_type),
        symbol(&func.name),
        params.join(", ")
    );

    for (index, block) in func.blocks.iter().enumerate() {
        let id = BlockId(u32::try_from(index).unwrap_or(0));
        let _ = writeln!(out, "{}:", label(id));
        if index == 0 {
            for line in &prologue {
                let _ = writeln!(out, "  {line}");
            }
        }
        // Block parameters become `phi`, one incoming per predecessor edge.
        for (slot, param) in block.params.iter().enumerate() {
            let ty = ty_of(&func.values[param.0 as usize].ty, func)?;
            let incoming = incoming_for(func, id, slot);
            if incoming.is_empty() {
                return Err(refuse(
                    func,
                    &format!("a block parameter no edge supplies, in {}", label(id)),
                ));
            }
            let _ = writeln!(
                out,
                "  {} = phi {ty} {}",
                name(*param),
                incoming.join(", ")
            );
        }
        for value in &block.ops {
            let line = operation(program, func, *value)?;
            if !line.is_empty() {
                let _ = writeln!(out, "  {line}");
            }
        }
        // Anything an outgoing edge has to convert, before the terminator that
        // carries it: a phi's incoming value must be available in the
        // predecessor, so this is the only place it can go.
        for line in outgoing_conversions(func, id) {
            let _ = writeln!(out, "  {line}");
        }
        let _ = writeln!(out, "  {}", terminator(func, &block.terminator)?);
    }
    let _ = writeln!(out, "}}");
    Ok(out)
}

/// The name an edge supplies for one block parameter, and the conversion it
/// needs to get there.
///
/// The verifier's `compatible` treats **any scalar as compatible with any
/// other**: an `i32` may flow along an edge into an `f64` block parameter. That
/// is sound for the C backend, which writes `v7 = v0;` and lets C convert, and
/// it is not sound here -- a `phi double` taking an `i32` is not a module.
///
/// So the conversion is written out, in the *predecessor*, because that is
/// where a phi's incoming value has to be available. It is the same thing C was
/// doing silently, and the IR being under-specified about it is a real finding:
/// nothing but a second backend could have noticed, because the first one's
/// language happened to fill the gap.
fn edge_value(func: &Func, from: BlockId, to: BlockId, slot: usize, value: ValueId) -> (String, Option<String>) {
    let Some(param) = func.blocks[to.0 as usize].params.get(slot) else {
        return (name(value), None);
    };
    let have = &func.values[value.0 as usize].ty;
    let want = &func.values[param.0 as usize].ty;
    if have == want {
        return (name(value), None);
    }
    let (Ok(from_ty), Ok(to_ty)) = (ty_of(have, func), ty_of(want, func)) else {
        return (name(value), None);
    };
    if from_ty == to_ty {
        return (name(value), None);
    }
    let Ok(instruction) = conversion(have, want, func) else {
        return (name(value), None);
    };
    let into = format!("%e{}_{}_{slot}", from.0, to.0);
    let line = format!("{into} = {instruction} {from_ty} {} to {to_ty}", name(value));
    (into, Some(line))
}

/// The conversions this block's outgoing edges need.
fn outgoing_conversions(func: &Func, from: BlockId) -> Vec<String> {
    let mut lines = Vec::new();
    let collect = |to: BlockId, args: &[ValueId], lines: &mut Vec<String>| {
        for (slot, value) in args.iter().enumerate() {
            if let (_, Some(line)) = edge_value(func, from, to, slot, *value) {
                lines.push(line);
            }
        }
    };
    match &func.blocks[from.0 as usize].terminator {
        Terminator::Jump { target, args } => collect(*target, args, &mut lines),
        Terminator::Branch {
            then_target,
            then_args,
            else_target,
            else_args,
            ..
        } => {
            collect(*then_target, then_args, &mut lines);
            collect(*else_target, else_args, &mut lines);
        }
        _ => {}
    }
    lines
}

/// Every `[value, %predecessor]` pair reaching one block parameter.
fn incoming_for(func: &Func, target: BlockId, slot: usize) -> Vec<String> {
    let mut pairs = Vec::new();
    for (index, block) in func.blocks.iter().enumerate() {
        let from = BlockId(u32::try_from(index).unwrap_or(0));
        let mut add = |to: BlockId, args: &[ValueId]| {
            if to == target && let Some(value) = args.get(slot) {
                let (supplied, _) = edge_value(func, from, to, slot, *value);
                pairs.push(format!("[ {supplied}, %{} ]", label(from)));
            }
        };
        match &block.terminator {
            Terminator::Jump { target: to, args } => add(*to, args),
            Terminator::Branch {
                then_target,
                then_args,
                else_target,
                else_args,
                ..
            } => {
                add(*then_target, then_args);
                add(*else_target, else_args);
            }
            _ => {}
        }
    }
    pairs
}

fn terminator(func: &Func, term: &Terminator) -> Result<String, Diagnostic> {
    Ok(match term {
        Terminator::Return(Some(value)) => {
            let ty = ty_of(&func.values[value.0 as usize].ty, func)?;
            format!("ret {ty} {}", name(*value))
        }
        Terminator::Return(None) => "ret void".to_owned(),
        Terminator::Jump { target, .. } => format!("br label %{}", label(*target)),
        Terminator::Branch {
            cond,
            then_target,
            else_target,
            ..
        } => format!(
            "br i1 {}, label %{}, label %{}",
            name(*cond),
            label(*then_target),
            label(*else_target)
        ),
        // A claim the compiler is making, and LLVM has the same word for it.
        Terminator::Unreachable => "unreachable".to_owned(),
        // Not a claim, an absence -- and the C backend's note explains what
        // rendering it as a licence cost once. Refused rather than rendered.
        Terminator::FellThrough => {
            return Err(refuse(func, "a block that falls out of the end of a function"));
        }
    })
}

/// Where a field sits, and what it holds.
///
/// The offset comes from the layout engine and the *type* from the operation
/// rather than from the layout: a field whose own type has no layout is a
/// pointer here exactly as it is in the C backend, and the operation says so.
fn field_at(
    program: &Program,
    func: &Func,
    object: ValueId,
    field: u32,
    ty: &HirType,
) -> Result<(u32, &'static str), Diagnostic> {
    let HirType::Managed(nts_core::hir::ManagedType::Object(id)) =
        &func.values[object.0 as usize].ty
    else {
        return Err(refuse(func, "a field of something that is not an object"));
    };
    let layout = program
        .layouts
        .iter()
        .find(|layout| layout.types.contains(id))
        .ok_or_else(|| refuse(func, "a field of a type with no layout"))?;
    let placed = nts_codegen_common::layout::place(&layout.fields)
        .ok_or_else(|| refuse(func, "an object whose fields cannot be placed"))?;
    let offset = *placed
        .offsets
        .get(field as usize)
        .ok_or_else(|| refuse(func, "a field index outside its layout"))?;
    Ok((offset, ty_of(ty, func)?))
}

fn operation(program: &Program, func: &Func, value: ValueId) -> Result<String, Diagnostic> {
    let op = &func.values[value.0 as usize];
    let out = name(value);
    Ok(match &op.kind {
        // Already named by the signature.
        OpKind::Param(_) | OpKind::BlockParam(_) => String::new(),
        OpKind::ConstFloat(number) => {
            // LLVM reads a float literal as a C double, and prints one back
            // exactly when it is written in full. A value that is not
            // representable is written as its bits so nothing is lost in the
            // spelling.
            //
            // `x - 0.0` rather than `0.0 + x`, and the difference is one value:
            // `0.0 + -0.0` is `+0.0`, because a sum of opposite signs that is
            // exactly zero is positive under round-to-nearest. Subtraction has
            // no such case -- `-0.0 - 0.0` is `-0.0 + -0.0`, like signs, so the
            // sign survives -- and `x - 0.0` is exact for every other double
            // too. Nothing produces a `-0` literal today, since `-0` lowers as
            // a negation of zero; this is so that a constant-folding pass in
            // the middle end cannot quietly turn `1 / -0` from `-Infinity` into
            // `Infinity` later.
            //
            // An instruction at all is a wart: a constant has no SSA name in
            // LLVM and should be substituted at its uses, which needs `name` to
            // tell a definition from a use and it currently cannot. The
            // optimizer folds this away at -O1, so it costs spelling rather
            // than speed.
            format!("{out} = fsub double {}, 0.0", float_literal(*number))
        }
        OpKind::ConstInt(number) => {
            let ty = ty_of(&op.ty, func)?;
            format!("{out} = add {ty} 0, {number}")
        }
        // The address of the static storage, which is what a string value is.
        OpKind::ConstString(text) => {
            let index = literal_table(program)
                .iter()
                .position(|known| known == text)
                .unwrap_or(0);
            format!("{out} = getelementptr i8, ptr @nts_str_{index}, i64 0")
        }
        OpKind::ConstBool(flag) => {
            format!("{out} = add i1 0, {}", u8::from(*flag))
        }
        OpKind::Erase { .. } | OpKind::Unerase { .. } | OpKind::TagOf { .. } => {
            return tagging(func, value, &out);
        }
        // Before the general binary arm, because it *is* a binary and the
        // general one would match it first -- and an `icmp` on a sixteen-byte
        // aggregate is not an instruction.
        OpKind::Binary {
            op: BinOp::Eq | BinOp::Ne,
            lhs,
            ..
        } if func.values[lhs.0 as usize].ty == HirType::Erased => {
            return tagging(func, value, &out);
        }
        // Two operators wear the `+` token and this is the other one. The
        // lowering already decided which, from the result type, so there is
        // nothing to work out here.
        OpKind::Binary {
            op: BinOp::Concat,
            lhs,
            rhs,
        } => format!(
            "{out} = call ptr @nts_concat(ptr {}, ptr {})",
            name(*lhs),
            name(*rhs)
        ),
        OpKind::Binary { op: bin, lhs, rhs } => {
            // Both operands at one type, which C picks for itself and a module
            // has to be told. The IR does not require the two to agree --
            // `verify::compatible` calls any scalar compatible with any other
            // -- so a `double` and an `int64_t` reached one `+` and this wrote
            // `fadd double %a, %b` with `%b` an `i64`.
            let left = &func.values[lhs.0 as usize].ty;
            let right = &func.values[rhs.0 as usize].ty;
            let joint = usual_conversion(left, right);
            let ty = ty_of(&joint, func)?;
            let float = matches!(joint, HirType::Float { .. });
            let instruction = binary(*bin, float, wraps(&joint), func)?;
            let mut lines = Vec::new();
            let a = at_joint(func, &out, "l", &joint, *lhs, &mut lines)?;
            let b = at_joint(func, &out, "r", &joint, *rhs, &mut lines)?;
            // A comparison answers a bool whatever it compared; everything else
            // answers at the type it worked in, and where the slot the middle
            // end gave it is narrower or wider than that, C would have
            // converted on the way out.
            let want = ty_of(&op.ty, func)?;
            let landing = if op.ty == HirType::Bool || want == ty {
                out.clone()
            } else {
                format!("{out}.o")
            };
            lines.push(format!("{landing} = {instruction} {ty} {a}, {b}"));
            if landing != out {
                let back = conversion(&joint, &op.ty, func)?;
                lines.push(format!("{out} = {back} {ty} {landing} to {want}"));
            }
            lines.join("\n  ")
        }
        OpKind::Unary { op: un, operand } => unary(func, &out, value, *un, *operand)?,
        // A representation change specialization decided on. The C backend
        // spells it as a cast; LLVM makes the direction explicit, which is the
        // same instruction and a better record of what was meant.
        //
        // Out-of-range float to integer is undefined in C and poison here --
        // the same hazard by the same argument, and specialization only emits
        // one where the interval analysis proved the value fits.
        OpKind::Convert(operand) => {
            let from = &func.values[operand.0 as usize].ty;
            let to = &op.ty;
            let (from_ty, to_ty) = (ty_of(from, func)?, ty_of(to, func)?);
            // `int32_t` to `uint32_t` is a conversion in C and nothing at all
            // in LLVM: same width, same bits, and signedness is a property of
            // the *operation* here rather than of the type. Falling through to
            // the width comparison produced `zext i32 %v to i32`, which is not
            // an instruction -- two benchmarks failed to assemble on it.
            //
            // There is no no-op cast, so this is the same `add x, 0` the
            // backend already uses to give a constant a name.
            if from_ty == to_ty {
                format!("{out} = add {from_ty} {}, 0", name(*operand))
            } else {
                let instruction = conversion(from, to, func)?;
                format!(
                    "{out} = {instruction} {from_ty} {} to {to_ty}",
                    name(*operand)
                )
            }
        }
        OpKind::Call { .. } => return call(program, func, value, &out),
        // A null pointer, which is what an absent reference is: the one spare
        // value a pointer has, and the whole reason `T | null` costs nothing.
        OpKind::ConstNull | OpKind::ConstUndefined if matches!(op.ty, HirType::Managed(_)) => {
            format!("{out} = inttoptr i64 0 to ptr")
        }
        // Where there are *two* absences the value is erased and each has a tag
        // of its own, which is the whole reason that union is not a pointer.
        // The payload is zero rather than undefined: a program that reads it
        // through a wrong narrowing then gets a zero rather than whatever was
        // in the register, which is the same choice `nts_value_of_undefined`
        // makes.
        OpKind::ConstNull | OpKind::ConstUndefined if op.ty == HirType::Erased => {
            let tag = if matches!(op.kind, OpKind::ConstNull) {
                nts_core::hir::tags::NULL
            } else {
                nts_core::hir::tags::UNDEFINED
            };
            format!(
                "{out}.half = insertvalue {ERASED_TYPE} undef, i32 {tag}, 0\n  \
                 {out} = insertvalue {ERASED_TYPE} {out}.half, i64 0, 1"
            )
        }
        _ => return memory_operation(program, func, value, &out),
    })
}

/// The two operations that make an object.
///
/// Both need a descriptor, which is the piece of the runtime a backend has to
/// *build* rather than call: it is data the collector reads, so it is emitted
/// here and everything in it comes from the middle end.
///
/// On the heap that is the allocator handed the descriptor; in the frame it is
/// an `alloca` and the header written out, which is what the C backend's
/// `v_frame.header.descriptor = ...` compiles to and one of the reasons escape
/// analysis is worth having.
fn allocation(
    program: &Program,
    func: &Func,
    value: ValueId,
    out: &str,
) -> Result<String, Diagnostic> {
    let op = &func.values[value.0 as usize];
    let out = out.to_owned();
    Ok(match &op.kind {
        OpKind::ArrayNew { length, zeroed } => {
            let HirType::Managed(nts_core::hir::ManagedType::Array(element)) = &op.ty else {
                return Err(refuse(func, "an array of something with no element type"));
            };
            // Two entry points rather than a flag, so the branch is taken here
            // rather than once per allocation at run time.
            let allocate = if *zeroed {
                "@nts_array_new"
            } else {
                "@nts_array_new_uninitialized"
            };
            let descriptor = if element.is_managed() {
                "@nts_desc_ref".to_owned()
            } else {
                format!("@nts_desc_arr_{}", element_tag(element))
            };
            let mut before = Vec::new();
            let count = helper_operand(
                func,
                &out,
                allocate.trim_start_matches('@'),
                1,
                *length,
                &mut before,
            )?;
            before.push(format!(
                "{out} = call ptr {allocate}(ptr {descriptor}, {count})"
            ));
            before.join("\n  ")
        }
        OpKind::ObjectNew { frame } => {
            let HirType::Managed(nts_core::hir::ManagedType::Object(id)) = &op.ty else {
                return Err(refuse(func, "an allocation of something that is not an object"));
            };
            let layout = program
                .layouts
                .iter()
                .find(|layout| layout.types.contains(id))
                .ok_or_else(|| refuse(func, "an allocation of a type with no layout"))?;
            let placed = nts_codegen_common::layout::place(&layout.fields)
                .ok_or_else(|| refuse(func, "an object whose fields cannot be placed"))?;
            let tag = descriptor_name(layout);
            if *frame {
                // `NTS_IMMORTAL` in the count word, so the counting pass's
                // release is a no-op on storage that was never allocated.
                [
                    format!("{out} = alloca i8, i64 {}, align {}", placed.size, placed.align),
                    format!("store ptr @nts_desc_{tag}, ptr {out}{}", tbaa("ptr")),
                    format!("{out}.rc = getelementptr i8, ptr {out}, i64 8"),
                    format!(
                        "store i64 {}, ptr {out}.rc{}",
                        nts_codegen_common::layout::IMMORTAL,
                        tbaa("i64")
                    ),
                ]
                .join("\n  ")
            } else {
                format!("{out} = call ptr @nts_object_new(ptr @nts_desc_{tag})")
            }
        }
        other => {
            return Err(refuse(
                func,
                &format!("the operation {other:?}, which does not allocate"),
            ));
        }
    })
}

/// Reading and writing an array's elements.
///
/// The block is a separate allocation -- which is what lets an array grow
/// without the object moving -- so this is a load of the block pointer and then
/// an index into it.
fn element_access(func: &Func, value: ValueId, out: &str) -> Result<String, Diagnostic> {
    let op = &func.values[value.0 as usize];
    let out = out.to_owned();
    Ok(match &op.kind {
        OpKind::ArrayGet {
            array,
            index,
            checked,
        } => {
            let held = array_element(func, *array)?;
            let element = ty_of(held, func)?;
            let want = ty_of(&op.ty, func)?;
            let landing = if element == want {
                out.clone()
            } else {
                format!("{out}.e")
            };
            let mut lines = index_lines(func, &out, *array, *index, *checked);
            lines.push(format!("{out}.block = load ptr, ptr {out}.blk{}", tbaa("ptr")));
            lines.push(format!(
                "{out}.at = getelementptr {element}, ptr {out}.block, i32 {out}.i"
            ));
            lines.push(format!(
                "{landing} = load {element}, ptr {out}.at{}",
                tbaa(element)
            ));
            if element != want {
                let instruction = conversion(held, &op.ty, func)?;
                lines.push(format!("{out} = {instruction} {element} {landing} to {want}"));
            }
            lines.join("\n  ")
        }
        OpKind::ArraySet {
            array,
            index,
            value,
            checked,
        } => {
            let held = array_element(func, *array)?;
            let element = ty_of(held, func)?;
            let stored = &func.values[value.0 as usize].ty;
            let have = ty_of(stored, func)?;
            let mut lines = index_lines(func, &out, *array, *index, *checked);
            lines.push(format!("{out}.block = load ptr, ptr {out}.blk{}", tbaa("ptr")));
            lines.push(format!(
                "{out}.at = getelementptr {element}, ptr {out}.block, i32 {out}.i"
            ));
            let put = if have == element {
                name(*value)
            } else {
                let fitted = format!("{out}.v");
                let instruction = conversion(stored, held, func)?;
                lines.push(format!(
                    "{fitted} = {instruction} {have} {} to {element}",
                    name(*value)
                ));
                fitted
            };
            lines.push(format!(
                "store {element} {put}, ptr {out}.at{}",
                tbaa(element)
            ));
            lines.join("\n  ")
        }
        other => {
            return Err(refuse(
                func,
                &format!("the operation {other:?}, which is not an element access"),
            ));
        }
    })
}

/// Counting, and module-scope storage.
///
/// The counting pass decides where a retain and a release go and both backends
/// emit one call each; under `NoGC` there are none, because the pass that would
/// have inserted them did not run. A global is `internal` unless the program
/// exports it, for the same reason the C backend makes it `static`.
fn counting_or_global(program: &Program, func: &Func, value: ValueId, out: &str)
    -> Result<String, Diagnostic>
{
    let op = &func.values[value.0 as usize];
    let out = out.to_owned();
    Ok(match &op.kind {
        // Counting, which the memory provider decides and both backends emit
        // the same way: one call each, and nothing under NoGC because the pass
        // that would have inserted them did not run.
        OpKind::Retain(object) => format!("call void @nts_retain(ptr {})", name(*object)),
        OpKind::Release(object) => format!("call void @nts_release(ptr {})", name(*object)),
        OpKind::GlobalGet(global) => {
            let ty = ty_of(&op.ty, func)?;
            format!(
                "{out} = load {ty}, ptr {}{}",
                symbol(&global_symbol(program, *global as usize)),
                tbaa(ty)
            )
        }
        OpKind::GlobalSet { global, value } => {
            let ty = ty_of(&func.values[value.0 as usize].ty, func)?;
            format!(
                "store {ty} {}, ptr {}{}",
                name(*value),
                symbol(&global_symbol(program, *global as usize)),
                tbaa(ty)
            )
        }
        other => {
            return Err(refuse(
                func,
                &format!("the operation {other:?}, which is neither counting nor a global"),
            ));
        }
    })
}

/// Reading a length, and reading a code unit.
///
/// Both are a load through a header, and both differ from an array's rule in
/// the same direction: a string is immutable and cannot grow, so its count is
/// the header's own and an index out of range answers NaN rather than trapping.
fn text_operation(func: &Func, value: ValueId, out: &str) -> Result<String, Diagnostic> {
    let op = &func.values[value.0 as usize];
    let out = out.to_owned();
    Ok(match &op.kind {
        // The count is the last four bytes of the header, whatever it belongs
        // to: an array reaches through its header because it can grow, and a
        // string *is* one.
        // A code unit. Checked goes through the runtime, which answers NaN out
        // of range rather than trapping -- a string's rule, and the opposite of
        // an array's.
        OpKind::StringUnitAt {
            string,
            index,
            checked,
        } => {
            // Both the index and the result are whatever specialization
            // decided, not whatever the runtime happens to declare. This used
            // to write `double` for both, so a narrowed index was handed to
            // `nts_unit_fn(ptr, i32)` as a `double` and a narrowed *result* was
            // produced as a `double` that every later reader then disagreed
            // with -- one bad type propagating to every use of it. `Length`
            // next door had it right all along.
            let returns = ty_of(&op.ty, func)?;
            let helper = if *checked {
                "nts_str_char_code_at_fn"
            } else {
                "nts_unit_fn"
            };
            // What the helper hands back, from the table rather than from
            // memory: one is a `double` and the other a `uint16_t`, and the
            // second carries `zeroext`.
            let known = signatures::signature(helper)
                .ok_or_else(|| refuse(func, "a string read with no declared helper"))?;
            let produced = known.returns.split_whitespace().last().unwrap_or(known.returns);
            let mut lines = Vec::new();
            let at = helper_operand(func, &out, helper, 1, *index, &mut lines)?;
            let call = format!(
                "call {} @{helper}(ptr {}, {at})",
                known.returns,
                name(*string)
            );
            if produced == returns {
                lines.push(format!("{out} = {call}"));
            } else {
                let raw = format!("{out}.u");
                lines.push(format!("{raw} = {call}"));
                lines.push(converted(&out, produced, returns, &raw, func)?);
            }
            lines.join("\n  ")
        }
        OpKind::Length(of) => {
            let returns = ty_of(&op.ty, func)?;
            let at = format!("{out}.at");
            let raw = format!("{out}.raw");
            let offset = nts_codegen_common::layout::LENGTH_OFFSET;
            let mut lines = vec![
                format!("{at} = getelementptr i8, ptr {}, i64 {offset}", name(*of)),
                format!("{raw} = load i32, ptr {at}{}", tbaa("i32")),
            ];
            lines.push(if returns == "i32" {
                format!("{out} = add i32 {raw}, 0")
            } else {
                format!("{out} = uitofp i32 {raw} to {returns}")
            });
            lines.join("\n  ")
        }
        other => {
            return Err(refuse(
                func,
                &format!("the operation {other:?}, which reads no length"),
            ));
        }
    })
}

/// Putting a value in a tagged one, taking it back out, and comparing two.
///
/// The whole of what a tag is *for*: `1 == true` and `[1] == 1` are questions
/// only a tag can answer, and the runtime answers them. The payload eightbyte
/// holds the union's first member, the `double`, so an integer is converted
/// before it is stored -- the same conversion `nts_value_of_number(x)` makes.
fn tagging(func: &Func, value: ValueId, out: &str) -> Result<String, Diagnostic> {
    let op = &func.values[value.0 as usize];
    let out = out.to_owned();
    Ok(match &op.kind {
        // Comparing two tagged values, which is the one thing carrying a tag is
        // *for*: `1 == true` and `[1] == 1` are questions only a tag can
        // answer, and the runtime answers them. Four scalars, because each
        // sixteen-byte value is two.
        OpKind::Binary {
            op: bin @ (BinOp::Eq | BinOp::Ne),
            lhs,
            rhs,
        } => {
            let parts: Vec<String> = [lhs, rhs]
                .iter()
                .enumerate()
                .flat_map(|(at, held)| {
                    [
                        format!("{out}.t{at} = extractvalue {ERASED_TYPE} {}, 0", name(**held)),
                        format!("{out}.p{at} = extractvalue {ERASED_TYPE} {}, 1", name(**held)),
                    ]
                })
                .collect();
            let same = format!("{out}.eq");
            let call = format!(
                "{same} = call zeroext i1 @nts_value_strict_eq(i32 {out}.t0, i64 {out}.p0, \
                 i32 {out}.t1, i64 {out}.p1)"
            );
            let answer = if matches!(bin, BinOp::Ne) {
                format!("{out} = xor i1 {same}, true")
            } else {
                format!("{out} = add i1 {same}, 0")
            };
            format!("{}\n  {call}\n  {answer}", parts.join("\n  "))
        }
        // Putting a value in a tagged one. The payload eightbyte holds the
        // union's first member, which is the `double` -- so an *integer* is
        // converted before it is stored, exactly as the C backend's
        // `nts_value_of_number(x)` converts it, and a bool and a pointer are
        // widened to the same eightbyte.
        OpKind::Erase { value } => {
            let from = &func.values[value.0 as usize].ty;
            let tag = tag_of(from)
                .ok_or_else(|| refuse(func, &format!("erasing a value of type {from:?}")))?;
            let bits = format!("{out}.bits");
            let widen = payload_from(func, &out, &bits, from, *value)?;
            format!(
                "{widen}\n  {out}.half = insertvalue {ERASED_TYPE} undef, i32 {tag}, 0\n  \
                 {out} = insertvalue {ERASED_TYPE} {out}.half, i64 {bits}, 1"
            )
        }
        // Reading the payload back, at the type the checker narrowed to.
        // Unchecked by construction, exactly as the C backend's union read is:
        // the licence comes from the narrowing and from nothing else.
        OpKind::Unerase { value } => {
            let bits = format!("{out}.bits");
            let read = format!("{bits} = extractvalue {ERASED_TYPE} {}, 1", name(*value));
            let narrow = payload_into(func, &out, &bits, &op.ty)?;
            format!("{read}\n  {narrow}")
        }
        OpKind::TagOf { value } => {
            format!("{out} = extractvalue {ERASED_TYPE} {}, 0", name(*value))
        }
        other => {
            return Err(refuse(
                func,
                &format!("the operation {other:?}, which reads no tag"),
            ));
        }
    })
}

/// A call, direct or into the runtime.
///
/// Two things happen here that C does silently. An erased argument becomes
/// *two* scalars, because that is how the platform passes a sixteen-byte
/// struct. And an argument whose type is not the one the runtime declares is
/// converted -- C does that at the call and says nothing, which is how
/// `nts_tag_name(uint32_t)` came to be handed a double.
fn call(
    program: &Program,
    func: &Func,
    value: ValueId,
    out: &str,
) -> Result<String, Diagnostic> {
    let op = &func.values[value.0 as usize];
    let out = out.to_owned();
    Ok(match &op.kind {
        OpKind::Call { callee, args, .. } => {
            let returns = ty_of(&op.ty, func)?;
            let target = match callee {
                Callee::Direct(target) | Callee::External(target) => target,
                // A dispatch through a method table. It needs the table, which
                // needs a descriptor, which is the next thing to build.
                Callee::Virtual { .. } | Callee::Closure { .. } => {
                    return Err(refuse(func, "a dispatched call, which needs a method table"));
                }
            };
            // What the *callee* was defined as, for a call to something in
            // this program. The signature table answers this for the runtime
            // and nothing answered it for our own functions: the definition
            // took its types from the callee's `Func` and the call site took
            // them from the operation, so `Closure0__call` was defined
            // `double` and called `i32`.
            //
            // Nothing rejects that -- it verifies, and it is the ABI mismatch
            // it looks like: the callee returns in xmm0 and the caller reads
            // eax. Worse for speed, **LLVM cannot inline a call whose signature
            // disagrees with its callee**, so a one-line closure stayed a call
            // in the innermost loop of `benches/cases/closures` and the case
            // ran 14x slower than the same HIR through the C backend.
            let defined = match callee {
                Callee::Direct(target) => program.funcs.iter().find(|it| &it.name == target),
                _ => None,
            };
            let mut rendered = Vec::new();
            let mut before: Vec<String> = Vec::new();
            for (at, arg) in args.iter().enumerate() {
                let arg_ty = &func.values[arg.0 as usize].ty;
                // Two scalars, because that is how the platform passes a
                // sixteen-byte struct and how clang emits the same call.
                if *arg_ty == HirType::Erased {
                    let tag = format!("{}.a{}", out, arg.0);
                    let bits = format!("{}.b{}", out, arg.0);
                    before.push(format!(
                        "{tag} = extractvalue {ERASED_TYPE} {}, 0",
                        name(*arg)
                    ));
                    before.push(format!(
                        "{bits} = extractvalue {ERASED_TYPE} {}, 1",
                        name(*arg)
                    ));
                    rendered.push(format!("i32 {tag}"));
                    rendered.push(format!("i64 {bits}"));
                    continue;
                }
                let ty = ty_of(arg_ty, func)?;
                // What the callee actually declares. C converts at the call and
                // says nothing; here the conversion has to be written down,
                // which is the better of the two.
                //
                // The runtime's index is into `rendered` because an erased
                // parameter is two entries there and one here; our own
                // functions carry one parameter per argument.
                let wanted = match callee {
                    Callee::External(target) => signatures::signature(target)
                        .and_then(|known| known.params.get(rendered.len()))
                        .map(|spec| spec.split_whitespace().next().unwrap_or(spec)),
                    Callee::Direct(_) => defined
                        .and_then(|it| it.params.get(at))
                        .and_then(|param| ty_of(&param.ty, func).ok()),
                    _ => None,
                };
                match wanted {
                    Some(target_ty) if target_ty != ty => {
                        let at = format!("{out}.c{}", arg.0);
                        before.push(converted(&at, ty, target_ty, &name(*arg), func)?);
                        rendered.push(format!("{target_ty} {at}"));
                    }
                    _ => rendered.push(format!("{ty} {}{}", extension(arg_ty), name(*arg))),
                }
            }
            // A helper the table does not carry is one this backend cannot
            // call. `nts_to_uint8` is `static inline` in the header, so there
            // is no symbol to link against and no signature to read -- and
            // emitting the call anyway produced a module that referenced a name
            // nothing defined. That is not a refusal, it is a broken build.
            //
            // The same distinction the `_fn` companions exist for: a `static
            // inline` is not a contract another code generator can read.
            match callee {
                Callee::External(target) if signatures::signature(target).is_none() => {
                    return Err(refuse(
                        func,
                        &format!(
                            "a call to {target}, which the runtime declares only as a \
                             `static inline` and so exposes no symbol for"
                        ),
                    ));
                }
                _ => {}
            }
            // The type the *callee* returns, which is not always the type the
            // rest of the function wants: C converts a `double` result into an
            // `int64_t` slot without a word, and the op carries the slot's type.
            let declared = match callee {
                Callee::External(target) => signatures::signature(target)
                    .map(|known| known.returns.split_whitespace().last().unwrap_or(known.returns)),
                Callee::Direct(_) => defined.and_then(|it| ty_of(&it.return_type, it).ok()),
                _ => None,
            };
            let call_returns = declared.unwrap_or(returns);
            let call = format!(
                "call {}{call_returns} {}({})",
                extension(&op.ty),
                symbol(target),
                rendered.join(", ")
            );
            let call = if returns == "void" {
                call
            } else if call_returns == returns {
                format!("{out} = {call}")
            } else {
                let raw = format!("{out}.r");
                let fix = converted(&out, call_returns, returns, &raw, func)?;
                format!("{raw} = {call}\n  {fix}")
            };
            if before.is_empty() {
                call
            } else {
                before.push(call);
                before.join("\n  ")
            }
        }
        other => {
            return Err(refuse(func, &format!("the operation {other:?}, which is not a call")));
        }
    })
}

/// A concrete value, widened into the payload eightbyte.
///
/// The union's first member is the `double`, so an integer is converted to one
/// before its bits are stored -- the same conversion `nts_value_of_number(x)`
/// performs when C passes it an `int`. A bool and a pointer widen directly.
fn payload_from(
    func: &Func,
    out: &str,
    bits: &str,
    from: &HirType,
    value: ValueId,
) -> Result<String, Diagnostic> {
    Ok(match from {
        HirType::Float { .. } => format!("{bits} = bitcast double {} to i64", name(value)),
        HirType::Int { signed, .. } => {
            let wide = format!("{out}.d");
            let widen = if *signed { "sitofp" } else { "uitofp" };
            format!(
                "{wide} = {widen} {} {} to double\n  {bits} = bitcast double {wide} to i64",
                ty_of(from, func)?,
                name(value)
            )
        }
        HirType::Bool => format!("{bits} = zext i1 {} to i64", name(value)),
        HirType::Managed(_) => format!("{bits} = ptrtoint ptr {} to i64", name(value)),
        other => return Err(refuse(func, &format!("erasing a value of type {other:?}"))),
    })
}

/// The payload eightbyte, read back at the type the checker narrowed to.
///
/// Unchecked by construction, exactly as the C backend's union read is: the
/// licence comes from the narrowing and from nothing else.
fn payload_into(
    func: &Func,
    out: &str,
    bits: &str,
    want: &HirType,
) -> Result<String, Diagnostic> {
    Ok(match want {
        HirType::Float { .. } => format!("{out} = bitcast i64 {bits} to double"),
        HirType::Int { signed, .. } => {
            let wide = format!("{out}.d");
            let narrow = if *signed { "fptosi" } else { "fptoui" };
            format!(
                "{wide} = bitcast i64 {bits} to double\n  \
                 {out} = {narrow} double {wide} to {}",
                ty_of(want, func)?
            )
        }
        HirType::Bool => format!("{out} = trunc i64 {bits} to i1"),
        HirType::Managed(_) => format!("{out} = inttoptr i64 {bits} to ptr"),
        other => return Err(refuse(func, &format!("reading back a {other:?}"))),
    })
}

/// The operations that read or write memory.
///
/// Split from the rest because this is the half of the backend that depends on
/// `nts_codegen_common::layout` -- every one of these needs to know where
/// something sits, and none of the arithmetic does.
fn memory_operation(
    program: &Program,
    func: &Func,
    value: ValueId,
    out: &str,
) -> Result<String, Diagnostic> {
    let op = &func.values[value.0 as usize];
    let out = out.to_owned();
    Ok(match &op.kind {
        // Making one is next door: an allocation needs a descriptor, which is
        // data rather than code and the one piece of the runtime a backend has
        // to build.
        OpKind::ObjectNew { .. } | OpKind::ArrayNew { .. } => {
            return allocation(program, func, value, &out);
        }
        OpKind::ArrayGet { .. } | OpKind::ArraySet { .. } => {
            return element_access(func, value, &out);
        }
        OpKind::Length(_) | OpKind::StringUnitAt { .. } => {
            return text_operation(func, value, &out);
        }
        OpKind::Retain(_) | OpKind::Release(_) | OpKind::GlobalGet(_) | OpKind::GlobalSet { .. } => {
            return counting_or_global(program, func, value, &out);
        }
        // A field, at the offset this compiler computed.
        //
        // The C backend writes `p->x` and lets clang place it; there is no
        // `p->x` here, so `nts_codegen_common::layout` is not merely checked by
        // the `_Static_assert`s it emits -- it is the only thing that knows
        // where the field is. That is the whole reason the placement moved out
        // of the backend.
        //
        // `getelementptr i8` and a byte offset rather than an indexed GEP into
        // a named struct: opaque pointers mean the type is not carried by the
        // value, and a byte offset is exactly what the descriptor's reference
        // map already holds.
        //
        // Two instructions rather than one, because a *constant*
        // `getelementptr` may not name a function-local value and the object
        // always is one. The address gets a name of its own, derived from the
        // value it serves so nothing has to be counted.
        OpKind::FieldGet { object, field } => {
            let (offset, ty) = field_at(program, func, *object, *field, &op.ty)?;
            let at = format!("{out}.at");
            format!(
                "{at} = getelementptr i8, ptr {}, i64 {offset}\n  {out} = load {ty}, ptr {at}{}",
                name(*object),
                tbaa(ty)
            )
        }
        OpKind::FieldSet {
            object,
            field,
            value,
        } => {
            let stored = func.values[value.0 as usize].ty.clone();
            let (offset, ty) = field_at(program, func, *object, *field, &stored)?;
            let at = format!("{out}.at");
            format!(
                "{at} = getelementptr i8, ptr {}, i64 {offset}\n  store {ty} {}, ptr {at}{}",
                name(*object),
                name(*value),
                tbaa(ty)
            )
        }
        // Everything that touches memory is next door: it is the half of this
        // backend that depends on the layout engine, and keeping it together
        // is what makes that dependency visible.
        other => {
            return Err(refuse(
                func,
                &format!("the operation {other:?}, which this backend does not render yet"),
            ));
        }
    })
}

/// A double, written so that reading it back gives the same value.
///
/// LLVM accepts a decimal literal only when it is exactly representable, and
/// hexadecimal bits otherwise. Writing the bits always would be correct and
/// unreadable; writing decimal always would be wrong. So: decimal for the
/// whole numbers a program is mostly made of, bits for the rest.
fn float_literal(number: f64) -> String {
    if number.is_finite() && number.fract() == 0.0 && number.abs() < 1e15 {
        format!("{number:.1}")
    } else {
        format!("0x{:016X}", number.to_bits())
    }
}

/// One operand of a binary operation, converted to the type both meet at.
///
/// Any conversion goes into `lines`, ahead of the operation.
fn at_joint(
    func: &Func,
    out: &str,
    side: &str,
    joint: &HirType,
    value: ValueId,
    lines: &mut Vec<String>,
) -> Result<String, Diagnostic> {
    let held = &func.values[value.0 as usize].ty;
    let (have, want) = (ty_of(held, func)?, ty_of(joint, func)?);
    if have == want {
        return Ok(name(value));
    }
    let slot = format!("{out}.{side}");
    let instruction = conversion(held, joint, func)?;
    lines.push(format!(
        "{slot} = {instruction} {have} {} to {want}",
        name(value)
    ));
    Ok(slot)
}

/// The one type two operands of a binary operation meet at.
///
/// C's usual arithmetic conversions, because C is the oracle and this is
/// exactly what it does silently at every mixed-type `+`: a `double` on either
/// side wins, then `bigint`, then the wider integer -- and at equal width the
/// unsigned one, which is C's rule and not an arbitrary tiebreak. A `bool`
/// never wins, because it promotes.
fn usual_conversion(left: &HirType, right: &HirType) -> HirType {
    if left == right {
        return left.clone();
    }
    match (left, right) {
        (HirType::Float { bits: a }, HirType::Float { bits: b }) => {
            HirType::Float { bits: *a.max(b) }
        }
        (HirType::Float { .. }, _) => left.clone(),
        (_, HirType::Float { .. }) => right.clone(),
        (HirType::BigInt, _) | (_, HirType::BigInt) => HirType::BigInt,
        (
            HirType::Int {
                bits: a,
                signed: left_signed,
            },
            HirType::Int {
                bits: b,
                signed: right_signed,
            },
        ) => HirType::Int {
            bits: *a.max(b),
            // The wider operand's signedness wins, and at equal width an
            // unsigned one does -- C's rule, not a tiebreak invented here.
            signed: match a.cmp(b) {
                std::cmp::Ordering::Equal => *left_signed && *right_signed,
                std::cmp::Ordering::Greater => *left_signed,
                std::cmp::Ordering::Less => *right_signed,
            },
        },
        (HirType::Bool, other) | (other, HirType::Bool) => other.clone(),
        _ => left.clone(),
    }
}

/// Whether overflow of this type wraps rather than being undefined.
///
/// The distinction is C's, and this backend inherits it rather than inventing
/// it: `int32_t` overflow is undefined and `uint32_t` overflow wraps, so the C
/// backend has *always* been compiled under the stronger assumption. Saying so
/// here is what makes the two backends agree; staying silent made this one
/// strictly more conservative than its own oracle, which is a divergence in the
/// direction nobody wants -- the primary backend giving up an optimization the
/// reference implementation already takes.
///
/// `bigint` is `__int128`, which is signed, and clang emits `add nsw i128` for
/// it. Whether *that* is the semantics `bigint` should have is a question for
/// the middle end, where it would change both backends at once. It is not a
/// question this file gets to answer on its own.
fn wraps(ty: &HirType) -> bool {
    !matches!(ty, HirType::Int { signed: true, .. } | HirType::BigInt)
}

/// The instruction, and the overflow flag where the type licenses one.
///
/// Which operations carry `nsw` is taken from clang rather than from the
/// standard: `+`, `-`, `*` and unary `-` on a signed type, and nothing else. In
/// particular `<<` does not, even on a signed operand, and `/` and `>>` do not.
/// Reading it off a compiler beats reading it off C11 6.5 and getting one case
/// subtly wrong, for the same reason the signature table is generated.
///
/// There is no `nuw` anywhere, and its absence is the point: unsigned overflow
/// in C is *defined* to wrap, so claiming otherwise would be the one place this
/// backend promised more than the oracle does.
fn binary(
    op: BinOp,
    float: bool,
    wraps: bool,
    func: &Func,
) -> Result<&'static str, Diagnostic> {
    Ok(match (op, float) {
        (BinOp::Add, true) => "fadd",
        (BinOp::Add, false) if wraps => "add",
        (BinOp::Add, false) => "add nsw",
        (BinOp::Sub, true) => "fsub",
        (BinOp::Sub, false) if wraps => "sub",
        (BinOp::Sub, false) => "sub nsw",
        (BinOp::Mul, true) => "fmul",
        (BinOp::Mul, false) if wraps => "mul",
        (BinOp::Mul, false) => "mul nsw",
        (BinOp::Div, true) => "fdiv",
        (BinOp::Div, false) => "sdiv",
        (BinOp::Rem, true) => "frem",
        (BinOp::Rem, false) => "srem",
        // `ordered` comparisons, which answer false when either side is NaN --
        // which is what JavaScript's relational operators do.
        (BinOp::Lt, true) => "fcmp olt",
        (BinOp::Le, true) => "fcmp ole",
        (BinOp::Gt, true) => "fcmp ogt",
        (BinOp::Ge, true) => "fcmp oge",
        (BinOp::Eq, true) => "fcmp oeq",
        (BinOp::Ne, true) => "fcmp une",
        (BinOp::Lt, false) => "icmp slt",
        (BinOp::Le, false) => "icmp sle",
        (BinOp::Gt, false) => "icmp sgt",
        (BinOp::Ge, false) => "icmp sge",
        (BinOp::Eq, false) => "icmp eq",
        (BinOp::Ne, false) => "icmp ne",
        (BinOp::BitAnd, false) => "and",
        (BinOp::BitOr, false) => "or",
        (BinOp::BitXor, false) => "xor",
        (BinOp::Shl, false) => "shl",
        (BinOp::Shr, false) => "ashr",
        (BinOp::UShr, false) => "lshr",
        _ => {
            return Err(refuse(
                func,
                &format!("the operator {op:?} on this representation"),
            ));
        }
    })
}

/// One argument, at the type the runtime declares for it.
///
/// The conversions C performs silently at a call, written out. Only the pairs
/// that actually occur: a tag handed over as a double and wanted as a
/// `uint32_t`, a length the other way, an index narrowed. Anything else is
/// refused, because a silent conversion is what caused this.
fn converted(
    into: &str,
    have: &str,
    want: &str,
    from: &str,
    func: &Func,
) -> Result<String, Diagnostic> {
    let instruction = match (have, want) {
        ("double", "i32" | "i64" | "i16" | "i8") => "fptoui",
        ("i32" | "i64" | "i16" | "i8", "double") => "uitofp",
        ("i64", "i32") | ("i32" | "i64", "i16" | "i8") | ("i16", "i8") => "trunc",
        // A narrower unsigned value into a wider slot, `i1` included: a bool is
        // one unsigned bit and widens the way an unsigned integer does. A code
        // unit is a `uint16_t` and widens the same way, which is what a string
        // read needs when specialization has narrowed its result.
        ("i32" | "i1" | "i16" | "i8", "i64")
        | ("i1" | "i16" | "i8", "i32")
        | ("i8", "i16") => "zext",
        _ => {
            return Err(refuse(
                func,
                &format!("an argument of {have} where the runtime declares {want}"),
            ));
        }
    };
    Ok(format!("{into} = {instruction} {have} {from} to {want}"))
}

/// The instruction that turns one representation into another.
///
/// Named per direction rather than derived, because getting one of these
/// backwards is a wrong answer that compiles: `sitofp` where `uitofp` belongs
/// reads 4294967295 as -1.
fn conversion(from: &HirType, to: &HirType, func: &Func) -> Result<&'static str, Diagnostic> {
    Ok(match (from, to) {
        (HirType::Int { signed: true, .. } | HirType::BigInt, HirType::Float { .. }) => "sitofp",
        // A bool is one unsigned bit, so it converts the way an unsigned
        // integer does -- the same instruction for the same reason, not two
        // cases that happen to agree.
        (
            HirType::Int { signed: false, .. } | HirType::Bool,
            HirType::Float { .. },
        ) => "uitofp",
        (HirType::Float { .. }, HirType::Int { signed: true, .. }) => "fptosi",
        (HirType::Float { .. }, HirType::Int { signed: false, .. }) => "fptoui",
        (HirType::Float { bits: 32 }, HirType::Float { bits: 64 }) => "fpext",
        (HirType::Float { bits: 64 }, HirType::Float { bits: 32 }) => "fptrunc",
        (HirType::Bool, HirType::Int { .. }) => "zext",
        (
            HirType::Int { bits: wide, .. },
            HirType::Int {
                bits: narrow,
                signed,
            },
        ) => {
            if wide > narrow {
                "trunc"
            } else if *signed {
                "sext"
            } else {
                "zext"
            }
        }
        _ => {
            return Err(refuse(
                func,
                &format!("a conversion from {from:?} to {to:?}"),
            ));
        }
    })
}

fn unary(
    func: &Func,
    out: &str,
    value: ValueId,
    op: UnOp,
    operand: ValueId,
) -> Result<String, Diagnostic> {
    let ty = ty_of(&func.values[operand.0 as usize].ty, func)?;
    let float = matches!(func.values[operand.0 as usize].ty, HirType::Float { .. });
    Ok(match op {
        UnOp::Neg if float => format!("{out} = fneg {ty} {}", name(operand)),
        // `sub nsw 0, x` on a signed type, which is what clang emits for
        // `-a` -- and it is a real promise rather than a formality, because
        // negating `INT32_MIN` is exactly the case it excludes.
        UnOp::Neg => {
            let flag = if wraps(&func.values[operand.0 as usize].ty) {
                ""
            } else {
                " nsw"
            };
            format!("{out} = sub{flag} {ty} 0, {}", name(operand))
        }
        UnOp::Not => format!("{out} = xor i1 {}, true", name(operand)),
        // An integer, a `bigint` and a reference are all "not the zero value".
        // A double additionally has to exclude NaN, which is falsy and which a
        // plain inequality would call true, since every comparison with a NaN
        // is false -- `fcmp one` is *ordered* and not equal, which is exactly
        // both conditions. And a string is falsy when absent *or* empty, which
        // is a short circuit and so a call.
        UnOp::Truthy => match &func.values[operand.0 as usize].ty {
            HirType::Managed(nts_core::hir::ManagedType::String) => format!(
                "{out} = call zeroext i1 @nts_string_truthy(ptr {})",
                name(operand)
            ),
            HirType::Managed(_) => {
                format!("{out} = icmp ne ptr {}, null", name(operand))
            }
            HirType::Int { .. } | HirType::BigInt => {
                format!("{out} = icmp ne {ty} {}, 0", name(operand))
            }
            HirType::Bool => format!("{out} = add i1 {}, 0", name(operand)),
            _ => format!("{out} = fcmp one {ty} {}, 0.0", name(operand)),
        },
        UnOp::Abs if float => format!("{out} = call double @llvm.fabs.f64(double {})", name(operand)),
        UnOp::Sqrt => format!("{out} = call double @llvm.sqrt.f64(double {})", name(operand)),
        // ToInt32 and ToUint32 on something already an integer, which is the
        // case specialization exists to produce: reduce modulo 2^32 and
        // reinterpret. The C backend writes `(int32_t)(uint32_t)x` for exactly
        // this and calls the runtime only for a genuine double -- which this
        // slice has no runtime to call, so it says so.
        // A genuine double: the ten-instruction reduction the runtime spells
        // out, called rather than reproduced. Inlining it here would be a
        // second implementation of ToInt32 to keep in step with the first, and
        // the differential would only find the difference after it shipped.
        UnOp::ToInt32 | UnOp::ToUint32 => {
            // LLVM's integer types carry no sign, so both coercions land in
            // `i32` and only the *widening* differs: `sext` keeps a negative
            // number negative, `zext` does not.
            let signed = matches!(op, UnOp::ToInt32);
            let want = ty_of(&func.values[value.0 as usize].ty, func)?;
            // The coercion *is* a reduction to thirty-two bits, so that happens
            // first -- and then the result goes into whatever slot the middle
            // end gave it, which is not always a thirty-two bit one.
            //
            // Producing `i32` and calling it the result's type made a value
            // whose emitted width disagreed with its recorded one. Nothing
            // complained at the definition; every later reader converted from
            // the width the HIR claimed, and `%v22`, an `i32`, was truncated
            // from `i64`. One hardcoded type, and the module stopped verifying
            // several instructions away from the cause.
            let reduced = if want == "i32" {
                out.to_owned()
            } else {
                format!("{out}.n")
            };
            let reduce = if float {
                // A genuine double: the ten-instruction reduction the runtime
                // spells out, called rather than reproduced. Inlining it here
                // would be a second implementation of ToInt32 to keep in step
                // with the first, and the differential would only find the
                // difference after it shipped.
                let helper = if signed {
                    "nts_to_int32_fn"
                } else {
                    "nts_to_uint32_fn"
                };
                format!("{reduced} = call i32 @{helper}(double {})", name(operand))
            } else {
                let HirType::Int { bits, .. } = func.values[operand.0 as usize].ty else {
                    return Err(refuse(func, "a width-changing coercion of a non-integer"));
                };
                match bits.cmp(&32) {
                    std::cmp::Ordering::Greater => {
                        format!("{reduced} = trunc {ty} {} to i32", name(operand))
                    }
                    // Already thirty-two bits: the reinterpretation is free and
                    // LLVM's types carry no sign, so there is nothing to emit.
                    std::cmp::Ordering::Equal => {
                        format!("{reduced} = add {ty} {}, 0", name(operand))
                    }
                    std::cmp::Ordering::Less if signed => {
                        format!("{reduced} = sext {ty} {} to i32", name(operand))
                    }
                    std::cmp::Ordering::Less => {
                        format!("{reduced} = zext {ty} {} to i32", name(operand))
                    }
                }
            };
            if want == "i32" {
                reduce
            } else {
                // The widening keeps the sign the coercion just established:
                // a `ToInt32` result is signed and a `ToUint32` result is not.
                // Backwards here reads 4294967295 as -1.
                let land = match want {
                    "i64" if signed => "sext",
                    "i64" => "zext",
                    "i16" | "i8" => "trunc",
                    "double" if signed => "sitofp",
                    "double" => "uitofp",
                    _ => {
                        return Err(refuse(
                            func,
                            &format!("a thirty-two bit coercion landing in {want}"),
                        ));
                    }
                };
                format!("{reduce}\n  {out} = {land} i32 {reduced} to {want}")
            }
        }
        other => {
            return Err(refuse(
                func,
                &format!("the unary operator {other:?}, which this backend does not render yet"),
            ));
        }
    })
}
