//! Every runtime function's signature on arm64 (AAPCS64), as clang reports it
//! for `arm64-apple-macos13` against the macOS SDK the Apple lane builds with.
//!
//! The same header as `signatures.rs`, and not the same declarations, measured
//! by the Apple lane over all 353: AAPCS64 passes and returns an erased value
//! (sixteen bytes) as `[2 x i64]` where System V splits it into `i32, i64`,
//! passes a record larger than sixteen bytes (`NtsTask`) as a pointer to a
//! copy where System V copies it onto the stack (`byval`), and widens nothing
//! a function returns. 52 differ; `tests/signatures.rs` generates this table
//! and checks it exactly as it does `signatures.rs`, and skips without the SDK.
//!
//! Until the backend passes an erased value as `[2 x i64]`, a function holding
//! one is refused on arm64 rather than emitted with System V's split, which
//! this table's declarations would make a call that disagrees with its callee.

use super::signatures::Signature;

/// Sorted by name, so a lookup is a binary search and a diff is readable.
pub const SIGNATURES_ARM64: &[Signature] = &[
    Signature { name: "fmod", returns: "double", params: &["double", "double"], attributes: &["nounwind"] },
    Signature { name: "llvm.fabs.f32", returns: "float", params: &["float"], attributes: &["nocallback", "nocreateundeforpoison", "nofree", "nosync", "nounwind", "speculatable", "willreturn", "memory(none)"] },
    Signature { name: "llvm.fabs.f64", returns: "double", params: &["double"], attributes: &["nocallback", "nocreateundeforpoison", "nofree", "nosync", "nounwind", "speculatable", "willreturn", "memory(none)"] },
    Signature { name: "llvm.floor.f64", returns: "double", params: &["double"], attributes: &["nocallback", "nocreateundeforpoison", "nofree", "nosync", "nounwind", "speculatable", "willreturn", "memory(none)"] },
    Signature { name: "llvm.is.fpclass.f64", returns: "i1", params: &["double", "i32 immarg"], attributes: &["nocallback", "nocreateundeforpoison", "nofree", "nosync", "nounwind", "speculatable", "willreturn", "memory(none)"] },
    Signature { name: "llvm.memcpy.p0.p0.i64", returns: "void", params: &["ptr noalias writeonly captures(none)", "ptr noalias readonly captures(none)", "i64", "i1 immarg"], attributes: &["nocallback", "nofree", "nounwind", "willreturn", "memory(argmem: readwrite)"] },
    Signature { name: "llvm.trunc.f64", returns: "double", params: &["double"], attributes: &["nocallback", "nocreateundeforpoison", "nofree", "nosync", "nounwind", "speculatable", "willreturn", "memory(none)"] },
    Signature { name: "nts_alloc", returns: "noalias nonnull ptr", params: &["i64"], attributes: &[] },
    Signature { name: "nts_append_slot", returns: "i32", params: &["ptr", "double"], attributes: &[] },
    Signature { name: "nts_array_at", returns: "double", params: &["ptr", "double"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_array_at_foreign", returns: "ptr", params: &["ptr", "double"], attributes: &[] },
    Signature { name: "nts_array_at_ref", returns: "ptr", params: &["ptr", "double"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_array_at_value", returns: "[2 x i64]", params: &["ptr", "double"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_array_concat", returns: "ptr", params: &["ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_array_concat_foreign", returns: "ptr", params: &["ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_array_concat_ref", returns: "ptr", params: &["ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_array_concat_value", returns: "ptr", params: &["ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_array_element", returns: "[2 x i64]", params: &["[2 x i64]", "double"], attributes: &[] },
    Signature { name: "nts_array_extend", returns: "void", params: &["ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_array_extend_foreign", returns: "void", params: &["ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_array_extend_ref", returns: "void", params: &["ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_array_fill", returns: "ptr", params: &["ptr", "double"], attributes: &[] },
    Signature { name: "nts_array_fill_bool", returns: "ptr", params: &["ptr", "i1 zeroext"], attributes: &[] },
    Signature { name: "nts_array_fill_foreign", returns: "ptr", params: &["ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_array_fill_from_nsarray", returns: "void", params: &["ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_array_fill_ref", returns: "ptr", params: &["ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_array_fill_strings_from_nsarray", returns: "void", params: &["ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_array_includes", returns: "zeroext i1", params: &["ptr", "double"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_array_includes_ref", returns: "zeroext i1", params: &["ptr", "ptr"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_array_includes_str", returns: "zeroext i1", params: &["ptr", "ptr"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_array_includes_str_value", returns: "zeroext i1", params: &["ptr", "[2 x i64]"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_array_index_of", returns: "double", params: &["ptr", "double"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_array_index_of_ref", returns: "double", params: &["ptr", "ptr"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_array_index_of_str", returns: "double", params: &["ptr", "ptr"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_array_index_of_str_value", returns: "double", params: &["ptr", "[2 x i64]"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_array_join_num", returns: "ptr", params: &["ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_array_join_str", returns: "ptr", params: &["ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_array_keep_first", returns: "void", params: &["ptr", "double"], attributes: &[] },
    Signature { name: "nts_array_last_index_of", returns: "double", params: &["ptr", "double"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_array_new", returns: "noalias nonnull ptr", params: &["ptr", "double"], attributes: &[] },
    Signature { name: "nts_array_new_uninitialized", returns: "noalias nonnull ptr", params: &["ptr", "double"], attributes: &[] },
    Signature { name: "nts_array_of_numbers", returns: "noalias nonnull ptr", params: &["double"], attributes: &[] },
    Signature { name: "nts_array_pop", returns: "double", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_array_pop_ref", returns: "ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_array_pop_value", returns: "[2 x i64]", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_array_push", returns: "double", params: &["ptr", "double"], attributes: &[] },
    Signature { name: "nts_array_push_ref", returns: "double", params: &["ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_array_push_value", returns: "double", params: &["ptr", "[2 x i64]"], attributes: &[] },
    Signature { name: "nts_array_reverse", returns: "ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_array_reverse_ref", returns: "ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_array_set_length", returns: "void", params: &["ptr", "double"], attributes: &[] },
    Signature { name: "nts_array_set_length_foreign", returns: "void", params: &["ptr", "double"], attributes: &[] },
    Signature { name: "nts_array_set_length_ref", returns: "void", params: &["ptr", "double"], attributes: &[] },
    Signature { name: "nts_array_set_length_value", returns: "void", params: &["ptr", "double"], attributes: &[] },
    Signature { name: "nts_array_shift", returns: "double", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_array_shift_ref", returns: "ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_array_shift_value", returns: "[2 x i64]", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_array_slice", returns: "ptr", params: &["ptr", "double", "double"], attributes: &[] },
    Signature { name: "nts_array_slice_foreign", returns: "ptr", params: &["ptr", "double", "double"], attributes: &[] },
    Signature { name: "nts_array_slice_ref", returns: "ptr", params: &["ptr", "double", "double"], attributes: &[] },
    Signature { name: "nts_array_sort_str", returns: "ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_array_splice", returns: "ptr", params: &["ptr", "double", "double"], attributes: &[] },
    Signature { name: "nts_array_splice_ref", returns: "ptr", params: &["ptr", "double", "double"], attributes: &[] },
    Signature { name: "nts_array_unshift", returns: "double", params: &["ptr", "double"], attributes: &[] },
    Signature { name: "nts_array_unshift_ref", returns: "double", params: &["ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_bigint_as_intn", returns: "i128", params: &["double", "i128"], attributes: &[] },
    Signature { name: "nts_bigint_as_uintn", returns: "i128", params: &["double", "i128"], attributes: &[] },
    Signature { name: "nts_bigint_from_number", returns: "i128", params: &["double"], attributes: &[] },
    Signature { name: "nts_bigint_shl", returns: "i128", params: &["i128", "i128"], attributes: &[] },
    Signature { name: "nts_bigint_shr", returns: "i128", params: &["i128", "i128"], attributes: &[] },
    Signature { name: "nts_bigint_to_string", returns: "ptr", params: &["i128"], attributes: &[] },
    Signature { name: "nts_bool_to_string", returns: "ptr", params: &["i1 zeroext"], attributes: &[] },
    Signature { name: "nts_bounds", returns: "void", params: &["double", "i32"], attributes: &[] },
    Signature { name: "nts_buffer_byte_length", returns: "double", params: &["ptr"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_buffer_detached", returns: "zeroext i1", params: &["ptr"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_buffer_max_byte_length", returns: "double", params: &["ptr"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_buffer_new", returns: "noalias ptr", params: &["double"], attributes: &[] },
    Signature { name: "nts_buffer_new_resizable", returns: "noalias ptr", params: &["double", "double"], attributes: &[] },
    Signature { name: "nts_buffer_resizable", returns: "zeroext i1", params: &["ptr"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_buffer_resize", returns: "void", params: &["ptr", "double"], attributes: &[] },
    Signature { name: "nts_buffer_slice", returns: "noalias ptr", params: &["ptr", "double", "double"], attributes: &[] },
    Signature { name: "nts_buffer_transfer", returns: "noalias ptr", params: &["ptr", "double", "i1 zeroext"], attributes: &[] },
    Signature { name: "nts_callback_enter", returns: "void", params: &[], attributes: &[] },
    Signature { name: "nts_callback_leave", returns: "void", params: &[], attributes: &[] },
    Signature { name: "nts_callback_task", returns: "void", params: &["ptr dead_on_unwind writable sret(%struct.NtsTask) align 8", "ptr", "double", "i1 zeroext"], attributes: &[] },
    Signature { name: "nts_cancel_delayed", returns: "void", params: &["i64"], attributes: &[] },
    Signature { name: "nts_cell_unready", returns: "void", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_check_fn", returns: "i32", params: &["ptr", "i32"], attributes: &[] },
    Signature { name: "nts_check_or_grow_fn", returns: "i32", params: &["ptr", "i32"], attributes: &[] },
    Signature { name: "nts_checkpoint", returns: "void", params: &[], attributes: &[] },
    Signature { name: "nts_checkpoint_after_callbacks", returns: "void", params: &["i1 zeroext"], attributes: &[] },
    Signature { name: "nts_clear_timeout", returns: "void", params: &["double"], attributes: &[] },
    Signature { name: "nts_closure_lend", returns: "ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_closure_lend_once", returns: "ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_closure_notify", returns: "ptr", params: &[], attributes: &[] },
    Signature { name: "nts_closure_unlend", returns: "void", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_closure_unlend_once", returns: "void", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_closures_owed", returns: "i64", params: &[], attributes: &[] },
    Signature { name: "nts_collect_cycles", returns: "void", params: &[], attributes: &[] },
    Signature { name: "nts_collection_epoch", returns: "i64", params: &[], attributes: &[] },
    Signature { name: "nts_concat", returns: "noalias nonnull ptr", params: &["ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_concat_into", returns: "ptr", params: &["ptr", "ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_counted_allocations", returns: "i64", params: &[], attributes: &[] },
    Signature { name: "nts_counted_releases", returns: "i64", params: &[], attributes: &[] },
    Signature { name: "nts_counted_retains", returns: "i64", params: &[], attributes: &[] },
    Signature { name: "nts_counting_reset", returns: "void", params: &[], attributes: &[] },
    Signature { name: "nts_cstring_release", returns: "void", params: &["ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_cstrings_release", returns: "void", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_cycle_candidates", returns: "i64", params: &[], attributes: &[] },
    Signature { name: "nts_dataview_buffer", returns: "ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_dataview_byte_length", returns: "double", params: &["ptr"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_dataview_byte_offset", returns: "double", params: &["ptr"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_dataview_get_bigint64", returns: "i128", params: &["ptr", "double", "i1 zeroext"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_dataview_get_biguint64", returns: "i128", params: &["ptr", "double", "i1 zeroext"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_dataview_get_float32", returns: "double", params: &["ptr", "double", "i1 zeroext"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_dataview_get_float64", returns: "double", params: &["ptr", "double", "i1 zeroext"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_dataview_get_int16", returns: "double", params: &["ptr", "double", "i1 zeroext"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_dataview_get_int32", returns: "double", params: &["ptr", "double", "i1 zeroext"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_dataview_get_int8", returns: "double", params: &["ptr", "double"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_dataview_get_uint16", returns: "double", params: &["ptr", "double", "i1 zeroext"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_dataview_get_uint32", returns: "double", params: &["ptr", "double", "i1 zeroext"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_dataview_get_uint8", returns: "double", params: &["ptr", "double"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_dataview_over", returns: "noalias ptr", params: &["ptr", "double"], attributes: &[] },
    Signature { name: "nts_dataview_part", returns: "noalias ptr", params: &["ptr", "double", "double"], attributes: &[] },
    Signature { name: "nts_dataview_set_bigint64", returns: "void", params: &["ptr", "double", "i128", "i1 zeroext"], attributes: &[] },
    Signature { name: "nts_dataview_set_biguint64", returns: "void", params: &["ptr", "double", "i128", "i1 zeroext"], attributes: &[] },
    Signature { name: "nts_dataview_set_float32", returns: "void", params: &["ptr", "double", "double", "i1 zeroext"], attributes: &[] },
    Signature { name: "nts_dataview_set_float64", returns: "void", params: &["ptr", "double", "double", "i1 zeroext"], attributes: &[] },
    Signature { name: "nts_dataview_set_int16", returns: "void", params: &["ptr", "double", "double", "i1 zeroext"], attributes: &[] },
    Signature { name: "nts_dataview_set_int32", returns: "void", params: &["ptr", "double", "double", "i1 zeroext"], attributes: &[] },
    Signature { name: "nts_dataview_set_int8", returns: "void", params: &["ptr", "double", "double"], attributes: &[] },
    Signature { name: "nts_dataview_set_uint16", returns: "void", params: &["ptr", "double", "double", "i1 zeroext"], attributes: &[] },
    Signature { name: "nts_dataview_set_uint32", returns: "void", params: &["ptr", "double", "double", "i1 zeroext"], attributes: &[] },
    Signature { name: "nts_dataview_set_uint8", returns: "void", params: &["ptr", "double", "double"], attributes: &[] },
    Signature { name: "nts_date_new", returns: "noalias nonnull ptr", params: &["double"], attributes: &[] },
    Signature { name: "nts_date_value", returns: "double", params: &["ptr"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_decode_uri", returns: "ptr", params: &["ptr", "double"], attributes: &[] },
    Signature { name: "nts_delay", returns: "double", params: &["double"], attributes: &[] },
    Signature { name: "nts_encode_uri", returns: "ptr", params: &["ptr", "double"], attributes: &[] },
    Signature { name: "nts_enqueue_microtask", returns: "void", params: &["ptr dead_on_return"], attributes: &[] },
    Signature { name: "nts_enqueue_tick", returns: "void", params: &["ptr dead_on_return"], attributes: &[] },
    Signature { name: "nts_enter", returns: "void", params: &[], attributes: &[] },
    Signature { name: "nts_environment_create", returns: "ptr", params: &[], attributes: &[] },
    Signature { name: "nts_environment_current", returns: "ptr", params: &[], attributes: &[] },
    Signature { name: "nts_environment_destroy", returns: "void", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_environment_enter", returns: "i64", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_environment_has_platform", returns: "zeroext i1", params: &[], attributes: &[] },
    Signature { name: "nts_environment_install_platform", returns: "void", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_environment_leave", returns: "void", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_environment_platform", returns: "ptr", params: &[], attributes: &[] },
    Signature { name: "nts_has_pending_work", returns: "zeroext i1", params: &[], attributes: &[] },
    Signature { name: "nts_host_install", returns: "void", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_in_callback", returns: "zeroext i1", params: &[], attributes: &[] },
    Signature { name: "nts_index_fn", returns: "i32", params: &["ptr", "double"], attributes: &[] },
    Signature { name: "nts_is_array", returns: "zeroext i1", params: &["[2 x i64]"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_is_buffer", returns: "zeroext i1", params: &["[2 x i64]"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_is_class", returns: "zeroext i1", params: &["[2 x i64]", "ptr"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_is_data_view", returns: "zeroext i1", params: &["[2 x i64]"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_is_date", returns: "zeroext i1", params: &["[2 x i64]"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_is_finite", returns: "zeroext i1", params: &["double"], attributes: &[] },
    Signature { name: "nts_is_integer", returns: "zeroext i1", params: &["double"], attributes: &[] },
    Signature { name: "nts_is_map", returns: "zeroext i1", params: &["[2 x i64]"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_is_owner_thread", returns: "zeroext i1", params: &[], attributes: &[] },
    Signature { name: "nts_is_promise", returns: "zeroext i1", params: &["[2 x i64]"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_is_safe_integer", returns: "zeroext i1", params: &["double"], attributes: &[] },
    Signature { name: "nts_is_set", returns: "zeroext i1", params: &["[2 x i64]"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_is_view_kind", returns: "zeroext i1", params: &["[2 x i64]", "double"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_landing_detail", returns: "ptr", params: &["ptr"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_landing_pop", returns: "void", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_landing_push", returns: "void", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_landing_thrown", returns: "[2 x i64]", params: &["ptr"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_leave", returns: "void", params: &[], attributes: &[] },
    Signature { name: "nts_live_bytes", returns: "i64", params: &[], attributes: &[] },
    Signature { name: "nts_live_count", returns: "i64", params: &[], attributes: &[] },
    Signature { name: "nts_map_clear", returns: "void", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_map_copy", returns: "noalias nonnull ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_map_delete", returns: "zeroext i1", params: &["ptr", "[2 x i64]"], attributes: &[] },
    Signature { name: "nts_map_get", returns: "[2 x i64]", params: &["ptr", "[2 x i64]"], attributes: &[] },
    Signature { name: "nts_map_has", returns: "zeroext i1", params: &["ptr", "[2 x i64]"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_map_key_at", returns: "[2 x i64]", params: &["ptr", "double"], attributes: &[] },
    Signature { name: "nts_map_keys_str", returns: "noalias nonnull ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_map_new", returns: "noalias nonnull ptr", params: &["double"], attributes: &[] },
    Signature { name: "nts_map_next", returns: "double", params: &["ptr", "double"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_map_set", returns: "ptr", params: &["ptr", "[2 x i64]", "[2 x i64]"], attributes: &[] },
    Signature { name: "nts_map_value_at", returns: "[2 x i64]", params: &["ptr", "double"], attributes: &[] },
    Signature { name: "nts_math_acos", returns: "double", params: &["double"], attributes: &[] },
    Signature { name: "nts_math_asin", returns: "double", params: &["double"], attributes: &[] },
    Signature { name: "nts_math_atan", returns: "double", params: &["double"], attributes: &[] },
    Signature { name: "nts_math_atan2", returns: "double", params: &["double", "double"], attributes: &[] },
    Signature { name: "nts_math_cbrt", returns: "double", params: &["double"], attributes: &[] },
    Signature { name: "nts_math_cos", returns: "double", params: &["double"], attributes: &[] },
    Signature { name: "nts_math_cosh", returns: "double", params: &["double"], attributes: &[] },
    Signature { name: "nts_math_exp", returns: "double", params: &["double"], attributes: &[] },
    Signature { name: "nts_math_expm1", returns: "double", params: &["double"], attributes: &[] },
    Signature { name: "nts_math_fround", returns: "double", params: &["double"], attributes: &[] },
    Signature { name: "nts_math_hypot", returns: "double", params: &["double", "double"], attributes: &[] },
    Signature { name: "nts_math_log", returns: "double", params: &["double"], attributes: &[] },
    Signature { name: "nts_math_log10", returns: "double", params: &["double"], attributes: &[] },
    Signature { name: "nts_math_log1p", returns: "double", params: &["double"], attributes: &[] },
    Signature { name: "nts_math_log2", returns: "double", params: &["double"], attributes: &[] },
    Signature { name: "nts_math_pow", returns: "double", params: &["double", "double"], attributes: &[] },
    Signature { name: "nts_math_sign", returns: "double", params: &["double"], attributes: &[] },
    Signature { name: "nts_math_sin", returns: "double", params: &["double"], attributes: &[] },
    Signature { name: "nts_math_sinh", returns: "double", params: &["double"], attributes: &[] },
    Signature { name: "nts_math_tan", returns: "double", params: &["double"], attributes: &[] },
    Signature { name: "nts_math_tanh", returns: "double", params: &["double"], attributes: &[] },
    Signature { name: "nts_max_fn", returns: "double", params: &["double", "double"], attributes: &[] },
    Signature { name: "nts_min_fn", returns: "double", params: &["double", "double"], attributes: &[] },
    Signature { name: "nts_no_arm", returns: "void", params: &["ptr"], attributes: &["noreturn"] },
    Signature { name: "nts_nsarray_of_objects", returns: "ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_nsarray_of_strings", returns: "ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_nsstring_of", returns: "ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_number_to_fixed", returns: "ptr", params: &["double", "double"], attributes: &[] },
    Signature { name: "nts_number_to_string", returns: "ptr", params: &["double"], attributes: &[] },
    Signature { name: "nts_number_to_string_into", returns: "ptr", params: &["ptr", "double"], attributes: &[] },
    Signature { name: "nts_number_to_string_radix", returns: "ptr", params: &["double", "double"], attributes: &[] },
    Signature { name: "nts_objc_adopt", returns: "void", params: &["ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_objc_register_class", returns: "void", params: &["ptr", "ptr", "ptr", "i32"], attributes: &[] },
    Signature { name: "nts_object_new", returns: "noalias nonnull ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_parse_float", returns: "double", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_parse_int", returns: "double", params: &["ptr", "double"], attributes: &[] },
    Signature { name: "nts_permanent_count", returns: "i64", params: &[], attributes: &[] },
    Signature { name: "nts_post_delayed", returns: "i64", params: &["ptr dead_on_return", "double", "i1 zeroext"], attributes: &[] },
    Signature { name: "nts_post_from_any_thread", returns: "void", params: &["ptr dead_on_return"], attributes: &[] },
    Signature { name: "nts_post_task", returns: "void", params: &["ptr dead_on_return"], attributes: &[] },
    Signature { name: "nts_presence_clear_fn", returns: "void", params: &["ptr", "i32"], attributes: &[] },
    Signature { name: "nts_presence_has_fn", returns: "zeroext i1", params: &["ptr", "i32"], attributes: &[] },
    Signature { name: "nts_presence_has_value", returns: "zeroext i1", params: &["[2 x i64]", "i32"], attributes: &[] },
    Signature { name: "nts_presence_init_fn", returns: "void", params: &["ptr", "i32"], attributes: &[] },
    Signature { name: "nts_presence_set_fn", returns: "void", params: &["ptr", "i32"], attributes: &[] },
    Signature { name: "nts_promise_adopt", returns: "void", params: &["ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_promise_all", returns: "ptr", params: &["ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_promise_fulfill_number", returns: "void", params: &["ptr", "double"], attributes: &[] },
    Signature { name: "nts_promise_fulfill_pointer", returns: "void", params: &["ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_promise_fulfill_reference", returns: "void", params: &["ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_promise_fulfill_tagged", returns: "void", params: &["ptr", "ptr", "i32"], attributes: &[] },
    Signature { name: "nts_promise_fulfill_value", returns: "void", params: &["ptr", "[2 x i64]"], attributes: &[] },
    Signature { name: "nts_promise_fulfill_void", returns: "void", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_promise_is_rejected", returns: "zeroext i1", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_promise_join", returns: "i32", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_promise_new", returns: "ptr", params: &[], attributes: &[] },
    Signature { name: "nts_promise_number", returns: "double", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_promise_pointer", returns: "ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_promise_race", returns: "ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_promise_reason", returns: "[2 x i64]", params: &["ptr"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_promise_reference", returns: "ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_promise_reject", returns: "void", params: &["ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_promise_reject_value", returns: "void", params: &["ptr", "[2 x i64]"], attributes: &[] },
    Signature { name: "nts_promise_reject_with", returns: "void", params: &["ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_promise_state", returns: "double", params: &["ptr"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_promise_subscribe", returns: "void", params: &["ptr", "ptr dead_on_return"], attributes: &[] },
    Signature { name: "nts_promise_value", returns: "[2 x i64]", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_raise", returns: "void", params: &["[2 x i64]"], attributes: &[] },
    Signature { name: "nts_raise_take", returns: "[2 x i64]", params: &[], attributes: &[] },
    Signature { name: "nts_raising", returns: "i32", params: &[], attributes: &[] },
    Signature { name: "nts_register_holders", returns: "void", params: &["i32", "ptr"], attributes: &[] },
    Signature { name: "nts_release", returns: "void", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_retain", returns: "void", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_round_fn", returns: "double", params: &["double"], attributes: &[] },
    Signature { name: "nts_set_add", returns: "ptr", params: &["ptr", "[2 x i64]"], attributes: &[] },
    Signature { name: "nts_set_new", returns: "noalias nonnull ptr", params: &["double"], attributes: &[] },
    Signature { name: "nts_set_timeout", returns: "double", params: &["ptr", "double", "double", "i1 zeroext"], attributes: &[] },
    Signature { name: "nts_slot_or_grow_fn", returns: "i32", params: &["ptr", "double"], attributes: &[] },
    Signature { name: "nts_str_alloc", returns: "ptr", params: &["ptr", "i32"], attributes: &[] },
    Signature { name: "nts_str_append", returns: "ptr", params: &["ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_str_at", returns: "ptr", params: &["ptr", "double"], attributes: &[] },
    Signature { name: "nts_str_at_into", returns: "ptr", params: &["ptr", "ptr", "double"], attributes: &[] },
    Signature { name: "nts_str_char_at", returns: "ptr", params: &["ptr", "double"], attributes: &[] },
    Signature { name: "nts_str_char_at_into", returns: "ptr", params: &["ptr", "ptr", "double"], attributes: &[] },
    Signature { name: "nts_str_char_code_at_fn", returns: "double", params: &["ptr", "double"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_str_char_code_at_int_fn", returns: "double", params: &["ptr", "i64"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_str_code_point_at", returns: "double", params: &["ptr", "double"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_str_ends_with", returns: "zeroext i1", params: &["ptr", "ptr"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_str_includes", returns: "zeroext i1", params: &["ptr", "ptr"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_str_index_of", returns: "double", params: &["ptr", "ptr"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_str_index_of_from", returns: "double", params: &["ptr", "ptr", "double"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_str_is_well_formed", returns: "zeroext i1", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_str_last_index_of", returns: "double", params: &["ptr", "ptr"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_str_pad_end", returns: "ptr", params: &["ptr", "double", "ptr"], attributes: &[] },
    Signature { name: "nts_str_pad_start", returns: "ptr", params: &["ptr", "double", "ptr"], attributes: &[] },
    Signature { name: "nts_str_point_width", returns: "double", params: &["ptr", "double"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_str_raw", returns: "ptr", params: &["i32", "i32"], attributes: &[] },
    Signature { name: "nts_str_relative_at", returns: "noalias ptr", params: &["ptr", "double"], attributes: &[] },
    Signature { name: "nts_str_repeat", returns: "ptr", params: &["ptr", "double"], attributes: &[] },
    Signature { name: "nts_str_replace", returns: "ptr", params: &["ptr", "ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_str_replace_all", returns: "ptr", params: &["ptr", "ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_str_slice", returns: "ptr", params: &["ptr", "double", "double"], attributes: &[] },
    Signature { name: "nts_str_slice_into", returns: "ptr", params: &["ptr", "ptr", "double", "double"], attributes: &[] },
    Signature { name: "nts_str_split", returns: "ptr", params: &["ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_str_starts_with", returns: "zeroext i1", params: &["ptr", "ptr"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_str_substring", returns: "ptr", params: &["ptr", "double", "double"], attributes: &[] },
    Signature { name: "nts_str_substring_general", returns: "ptr", params: &["ptr", "ptr", "double", "double"], attributes: &[] },
    Signature { name: "nts_str_substring_into_fn", returns: "ptr", params: &["ptr", "ptr", "double", "double"], attributes: &[] },
    Signature { name: "nts_str_to_lower_case", returns: "ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_str_to_number", returns: "double", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_str_to_upper_case", returns: "ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_str_to_well_formed", returns: "ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_str_trim", returns: "ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_str_trim_end", returns: "ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_str_trim_start", returns: "ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_string_cmp", returns: "i32", params: &["ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_string_eq", returns: "zeroext i1", params: &["ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_string_from_char_code", returns: "ptr", params: &["double"], attributes: &[] },
    Signature { name: "nts_string_from_char_code_into", returns: "ptr", params: &["ptr", "double"], attributes: &[] },
    Signature { name: "nts_string_from_code_point", returns: "ptr", params: &["double"], attributes: &[] },
    Signature { name: "nts_string_from_code_point_into", returns: "ptr", params: &["ptr", "double"], attributes: &[] },
    Signature { name: "nts_string_from_cstring", returns: "noalias ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_string_from_required_cstring", returns: "noalias nonnull ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_string_from_utf8", returns: "ptr", params: &["ptr", "i64"], attributes: &[] },
    Signature { name: "nts_string_of_nsstring", returns: "ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_string_to_cstring", returns: "ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_string_to_utf16", returns: "ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_string_truthy", returns: "zeroext i1", params: &["ptr"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_strings_from_cstrings", returns: "ptr", params: &["ptr", "i1 zeroext"], attributes: &[] },
    Signature { name: "nts_strings_to_cstrings", returns: "noalias ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_symbol_description", returns: "ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_symbol_for", returns: "ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_symbol_key_for", returns: "ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_symbol_new", returns: "noalias nonnull ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_symbol_to_string", returns: "noalias nonnull ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_tag_name", returns: "ptr", params: &["i32"], attributes: &[] },
    Signature { name: "nts_tag_of_reference", returns: "i32", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_task_run", returns: "void", params: &["ptr dead_on_return"], attributes: &[] },
    Signature { name: "nts_thrown_class", returns: "ptr", params: &["[2 x i64]"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_to_index", returns: "double", params: &["double"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_to_int16_fn", returns: "signext i16", params: &["double"], attributes: &[] },
    Signature { name: "nts_to_int32_fn", returns: "i32", params: &["double"], attributes: &[] },
    Signature { name: "nts_to_int8_fn", returns: "signext i8", params: &["double"], attributes: &[] },
    Signature { name: "nts_to_uint16_fn", returns: "zeroext i16", params: &["double"], attributes: &[] },
    Signature { name: "nts_to_uint32_fn", returns: "i32", params: &["double"], attributes: &[] },
    Signature { name: "nts_to_uint8_fn", returns: "zeroext i8", params: &["double"], attributes: &[] },
    Signature { name: "nts_uncaught", returns: "void", params: &["[2 x i64]", "ptr"], attributes: &["noreturn"] },
    Signature { name: "nts_unit_fn", returns: "zeroext i16", params: &["ptr", "i32"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_utf16_release", returns: "void", params: &["ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_value_eq_boolean_fn", returns: "zeroext i1", params: &["[2 x i64]", "i1 zeroext"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_value_eq_number_fn", returns: "zeroext i1", params: &["[2 x i64]", "double"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_value_eq_reference", returns: "zeroext i1", params: &["[2 x i64]", "ptr"], attributes: &[] },
    Signature { name: "nts_value_eq_string", returns: "zeroext i1", params: &["[2 x i64]", "ptr"], attributes: &[] },
    Signature { name: "nts_value_is_view", returns: "zeroext i1", params: &["[2 x i64]"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_value_number_or", returns: "double", params: &["[2 x i64]", "double"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_value_release", returns: "void", params: &["[2 x i64]"], attributes: &[] },
    Signature { name: "nts_value_retain", returns: "void", params: &["[2 x i64]"], attributes: &[] },
    Signature { name: "nts_value_strict_eq", returns: "zeroext i1", params: &["[2 x i64]", "[2 x i64]"], attributes: &[] },
    Signature { name: "nts_value_to_number", returns: "double", params: &["[2 x i64]"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_value_to_string", returns: "ptr", params: &["[2 x i64]"], attributes: &[] },
    Signature { name: "nts_value_truthy_fn", returns: "zeroext i1", params: &["[2 x i64]"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_view_buffer", returns: "ptr", params: &["ptr"], attributes: &[] },
    Signature { name: "nts_view_byte_length", returns: "double", params: &["ptr"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_view_byte_offset", returns: "double", params: &["ptr"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_view_bytes", returns: "ptr", params: &["ptr"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_view_check_fn", returns: "i32", params: &["ptr", "i32"], attributes: &[] },
    Signature { name: "nts_view_copy_within", returns: "void", params: &["ptr", "double", "double", "double"], attributes: &[] },
    Signature { name: "nts_view_fill", returns: "void", params: &["ptr", "double", "double", "double"], attributes: &[] },
    Signature { name: "nts_view_get", returns: "double", params: &["ptr", "double"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_view_index_fn", returns: "i32", params: &["ptr", "double"], attributes: &[] },
    Signature { name: "nts_view_join", returns: "ptr", params: &["ptr", "ptr"], attributes: &[] },
    Signature { name: "nts_view_length", returns: "double", params: &["ptr"], attributes: &["nounwind", "willreturn", "memory(read)"] },
    Signature { name: "nts_view_new", returns: "noalias ptr", params: &["ptr", "double", "double", "double", "i1 zeroext"], attributes: &[] },
    Signature { name: "nts_view_put", returns: "void", params: &["ptr", "double", "double"], attributes: &[] },
    Signature { name: "nts_view_set", returns: "void", params: &["ptr", "ptr", "double"], attributes: &[] },
    Signature { name: "nts_view_slice", returns: "noalias ptr", params: &["ptr", "double", "double"], attributes: &[] },
    Signature { name: "nts_view_subarray", returns: "noalias ptr", params: &["ptr", "double", "double"], attributes: &[] },
    Signature { name: "nts_view_unlend", returns: "void", params: &["ptr"], attributes: &[] },
];
