//! Every runtime function's signature, as clang reports it.
//!
//! # Why this is generated
//!
//! The first version of this backend read a helper's signature off the *call
//! site* -- the argument types the lowering chose and the result type the
//! operation carries. That is sound only where the two already agree, and they
//! do not: `nts_tag_name` takes a `uint32_t` and the lowering hands it a
//! double, because C converts implicitly at the call and the C backend never
//! had to think about it. LLVM has no implicit conversion, so the double went
//! into an SSE register and the callee read an integer one. `typeof v` answered
//! "undefined" for a number.
//!
//! So the signatures come from clang, which is the only thing that knows them.
//! `tests/signatures.rs` regenerates this from `nts_runtime.h` and fails if it
//! has drifted, which is what makes a generated file safe to check in.
//!
//! Attributes are kept: `zeroext` and `signext` are the ABI, not decoration.

/// A runtime function: its name, its result, and its parameters.
#[derive(Debug)]
pub struct Signature {
    pub name: &'static str,
    pub returns: &'static str,
    pub params: &'static [&'static str],
}

/// Sorted by name, so a lookup is a binary search and a diff is readable.
pub const SIGNATURES: &[Signature] = &[
    Signature { name: "fmod", returns: "double", params: &["double", "double"] },
    Signature { name: "llvm.floor.f64", returns: "double", params: &["double"] },
    Signature { name: "llvm.is.fpclass.f64", returns: "i1", params: &["double", "i32 immarg"] },
    Signature { name: "llvm.memcpy.p0.p0.i64", returns: "void", params: &["ptr noalias writeonly captures(none)", "ptr noalias readonly captures(none)", "i64", "i1 immarg"] },
    Signature { name: "llvm.trunc.f64", returns: "double", params: &["double"] },
    Signature { name: "nts_alloc", returns: "ptr", params: &["i64"] },
    Signature { name: "nts_array_at", returns: "double", params: &["ptr", "double"] },
    Signature { name: "nts_array_at_ref", returns: "ptr", params: &["ptr", "double"] },
    Signature { name: "nts_array_at_value", returns: "{ i32, i64 }", params: &["ptr", "double"] },
    Signature { name: "nts_array_fill", returns: "ptr", params: &["ptr", "double"] },
    Signature { name: "nts_array_fill_bool", returns: "ptr", params: &["ptr", "i1 zeroext"] },
    Signature { name: "nts_array_fill_ref", returns: "ptr", params: &["ptr", "ptr"] },
    Signature { name: "nts_array_includes", returns: "zeroext i1", params: &["ptr", "double"] },
    Signature { name: "nts_array_includes_ref", returns: "zeroext i1", params: &["ptr", "ptr"] },
    Signature { name: "nts_array_includes_str", returns: "zeroext i1", params: &["ptr", "ptr"] },
    Signature { name: "nts_array_index_of", returns: "double", params: &["ptr", "double"] },
    Signature { name: "nts_array_index_of_ref", returns: "double", params: &["ptr", "ptr"] },
    Signature { name: "nts_array_index_of_str", returns: "double", params: &["ptr", "ptr"] },
    Signature { name: "nts_array_join_str", returns: "ptr", params: &["ptr", "ptr"] },
    Signature { name: "nts_array_last_index_of", returns: "double", params: &["ptr", "double"] },
    Signature { name: "nts_array_new", returns: "ptr", params: &["ptr", "double"] },
    Signature { name: "nts_array_new_uninitialized", returns: "ptr", params: &["ptr", "double"] },
    Signature { name: "nts_array_pop", returns: "double", params: &["ptr"] },
    Signature { name: "nts_array_pop_ref", returns: "ptr", params: &["ptr"] },
    Signature { name: "nts_array_pop_value", returns: "{ i32, i64 }", params: &["ptr"] },
    Signature { name: "nts_array_push", returns: "double", params: &["ptr", "double"] },
    Signature { name: "nts_array_push_ref", returns: "double", params: &["ptr", "ptr"] },
    Signature { name: "nts_array_reverse", returns: "ptr", params: &["ptr"] },
    Signature { name: "nts_array_reverse_ref", returns: "ptr", params: &["ptr"] },
    Signature { name: "nts_array_slice", returns: "ptr", params: &["ptr", "double", "double"] },
    Signature { name: "nts_array_slice_ref", returns: "ptr", params: &["ptr", "double", "double"] },
    Signature { name: "nts_bigint_as_intn", returns: "i128", params: &["double", "i128"] },
    Signature { name: "nts_bigint_as_uintn", returns: "i128", params: &["double", "i128"] },
    Signature { name: "nts_bigint_shl", returns: "i128", params: &["i128", "i128"] },
    Signature { name: "nts_bigint_shr", returns: "i128", params: &["i128", "i128"] },
    Signature { name: "nts_bigint_to_string", returns: "ptr", params: &["i128"] },
    Signature { name: "nts_bool_to_string", returns: "ptr", params: &["i1 zeroext"] },
    Signature { name: "nts_bounds", returns: "void", params: &["double", "i32"] },
    Signature { name: "nts_callback_task", returns: "void", params: &["ptr dead_on_unwind writable sret(%struct.NtsTask) align 8", "ptr", "double", "i1 zeroext"] },
    Signature { name: "nts_cancel_delayed", returns: "void", params: &["i64"] },
    Signature { name: "nts_cell_unready", returns: "void", params: &["ptr"] },
    Signature { name: "nts_check_fn", returns: "i32", params: &["ptr", "i32"] },
    Signature { name: "nts_checkpoint", returns: "void", params: &[] },
    Signature { name: "nts_clear_timeout", returns: "void", params: &["double"] },
    Signature { name: "nts_collect_cycles", returns: "void", params: &[] },
    Signature { name: "nts_concat", returns: "ptr", params: &["ptr", "ptr"] },
    Signature { name: "nts_concat_into", returns: "ptr", params: &["ptr", "ptr", "ptr"] },
    Signature { name: "nts_cycle_candidates", returns: "i64", params: &[] },
    Signature { name: "nts_delay", returns: "double", params: &["double"] },
    Signature { name: "nts_enqueue_microtask", returns: "void", params: &["ptr byval(%struct.NtsTask) align 8"] },
    Signature { name: "nts_enqueue_tick", returns: "void", params: &["ptr byval(%struct.NtsTask) align 8"] },
    Signature { name: "nts_enter", returns: "void", params: &[] },
    Signature { name: "nts_has_pending_work", returns: "zeroext i1", params: &[] },
    Signature { name: "nts_host_install", returns: "void", params: &["ptr"] },
    Signature { name: "nts_index_fn", returns: "i32", params: &["ptr", "double"] },
    Signature { name: "nts_is_finite", returns: "zeroext i1", params: &["double"] },
    Signature { name: "nts_is_integer", returns: "zeroext i1", params: &["double"] },
    Signature { name: "nts_is_owner_thread", returns: "zeroext i1", params: &[] },
    Signature { name: "nts_is_safe_integer", returns: "zeroext i1", params: &["double"] },
    Signature { name: "nts_leave", returns: "void", params: &[] },
    Signature { name: "nts_live_bytes", returns: "i64", params: &[] },
    Signature { name: "nts_live_count", returns: "i64", params: &[] },
    Signature { name: "nts_map_clear", returns: "void", params: &["ptr"] },
    Signature { name: "nts_map_delete", returns: "zeroext i1", params: &["ptr", "i32", "i64"] },
    Signature { name: "nts_map_get", returns: "{ i32, i64 }", params: &["ptr", "i32", "i64"] },
    Signature { name: "nts_map_has", returns: "zeroext i1", params: &["ptr", "i32", "i64"] },
    Signature { name: "nts_map_key_at", returns: "{ i32, i64 }", params: &["ptr", "double"] },
    Signature { name: "nts_map_new", returns: "ptr", params: &["double"] },
    Signature { name: "nts_map_next", returns: "double", params: &["ptr", "double"] },
    Signature { name: "nts_map_set", returns: "ptr", params: &["ptr", "i32", "i64", "i32", "i64"] },
    Signature { name: "nts_map_value_at", returns: "{ i32, i64 }", params: &["ptr", "double"] },
    Signature { name: "nts_math_acos", returns: "double", params: &["double"] },
    Signature { name: "nts_math_asin", returns: "double", params: &["double"] },
    Signature { name: "nts_math_atan", returns: "double", params: &["double"] },
    Signature { name: "nts_math_atan2", returns: "double", params: &["double", "double"] },
    Signature { name: "nts_math_cbrt", returns: "double", params: &["double"] },
    Signature { name: "nts_math_cos", returns: "double", params: &["double"] },
    Signature { name: "nts_math_cosh", returns: "double", params: &["double"] },
    Signature { name: "nts_math_exp", returns: "double", params: &["double"] },
    Signature { name: "nts_math_expm1", returns: "double", params: &["double"] },
    Signature { name: "nts_math_fround", returns: "double", params: &["double"] },
    Signature { name: "nts_math_hypot", returns: "double", params: &["double", "double"] },
    Signature { name: "nts_math_log", returns: "double", params: &["double"] },
    Signature { name: "nts_math_log10", returns: "double", params: &["double"] },
    Signature { name: "nts_math_log1p", returns: "double", params: &["double"] },
    Signature { name: "nts_math_log2", returns: "double", params: &["double"] },
    Signature { name: "nts_math_pow", returns: "double", params: &["double", "double"] },
    Signature { name: "nts_math_sign", returns: "double", params: &["double"] },
    Signature { name: "nts_math_sin", returns: "double", params: &["double"] },
    Signature { name: "nts_math_sinh", returns: "double", params: &["double"] },
    Signature { name: "nts_math_tan", returns: "double", params: &["double"] },
    Signature { name: "nts_math_tanh", returns: "double", params: &["double"] },
    Signature { name: "nts_number_to_string", returns: "ptr", params: &["double"] },
    Signature { name: "nts_object_new", returns: "ptr", params: &["ptr"] },
    Signature { name: "nts_post_delayed", returns: "i64", params: &["ptr byval(%struct.NtsTask) align 8", "double", "i1 zeroext"] },
    Signature { name: "nts_post_from_any_thread", returns: "void", params: &["ptr byval(%struct.NtsTask) align 8"] },
    Signature { name: "nts_post_task", returns: "void", params: &["ptr byval(%struct.NtsTask) align 8"] },
    Signature { name: "nts_promise_all", returns: "ptr", params: &["ptr", "ptr"] },
    Signature { name: "nts_promise_fulfill_number", returns: "void", params: &["ptr", "double"] },
    Signature { name: "nts_promise_fulfill_reference", returns: "void", params: &["ptr", "ptr"] },
    Signature { name: "nts_promise_fulfill_tagged", returns: "void", params: &["ptr", "ptr", "i32"] },
    Signature { name: "nts_promise_fulfill_value", returns: "void", params: &["ptr", "i32", "i64"] },
    Signature { name: "nts_promise_fulfill_void", returns: "void", params: &["ptr"] },
    Signature { name: "nts_promise_is_rejected", returns: "zeroext i1", params: &["ptr"] },
    Signature { name: "nts_promise_new", returns: "ptr", params: &[] },
    Signature { name: "nts_promise_number", returns: "double", params: &["ptr"] },
    Signature { name: "nts_promise_race", returns: "ptr", params: &["ptr"] },
    Signature { name: "nts_promise_reference", returns: "ptr", params: &["ptr"] },
    Signature { name: "nts_promise_reject", returns: "void", params: &["ptr", "ptr"] },
    Signature { name: "nts_promise_reject_with", returns: "void", params: &["ptr", "ptr"] },
    Signature { name: "nts_promise_subscribe", returns: "void", params: &["ptr", "ptr byval(%struct.NtsTask) align 8"] },
    Signature { name: "nts_promise_value", returns: "{ i32, i64 }", params: &["ptr"] },
    Signature { name: "nts_release", returns: "void", params: &["ptr"] },
    Signature { name: "nts_retain", returns: "void", params: &["ptr"] },
    Signature { name: "nts_set_add", returns: "ptr", params: &["ptr", "i32", "i64"] },
    Signature { name: "nts_set_new", returns: "ptr", params: &["double"] },
    Signature { name: "nts_set_timeout", returns: "double", params: &["ptr", "double", "double", "i1 zeroext"] },
    Signature { name: "nts_str_char_at", returns: "ptr", params: &["ptr", "double"] },
    Signature { name: "nts_str_char_at_into", returns: "ptr", params: &["ptr", "ptr", "double"] },
    Signature { name: "nts_str_char_code_at_fn", returns: "double", params: &["ptr", "double"] },
    Signature { name: "nts_str_code_point_at", returns: "double", params: &["ptr", "double"] },
    Signature { name: "nts_str_ends_with", returns: "zeroext i1", params: &["ptr", "ptr"] },
    Signature { name: "nts_str_includes", returns: "zeroext i1", params: &["ptr", "ptr"] },
    Signature { name: "nts_str_index_of", returns: "double", params: &["ptr", "ptr"] },
    Signature { name: "nts_str_last_index_of", returns: "double", params: &["ptr", "ptr"] },
    Signature { name: "nts_str_point_width", returns: "double", params: &["ptr", "double"] },
    Signature { name: "nts_str_repeat", returns: "ptr", params: &["ptr", "double"] },
    Signature { name: "nts_str_replace", returns: "ptr", params: &["ptr", "ptr", "ptr"] },
    Signature { name: "nts_str_replace_all", returns: "ptr", params: &["ptr", "ptr", "ptr"] },
    Signature { name: "nts_str_slice", returns: "ptr", params: &["ptr", "double", "double"] },
    Signature { name: "nts_str_slice_into", returns: "ptr", params: &["ptr", "ptr", "double", "double"] },
    Signature { name: "nts_str_split", returns: "ptr", params: &["ptr", "ptr"] },
    Signature { name: "nts_str_starts_with", returns: "zeroext i1", params: &["ptr", "ptr"] },
    Signature { name: "nts_str_substring", returns: "ptr", params: &["ptr", "double", "double"] },
    Signature { name: "nts_str_substring_general", returns: "ptr", params: &["ptr", "ptr", "double", "double"] },
    Signature { name: "nts_str_trim", returns: "ptr", params: &["ptr"] },
    Signature { name: "nts_str_trim_end", returns: "ptr", params: &["ptr"] },
    Signature { name: "nts_str_trim_start", returns: "ptr", params: &["ptr"] },
    Signature { name: "nts_string_eq", returns: "zeroext i1", params: &["ptr", "ptr"] },
    Signature { name: "nts_string_from_char_code", returns: "ptr", params: &["double"] },
    Signature { name: "nts_string_from_code_point", returns: "ptr", params: &["double"] },
    Signature { name: "nts_string_from_utf8", returns: "ptr", params: &["ptr", "i64"] },
    Signature { name: "nts_string_truthy", returns: "zeroext i1", params: &["ptr"] },
    Signature { name: "nts_tag_name", returns: "ptr", params: &["i32"] },
    Signature { name: "nts_tag_of_reference", returns: "i32", params: &["ptr"] },
    Signature { name: "nts_task_run", returns: "void", params: &["ptr byval(%struct.NtsTask) align 8"] },
    Signature { name: "nts_thrown", returns: "void", params: &["ptr"] },
    Signature { name: "nts_to_int32_fn", returns: "i32", params: &["double"] },
    Signature { name: "nts_to_uint32_fn", returns: "i32", params: &["double"] },
    Signature { name: "nts_unit_fn", returns: "zeroext i16", params: &["ptr", "i32"] },
    Signature { name: "nts_value_eq_reference", returns: "zeroext i1", params: &["i32", "i64", "ptr"] },
    Signature { name: "nts_value_eq_string", returns: "zeroext i1", params: &["i32", "i64", "ptr"] },
    Signature { name: "nts_value_release", returns: "void", params: &["i32", "i64"] },
    Signature { name: "nts_value_retain", returns: "void", params: &["i32", "i64"] },
    Signature { name: "nts_value_strict_eq", returns: "zeroext i1", params: &["i32", "i64", "i32", "i64"] },
    Signature { name: "nts_value_to_string", returns: "ptr", params: &["i32", "i64"] },
];

/// The signature of a runtime function, if the runtime declares one.
#[must_use]
pub fn signature(name: &str) -> Option<&'static Signature> {
    SIGNATURES
        .binary_search_by(|known| known.name.cmp(name))
        .ok()
        .map(|at| &SIGNATURES[at])
}
