// Generated by `nts bind-c`. Edit the command, not this file.
//
// Derived from one compiler's reading of these headers under these macros,
// which makes it a claim like any hand-written binding. `native_witness.c`
// is what proves it against the headers a consumer actually compiles with.
/**
 * @ntsHeader sys/stat.h
 * @ntsDefine _GNU_SOURCE
 */
declare module "c:sys/stat" {
  import type { CArray, ConstPtr, Ptr, Struct, c_char, c_int, c_long, c_uint, c_ulong } from "c:types";
  export type Stat = Struct<{
    st_dev: c_ulong;
    st_ino: c_ulong;
    st_nlink: c_ulong;
    st_mode: c_uint;
    st_uid: c_uint;
    st_gid: c_uint;
    __pad0: c_int;
    st_rdev: c_ulong;
    st_size: c_long;
    st_blksize: c_long;
    st_blocks: c_long;
    st_atim: TimeSpec;
    st_mtim: TimeSpec;
    st_ctim: TimeSpec;
    __glibc_reserved: CArray<c_long, 3>;
  }, "stat">;
  export type TimeSpec = Struct<{
    tv_sec: c_long;
    tv_nsec: c_long;
  }, "timespec">;
  /** Nothing of `file` or `buf` outlives the call -- an authored claim, which no header
   * states and this tool did not read anywhere.
   * @ntsNoEscape file buf */
  export function stat(file: ConstPtr<c_char>, buf: Ptr<Stat>): c_int;
}
