// Generated by `nts bind-c`. Edit the command, not this file.
//
// Derived from one compiler's reading of these headers under these macros,
// which makes it a claim like any hand-written binding. `native_witness.c`
// is what proves it against the headers a consumer actually compiles with.
/**
 * @ntsHeader sys/resource.h
 */
declare module "c:sys/resource" {
  import type { Ptr, Struct, c_int, c_long } from "c:types";
  export type Rusage = Struct<{
    ru_utime: Timeval;
    ru_stime: Timeval;
    ru_maxrss: c_long; // the same bytes as __ru_maxrss_word
    ru_ixrss: c_long; // the same bytes as __ru_ixrss_word
    ru_idrss: c_long; // the same bytes as __ru_idrss_word
    ru_isrss: c_long; // the same bytes as __ru_isrss_word
    ru_minflt: c_long; // the same bytes as __ru_minflt_word
    ru_majflt: c_long; // the same bytes as __ru_majflt_word
    ru_nswap: c_long; // the same bytes as __ru_nswap_word
    ru_inblock: c_long; // the same bytes as __ru_inblock_word
    ru_oublock: c_long; // the same bytes as __ru_oublock_word
    ru_msgsnd: c_long; // the same bytes as __ru_msgsnd_word
    ru_msgrcv: c_long; // the same bytes as __ru_msgrcv_word
    ru_nsignals: c_long; // the same bytes as __ru_nsignals_word
    ru_nvcsw: c_long; // the same bytes as __ru_nvcsw_word
    ru_nivcsw: c_long; // the same bytes as __ru_nivcsw_word
  }, "rusage">;
  export type Timeval = Struct<{
    tv_sec: c_long;
    tv_usec: c_long;
  }, "timeval">;
  /** Nothing of `usage` outlives the call -- an authored claim, which no header
   * states and this tool did not read anywhere.
   * @ntsNoEscape usage */
  export function getrusage(who: c_int, usage: Ptr<Rusage>): c_int;
}
