//! The library interface. Layouts are emitted once and shared with program.c;
//! typedefs preserve their identity without making callers name internal `TypeN` tags.

use super::{
    CodeWriter, Diagnostic, HirType, ManagedType, Origin, Program, c_global, c_identifier,
    c_member_at, format_signature, layout_of, object_type_name, return_c_type, signature,
};
use rustc_hash::FxHashSet;

const PRELUDE: &str = "/* Generated by nts. Do not edit. */\n#ifndef NTS_PROGRAM_H\n#define NTS_PROGRAM_H\n#include \"nts_runtime.h\"\n";

pub(super) fn empty() -> String {
    format!("{PRELUDE}#endif /* NTS_PROGRAM_H */\n")
}

pub(super) fn emit(
    program: &Program,
    defined: &FxHashSet<String>,
    origin: &Origin,
    object_types: &str,
    diagnostics: &mut Vec<Diagnostic>,
) -> String {
    let mut writer = CodeWriter::new();
    for line in PRELUDE.lines().chain(object_types.lines()) {
        writer.line(origin, line);
    }
    writer.line(origin, "/* Object aliases below are named from the export and parameter; returns use <export>_return_t.");
    writer.line(origin, " * Regenerate this header together with program.c. Managed pointers must follow the runtime's lifetime rules.");
    writer.line(origin, " * For promises: call, run nts_checkpoint(), then inspect nts_promise_state() (0 pending, 1 fulfilled, 2 rejected).");
    writer.line(origin, " * Read nts_promise_value() only after settlement. A checkpoint drains microtasks; pending I/O needs a host loop. */");

    // Typedefs share C's ordinary identifier namespace with functions/globals.
    // Reserve these first so an alias never makes an otherwise legal export invalid.
    let mut names: FxHashSet<String> = program
        .funcs
        .iter()
        .map(|f| c_identifier(&f.name))
        .collect();
    names.extend(
        program
            .globals
            .iter()
            .map(|g| c_global(&g.name, program.funcs.iter().map(|f| f.name.as_str()))),
    );
    names.extend(program.layouts.iter().map(object_type_name));
    let next_entries = next_exports(program, defined, &mut names);
    for ((internal, published), next) in program.public_api.iter().zip(&next_entries) {
        let Some(func) = program
            .funcs
            .iter()
            .find(|f| f.name == *internal && defined.contains(&c_identifier(internal)))
        else {
            continue;
        };
        let result = (|| -> Result<(), Diagnostic> {
            let returns = boundary_type(
                &mut writer,
                &mut names,
                program,
                &func.return_type,
                &func.origin,
                &format!("{published}_return_t"),
            )?;
            let mut params = Vec::new();
            for (index, param) in func.params.iter().enumerate() {
                let ty = boundary_type(
                    &mut writer,
                    &mut names,
                    program,
                    &param.ty,
                    &param.origin,
                    &format!("{published}_{}_t", param.name),
                )?;
                params.push(format!("{ty} v{index}"));
            }
            let display = published.escape_default().to_string().replace("*/", "* /");
            writer.line(
                &func.origin,
                format!(
                    "/* Export: {display}. C symbol: {}. */",
                    c_identifier(internal)
                ),
            );
            writer.line(
                &func.origin,
                format!("{};", format_signature(internal, &returns, &params, true)),
            );
            if let Some(next) = next {
                emit_next(
                    &mut writer,
                    &mut names,
                    program,
                    next,
                    &returns,
                    published,
                    &func.origin,
                )?;
            }
            Ok(())
        })();
        if let Err(problem) = result {
            diagnostics.push(problem);
        }
    }
    // Top-level initializers are part of embedding even though they are not a TS export.
    if let Some(init) = program.funcs.iter().find(|f| {
        f.name == nts_core::hir::lower::MODULE_INIT && defined.contains(&c_identifier(&f.name))
    }) {
        writer.line(
            origin,
            "/* Call once before other exports to evaluate module-level initializers. */",
        );
        match signature(program, init) {
            Ok(signature) => writer.line(origin, format!("{signature};")),
            Err(problem) => diagnostics.push(problem),
        }
    }
    writer.line(origin, "#endif /* NTS_PROGRAM_H */");
    writer.text().to_owned()
}

struct NextExport<'a> {
    generator: &'a nts_core::hir::GeneratorResumption,
    resume: &'a nts_core::hir::Func,
    name: String,
}

fn next_exports<'a>(
    program: &'a Program,
    defined: &FxHashSet<String>,
    names: &mut FxHashSet<String>,
) -> Vec<Option<NextExport<'a>>> {
    program
        .public_api
        .iter()
        .map(|(internal, published)| {
            let generator = program.generators.iter().find(|generator| {
                generator.constructor == *internal
                    && generator.frame.kind == nts_core::hir::GeneratorKind::Sync
                    && defined.contains(&c_identifier(&generator.resume))
            })?;
            let resume = program.funcs.iter().find(|f| f.name == generator.resume)?;
            Some(NextExport {
                generator,
                resume,
                name: unique_name(names, &format!("{published}_next")),
            })
        })
        .collect()
}

fn emit_next(
    writer: &mut CodeWriter,
    names: &mut FxHashSet<String>,
    program: &Program,
    next: &NextExport<'_>,
    returns: &str,
    published: &str,
    origin: &Origin,
) -> Result<(), Diagnostic> {
    let frame_ty = HirType::Managed(ManagedType::Object(next.generator.frame.ty));
    let layout = layout_of(program, &frame_ty, origin)?;
    let yielded = boundary_type(
        writer,
        names,
        program,
        &next.generator.frame.yields,
        origin,
        &format!("{published}_yield_t"),
    )?;
    writer.line(origin, format!("{};", signature(program, next.resume)?));
    writer.line(origin, "/* Returns true and writes *value for a yield; false after completion, leaving *value unchanged.");
    writer.line(origin, " * The frame is borrowed. Managed yielded values are borrowed until the next step or frame release. */");
    writer.line(
        origin,
        format!(
            "static inline bool {}({returns} frame, {yielded} *value) {{",
            next.name
        ),
    );
    writer.line(
        origin,
        format!(
            "    {} *state = ({} *)frame;",
            object_type_name(layout),
            object_type_name(layout)
        ),
    );
    writer.line(
        origin,
        format!(
            "    if ({}(state)) return false;",
            c_identifier(&next.resume.name)
        ),
    );
    writer.line(
        origin,
        format!(
            "    *value = state->{};",
            c_member_at(layout, nts_core::hir::suspend::FIELD_YIELDED as usize)
        ),
    );
    writer.line(origin, "    return true;");
    writer.line(origin, "}");
    Ok(())
}

fn boundary_type(
    writer: &mut CodeWriter,
    names: &mut FxHashSet<String>,
    program: &Program,
    ty: &HirType,
    origin: &Origin,
    preferred: &str,
) -> Result<String, Diagnostic> {
    if !matches!(ty, HirType::Managed(ManagedType::Object(_))) {
        return return_c_type(program, ty, origin);
    }
    let layout = layout_of(program, ty, origin)?;
    let alias = unique_name(names, preferred);
    writer.line(
        origin,
        format!("typedef struct {} {alias};", object_type_name(layout)),
    );
    Ok(format!("{alias} *"))
}

fn unique_name(names: &mut FxHashSet<String>, preferred: &str) -> String {
    let base = c_identifier(preferred);
    let mut alias = base.clone();
    let mut suffix = 2;
    while !names.insert(alias.clone()) {
        alias = format!("{base}_{suffix}");
        suffix += 1;
    }
    alias
}
