//! The library interface. Layouts are emitted once and shared with program.c;
//! typedefs preserve their identity without making callers name internal `TypeN` tags.

use super::{
    CodeWriter, Diagnostic, HirType, ManagedType, Origin, Program, c_global, c_identifier,
    c_member_at, format_signature, layout_of, object_type_name, return_c_type, signature,
};
use rustc_hash::FxHashSet;

const PRELUDE: &str = "/* Generated by nts. Do not edit. */\n#ifndef NTS_PROGRAM_H\n#define NTS_PROGRAM_H\n";
const RUNTIME_INCLUDE: &str = "#include \"nts_runtime.h\"";

/// What the program's native bindings named, brought in before anything uses it.
///
/// **Included rather than redefined.** A foreign struct is a type some header
/// defines, and this file used to define its own copy -- so a translation unit
/// including both got `redefinition of 'struct utsname'`, and the two could
/// never meet. A C consumer wanting to call `uname` itself had to choose.
///
/// **The macros are required, not set.** A feature-test macro only does
/// anything before the first system header, and this file has no way to be
/// there: an includer that reached for `<stdio.h>` first has already fixed the
/// answer. Setting one here would work in the easy case and silently produce a
/// different `struct utsname` in the other. So it is asked for, by name, and a
/// build that forgot gets a message instead of a different struct.
pub(super) fn bindings(writer: &mut CodeWriter, origin: &Origin, program: &Program) {
    if !super::native_memory::needs_headers(program) {
        return;
    }
    // Required, not set. This file cannot be first -- an includer that reached
    // for <stdio.h> already fixed the answer -- so defining a feature-test
    // macro here would work in the easy case and silently produce a different
    // struct in the other. Asked for by name instead, so a build that forgot
    // gets a message rather than a different struct.
    for define in &program.native_defines {
        let name = define.split_once('=').map_or(define.as_str(), |(name, _)| name);
        writer.line(origin, format!("#ifndef {name}"));
        writer.line(
            origin,
            format!("#error \"this program's native bindings were checked under {name}; compile with -D{define}\""),
        );
        writer.line(origin, "#endif");
    }
    include_headers(writer, origin, program);
}

/// The headers a binding named, spelled as it spelled them.
///
/// `<x.h>` and `"x.h"` differ in where the preprocessor looks, and a project
/// header on the quoted path is not the system one that shares its name.
pub(super) fn include_headers(writer: &mut CodeWriter, origin: &Origin, program: &Program) {
    for header in &program.native_headers {
        let spelled = if header.starts_with('<') || header.starts_with('"') {
            header.clone()
        } else {
            format!("<{header}>")
        };
        writer.line(origin, format!("#include {spelled}"));
    }
}

pub(super) fn empty() -> String {
    format!("{PRELUDE}{RUNTIME_INCLUDE}\n#endif /* NTS_PROGRAM_H */\n")
}

pub(super) fn emit(
    program: &Program,
    defined: &FxHashSet<String>,
    origin: &Origin,
    object_types: &str,
    diagnostics: &mut Vec<Diagnostic>,
) -> String {
    let mut writer = CodeWriter::new();
    for line in PRELUDE.lines() {
        writer.line(origin, line);
    }
    bindings(&mut writer, origin, program);
    for line in std::iter::once(RUNTIME_INCLUDE).chain(object_types.lines()) {
        writer.line(origin, line);
    }
    writer.line(origin, "/* Object aliases below are named from the export and parameter; returns use <export>_return_t.");
    writer.line(origin, " * Regenerate this header together with program.c. Managed pointers must follow the runtime's lifetime rules.");
    writer.line(origin, " * If `module__init` is declared below, call it once before any export: the");
    writer.line(origin, " * program has module-level state, and an export that reads it before the");
    writer.line(origin, " * initializer runs sees a zero rather than what the module assigned.");
    writer.line(origin, " * For promises: call, run nts_checkpoint(), then inspect nts_promise_state() (0 pending, 1 fulfilled, 2 rejected).");
    writer.line(origin, " * Read nts_promise_value() only after settlement. A checkpoint drains microtasks; pending I/O needs a host loop. */");

    // Typedefs share C's ordinary identifier namespace with functions/globals.
    // Reserve these first so an alias never makes an otherwise legal export invalid.
    let mut names: FxHashSet<String> = program
        .funcs
        .iter()
        .map(|f| c_identifier(&f.name))
        .collect();
    names.extend(
        program
            .globals
            .iter()
            .map(|g| c_global(&g.name, program.funcs.iter().map(|f| f.name.as_str()))),
    );
    names.extend(program.layouts.iter().map(object_type_name));
    let next_entries = next_exports(program, defined, &mut names);
    for ((internal, published), next) in program.public_api.iter().zip(&next_entries) {
        let Some(func) = program
            .funcs
            .iter()
            .find(|f| f.name == *internal && defined.contains(&c_identifier(internal)))
        else {
            continue;
        };
        let result = (|| -> Result<(), Diagnostic> {
            let returns = boundary_type(
                &mut writer,
                &mut names,
                program,
                &func.return_type,
                &func.origin,
                &format!("{published}_return_t"),
            )?;
            let mut params = Vec::new();
            for (index, param) in func.params.iter().enumerate() {
                let ty = boundary_type(
                    &mut writer,
                    &mut names,
                    program,
                    &param.ty,
                    &param.origin,
                    &format!("{published}_{}_t", param.name),
                )?;
                params.push(format!("{ty} v{index}"));
            }
            let display = published.escape_default().to_string().replace("*/", "* /");
            writer.line(
                &func.origin,
                format!(
                    "/* Export: {display}. C symbol: {}. */",
                    c_identifier(internal)
                ),
            );
            writer.line(
                &func.origin,
                format!("{};", format_signature(internal, &returns, &params, true)),
            );
            if let Some(next) = next {
                emit_next(
                    &mut writer,
                    &mut names,
                    program,
                    next,
                    &returns,
                    published,
                    &func.origin,
                )?;
            }
            Ok(())
        })();
        if let Err(problem) = result {
            diagnostics.push(problem);
        }
    }
    // Top-level initializers are part of embedding even though they are not a TS export.
    if let Some(init) = program.funcs.iter().find(|f| {
        f.name == nts_core::hir::lower::MODULE_INIT && defined.contains(&c_identifier(&f.name))
    }) {
        writer.line(
            origin,
            "/* Call once before other exports to evaluate module-level initializers. */",
        );
        match signature(program, init) {
            Ok(signature) => writer.line(origin, format!("{signature};")),
            Err(problem) => diagnostics.push(problem),
        }
    }
    published_values(&mut writer, &mut names, program, diagnostics);
    writer.line(origin, "#endif /* NTS_PROGRAM_H */");
    writer.text().to_owned()
}

struct NextExport<'a> {
    generator: &'a nts_core::hir::GeneratorResumption,
    resume: &'a nts_core::hir::Func,
    name: String,
}

fn next_exports<'a>(
    program: &'a Program,
    defined: &FxHashSet<String>,
    names: &mut FxHashSet<String>,
) -> Vec<Option<NextExport<'a>>> {
    program
        .public_api
        .iter()
        .map(|(internal, published)| {
            let generator = program.generators.iter().find(|generator| {
                generator.constructor == *internal
                    && generator.frame.kind == nts_core::hir::GeneratorKind::Sync
                    && defined.contains(&c_identifier(&generator.resume))
            })?;
            let resume = program.funcs.iter().find(|f| f.name == generator.resume)?;
            Some(NextExport {
                generator,
                resume,
                name: unique_name(names, &format!("{published}_next")),
            })
        })
        .collect()
}

fn emit_next(
    writer: &mut CodeWriter,
    names: &mut FxHashSet<String>,
    program: &Program,
    next: &NextExport<'_>,
    returns: &str,
    published: &str,
    origin: &Origin,
) -> Result<(), Diagnostic> {
    let frame_ty = HirType::Managed(ManagedType::Object(next.generator.frame.ty));
    let layout = layout_of(program, &frame_ty, origin)?;
    let yielded = boundary_type(
        writer,
        names,
        program,
        &next.generator.frame.yields,
        origin,
        &format!("{published}_yield_t"),
    )?;
    writer.line(origin, format!("{};", signature(program, next.resume)?));
    writer.line(origin, "/* Returns true and writes *value for a yield; false after completion, leaving *value unchanged.");
    writer.line(origin, " * The frame is borrowed. Managed yielded values are borrowed until the next step or frame release. */");
    writer.line(
        origin,
        format!(
            "static inline bool {}({returns} frame, {yielded} *value) {{",
            next.name
        ),
    );
    writer.line(
        origin,
        format!(
            "    {} *state = ({} *)frame;",
            object_type_name(layout),
            object_type_name(layout)
        ),
    );
    writer.line(
        origin,
        format!(
            "    if ({}(state)) return false;",
            c_identifier(&next.resume.name)
        ),
    );
    writer.line(
        origin,
        format!(
            "    *value = state->{};",
            c_member_at(layout, nts_core::hir::suspend::FIELD_YIELDED as usize)
        ),
    );
    writer.line(origin, "    return true;");
    writer.line(origin, "}");
    Ok(())
}

/// **A published value is an export too, and this header did not say so.**
/// `public_api` holds every export; the loop above looks each one up among
/// `funcs` and `continue`s when there is none, so `export const greeting`
/// was dropped in silence -- no diagnostic, and a header that looks complete.
///
/// `program.c` emits it with external linkage and its own comment says why:
/// "external linkage *is* a reader, and the whole point of publishing a
/// constant is that something outside this translation unit names it". Then
/// the header that consumer includes did not name it, so naming it meant
/// writing the `extern` by hand. The build lane's test for
/// `examples/library` does exactly that, which is how this surfaced -- a
/// consumer working around the header rather than a compiler error.
///
/// **After `module__init`'s declaration, deliberately.** A module-level
/// initializer is what assigns these, so the note about calling it first is
/// the thing a reader needs *before* being handed a name to read.
fn published_values(
    writer: &mut CodeWriter,
    names: &mut FxHashSet<String>,
    program: &Program,
    diagnostics: &mut Vec<Diagnostic>,
) {
    for (internal, published) in &program.public_api {
        let Some(global) = program
            .globals
            .iter()
            .find(|global| global.exported && global.name == *internal)
        else {
            continue;
        };
        let symbol = c_global(&global.name, program.funcs.iter().map(|f| f.name.as_str()));
        let result = (|| -> Result<(), Diagnostic> {
            let ty = boundary_type(
                writer,
                names,
                program,
                &global.ty,
                &global.origin,
                &format!("{published}_t"),
            )?;
            let display = published.escape_default().to_string().replace("*/", "* /");
            writer.line(
                &global.origin,
                format!("/* Export: {display}. C symbol: {symbol}. A value, not a function: it holds what `module__init` assigned. */"),
            );
            writer.line(&global.origin, format!("extern {ty} {symbol};"));
            Ok(())
        })();
        if let Err(problem) = result {
            diagnostics.push(problem);
        }
    }
}

fn boundary_type(
    writer: &mut CodeWriter,
    names: &mut FxHashSet<String>,
    program: &Program,
    ty: &HirType,
    origin: &Origin,
    preferred: &str,
) -> Result<String, Diagnostic> {
    if let HirType::NativePointer(nts_core::hir::native::Pointee::Record(layout)) = ty {
        let alias = unique_name(names, preferred);
        writer.line(origin, format!("typedef struct {} {alias};", layout.name));
        return Ok(format!("{alias} *"));
    }
    if !matches!(ty, HirType::Managed(ManagedType::Object(_))) {
        return return_c_type(program, ty, origin);
    }
    let layout = layout_of(program, ty, origin)?;
    let alias = unique_name(names, preferred);
    writer.line(
        origin,
        format!("typedef struct {} {alias};", object_type_name(layout)),
    );
    Ok(format!("{alias} *"))
}

fn unique_name(names: &mut FxHashSet<String>, preferred: &str) -> String {
    let base = c_identifier(preferred);
    let mut alias = base.clone();
    let mut suffix = 2;
    while !names.insert(alias.clone()) {
        alias = format!("{base}_{suffix}");
        suffix += 1;
    }
    alias
}
