// GENERATED by `nts bind`. Do not edit.
//
// Every comment below is emitted, not written by hand: where a member costs an
// allocation or loads a class, the declaration is where a reader is looking.
//
// The brands and the `java.*` namespace come from java.d.ts, which is global --
// this file must NOT import them, or it becomes a module and declares nothing.

declare module "java:com.example.ui" {
  /** com.example.ui.Loader */
  export class Loader {
    constructor();
    static load(a0: string, a1: (a0: Uint8Array) => void): void;
  }

  /** com.example.ui.Rect */
  export class Rect {
    left: number;
    top: number;
    right: number;
    bottom: number;
    constructor();
    constructor(a0: number, a1: number, a2: number, a3: number);
    width(): number;
    height(): number;
  }

  /** com.example.ui.View */
  export class View {
    constructor();
    setOnTouch(a0: (a0: number, a1: number) => boolean): void;
    dispatchTouch(a0: number, a1: number): boolean;
    /** Inherited. */
    left: number;
    /** Inherited. */
    top: number;
    /** Inherited. */
    right: number;
    /** Inherited. */
    bottom: number;
    /** Inherited. */
    onMeasure(a0: number, a1: number): void;
    /** Inherited. */
    setBounds(a0: number, a1: number, a2: number, a3: number): void;
    /** Inherited. */
    setBounds(a0: Rect): void;
  }

  /** com.example.ui.Widget */
  export class Widget {
    left: number;
    top: number;
    right: number;
    bottom: number;
    constructor();
    onMeasure(a0: number, a1: number): void;
    setBounds(a0: number, a1: number, a2: number, a3: number): void;
    setBounds(a0: Rect): void;
  }

}
