// GENERATED by `nts bind`. Do not edit.
//
// Every comment below is emitted, not written by hand: where a member costs an
// allocation or loads a class, the declaration is where a reader is looking.
//
// The brands and the `java.*` namespace come from java.d.ts, which is global --
// this file must NOT import them, or it becomes a module and declares nothing.

declare module "java:com.example.ui" {
  /** com.example.ui.Drawable */
  export abstract class Drawable {
    constructor();
    alpha(): number;
    draw(a0: Rect): void;
  }

  /** com.example.ui.Loader Final: cannot be extended. */
  export class Loader {
    constructor();
    static load(a0: string, a1: Loader.OnBytes | ((a0: Uint8Array) => void)): void;
  }

  export namespace Loader {
    /** com.example.ui.Loader$OnBytes */
    export interface OnBytes {
      onBytes(a0: Uint8Array): void;
    }
  }

  /** com.example.ui.Rect Final: cannot be extended. */
  export class Rect {
    left: number;
    top: number;
    right: number;
    bottom: number;
    constructor();
    constructor(a0: number, a1: number, a2: number, a3: number);
    compareTo(a0: Rect): number;
    width(): number;
    height(): number;
  }

  /** com.example.ui.View */
  export class View {
    constructor();
    setOnTouch(a0: View.OnTouch | ((a0: number, a1: number) => boolean)): void;
    dispatchTouch(a0: number, a1: number): boolean;
    /** Inherited. */
    left: number;
    /** Inherited. */
    top: number;
    /** Inherited. */
    right: number;
    /** Inherited. */
    bottom: number;
    /** Inherited. */
    onMeasure(a0: number, a1: number): void;
    /** Inherited. */
    protected onDraw(a0: Rect): void;
    /** Inherited. */
    setBounds(a0: number, a1: number, a2: number, a3: number): void;
    /** Inherited. */
    static defaultPadding(): number;
    /** Inherited. */
    setPadding(...a0: number[]): void;
    /** Inherited. */
    press(a0: Widget.Pressable): void;
    /** Inherited. */
    post(a0: Widget.Task | ((a0: number) => void)): void;
    /** Inherited. */
    setBounds(a0: Rect): void;
  }

  export namespace View {
    /** com.example.ui.View$OnTouch */
    export interface OnTouch {
      onTouch(a0: number, a1: number): boolean;
    }
  }

  /** com.example.ui.Widget */
  export class Widget {
    left: number;
    top: number;
    right: number;
    bottom: number;
    constructor();
    onMeasure(a0: number, a1: number): void;
    protected onDraw(a0: Rect): void;
    setBounds(a0: number, a1: number, a2: number, a3: number): void;
    static defaultPadding(): number;
    setPadding(...a0: number[]): void;
    press(a0: Widget.Pressable): void;
    post(a0: Widget.Task | ((a0: number) => void)): void;
    setBounds(a0: Rect): void;
  }

  export namespace Widget {
    /** com.example.ui.Widget$Pressable */
    export interface Pressable {
      press(): void;
      /** Inherited. */
      run(a0: number): void;
    }
    export namespace Pressable {
        /** Inherited. */
        const KIND: string;
    }
    /** com.example.ui.Widget$Task */
    export interface Task {
      run(a0: number): void;
    }
    export namespace Task {
        /** Inlined at the call site: the class is never loaded for this. */
        const KIND: string;
        function none(): Widget.Task | null;
    }
  }

}
