// Public `node:stream/iter` namespace, introduced experimentally in Node 24.
// The namespace is frozen by `shape.mjs` for Node-host conformance; freezing
// is public CommonJS object shape and is not part of the compiled algorithms.

import { from, fromSync } from "./from.ts";
import {
  array,
  arrayBuffer,
  arrayBufferSync,
  arraySync,
  bytes,
  bytesSync,
  merge,
  ondrain,
  tap,
  tapSync,
  text,
  textSync,
} from "./consumers.ts";
import { pipeTo, pipeToSync, pull, pullSync } from "./pull.ts";
import { push } from "./push.ts";
import { duplex } from "./duplex.ts";
import { Broadcast, broadcast } from "./broadcast.ts";
import { Share, share, SyncShare, shareSync } from "./share.ts";
import {
  fromReadable,
  fromWritable,
  toReadable,
  toReadableSync,
  toWritable,
} from "./classic.ts";
import {
  broadcastProtocol,
  drainableProtocol,
  shareProtocol,
  shareSyncProtocol,
  toAsyncStreamable,
  toStreamable,
} from "./types.ts";

export {
  array,
  arrayBuffer,
  arrayBufferSync,
  arraySync,
  Broadcast,
  broadcast,
  broadcastProtocol,
  bytes,
  bytesSync,
  merge,
  ondrain,
  drainableProtocol,
  from,
  fromReadable,
  fromSync,
  fromWritable,
  duplex,
  pipeTo,
  pipeToSync,
  pull,
  pullSync,
  push,
  shareProtocol,
  Share,
  share,
  SyncShare,
  shareSync,
  shareSyncProtocol,
  tap,
  tapSync,
  text,
  textSync,
  toAsyncStreamable,
  toReadable,
  toReadableSync,
  toStreamable,
  toWritable,
};

export const Stream = {
  from,
  fromReadable,
  fromSync,
  fromWritable,
  push,
  broadcast,
  Broadcast,
  share,
  shareSync,
  Share,
  SyncShare,
  duplex,
  pull,
  pullSync,
  pipeTo,
  pipeToSync,
  bytes,
  text,
  arrayBuffer,
  array,
  merge,
  bytesSync,
  ondrain,
  textSync,
  arrayBufferSync,
  arraySync,
  tap,
  tapSync,
  toStreamable,
  toAsyncStreamable,
  toReadable,
  toReadableSync,
  toWritable,
  broadcastProtocol,
  shareProtocol,
  shareSyncProtocol,
  drainableProtocol,
};
