// One C implementation behind a TypeScript surface, for every target including
// the Node addon. Nothing here is platform-conditional.
//
// `c:digest` is generated by `nts build` from `native/digest.h`, which
// `nts.config.ts` names. The import is what says which module and which
// function; the config says where the header is; neither repeats the other.
import { digest_step } from "c:digest";
import type { c_uint32 } from "c:types";

/** The FNV offset basis, which a chain of `digest` calls starts from. */
export const seed = 2166136261;

export function digest(from: number, value: number): number {
  return digest_step(from as c_uint32, value as c_uint32);
}
