//! Emitting C from HIR.
//!
//! # A printer, not a decision-maker
//!
//! Block order and the copies a block-parameter edge implies are decided in
//! `nts-codegen-common`, so nothing here chooses anything a JVM emitter would
//! have to choose again. What is left is spelling.
//!
//! # Scalars only, for now
//!
//! A managed reference needs a runtime — an allocator, a header, a collector —
//! and none of that exists yet. Rather than emit a plausible `char *` and pretend,
//! a function touching a managed type is refused. RFC §4.1 again: the failure has
//! to be visible.

use nts_codegen_common::{CodeWriter, Copy, block_order, destruct};
use nts_core::hir::{
    BinOp, BlockId, Callee, Func, HirType, ManagedType, OpKind, Program, Terminator, UnOp, ValueId,
};
use nts_diagnostics::Diagnostic;
use nts_semantic_schema::Origin;

/// C for one program, and what could not be emitted.
#[derive(Debug)]
pub struct Emitted {
    pub writer: CodeWriter,
    pub diagnostics: Vec<Diagnostic>,
}

impl Emitted {
    #[must_use]
    pub fn is_complete(&self) -> bool {
        self.diagnostics.is_empty()
    }
}

/// Emit a whole program as one translation unit.
#[must_use]
pub fn emit(program: &Program) -> Emitted {
    let mut writer = CodeWriter::new();
    let mut diagnostics = Vec::new();

    let Some(first) = program.funcs.first() else {
        return Emitted {
            writer,
            diagnostics,
        };
    };
    let origin = first.origin.clone();

    // Each function is emitted speculatively and kept only if it succeeded. A
    // half-emitted function is worse than an absent one: it declares a signature
    // and a body that does not return, which compiles into a callable shell.
    // Two different TypeScript names can mangle to one C name — `double` and
    // `double_` both become `double_`. Emitting both would produce a redefinition
    // error far from its cause, so it is caught here where the cause is known.
    let mut claimed: rustc_hash::FxHashMap<String, &str> = rustc_hash::FxHashMap::default();
    for func in &program.funcs {
        let c_name = c_identifier(&func.name);
        if let Some(previous) = claimed.insert(c_name.clone(), &func.name)
            && previous != func.name
        {
            diagnostics.push(Diagnostic::error(
                "NTS2004",
                format!(
                    "`{}` and `{previous}` both need the C name `{c_name}`",
                    func.name
                ),
                func.origin.location,
            ));
        }
    }

    let mut bodies = Vec::new();
    for func in &program.funcs {
        let mut body = CodeWriter::new();
        match emit_func(&mut body, func) {
            Ok(signature) => bodies.push((signature, body, func)),
            Err(diagnostic) => diagnostics.push(diagnostic),
        }
    }

    let helpers = helpers_reached(&bodies);
    let descriptors = descriptors_reached(&bodies);

    writer.line(&origin, "/* Generated by nts. Do not edit. */");
    writer.line(&origin, "#include <stdbool.h>");
    writer.line(&origin, "#include <stdint.h>");
    if !helpers.is_empty() {
        writer.line(&origin, "#include <math.h>");
    }
    if helpers.iter().any(|helper| {
        helper.starts_with("nts_a")
            || helper.starts_with("nts_b")
            || helper.starts_with("nts_c")
            || helper.starts_with("nts_i")
    }) {
        writer.line(&origin, "#include <stddef.h>");
        writer.line(&origin, "#include <stdio.h>");
        writer.line(&origin, "#include <stdlib.h>");
        writer.line(&origin, "#include <string.h>");
    }
    writer.blank(&origin);
    emit_prelude(&mut writer, &origin, &helpers, &descriptors);

    // Forward declarations, so a call does not depend on definition order — and
    // only for functions that actually have a definition.
    for (signature, _, _) in &bodies {
        writer.line(&origin, format!("{signature};"));
    }
    writer.blank(&origin);

    for (_, body, _) in bodies {
        writer.append(body);
    }

    Emitted {
        writer,
        diagnostics,
    }
}

/// Identifiers C will not let us use for a function.
///
/// C11 keywords, the macros `<stdbool.h>` defines, and `main`. TypeScript has no
/// such restriction, so `function double()` is perfectly good source that cannot
/// be spelled that way in C.
const RESERVED: &[&str] = &[
    "alignas",
    "alignof",
    "auto",
    "bool",
    "break",
    "case",
    "char",
    "const",
    "constexpr",
    "continue",
    "default",
    "do",
    "double",
    "else",
    "enum",
    "extern",
    "false",
    "float",
    "for",
    "goto",
    "if",
    "inline",
    "int",
    "long",
    "main",
    "nullptr",
    "register",
    "restrict",
    "return",
    "short",
    "signed",
    "sizeof",
    "static",
    "static_assert",
    "struct",
    "switch",
    "thread_local",
    "true",
    "typedef",
    "typeof",
    "union",
    "unsigned",
    "void",
    "volatile",
    "while",
];

/// The C spelling of a function name.
///
/// Appending an underscore is the whole rule: it is reversible by inspection,
/// which matters because an exported name is an ABI that a human will link
/// against. Names this backend generates itself (`v0`, `t0`, `b0`) are mangled
/// the same way, so a function called `v0` cannot shadow a parameter.
fn c_identifier(name: &str) -> String {
    let generated = matches!(name.as_bytes().first(), Some(b'v' | b't' | b'b'))
        && name.len() > 1
        && name[1..].bytes().all(|b| b.is_ascii_digit());

    if RESERVED.contains(&name) || generated || name.starts_with('_') {
        format!("{name}_")
    } else {
        name.to_string()
    }
}

/// The runtime helpers the emitted functions actually reach.
///
/// Scanned rather than accumulated during emission because an uncalled `static`
/// is a warning, and the generated file is compiled with -Werror. A helper that
/// every use turned out to be able to inline away must not be emitted at all.
fn helpers_reached(bodies: &[(String, CodeWriter, &Func)]) -> Vec<&'static str> {
    // calls is a warning, and the generated file is compiled with -Werror.
    let mut helpers: Vec<&'static str> = Vec::new();
    let need = |helper: &'static str, into: &mut Vec<&'static str>| {
        if !into.contains(&helper) {
            into.push(helper);
        }
    };
    for func in bodies.iter().map(|(_, _, func)| *func) {
        // Any array-typed value needs the type declarations, even a function
        // that only passes one along.
        if func
            .values
            .iter()
            .any(|op| matches!(op.ty, HirType::Managed(ManagedType::Array(_))))
        {
            need("nts_array", &mut helpers);
        }
        for op in &func.values {
            // An element access needs a bounds test only where one was not
            // proven unnecessary, and which test depends on how the index is
            // represented.
            if let OpKind::ArrayGet { index, checked, .. } | OpKind::ArraySet { index, checked, .. } =
                &op.kind
                && *checked
            {
                need("nts_bounds", &mut helpers);
                if matches!(func.values[index.0 as usize].ty, HirType::Int { .. }) {
                    need("nts_check", &mut helpers);
                } else {
                    need("nts_index", &mut helpers);
                }
            }
            let needed = match &op.kind {
                OpKind::Unary {
                    op: UnOp::ToInt32, ..
                } => "nts_to_int32",
                OpKind::Unary {
                    op: UnOp::ToUint32, ..
                } => "nts_to_uint32",
                OpKind::Binary { op: BinOp::Shl, .. } => "nts_shl",
                OpKind::Binary { op: BinOp::Shr, .. } => "nts_shr",
                OpKind::Binary {
                    op: BinOp::UShr, ..
                } => "nts_ushr",
                OpKind::ArrayNew { .. } => "nts_array_new",
                OpKind::ArrayLen(_) => "nts_array",
                OpKind::Binary { op: BinOp::Min, .. } => "nts_min",
                OpKind::Binary { op: BinOp::Max, .. } => "nts_max",
                OpKind::Unary {
                    op: UnOp::Round,
                    operand,
                } if !matches!(func.values[operand.0 as usize].ty, HirType::Int { .. }) => {
                    "nts_round"
                }
                OpKind::Unary {
                    op: UnOp::Truthy,
                    operand,
                } if !matches!(func.values[operand.0 as usize].ty, HirType::Int { .. }) => {
                    // For `isnan`.
                    "math.h"
                }
                // floor/ceil/trunc/fabs come from <math.h> rather than from a
                // helper, but they are why it has to be included.
                OpKind::Unary {
                    op: UnOp::Floor | UnOp::Ceil | UnOp::Trunc | UnOp::Abs,
                    operand,
                } if !matches!(func.values[operand.0 as usize].ty, HirType::Int { .. }) => "math.h",
                _ => continue,
            };
            // A coercion whose operand is already in the target representation
            // emits an assignment, not a call.
            if let OpKind::Unary {
                op: coercion @ (UnOp::ToInt32 | UnOp::ToUint32),
                operand,
            } = &op.kind
                && (coercion_is_free(func, *coercion, *operand)
                    || matches!(func.values[operand.0 as usize].ty, HirType::Int { .. }))
            {
                // Emitted as a cast, not a call.
                continue;
            }
            need(needed, &mut helpers);
        }
    }
    if helpers.contains(&"nts_array_new") {
        need("nts_array", &mut helpers);
        need("nts_alloc", &mut helpers);
    }
    helpers
}

/// The runtime the emitted functions reach, and the headers it needs.
fn emit_prelude(
    writer: &mut CodeWriter,
    origin: &Origin,
    helpers: &[&'static str],
    descriptors: &[&'static str],
) {
    if !helpers.is_empty() {
        writer.line(origin, "#include <math.h>");
    }
    // The array runtime prints, allocates and zeroes.
    if helpers.iter().any(|helper| {
        matches!(
            *helper,
            "nts_array" | "nts_alloc" | "nts_array_new" | "nts_bounds" | "nts_check" | "nts_index"
        )
    }) {
        writer.line(origin, "#include <stddef.h>");
        writer.line(origin, "#include <stdio.h>");
        writer.line(origin, "#include <stdlib.h>");
        writer.line(origin, "#include <string.h>");
    }
    writer.blank(origin);

    for helper in PRELUDE_ORDER {
        if !helpers.contains(helper) {
            continue;
        }
        for line in prelude(helper) {
            writer.line(origin, *line);
        }
        writer.blank(origin);
    }

    for element in descriptors {
        writer.line(
            origin,
            format!(
                "static const NtsDescriptor {} = {{ sizeof({element}), 0, \"{element}[]\" }};",
                descriptor_name(element)
            ),
        );
    }
    if !descriptors.is_empty() {
        writer.blank(origin);
    }
}

/// The order runtime helpers must be emitted in.
///
/// They depend on each other — `nts_array_new` calls `nts_alloc`, and both
/// bounds tests call `nts_bounds` — so discovery order will not do.
const PRELUDE_ORDER: &[&str] = &[
    "nts_array",
    "nts_alloc",
    "nts_array_new",
    "nts_bounds",
    "nts_check",
    "nts_index",
    "nts_to_int32",
    "nts_to_uint32",
    "nts_shl",
    "nts_shr",
    "nts_ushr",
    "nts_round",
    "nts_min",
    "nts_max",
];

/// The element types the emitted functions actually allocate.
///
/// One descriptor per element type rather than per array: a descriptor is
/// immutable and describes the shape, not any particular array's contents.
fn descriptors_reached(bodies: &[(String, CodeWriter, &Func)]) -> Vec<&'static str> {
    let mut found: Vec<&'static str> = Vec::new();
    for func in bodies.iter().map(|(_, _, func)| *func) {
        for op in &func.values {
            if !matches!(op.kind, OpKind::ArrayNew { .. }) {
                continue;
            }
            if let Ok(element) = element_type(&op.ty, &op.origin)
                && !found.contains(&element)
            {
                found.push(element);
            }
        }
    }
    found
}

/// The C spelling of an array's element type.
fn element_type(array: &HirType, origin: &Origin) -> Result<&'static str, Diagnostic> {
    let HirType::Managed(ManagedType::Array(element)) = array else {
        return Err(Diagnostic::error(
            "NTS2005",
            "an array operation on something that is not an array",
            origin.location,
        ));
    };
    if element.is_managed() {
        return Err(Diagnostic::error(
            "NTS2001",
            "an array of managed references needs a collector to trace it, \
             which this backend does not have yet",
            origin.location,
        ));
    }
    c_type(element, origin)
}

/// The descriptor a given element type uses. One per element type, not per
/// array: the descriptor is immutable and says nothing about a particular
/// array's contents.
fn descriptor_name(element: &str) -> String {
    format!("nts_desc_{}", element.replace(' ', "_"))
}

/// The subscript for an element access, with or without a bounds test.
///
/// An unsigned comparison catches a negative index in the same instruction as
/// a too-large one, since a negative wraps to something enormous. Where the
/// analysis proved the index in range, there is no test at all.
fn index_expression(func: &Func, array: ValueId, index: ValueId, checked: bool) -> String {
    if !checked {
        // Proven in range, so the cast is exact whichever representation it
        // arrived in.
        return format!("(uint32_t){}", value_name(index));
    }
    if matches!(func.values[index.0 as usize].ty, HirType::Int { .. }) {
        format!(
            "nts_check({}, (uint32_t){})",
            value_name(array),
            value_name(index)
        )
    } else {
        format!("nts_index({}, {})", value_name(array), value_name(index))
    }
}

/// Whether a coercion is a no-op because its operand already has that shape.
fn coercion_is_free(func: &Func, coercion: UnOp, operand: ValueId) -> bool {
    let source = &func.values[operand.0 as usize].ty;
    match coercion {
        UnOp::ToInt32 => {
            *source
                == HirType::Int {
                    bits: 32,
                    signed: true,
                }
        }
        UnOp::ToUint32 => {
            *source
                == HirType::Int {
                    bits: 32,
                    signed: false,
                }
        }
        _ => false,
    }
}

/// The C source of one runtime helper.
///
/// These exist because C has no operator that means what JavaScript's does.
/// Writing `(int32_t)x` instead would be undefined behaviour for an
/// out-of-range double, and `a << b` undefined for `b >= 32` or negative `a` —
/// in both cases for inputs JavaScript defines perfectly well.
fn prelude(helper: &str) -> &'static [&'static str] {
    let array = array_prelude(helper);
    if array.is_empty() {
        numeric_prelude(helper)
    } else {
        array
    }
}

/// The managed-array runtime: descriptor, header, allocator, bounds tests.
fn array_prelude(helper: &str) -> &'static [&'static str] {
    match helper {
        "nts_array" => &[
            "/* Managed arrays. RFC 8.1: every managed object references an immutable",
            "   descriptor -- one per element type, since it describes the shape and not",
            "   the contents. `traced` is the reference-field map in its simplest form: an",
            "   array of scalars has no references to trace. */",
            "typedef struct NtsDescriptor {",
            "    uint32_t element_size;",
            "    uint32_t traced;",
            "    const char *name;",
            "} NtsDescriptor;",
            "",
            "/* RFC 8.2. `reserved` is the provider-reserved word: unused under NoGC, a",
            "   reference count under RC, a forwarding pointer under a moving collector.",
            "   It is not public ABI. */",
            "typedef struct NtsArray {",
            "    const NtsDescriptor *descriptor;",
            "    uintptr_t reserved;",
            "    uint32_t flags;",
            "    uint32_t length;",
            "} NtsArray;",
            "",
            "#define NTS_ELEMENTS(a, T) ((T *)((unsigned char *)(a) + sizeof(NtsArray)))",
        ],
        "nts_alloc" => &[
            "/* The NoGC provider (RFC 9.1): a bump allocator that never frees. For",
            "   compiler bring-up, allocation testing and bounded-lifetime tools. It must",
            "   never be selected silently for a general application. */",
            "static unsigned char *nts_bump = 0;",
            "static size_t nts_bump_left = 0;",
            "",
            "static void *nts_alloc(size_t bytes) {",
            "    bytes = (bytes + 15u) & ~(size_t)15u;",
            "    if (bytes > nts_bump_left) {",
            "        size_t chunk = bytes > (size_t)1048576 ? bytes : (size_t)1048576;",
            "        nts_bump = (unsigned char *)malloc(chunk);",
            "        if (!nts_bump) { fprintf(stderr, \"nts: out of memory\\n\"); abort(); }",
            "        nts_bump_left = chunk;",
            "    }",
            "    void *result = nts_bump;",
            "    nts_bump += bytes;",
            "    nts_bump_left -= bytes;",
            "    return result;",
            "}",
        ],
        "nts_array_new" => &[
            "static NtsArray *nts_array_new(const NtsDescriptor *descriptor, double length) {",
            "    if (!(length >= 0.0 && length <= 4294967295.0",
            "          && length == (double)(uint32_t)length)) {",
            "        fprintf(stderr, \"nts: %g is not a valid array length\\n\", length);",
            "        abort();",
            "    }",
            "    uint32_t count = (uint32_t)length;",
            "    size_t bytes = sizeof(NtsArray) + (size_t)count * descriptor->element_size;",
            "    NtsArray *array = (NtsArray *)nts_alloc(bytes);",
            "    array->descriptor = descriptor;",
            "    array->reserved = 0;",
            "    array->flags = 0;",
            "    array->length = count;",
            "    /* Zeroed rather than left as holes: there is no `undefined` in a double,",
            "       so a hole has no representation to leave behind. */",
            "    memset((unsigned char *)array + sizeof(NtsArray), 0,",
            "           (size_t)count * descriptor->element_size);",
            "    return array;",
            "}",
        ],
        "nts_bounds" => &[
            "static void nts_bounds(double index, uint32_t length) {",
            "    fprintf(stderr, \"nts: index %g is outside [0, %u)\\n\", index, length);",
            "    abort();",
            "}",
        ],
        "nts_check" => &[
            "/* One unsigned comparison catches a negative index too: it wraps to something",
            "   enormous, which is not less than the length. */",
            "static uint32_t nts_check(const NtsArray *array, uint32_t index) {",
            "    if (index >= array->length) { nts_bounds((double)index, array->length); }",
            "    return index;",
            "}",
        ],
        "nts_index" => &[
            "/* A double index must also be a whole number to name an element at all --",
            "   `xs[1.5]` is a property in JavaScript, not a slot. NaN fails the first",
            "   comparison. */",
            "static uint32_t nts_index(const NtsArray *array, double index) {",
            "    if (!(index >= 0.0 && index < (double)array->length",
            "          && index == (double)(uint32_t)index)) {",
            "        nts_bounds(index, array->length);",
            "    }",
            "    return (uint32_t)index;",
            "}",
        ],
        _ => &[],
    }
}

/// The numeric runtime: the coercions and operations C has no correct operator
/// for.
fn numeric_prelude(helper: &str) -> &'static [&'static str] {
    match helper {
        "nts_to_int32" => &[
            "/* JavaScript ToInt32: total, and wraps rather than trapping.",
            "",
            "   The first branch is the case that actually happens. A double whose",
            "   truncation fits in int32 needs only truncating, which is one instruction;",
            "   the general path costs calls to trunc and fmod and is 2.6x slower. NaN",
            "   fails both comparisons and falls through to the isfinite check. */",
            "static int32_t nts_to_int32(double x) {",
            "    if (x > -2147483649.0 && x < 2147483648.0) { return (int32_t)x; }",
            "    if (!isfinite(x)) { return 0; }",
            "    double m = fmod(trunc(x), 4294967296.0);",
            "    if (m < 0.0) { m += 4294967296.0; }",
            "    return (int32_t)(uint32_t)m;",
            "}",
        ],
        "nts_to_uint32" => &[
            "/* JavaScript ToUint32. As above; the fast path is the non-negative half of",
            "   the uint32 range. */",
            "static uint32_t nts_to_uint32(double x) {",
            "    if (x >= 0.0 && x < 4294967296.0) { return (uint32_t)x; }",
            "    if (!isfinite(x)) { return 0; }",
            "    double m = fmod(trunc(x), 4294967296.0);",
            "    if (m < 0.0) { m += 4294967296.0; }",
            "    return (uint32_t)m;",
            "}",
        ],
        "nts_shl" => &[
            "/* JavaScript `<<`: the count masks to five bits, and shifting a negative",
            "   value left is defined rather than undefined. */",
            "static int32_t nts_shl(int32_t a, int32_t b) {",
            "    return (int32_t)((uint32_t)a << ((uint32_t)b & 31u));",
            "}",
        ],
        "nts_shr" => &[
            "/* JavaScript `>>`: arithmetic, spelled so it does not depend on the",
            "   implementation's choice for a negative operand. */",
            "static int32_t nts_shr(int32_t a, int32_t b) {",
            "    uint32_t n = (uint32_t)b & 31u;",
            "    if (a < 0) { return (int32_t)~(~(uint32_t)a >> n); }",
            "    return (int32_t)((uint32_t)a >> n);",
            "}",
        ],
        "nts_ushr" => &[
            "/* JavaScript `>>>`: logical, and the one bitwise result that is uint32",
            "   rather than int32. */",
            "static uint32_t nts_ushr(int32_t a, int32_t b) {",
            "    return (uint32_t)a >> ((uint32_t)b & 31u);",
            "}",
        ],
        "nts_round" => &[
            "/* JavaScript Math.round: a half goes toward positive infinity, not away from",
            "   zero. C's round(-1.5) is -2; this is -1. */",
            "static double nts_round(double x) {",
            "    if (!isfinite(x)) { return x; }",
            "    return floor(x + 0.5);",
            "}",
        ],
        "nts_min" => &[
            "/* JavaScript Math.min: NaN wins, and -0 is below 0. C's fmin does neither. */",
            "static double nts_min(double a, double b) {",
            "    if (isnan(a) || isnan(b)) { return (double)NAN; }",
            "    if (a == 0.0 && b == 0.0) { return signbit(a) ? a : b; }",
            "    return a < b ? a : b;",
            "}",
        ],
        "nts_max" => &[
            "/* JavaScript Math.max. See nts_min. */",
            "static double nts_max(double a, double b) {",
            "    if (isnan(a) || isnan(b)) { return (double)NAN; }",
            "    if (a == 0.0 && b == 0.0) { return signbit(a) ? b : a; }",
            "    return a > b ? a : b;",
            "}",
        ],
        _ => &[],
    }
}

/// The C spelling of a representation.
fn c_type(ty: &HirType, origin: &Origin) -> Result<&'static str, Diagnostic> {
    Ok(match ty {
        HirType::Void => "void",
        HirType::Bool => "bool",
        HirType::Float { bits: 32 } => "float",
        HirType::Float { .. } => "double",
        HirType::Int {
            bits: 8,
            signed: true,
        } => "int8_t",
        HirType::Int {
            bits: 8,
            signed: false,
        } => "uint8_t",
        HirType::Int {
            bits: 16,
            signed: true,
        } => "int16_t",
        HirType::Int {
            bits: 16,
            signed: false,
        } => "uint16_t",
        HirType::Int {
            bits: 32,
            signed: true,
        } => "int32_t",
        HirType::Int {
            bits: 32,
            signed: false,
        } => "uint32_t",
        HirType::Int { signed: true, .. } => "int64_t",
        HirType::Int { signed: false, .. } => "uint64_t",
        // `never` reaching a value position means control got somewhere the type
        // system said it could not.
        HirType::Never => {
            return Err(Diagnostic::error(
                "NTS2002",
                "a value of type `never` reached code generation",
                origin.location,
            ));
        }
        // An array is a pointer to its header; the elements follow it. The
        // element type is not in the C type, because every access already knows
        // it from the HIR and spelling it here would need a struct per element
        // type for no benefit.
        HirType::Managed(ManagedType::Array(_)) => "NtsArray *",
        HirType::Managed(_) => {
            return Err(Diagnostic::error(
                "NTS2001",
                "strings and objects need a runtime, which this backend does not have yet",
                origin.location,
            ));
        }
    })
}

fn signature(func: &Func) -> Result<String, Diagnostic> {
    let returns = c_type(&func.return_type, &func.origin)?;
    if func.params.is_empty() {
        return Ok(format!("{returns} {}(void)", c_identifier(&func.name)));
    }
    let mut params = Vec::new();
    for (index, param) in func.params.iter().enumerate() {
        let ty = c_type(&param.ty, &param.origin)?;
        params.push(format!(
            "{ty} {}",
            value_name(ValueId(u32::try_from(index).unwrap_or(0)))
        ));
    }
    Ok(format!(
        "{returns} {}({})",
        c_identifier(&func.name),
        params.join(", ")
    ))
}

/// The C name of a value.
///
/// A parameter's value is the C parameter itself, which is why the arena is
/// numbered so that `%0..%n` are the parameters — no copy is needed to get an
/// argument into a local.
fn value_name(value: ValueId) -> String {
    format!("v{}", value.0)
}

fn block_label(block: BlockId) -> String {
    format!("b{}", block.0)
}

/// Emit one function, returning its signature so a declaration can be written.
fn emit_func(writer: &mut CodeWriter, func: &Func) -> Result<String, Diagnostic> {
    let signature = signature(func)?;
    writer.line(&func.origin, format!("{signature} {{"));
    emit_body(writer, func)?;
    writer.line(&func.origin, "}");
    writer.blank(&func.origin);
    Ok(signature)
}

fn emit_body(writer: &mut CodeWriter, func: &Func) -> Result<(), Diagnostic> {
    let order = block_order(func);

    // Every value except the parameters becomes a local. C scoping would not let
    // a value defined in one block be read in another, so they are all declared
    // at the top — where SSA guarantees each is assigned before any use.
    //
    // Declared from the block contents rather than from the value arena, so that
    // a value dead-code elimination dropped does not leave an unused local
    // behind. The arena keeps dead entries on purpose: a `ValueId` is an index
    // into it, and compacting would invalidate every reference in the function.
    let mut declared = rustc_hash::FxHashSet::default();
    let mut read = rustc_hash::FxHashSet::default();
    for block in &func.blocks {
        declared.extend(block.params.iter().copied());
        declared.extend(block.ops.iter().copied());
        read.extend(nts_core::hir::operands_of_terminator(&block.terminator));
        for value in &block.ops {
            read.extend(nts_core::hir::operands_of(
                &func.values[value.0 as usize].kind,
            ));
        }
    }

    // A parameter nothing reads is an error under -Werror, and constant folding
    // produces them for real: `fixed(scale: 8) { return scale * scale }` folds
    // to `64` and stops looking at its argument. The signature still has to
    // match, so the parameter stays and is discarded explicitly.
    writer.indent();
    for index in 0..func.params.len() {
        let id = ValueId(u32::try_from(index).unwrap_or(0));
        if !read.contains(&id) {
            writer.line(
                &func.params[index].origin,
                format!("(void){};", value_name(id)),
            );
        }
    }
    writer.dedent();

    writer.indent();
    for (index, op) in func.values.iter().enumerate() {
        // A parameter is already declared by the signature, a value nothing
        // reads was dropped by dead-code elimination, and an operation that
        // produces nothing has nothing to hold — `void v4;` is not a variable.
        if matches!(op.kind, OpKind::Param(_))
            || matches!(op.ty, HirType::Void)
            || !declared.contains(&ValueId(u32::try_from(index).unwrap_or(0)))
        {
            continue;
        }
        let ty = c_type(&op.ty, &op.origin)?;
        writer.line(
            &op.origin,
            format!(
                "{ty} {};",
                value_name(ValueId(u32::try_from(index).unwrap_or(0)))
            ),
        );
    }

    let temps = destruct::temp_count(func);
    for temp in 0..temps {
        // One scratch per cycle depth. Typed as the widest scalar, since a swap
        // only ever moves a value into a slot of its own type.
        writer.line(&func.origin, format!("double t{temp};"));
    }
    writer.dedent();

    // Only blocks something actually jumps to need a label. The entry never does,
    // and an unreferenced label is a warning in every C compiler worth using.
    let mut targeted = rustc_hash::FxHashSet::default();
    for block in &func.blocks {
        targeted.extend(block.terminator.successors());
    }

    for (position, block) in order.iter().enumerate() {
        let next = order.get(position + 1).copied();
        emit_block(writer, func, *block, next, targeted.contains(block))?;
    }
    Ok(())
}

fn emit_block(
    writer: &mut CodeWriter,
    func: &Func,
    block: BlockId,
    next: Option<BlockId>,
    labelled: bool,
) -> Result<(), Diagnostic> {
    let record = &func.blocks[block.0 as usize];
    let origin = func
        .values
        .get(record.ops.first().map_or(0, |v| v.0 as usize))
        .map_or_else(|| func.origin.clone(), |op| op.origin.clone());

    if labelled {
        writer.line(&origin, format!("{}:;", block_label(block)));
    }
    writer.indent();

    for value in &record.ops {
        emit_op(writer, func, *value)?;
    }
    emit_terminator(writer, func, block, next, &origin);

    writer.dedent();
    Ok(())
}

/// The C spelling of a binary operation.
fn binary_text(
    func: &Func,
    op: &nts_core::hir::Op,
    name: &str,
    bin: BinOp,
    lhs: ValueId,
    rhs: ValueId,
) -> Result<String, Diagnostic> {
    // A bitwise operator's operands are always coercion results — the lowering
    // guarantees it — so they hold int32 values whatever their representation
    // says. When specialization did not give them an integer type, the
    // arithmetic still has to happen in integers, so it is spelled with casts
    // around it. Those casts are exactly the cost the analysis removes.
    let integral = matches!(op.ty, HirType::Int { .. });
    // Cast decided per *operand*, from its own type. Deciding it from the
    // result's would emit `v14 | v15` with `v15` a double, which is not C.
    let cast = |value: ValueId| {
        if matches!(func.values[value.0 as usize].ty, HirType::Int { .. }) {
            value_name(value)
        } else {
            format!("(int32_t){}", value_name(value))
        }
    };
    let wrap = |text: String| {
        if integral {
            format!("{name} = {text};")
        } else {
            format!("{name} = (double)({text});")
        }
    };

    // Shifts are not C operators here. JavaScript masks the count to five bits,
    // where C leaves a shift by 32 or more undefined; `<<` on a negative signed
    // operand is undefined in C and defined in JavaScript. Each goes through a
    // helper that spells the real rule.
    let helper = match bin {
        BinOp::Shl => Some("nts_shl"),
        BinOp::Shr => Some("nts_shr"),
        BinOp::UShr => Some("nts_ushr"),
        _ => None,
    };
    if let Some(helper) = helper {
        return Ok(wrap(format!("{helper}({}, {})", cast(lhs), cast(rhs))));
    }

    let operator = match bin {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Rem => "%",
        BinOp::BitAnd => "&",
        BinOp::BitOr => "|",
        BinOp::BitXor => "^",
        BinOp::Lt => "<",
        BinOp::Le => "<=",
        BinOp::Gt => ">",
        BinOp::Ge => ">=",
        BinOp::Eq => "==",
        BinOp::Ne => "!=",
        BinOp::Shl | BinOp::Shr | BinOp::UShr => unreachable!("handled above"),
        // Not `fmin`/`fmax`: those return the non-NaN operand where JavaScript
        // returns NaN, and disagree about the two zeroes.
        BinOp::Min | BinOp::Max => {
            // Two integers cannot be NaN and have no second zero, so the whole
            // reason the helper exists is absent and a comparison will do.
            let both_integers = matches!(func.values[lhs.0 as usize].ty, HirType::Int { .. })
                && matches!(func.values[rhs.0 as usize].ty, HirType::Int { .. });
            if both_integers {
                let test = if matches!(bin, BinOp::Min) { "<" } else { ">" };
                return Ok(format!(
                    "{name} = {0} {test} {1} ? {0} : {1};",
                    value_name(lhs),
                    value_name(rhs)
                ));
            }
            let helper = if matches!(bin, BinOp::Min) {
                "nts_min"
            } else {
                "nts_max"
            };
            return Ok(wrap(format!(
                "{helper}({}, {})",
                value_name(lhs),
                value_name(rhs)
            )));
        }
        BinOp::Concat => {
            return Err(Diagnostic::error(
                "NTS2001",
                "string concatenation needs a runtime, which this backend does not have yet",
                op.origin.location,
            ));
        }
    };

    if matches!(bin, BinOp::BitAnd | BinOp::BitOr | BinOp::BitXor) {
        return Ok(wrap(format!("{} {operator} {}", cast(lhs), cast(rhs))));
    }

    // `%` is integer-only in C. On doubles it is `fmod`, and emitting `%` would
    // not compile — better than emitting something that does and is wrong, but
    // still worth naming. On integers it is exactly JavaScript's remainder:
    // both take the sign of the dividend.
    if matches!(bin, BinOp::Rem) && matches!(op.ty, HirType::Float { .. }) {
        return Err(Diagnostic::error(
            "NTS2003",
            "floating-point remainder needs `fmod`, which is not wired up yet",
            op.origin.location,
        ));
    }

    Ok(format!(
        "{name} = {} {operator} {};",
        value_name(lhs),
        value_name(rhs)
    ))
}

/// The C spelling of a unary operation.
fn unary_text(func: &Func, name: &str, un: UnOp, operand: ValueId, result: &HirType) -> String {
    match un {
        UnOp::Neg => format!("{name} = -{};", value_name(operand)),
        UnOp::Not => format!("{name} = !{};", value_name(operand)),
        UnOp::Truthy => {
            // An integer is truthy exactly when it is non-zero, and `!= 0` says
            // so. A double additionally has to exclude NaN, which is falsy and
            // which `!= 0` would call true — every comparison with a NaN is
            // false, including the inequality.
            if matches!(func.values[operand.0 as usize].ty, HirType::Int { .. }) {
                format!("{name} = {} != 0;", value_name(operand))
            } else {
                format!("{name} = ({0} != 0.0) && !isnan({0});", value_name(operand))
            }
        }
        UnOp::Floor | UnOp::Ceil | UnOp::Trunc | UnOp::Round | UnOp::Abs => {
            // An integer is already rounded, and taking its magnitude is a
            // comparison rather than a library call.
            let already_integral =
                matches!(func.values[operand.0 as usize].ty, HirType::Int { .. });
            if already_integral {
                return match un {
                    UnOp::Abs => format!("{name} = {0} < 0 ? -{0} : {0};", value_name(operand)),
                    _ => format!("{name} = {};", value_name(operand)),
                };
            }
            let call = match un {
                UnOp::Floor => "floor",
                UnOp::Ceil => "ceil",
                UnOp::Trunc => "trunc",
                UnOp::Abs => "fabs",
                // C's `round` rounds a half away from zero; JavaScript rounds it
                // toward positive infinity, so `Math.round(-1.5)` is `-1` and
                // `round(-1.5)` is `-2`.
                _ => "nts_round",
            };
            // Rounding in doubles and converting after, never the other way
            // round: `(int32_t)-3.7` is `-3` and `floor(-3.7)` is `-4`.
            if matches!(result, HirType::Int { .. }) {
                return format!("{name} = (int32_t){call}({});", value_name(operand));
            }
            format!("{name} = {call}({});", value_name(operand))
        }
        UnOp::ToInt32 | UnOp::ToUint32 => {
            // A value already in the target representation needs no coercion,
            // and that is the common case: integer code writing `x | 0` on
            // something already proven an integer.
            if coercion_is_free(func, un, operand) {
                return format!("{name} = {};", value_name(operand));
            }

            // An *integer* of some other width is a truncation, which C spells
            // as a cast through the unsigned type of the target — exactly
            // ToInt32's "reduce modulo 2^32, reinterpret signed", and one
            // instruction. Only a genuine double needs the total, wrapping,
            // fmod-based helper, and reaching for it on an `int64_t` operand
            // costs a conversion to double and a library call in the loop body
            // that the whole analysis existed to speed up.
            if matches!(func.values[operand.0 as usize].ty, HirType::Int { .. }) {
                return match un {
                    UnOp::ToInt32 => {
                        format!("{name} = (int32_t)(uint32_t){};", value_name(operand))
                    }
                    _ => format!("{name} = (uint32_t){};", value_name(operand)),
                };
            }

            let helper = if matches!(un, UnOp::ToInt32) {
                "nts_to_int32"
            } else {
                "nts_to_uint32"
            };
            format!("{name} = {helper}({});", value_name(operand))
        }
    }
}

fn emit_op(writer: &mut CodeWriter, func: &Func, value: ValueId) -> Result<(), Diagnostic> {
    let op = func.value(value);
    let name = value_name(value);
    let text = match &op.kind {
        // Nothing to compute at the definition site. A parameter *is* the C
        // parameter; a block parameter is written by the edges that jump here;
        // a return is spelled by the terminator.
        OpKind::Param(_) | OpKind::BlockParam(_) | OpKind::Return(_) => return Ok(()),
        OpKind::ConstInt(v) => format!("{name} = {v};"),
        // Enough digits to round-trip an f64 exactly. Fewer would change the
        // program's arithmetic.
        OpKind::ConstFloat(v) => format!("{name} = {v:?};"),
        OpKind::ConstBool(v) => format!("{name} = {v};"),
        OpKind::ConstString(_) => {
            return Err(Diagnostic::error(
                "NTS2001",
                "string constants need a runtime, which this backend does not have yet",
                op.origin.location,
            ));
        }
        OpKind::Binary { op: bin, lhs, rhs } => binary_text(func, op, &name, *bin, *lhs, *rhs)?,
        OpKind::Call { callee, args } => {
            let (Callee::Direct(target) | Callee::External(target)) = callee;
            let arguments: Vec<String> = args.iter().map(|a| value_name(*a)).collect();
            format!(
                "{name} = {}({});",
                c_identifier(target),
                arguments.join(", ")
            )
        }
        OpKind::Unary { op: un, operand } => unary_text(func, &name, *un, *operand, &op.ty),
        OpKind::ArrayNew { length } => {
            let element = element_type(&op.ty, &op.origin)?;
            format!(
                "{name} = nts_array_new(&{}, {});",
                descriptor_name(element),
                value_name(*length)
            )
        }
        OpKind::ArrayLen(array) => {
            let target = c_type(&op.ty, &op.origin)?;
            format!("{name} = ({target}){}->length;", value_name(*array))
        }
        OpKind::ArrayGet {
            array,
            index,
            checked,
        } => {
            let element = element_type(&func.values[array.0 as usize].ty, &op.origin)?;
            let slot = index_expression(func, *array, *index, *checked);
            format!(
                "{name} = NTS_ELEMENTS({}, {element})[{slot}];",
                value_name(*array)
            )
        }
        OpKind::ArraySet {
            array,
            index,
            value: stored,
            checked,
        } => {
            let element = element_type(&func.values[array.0 as usize].ty, &op.origin)?;
            let slot = index_expression(func, *array, *index, *checked);
            format!(
                "NTS_ELEMENTS({}, {element})[{slot}] = {};",
                value_name(*array),
                value_name(*stored)
            )
        }
        OpKind::Convert(operand) => {
            // A C cast. Between an integer and a double this is one instruction,
            // and every one is a place specialization decided two adjacent
            // values should live in different machine types.
            let target = c_type(&op.ty, &op.origin)?;
            format!("{name} = ({target}){};", value_name(*operand))
        }
    };
    writer.line(&op.origin, text);
    Ok(())
}

fn emit_terminator(
    writer: &mut CodeWriter,
    func: &Func,
    block: BlockId,
    next: Option<BlockId>,
    origin: &Origin,
) {
    let record = &func.blocks[block.0 as usize];

    // The copies an edge implies run before control leaves.
    let emit_edge = |writer: &mut CodeWriter, target: BlockId, args: &[ValueId]| {
        let params = &func.blocks[target.0 as usize].params;
        for copy in destruct::edge_copies(params, args) {
            let text = match copy {
                Copy::Move { to, from } => format!("{} = {};", value_name(to), value_name(from)),
                Copy::Save { temp, from } => format!("t{temp} = {};", value_name(from)),
                Copy::Restore { to, temp } => format!("{} = t{temp};", value_name(to)),
            };
            writer.line(origin, text);
        }
    };

    match &record.terminator {
        Terminator::Return(Some(value)) => {
            writer.line(origin, format!("return {};", value_name(*value)));
        }
        Terminator::Return(None) => writer.line(origin, "return;"),
        Terminator::Unreachable => {
            // A claim the compiler made. Saying so lets the C compiler optimize on
            // it, and makes a violated claim a crash rather than a fall-through.
            writer.line(origin, "__builtin_unreachable();");
        }
        Terminator::Jump { target, args } => {
            emit_edge(writer, *target, args);
            // The block order exists so this is usually free.
            if next != Some(*target) {
                writer.line(origin, format!("goto {};", block_label(*target)));
            }
        }
        Terminator::Branch {
            cond,
            then_target,
            then_args,
            else_target,
            else_args,
        } => {
            // Each arm's copies belong to that arm, so they are emitted inside it.
            writer.line(origin, format!("if ({}) {{", value_name(*cond)));
            writer.nested(|writer| {
                emit_edge(writer, *then_target, then_args);
                writer.line(origin, format!("goto {};", block_label(*then_target)));
            });
            writer.line(origin, "} else {");
            writer.nested(|writer| {
                emit_edge(writer, *else_target, else_args);
                writer.line(origin, format!("goto {};", block_label(*else_target)));
            });
            writer.line(origin, "}");
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_c_keyword_is_not_a_usable_function_name() {
        // `function double()` is ordinary TypeScript.
        assert_eq!(c_identifier("double"), "double_");
        assert_eq!(c_identifier("int"), "int_");
        assert_eq!(c_identifier("switch"), "switch_");
        // `main` is not a keyword, but a second definition of it does not link.
        assert_eq!(c_identifier("main"), "main_");
    }

    #[test]
    fn a_name_this_backend_generates_is_also_reserved() {
        // A function called `v0` would shadow the first parameter of every
        // function that calls it.
        assert_eq!(c_identifier("v0"), "v0_");
        assert_eq!(c_identifier("t12"), "t12_");
        assert_eq!(c_identifier("b3"), "b3_");
        // Only the exact generated shape. These are ordinary names.
        assert_eq!(c_identifier("v"), "v");
        assert_eq!(c_identifier("value0"), "value0");
        assert_eq!(c_identifier("b3x"), "b3x");
    }

    #[test]
    fn a_leading_underscore_is_reserved_to_the_implementation() {
        assert_eq!(c_identifier("_internal"), "_internal_");
    }

    #[test]
    fn an_ordinary_name_is_left_alone() {
        // Mangling everything would be simpler and would make every exported
        // symbol worse to link against.
        assert_eq!(c_identifier("compute"), "compute");
        assert_eq!(c_identifier("sumTo"), "sumTo");
    }
}
