//! Emitting C from HIR.
//!
//! # A printer, not a decision-maker
//!
//! Block order and the copies a block-parameter edge implies are decided in
//! `nts-codegen-common`, so nothing here chooses anything a JVM emitter would
//! have to choose again. What is left is spelling.
//!
//! # Scalars only, for now
//!
//! A managed reference needs a runtime — an allocator, a header, a collector —
//! and none of that exists yet. Rather than emit a plausible `char *` and pretend,
//! a function touching a managed type is refused. RFC §4.1 again: the failure has
//! to be visible.

use nts_codegen_common::{CodeWriter, Copy, block_order, destruct};
use nts_core::hir::{
    BinOp, BlockId, Callee, Func, HirType, ManagedType, OpKind, Program, Terminator, UnOp, ValueId,
};
use nts_diagnostics::Diagnostic;
use nts_semantic_schema::Origin;

/// The C runtime, as source.
///
/// Real C compiled as its own translation unit rather than text pasted into
/// every generated file. It lives under `runtime/c/` and is included here, so
/// it can be read, edited and reviewed as C -- and so an unused external
/// function is not a warning, which is what let the whole "work out which
/// helpers this program reaches" apparatus be deleted.
pub const RUNTIME_HEADER_NAME: &str = "nts_runtime.h";
pub const RUNTIME_HEADER: &str = include_str!("../../../../runtime/c/nts_runtime.h");
pub const RUNTIME_SOURCE_NAME: &str = "nts_runtime.c";
pub const RUNTIME_SOURCE: &str = include_str!("../../../../runtime/c/nts_runtime.c");

/// C for one program, and what could not be emitted.
#[derive(Debug)]
pub struct Emitted {
    pub writer: CodeWriter,
    pub diagnostics: Vec<Diagnostic>,
}

impl Emitted {
    #[must_use]
    pub fn is_complete(&self) -> bool {
        self.diagnostics.is_empty()
    }
}

/// Emit a whole program as one translation unit.
#[must_use]
pub fn emit(program: &Program) -> Emitted {
    let mut writer = CodeWriter::new();
    let mut diagnostics = Vec::new();

    let Some(first) = program.funcs.first() else {
        return Emitted {
            writer,
            diagnostics,
        };
    };
    let origin = first.origin.clone();

    // Each function is emitted speculatively and kept only if it succeeded. A
    // half-emitted function is worse than an absent one: it declares a signature
    // and a body that does not return, which compiles into a callable shell.
    // Two different TypeScript names can mangle to one C name — `double` and
    // `double_` both become `double_`. Emitting both would produce a redefinition
    // error far from its cause, so it is caught here where the cause is known.
    let mut claimed: rustc_hash::FxHashMap<String, &str> = rustc_hash::FxHashMap::default();
    for func in &program.funcs {
        let c_name = c_identifier(&func.name);
        if let Some(previous) = claimed.insert(c_name.clone(), &func.name)
            && previous != func.name
        {
            diagnostics.push(Diagnostic::error(
                "NTS2004",
                format!(
                    "`{}` and `{previous}` both need the C name `{c_name}`",
                    func.name
                ),
                func.origin.location,
            ));
        }
    }

    // Collected before emission so that every reference names the same static.
    let mut literals: Vec<String> = Vec::new();
    for func in &program.funcs {
        for op in &func.values {
            if let OpKind::ConstString(text) = &op.kind
                && !literals.contains(text)
            {
                literals.push(text.clone());
            }
        }
    }

    let mut bodies = Vec::new();
    for func in &program.funcs {
        let mut body = CodeWriter::new();
        match emit_func(&mut body, func, &literals) {
            Ok(signature) => bodies.push((signature, body, func)),
            Err(diagnostic) => diagnostics.push(diagnostic),
        }
    }

    let descriptors = descriptors_reached(&bodies);

    writer.line(&origin, "/* Generated by nts. Do not edit. */");
    // The runtime, and nothing else -- notably not <stdlib.h>, which declares
    // `div`, a name a TypeScript program is entitled to use.
    writer.line(&origin, format!("#include \"{RUNTIME_HEADER_NAME}\""));
    emit_descriptors(&mut writer, &origin, &descriptors);
    emit_literals(&mut writer, &origin, &literals);

    // Forward declarations, so a call does not depend on definition order — and
    // only for functions that actually have a definition.
    for (signature, _, _) in &bodies {
        writer.line(&origin, format!("{signature};"));
    }
    writer.blank(&origin);

    for (_, body, _) in bodies {
        writer.append(body);
    }

    Emitted {
        writer,
        diagnostics,
    }
}

/// Identifiers C will not let us use for a function.
///
/// C11 keywords, the macros `<stdbool.h>` defines, `main`, and the standard
/// library names declared by the headers the runtime needs. TypeScript has no
/// such restriction, so `function double()` and `function div()` are both
/// perfectly good source that cannot be spelled that way in C.
///
/// # The real fix, not done here
///
/// This list is bounded only by which headers the generated file includes, and
/// that is the wrong thing to depend on: adding one header could rename a user's
/// exported function. The runtime belongs in its own translation unit, with a
/// header declaring only the types and prototypes -- then the generated file
/// includes no system headers at all and the collision surface is the runtime's
/// own `nts_` prefix. That is a separate slice; this list makes the current
/// arrangement correct in the meantime.
const RESERVED: &[&str] = &[
    // C11 keywords and the macros <stdbool.h> defines.
    "alignas",
    "alignof",
    "auto",
    "bool",
    "break",
    "case",
    "char",
    "const",
    "constexpr",
    "continue",
    "default",
    "do",
    "double",
    "else",
    "enum",
    "extern",
    "false",
    "float",
    "for",
    "goto",
    "if",
    "inline",
    "int",
    "long",
    "main",
    "nullptr",
    "register",
    "restrict",
    "return",
    "short",
    "signed",
    "sizeof",
    "static",
    "static_assert",
    "struct",
    "switch",
    "thread_local",
    "true",
    "typedef",
    "typeof",
    "union",
    "unsigned",
    "void",
    "volatile",
    "while",
    // <math.h>, which the runtime header pulls in for the float builtins the
    // emitter uses directly. This is the whole collision surface now: a
    // generated file includes the runtime header and nothing else, so it no
    // longer picks up the hundreds of names <stdio.h> and <stdlib.h> declare.
    "acos",
    "asin",
    "atan",
    "atan2",
    "cbrt",
    "ceil",
    "cos",
    "cosh",
    "exp",
    "fabs",
    "floor",
    "fmax",
    "fmin",
    "fmod",
    "hypot",
    "isfinite",
    "isnan",
    "log",
    "log10",
    "log2",
    "modf",
    "pow",
    "round",
    "signbit",
    "sin",
    "sinh",
    "sqrt",
    "tan",
    "tanh",
    "trunc",
];

/// The C spelling of a function name.
///
/// Appending an underscore is the whole rule: it is reversible by inspection,
/// which matters because an exported name is an ABI that a human will link
/// against. Names this backend generates itself (`v0`, `t0`, `b0`) are mangled
/// the same way, so a function called `v0` cannot shadow a parameter.
fn c_identifier(name: &str) -> String {
    let generated = matches!(name.as_bytes().first(), Some(b'v' | b't' | b'b'))
        && name.len() > 1
        && name[1..].bytes().all(|b| b.is_ascii_digit());

    if RESERVED.contains(&name) || generated || name.starts_with('_') {
        format!("{name}_")
    } else {
        name.to_string()
    }
}

/// The C name of a string literal's static data.
fn literal_name(literals: &[String], text: &str) -> String {
    let index = literals.iter().position(|known| known == text).unwrap_or(0);
    format!("nts_str_{index}")
}

/// String literals, as static data.
///
/// Emitted as numeric code units rather than as C string literals: a C literal
/// would need escaping rules that do not match JavaScript's, and would carry
/// its own idea of what a byte means.
fn emit_literals(writer: &mut CodeWriter, origin: &Origin, literals: &[String]) {
    for (index, text) in literals.iter().enumerate() {
        let units: Vec<u16> = text.encode_utf16().collect();
        let name = format!("nts_str_{index}");
        // One byte per code unit whenever every one fits, which for ordinary
        // program text is always. The trailing zero is what makes a one-byte
        // string usable as a C string without copying.
        let wide = units.iter().any(|unit| *unit > 0xFF);
        let (element, descriptor, flags) = if wide {
            ("uint16_t", "nts_desc_string2", "NTS_TWO_BYTE")
        } else {
            ("unsigned char", "nts_desc_string1", "0")
        };
        let data: Vec<String> = units
            .iter()
            .map(std::string::ToString::to_string)
            .chain(std::iter::once("0".to_owned()))
            .collect();
        writer.line(
            origin,
            format!(
                "static const struct {{ NtsHeader header; {element} data[{}]; }} {name} = \
                 {{ {{ &{descriptor}, 0, {flags}, {} }}, {{ {} }} }};",
                data.len(),
                units.len(),
                data.join(", ")
            ),
        );
    }
    if !literals.is_empty() {
        writer.blank(origin);
    }
}

/// The per-program data: a descriptor per element type this program allocates.
///
/// The runtime itself is [`RUNTIME_HEADER`] and [`RUNTIME_SOURCE`] -- real C,
/// compiled separately -- so none of it is generated. What is generated is what
/// depends on the program.
fn emit_descriptors(writer: &mut CodeWriter, origin: &Origin, descriptors: &[&'static str]) {
    for element in descriptors {
        writer.line(
            origin,
            format!(
                "static const NtsDescriptor {} = {{ sizeof({element}), 0, \"{element}[]\" }};",
                descriptor_name(element)
            ),
        );
    }
    if !descriptors.is_empty() {
        writer.blank(origin);
    }
}

/// The element types the emitted functions actually allocate.
///
/// One descriptor per element type rather than per array: a descriptor is
/// immutable and describes the shape, not any particular array's contents.
fn descriptors_reached(bodies: &[(String, CodeWriter, &Func)]) -> Vec<&'static str> {
    let mut found: Vec<&'static str> = Vec::new();
    for func in bodies.iter().map(|(_, _, func)| *func) {
        for op in &func.values {
            if !matches!(op.kind, OpKind::ArrayNew { .. }) {
                continue;
            }
            if let Ok(element) = element_type(&op.ty, &op.origin)
                && !found.contains(&element)
            {
                found.push(element);
            }
        }
    }
    found
}

/// The C spelling of an array's element type.
fn element_type(array: &HirType, origin: &Origin) -> Result<&'static str, Diagnostic> {
    let HirType::Managed(ManagedType::Array(element)) = array else {
        return Err(Diagnostic::error(
            "NTS2005",
            "an array operation on something that is not an array",
            origin.location,
        ));
    };
    if element.is_managed() {
        return Err(Diagnostic::error(
            "NTS2001",
            "an array of managed references needs a collector to trace it, \
             which this backend does not have yet",
            origin.location,
        ));
    }
    c_type(element, origin)
}

/// The descriptor a given element type uses. One per element type, not per
/// array: the descriptor is immutable and says nothing about a particular
/// array's contents.
fn descriptor_name(element: &str) -> String {
    format!("nts_desc_{}", element.replace(' ', "_"))
}

/// The subscript for an element access, with or without a bounds test.
///
/// An unsigned comparison catches a negative index in the same instruction as
/// a too-large one, since a negative wraps to something enormous. Where the
/// analysis proved the index in range, there is no test at all.
fn index_expression(func: &Func, array: ValueId, index: ValueId, checked: bool) -> String {
    if !checked {
        // Proven in range, so the cast is exact whichever representation it
        // arrived in.
        return format!("(uint32_t){}", value_name(index));
    }
    if matches!(func.values[index.0 as usize].ty, HirType::Int { .. }) {
        format!(
            "nts_check({}, (uint32_t){})",
            value_name(array),
            value_name(index)
        )
    } else {
        format!("nts_index({}, {})", value_name(array), value_name(index))
    }
}

/// Whether a coercion is a no-op because its operand already has that shape.
fn coercion_is_free(func: &Func, coercion: UnOp, operand: ValueId) -> bool {
    let source = &func.values[operand.0 as usize].ty;
    match coercion {
        UnOp::ToInt32 => {
            *source
                == HirType::Int {
                    bits: 32,
                    signed: true,
                }
        }
        UnOp::ToUint32 => {
            *source
                == HirType::Int {
                    bits: 32,
                    signed: false,
                }
        }
        _ => false,
    }
}

fn c_type(ty: &HirType, origin: &Origin) -> Result<&'static str, Diagnostic> {
    Ok(match ty {
        HirType::Void => "void",
        HirType::Bool => "bool",
        HirType::Float { bits: 32 } => "float",
        HirType::Float { .. } => "double",
        HirType::Int {
            bits: 8,
            signed: true,
        } => "int8_t",
        HirType::Int {
            bits: 8,
            signed: false,
        } => "uint8_t",
        HirType::Int {
            bits: 16,
            signed: true,
        } => "int16_t",
        HirType::Int {
            bits: 16,
            signed: false,
        } => "uint16_t",
        HirType::Int {
            bits: 32,
            signed: true,
        } => "int32_t",
        HirType::Int {
            bits: 32,
            signed: false,
        } => "uint32_t",
        HirType::Int { signed: true, .. } => "int64_t",
        HirType::Int { signed: false, .. } => "uint64_t",
        // `never` reaching a value position means control got somewhere the type
        // system said it could not.
        HirType::Never => {
            return Err(Diagnostic::error(
                "NTS2002",
                "a value of type `never` reached code generation",
                origin.location,
            ));
        }
        // An array is a pointer to its header; the elements follow it. The
        // element type is not in the C type, because every access already knows
        // it from the HIR and spelling it here would need a struct per element
        // type for no benefit.
        HirType::Managed(ManagedType::Array(_)) => "NtsArray *",
        HirType::Managed(ManagedType::String) => "NtsString *",
        HirType::Managed(_) => {
            return Err(Diagnostic::error(
                "NTS2001",
                "strings and objects need a runtime, which this backend does not have yet",
                origin.location,
            ));
        }
    })
}

fn signature(func: &Func) -> Result<String, Diagnostic> {
    let returns = c_type(&func.return_type, &func.origin)?;
    if func.params.is_empty() {
        return Ok(format!("{returns} {}(void)", c_identifier(&func.name)));
    }
    let mut params = Vec::new();
    for (index, param) in func.params.iter().enumerate() {
        let ty = c_type(&param.ty, &param.origin)?;
        params.push(format!(
            "{ty} {}",
            value_name(ValueId(u32::try_from(index).unwrap_or(0)))
        ));
    }
    Ok(format!(
        "{returns} {}({})",
        c_identifier(&func.name),
        params.join(", ")
    ))
}

/// The C name of a value.
///
/// A parameter's value is the C parameter itself, which is why the arena is
/// numbered so that `%0..%n` are the parameters — no copy is needed to get an
/// argument into a local.
fn value_name(value: ValueId) -> String {
    format!("v{}", value.0)
}

fn block_label(block: BlockId) -> String {
    format!("b{}", block.0)
}

/// Emit one function, returning its signature so a declaration can be written.
fn emit_func(
    writer: &mut CodeWriter,
    func: &Func,
    literals: &[String],
) -> Result<String, Diagnostic> {
    let signature = signature(func)?;
    writer.line(&func.origin, format!("{signature} {{"));
    emit_body(writer, func, literals)?;
    writer.line(&func.origin, "}");
    writer.blank(&func.origin);
    Ok(signature)
}

fn emit_body(writer: &mut CodeWriter, func: &Func, literals: &[String]) -> Result<(), Diagnostic> {
    let order = block_order(func);

    // Every value except the parameters becomes a local. C scoping would not let
    // a value defined in one block be read in another, so they are all declared
    // at the top — where SSA guarantees each is assigned before any use.
    //
    // Declared from the block contents rather than from the value arena, so that
    // a value dead-code elimination dropped does not leave an unused local
    // behind. The arena keeps dead entries on purpose: a `ValueId` is an index
    // into it, and compacting would invalidate every reference in the function.
    let mut declared = rustc_hash::FxHashSet::default();
    let mut read = rustc_hash::FxHashSet::default();
    for block in &func.blocks {
        declared.extend(block.params.iter().copied());
        declared.extend(block.ops.iter().copied());
        read.extend(nts_core::hir::operands_of_terminator(&block.terminator));
        for value in &block.ops {
            read.extend(nts_core::hir::operands_of(
                &func.values[value.0 as usize].kind,
            ));
        }
    }

    // A parameter nothing reads is an error under -Werror, and constant folding
    // produces them for real: `fixed(scale: 8) { return scale * scale }` folds
    // to `64` and stops looking at its argument. The signature still has to
    // match, so the parameter stays and is discarded explicitly.
    writer.indent();
    for index in 0..func.params.len() {
        let id = ValueId(u32::try_from(index).unwrap_or(0));
        if !read.contains(&id) {
            writer.line(
                &func.params[index].origin,
                format!("(void){};", value_name(id)),
            );
        }
    }
    writer.dedent();

    writer.indent();
    for (index, op) in func.values.iter().enumerate() {
        // A parameter is already declared by the signature, a value nothing
        // reads was dropped by dead-code elimination, and an operation that
        // produces nothing has nothing to hold — `void v4;` is not a variable.
        if matches!(op.kind, OpKind::Param(_))
            || matches!(op.ty, HirType::Void)
            || !declared.contains(&ValueId(u32::try_from(index).unwrap_or(0)))
        {
            continue;
        }
        let ty = c_type(&op.ty, &op.origin)?;
        writer.line(
            &op.origin,
            format!(
                "{ty} {};",
                value_name(ValueId(u32::try_from(index).unwrap_or(0)))
            ),
        );
    }

    let temps = destruct::temp_count(func);
    for temp in 0..temps {
        // One scratch per cycle depth. Typed as the widest scalar, since a swap
        // only ever moves a value into a slot of its own type.
        writer.line(&func.origin, format!("double t{temp};"));
    }
    writer.dedent();

    // Only blocks something actually jumps to need a label. The entry never does,
    // and an unreferenced label is a warning in every C compiler worth using.
    let mut targeted = rustc_hash::FxHashSet::default();
    for block in &func.blocks {
        targeted.extend(block.terminator.successors());
    }

    for (position, block) in order.iter().enumerate() {
        let next = order.get(position + 1).copied();
        emit_block(
            writer,
            func,
            *block,
            next,
            targeted.contains(block),
            literals,
        )?;
    }
    Ok(())
}

fn emit_block(
    writer: &mut CodeWriter,
    func: &Func,
    block: BlockId,
    next: Option<BlockId>,
    labelled: bool,
    literals: &[String],
) -> Result<(), Diagnostic> {
    let record = &func.blocks[block.0 as usize];
    let origin = func
        .values
        .get(record.ops.first().map_or(0, |v| v.0 as usize))
        .map_or_else(|| func.origin.clone(), |op| op.origin.clone());

    if labelled {
        writer.line(&origin, format!("{}:;", block_label(block)));
    }
    writer.indent();

    for value in &record.ops {
        emit_op(writer, func, *value, literals)?;
    }
    emit_terminator(writer, func, block, next, &origin);

    writer.dedent();
    Ok(())
}

/// The C spelling of a binary operation.
fn binary_text(
    func: &Func,
    op: &nts_core::hir::Op,
    name: &str,
    bin: BinOp,
    lhs: ValueId,
    rhs: ValueId,
) -> Result<String, Diagnostic> {
    // A bitwise operator's operands are always coercion results — the lowering
    // guarantees it — so they hold int32 values whatever their representation
    // says. When specialization did not give them an integer type, the
    // arithmetic still has to happen in integers, so it is spelled with casts
    // around it. Those casts are exactly the cost the analysis removes.
    let integral = matches!(op.ty, HirType::Int { .. });
    // Cast decided per *operand*, from its own type. Deciding it from the
    // result's would emit `v14 | v15` with `v15` a double, which is not C.
    let cast = |value: ValueId| {
        if matches!(func.values[value.0 as usize].ty, HirType::Int { .. }) {
            value_name(value)
        } else {
            format!("(int32_t){}", value_name(value))
        }
    };
    let wrap = |text: String| {
        if integral {
            format!("{name} = {text};")
        } else {
            format!("{name} = (double)({text});")
        }
    };

    // Shifts are not C operators here. JavaScript masks the count to five bits,
    // where C leaves a shift by 32 or more undefined; `<<` on a negative signed
    // operand is undefined in C and defined in JavaScript. Each goes through a
    // helper that spells the real rule.
    let helper = match bin {
        BinOp::Shl => Some("nts_shl"),
        BinOp::Shr => Some("nts_shr"),
        BinOp::UShr => Some("nts_ushr"),
        _ => None,
    };
    if let Some(helper) = helper {
        return Ok(wrap(format!("{helper}({}, {})", cast(lhs), cast(rhs))));
    }

    // Strings compare by value: `"a" + "b" === "ab"` is true in JavaScript, and
    // those are two different allocations, so pointer equality is the wrong
    // answer rather than an approximation of it.
    if matches!(bin, BinOp::Eq | BinOp::Ne)
        && matches!(
            func.values[lhs.0 as usize].ty,
            HirType::Managed(ManagedType::String)
        )
    {
        let negate = if matches!(bin, BinOp::Ne) { "!" } else { "" };
        return Ok(format!(
            "{name} = {negate}nts_string_eq({}, {});",
            value_name(lhs),
            value_name(rhs)
        ));
    }

    let operator = match bin {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Rem => "%",
        BinOp::BitAnd => "&",
        BinOp::BitOr => "|",
        BinOp::BitXor => "^",
        BinOp::Lt => "<",
        BinOp::Le => "<=",
        BinOp::Gt => ">",
        BinOp::Ge => ">=",
        BinOp::Eq => "==",
        BinOp::Ne => "!=",
        BinOp::Shl | BinOp::Shr | BinOp::UShr => unreachable!("handled above"),
        // Not `fmin`/`fmax`: those return the non-NaN operand where JavaScript
        // returns NaN, and disagree about the two zeroes.
        BinOp::Min | BinOp::Max => {
            // Two integers cannot be NaN and have no second zero, so the whole
            // reason the helper exists is absent and a comparison will do.
            let both_integers = matches!(func.values[lhs.0 as usize].ty, HirType::Int { .. })
                && matches!(func.values[rhs.0 as usize].ty, HirType::Int { .. });
            if both_integers {
                let test = if matches!(bin, BinOp::Min) { "<" } else { ">" };
                return Ok(format!(
                    "{name} = {0} {test} {1} ? {0} : {1};",
                    value_name(lhs),
                    value_name(rhs)
                ));
            }
            let helper = if matches!(bin, BinOp::Min) {
                "nts_min"
            } else {
                "nts_max"
            };
            return Ok(wrap(format!(
                "{helper}({}, {})",
                value_name(lhs),
                value_name(rhs)
            )));
        }
        BinOp::Concat => {
            return Ok(format!(
                "{name} = nts_concat({}, {});",
                value_name(lhs),
                value_name(rhs)
            ));
        }
    };

    if matches!(bin, BinOp::BitAnd | BinOp::BitOr | BinOp::BitXor) {
        return Ok(wrap(format!("{} {operator} {}", cast(lhs), cast(rhs))));
    }

    // `%` is integer-only in C. On doubles it is `fmod`, and emitting `%` would
    // not compile — better than emitting something that does and is wrong, but
    // still worth naming. On integers it is exactly JavaScript's remainder:
    // both take the sign of the dividend.
    if matches!(bin, BinOp::Rem) && matches!(op.ty, HirType::Float { .. }) {
        return Err(Diagnostic::error(
            "NTS2003",
            "floating-point remainder needs `fmod`, which is not wired up yet",
            op.origin.location,
        ));
    }

    Ok(format!(
        "{name} = {} {operator} {};",
        value_name(lhs),
        value_name(rhs)
    ))
}

/// The C spelling of a unary operation.
fn unary_text(func: &Func, name: &str, un: UnOp, operand: ValueId, result: &HirType) -> String {
    match un {
        UnOp::Neg => format!("{name} = -{};", value_name(operand)),
        UnOp::Not => format!("{name} = !{};", value_name(operand)),
        UnOp::Truthy => {
            // An integer is truthy exactly when it is non-zero, and `!= 0` says
            // so. A double additionally has to exclude NaN, which is falsy and
            // which `!= 0` would call true — every comparison with a NaN is
            // false, including the inequality.
            if matches!(func.values[operand.0 as usize].ty, HirType::Int { .. }) {
                format!("{name} = {} != 0;", value_name(operand))
            } else {
                format!("{name} = ({0} != 0.0) && !isnan({0});", value_name(operand))
            }
        }
        UnOp::Floor | UnOp::Ceil | UnOp::Trunc | UnOp::Round | UnOp::Abs => {
            // An integer is already rounded, and taking its magnitude is a
            // comparison rather than a library call.
            let already_integral =
                matches!(func.values[operand.0 as usize].ty, HirType::Int { .. });
            if already_integral {
                return match un {
                    UnOp::Abs => format!("{name} = {0} < 0 ? -{0} : {0};", value_name(operand)),
                    _ => format!("{name} = {};", value_name(operand)),
                };
            }
            let call = match un {
                UnOp::Floor => "floor",
                UnOp::Ceil => "ceil",
                UnOp::Trunc => "trunc",
                UnOp::Abs => "fabs",
                // C's `round` rounds a half away from zero; JavaScript rounds it
                // toward positive infinity, so `Math.round(-1.5)` is `-1` and
                // `round(-1.5)` is `-2`.
                _ => "nts_round",
            };
            // Rounding in doubles and converting after, never the other way
            // round: `(int32_t)-3.7` is `-3` and `floor(-3.7)` is `-4`.
            if matches!(result, HirType::Int { .. }) {
                return format!("{name} = (int32_t){call}({});", value_name(operand));
            }
            format!("{name} = {call}({});", value_name(operand))
        }
        UnOp::ToInt32 | UnOp::ToUint32 => {
            // A value already in the target representation needs no coercion,
            // and that is the common case: integer code writing `x | 0` on
            // something already proven an integer.
            if coercion_is_free(func, un, operand) {
                return format!("{name} = {};", value_name(operand));
            }

            // An *integer* of some other width is a truncation, which C spells
            // as a cast through the unsigned type of the target — exactly
            // ToInt32's "reduce modulo 2^32, reinterpret signed", and one
            // instruction. Only a genuine double needs the total, wrapping,
            // fmod-based helper, and reaching for it on an `int64_t` operand
            // costs a conversion to double and a library call in the loop body
            // that the whole analysis existed to speed up.
            if matches!(func.values[operand.0 as usize].ty, HirType::Int { .. }) {
                return match un {
                    UnOp::ToInt32 => {
                        format!("{name} = (int32_t)(uint32_t){};", value_name(operand))
                    }
                    _ => format!("{name} = (uint32_t){};", value_name(operand)),
                };
            }

            let helper = if matches!(un, UnOp::ToInt32) {
                "nts_to_int32"
            } else {
                "nts_to_uint32"
            };
            format!("{name} = {helper}({});", value_name(operand))
        }
    }
}

fn emit_op(
    writer: &mut CodeWriter,
    func: &Func,
    value: ValueId,
    literals: &[String],
) -> Result<(), Diagnostic> {
    let op = func.value(value);
    let name = value_name(value);
    let text = match &op.kind {
        // Nothing to compute at the definition site. A parameter *is* the C
        // parameter; a block parameter is written by the edges that jump here;
        // a return is spelled by the terminator.
        OpKind::Param(_) | OpKind::BlockParam(_) | OpKind::Return(_) => return Ok(()),
        OpKind::ConstInt(v) => format!("{name} = {v};"),
        // Enough digits to round-trip an f64 exactly. Fewer would change the
        // program's arithmetic.
        OpKind::ConstFloat(v) => format!("{name} = {v:?};"),
        OpKind::ConstBool(v) => format!("{name} = {v};"),
        // A literal is immutable and known now, so it is static data rather
        // than an allocation. This is the difference between a string-heavy
        // program allocating once at startup and allocating in a loop.
        OpKind::ConstString(text) => {
            format!(
                "{name} = (NtsString *)(void *)&{};",
                literal_name(literals, text)
            )
        }
        OpKind::Binary { op: bin, lhs, rhs } => binary_text(func, op, &name, *bin, *lhs, *rhs)?,
        OpKind::Call { callee, args } => {
            let (Callee::Direct(target) | Callee::External(target)) = callee;
            let arguments: Vec<String> = args.iter().map(|a| value_name(*a)).collect();
            format!(
                "{name} = {}({});",
                c_identifier(target),
                arguments.join(", ")
            )
        }
        OpKind::Unary { op: un, operand } => unary_text(func, &name, *un, *operand, &op.ty),
        OpKind::ArrayNew { length } => {
            let element = element_type(&op.ty, &op.origin)?;
            format!(
                "{name} = nts_array_new(&{}, {});",
                descriptor_name(element),
                value_name(*length)
            )
        }
        OpKind::Length(array) => {
            let target = c_type(&op.ty, &op.origin)?;
            format!("{name} = ({target}){}->length;", value_name(*array))
        }
        OpKind::ArrayGet {
            array,
            index,
            checked,
        } => {
            let element = element_type(&func.values[array.0 as usize].ty, &op.origin)?;
            let slot = index_expression(func, *array, *index, *checked);
            format!(
                "{name} = NTS_ELEMENTS({}, {element})[{slot}];",
                value_name(*array)
            )
        }
        OpKind::ArraySet {
            array,
            index,
            value: stored,
            checked,
        } => {
            let element = element_type(&func.values[array.0 as usize].ty, &op.origin)?;
            let slot = index_expression(func, *array, *index, *checked);
            format!(
                "NTS_ELEMENTS({}, {element})[{slot}] = {};",
                value_name(*array),
                value_name(*stored)
            )
        }
        OpKind::Convert(operand) => {
            // A C cast. Between an integer and a double this is one instruction,
            // and every one is a place specialization decided two adjacent
            // values should live in different machine types.
            let target = c_type(&op.ty, &op.origin)?;
            format!("{name} = ({target}){};", value_name(*operand))
        }
    };
    writer.line(&op.origin, text);
    Ok(())
}

fn emit_terminator(
    writer: &mut CodeWriter,
    func: &Func,
    block: BlockId,
    next: Option<BlockId>,
    origin: &Origin,
) {
    let record = &func.blocks[block.0 as usize];

    // The copies an edge implies run before control leaves.
    let emit_edge = |writer: &mut CodeWriter, target: BlockId, args: &[ValueId]| {
        let params = &func.blocks[target.0 as usize].params;
        for copy in destruct::edge_copies(params, args) {
            let text = match copy {
                Copy::Move { to, from } => format!("{} = {};", value_name(to), value_name(from)),
                Copy::Save { temp, from } => format!("t{temp} = {};", value_name(from)),
                Copy::Restore { to, temp } => format!("{} = t{temp};", value_name(to)),
            };
            writer.line(origin, text);
        }
    };

    match &record.terminator {
        Terminator::Return(Some(value)) => {
            writer.line(origin, format!("return {};", value_name(*value)));
        }
        Terminator::Return(None) => writer.line(origin, "return;"),
        Terminator::Unreachable => {
            // A claim the compiler made. Saying so lets the C compiler optimize on
            // it, and makes a violated claim a crash rather than a fall-through.
            writer.line(origin, "__builtin_unreachable();");
        }
        Terminator::Jump { target, args } => {
            emit_edge(writer, *target, args);
            // The block order exists so this is usually free.
            if next != Some(*target) {
                writer.line(origin, format!("goto {};", block_label(*target)));
            }
        }
        Terminator::Branch {
            cond,
            then_target,
            then_args,
            else_target,
            else_args,
        } => {
            // Each arm's copies belong to that arm, so they are emitted inside it.
            writer.line(origin, format!("if ({}) {{", value_name(*cond)));
            writer.nested(|writer| {
                emit_edge(writer, *then_target, then_args);
                writer.line(origin, format!("goto {};", block_label(*then_target)));
            });
            writer.line(origin, "} else {");
            writer.nested(|writer| {
                emit_edge(writer, *else_target, else_args);
                writer.line(origin, format!("goto {};", block_label(*else_target)));
            });
            writer.line(origin, "}");
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_c_keyword_is_not_a_usable_function_name() {
        // `function double()` is ordinary TypeScript.
        assert_eq!(c_identifier("double"), "double_");
        assert_eq!(c_identifier("int"), "int_");
        assert_eq!(c_identifier("switch"), "switch_");
        // `main` is not a keyword, but a second definition of it does not link.
        assert_eq!(c_identifier("main"), "main_");
    }

    #[test]
    fn a_name_this_backend_generates_is_also_reserved() {
        // A function called `v0` would shadow the first parameter of every
        // function that calls it.
        assert_eq!(c_identifier("v0"), "v0_");
        assert_eq!(c_identifier("t12"), "t12_");
        assert_eq!(c_identifier("b3"), "b3_");
        // Only the exact generated shape. These are ordinary names.
        assert_eq!(c_identifier("v"), "v");
        assert_eq!(c_identifier("value0"), "value0");
        assert_eq!(c_identifier("b3x"), "b3x");
    }

    #[test]
    fn a_leading_underscore_is_reserved_to_the_implementation() {
        assert_eq!(c_identifier("_internal"), "_internal_");
    }

    #[test]
    fn an_ordinary_name_is_left_alone() {
        // Mangling everything would be simpler and would make every exported
        // symbol worse to link against.
        assert_eq!(c_identifier("compute"), "compute");
        assert_eq!(c_identifier("sumTo"), "sumTo");
    }
}
