// Generated by `nts bind-c`. Edit the command, not this file.
//
// Derived from one compiler's reading of these headers under these macros,
// which makes it a claim like any hand-written binding. `native_witness.c`
// is what proves it against the headers a consumer actually compiles with.
/**
 * @ntsHeader /home/akisarou/Projects/nts/examples/workspace/packages/crypto-core/native/digest.h
 */
declare module "c:digest" {
  import type { c_uint32 } from "c:types";
  export function digest_step(seed: c_uint32, value: c_uint32): c_uint32;
}
