// GENERATED by `nts bind --jar catalog.jar --out types/`. Do not edit.
//
// Generated against: catalog.jar, 2 classes, sha256 3f9a...  (recorded so a
// stale binding reports "generated against X, building against Y" rather than
// failing later with NoSuchMethodError)
//
// Every comment below is emitted by the generator, not written by hand: where a
// call costs a copy or an allocation, the binding says so at the declaration,
// because that is the only place a reader is already looking.

import type { int, float } from "./java";
import { java } from "./java";

declare module "java:com.example" {

  /** com.example.Kind -- a Java enum. */
  export class Kind {
    private constructor();

    // Enum constants are reference statics: a `getstatic`, and the first one
    // touched runs `Kind.<clinit>`. They do not inline.
    static readonly SMALL: Kind;
    static readonly MEDIUM: Kind;
    static readonly LARGE: Kind;

    /** Java's own `Enum.name()`. */
    name(): string;
    ordinal(): int;
    weight(): int;

    /** `Kind.values()` ALLOCATES a fresh array per call -- Java clones it to
     *  stop callers mutating the enum's own storage. Hoist it out of a loop. */
    static values(): Kind[];
    static valueOf(name: string): Kind;
  }

  /** com.example.Catalog */
  export class Catalog {
    constructor(label: string);

    // --- statics ------------------------------------------------------------

    /** Compiles to `ldc 512`. The class is never loaded to read this. */
    static readonly MAX: int;
    /** Compiles to `ldc "catalog"`. Also free. */
    static readonly NAME: string;
    /** A reference static: a real `getstatic`, and it triggers `<clinit>`.
     *  Do not cache this in a module-scope `const` -- that moves class
     *  initialisation to program start. */
    static readonly DEFAULT_KIND: Kind;

    // --- a public Java field ------------------------------------------------

    /** A direct `getfield`/`putfield`. Not one of our field ops, so the
     *  compiler does not reason about what it holds -- but reading it costs
     *  exactly what it costs `javac`. */
    hits: int;

    // --- collections: no copy, either direction -----------------------------

    /** Returns the Java `HashMap` itself. No copy. Values are boxed
     *  `Integer` because a Java map cannot hold a primitive -- Java's cost,
     *  paid by a Java caller too. */
    index(): java.util.HashMap<string, java.lang.Integer>;

    /** Returns the Java `List` itself. No copy. Use `get`/`size` or
     *  `iterator()`; `toArray()` allocates. */
    names(): java.util.List<string>;

    /** A Java `int[]` IS an `Int32Array` here -- same object, no copy, and
     *  the element type narrows because it is the TypeScript type. */
    counts(): Int32Array;

    /** A Java `byte[]` IS a `Uint8Array`. `subarray` is a view, not a copy. */
    bytes(): Uint8Array;

    // --- long ---------------------------------------------------------------

    /** `bigint`, not `number`: this value is 2^53+1 and a `number` would
     *  round it. Mixing it with a `number` needs an explicit conversion, and
     *  that friction is the point. */
    id(): bigint;

    // --- the overload set ---------------------------------------------------
    //
    // Four Java methods, three TypeScript signatures. The collapse is resolved
    // by losslessness, not by guessing:
    //
    //   a `number` is an f64, so it goes to find(double)  -- the ONLY
    //     candidate that receives it without loss. find(int) would truncate.
    //   a `bigint` goes to find(long).
    //   a `string` goes to find(String).
    //
    // find(int) is unreachable from TypeScript and is listed here so the
    // binding table is complete; call it with `Java.asInt(x)` if you need the
    // truncating form, which is explicit for the same reason.

    find(key: number): int;
    find(key: bigint): int;
    find(key: string): int;

    /** Two equally-lossless candidates for a `string`: `render(String)` and
     *  `render(Object)`. Java's own rule decides -- most specific applicable
     *  method, JLS 15.12.2 -- so this resolves to `render(String)`, which is
     *  what a Java programmer already expects. */
    render(value: string): string;
    render(value: unknown): string;

    // --- varargs ------------------------------------------------------------

    /** Java packs varargs into an array AT THE CALL SITE, so this allocates
     *  one `int[]` per call. That is what `javac` emits too. */
    sum(...values: int[]): int;

    // --- nullability --------------------------------------------------------

    /** `@Nullable` -- read from the CLASS-retention annotation table, which a
     *  reader that only looks at RuntimeVisibleAnnotations would miss. */
    describe(id: int): string | null;

    /** NOT annotated. The default for an unannotated reference return is
     *  `| null` -- refuse rather than miscompile. This one is declared
     *  non-null in `bind.overrides.json`, which is why it reads clean. */
    name(): string;

    // --- throwing -----------------------------------------------------------

    /** `throws NumberFormatException`. Today a Java exception is caught at the
     *  call site and raised as an `NtsRefusal` naming the exception -- the
     *  program declines rather than dying with a stack trace. It is NOT yet
     *  catchable by a TypeScript `try`/`catch`. */
    parse(s: string): int;

    // --- generics -----------------------------------------------------------
    //
    // Surfaced rather than erased, because Java erases generics at runtime and
    // so does TypeScript. Surfacing promises exactly what Java promises.

    repeat<T>(item: T, times: int): java.util.List<T>;

    /** `List<? extends Number>` -- a covariant wildcard, so read-only here. */
    total(xs: readonly number[] | java.util.List<number>): number;

    /** A raw `List`. Becomes `List<unknown>`, never `List<any>`. */
    raw(): java.util.List<unknown>;

    // --- nested and inner ---------------------------------------------------

    /** A true inner class. `new Catalog.Cursor(n)` is not expressible -- it
     *  needs the outer instance -- so the binding surfaces the factory the
     *  outer class already provides. Where none exists, `nts bind` emits
     *  `newCursor(...)` and passes `this` as the synthetic first argument,
     *  which is exactly what `javac` emits for `outer.new Cursor(n)`. */
    cursorAt(at: int): Catalog.Cursor;
  }

  export namespace Catalog {
    /** Static nested: binary name `com/example/Catalog$Entry`. No outer
     *  instance, so it constructs like any other class. */
    export class Entry {
      constructor(key: string);
      readonly key: string;
    }

    /** Inner: holds a reference to its outer `Catalog`. */
    export class Cursor {
      private constructor();
      at: int;
      owner(): string;
    }
  }
}
