// The shared prelude every generated binding relies on.
//
// **A global script, not a module.** There is no top-level `import` or `export`
// in this file, deliberately: a `.d.ts` with one is a module, and then its
// declarations are not ambient and `java.util.List` resolves nowhere. Compiling
// the project is what established that; reading it did not.
//
// WRITTEN BY HAND, and deliberately. An earlier version of this header claimed
// to be "GENERATED by `nts bind --prelude`" and drift-tested; there is no
// `--prelude` mode and nothing tests this file. Both claims were false and a
// reader had no way to tell.
//
// Hand-written is the right answer here, which is why the fix is to the header
// rather than to the file. Generating `java.lang.Integer` from the JDK gives
// fifty methods where three are wanted, and a prelude that every binding
// imports should be the small curated surface a caller actually needs. The
// generator's job is the *jar you are binding*; this is the vocabulary those
// bindings are written in.
//
// WHAT IT COSTS, stated rather than discovered: no binding table is emitted for
// this file, because a table is produced by the generator and this file does not
// come from it. Measured on `java-from-ts` -- of 35 declarations a call resolved
// to, 26 were in the generated `com.example.d.ts` and had a row; the 9 here did
// not. So a call into `java.util.List.get` cannot lower even once the
// foreign-call arm exists upstream. Closing that means either generating a
// prelude after all, or writing its table by hand beside it.

// --- why there are no numeric brands here ---------------------------------
//
// An earlier version of this file declared `int`, `long`, `short`, `float` and
// `double` as branded numbers, so that `find(int)` and `find(double)` stayed
// apart when both collapse to one TypeScript name.
//
// (The five names above read `number` five times until just now: removing the
// brands was done with a substitution over the type mapping, and it rewrote the
// prose describing them along with the code. A comment is not protected by the
// thing it describes being correct.)
//
// **Deleted, because it does not lower.** Measured 2026-09-13: a branded
// intersection survives in exactly one position -- a *free* declared function's
// parameter -- and is refused as a return, as a class property, and as a class
// method's parameter. A binding is a class, so the brand was refused at every
// position the generator actually emits.
//
// What replaced it: every Java integral width is `number`, and an overload that
// would collide is renamed by the generator -- `find$number` beside `find`. The
// exception is arrays, where the width survives on its own, because a typed
// array IS a distinct TypeScript type and needs no brand to be one.

// --- the collections that stay Java ------------------------------------------
//
// These are NOT converted. A `java.util.HashMap` handed back by a Java method
// is the same object on both sides, and calling it from TypeScript is an
// `invokeinterface` -- no copy, no wrapper, no marshalling. The cost of
// pretending it were a JS `Map` would be a copy per crossing; see "Java data
// structures stay Java".

// The type parameters carry `= unknown` defaults so a **raw** Java type is
// expressible. `Catalog.raw()` returns a pre-generics `List` with no `Signature`
// attribute, so the generator emits a bare `java.util.List` -- without a default
// that is `TS2314 Generic type 'List<T>' requires 1 type argument(s)`, a hard
// error rather than a cosmetic one. `unknown` rather than `any`, so nothing
// downstream is silenced.
declare namespace java.util {
  interface Iterator<T = unknown> {
    hasNext(): boolean;
    next(): T;
  }

  interface Collection<T = unknown> {
    size(): number;
    isEmpty(): boolean;
    contains(o: T): boolean;
    iterator(): Iterator<T>;
    /** Allocates. Prefer `iterator()` in a loop. */
    toArray(): T[];
  }

  interface List<T = unknown> extends Collection<T> {
    get(index: number): T;
    set(index: number, element: T): T;
    add(element: T): boolean;
    indexOf(o: T): number;
  }

  interface Map<K = unknown, V = unknown> {
    size(): number;
    isEmpty(): boolean;
    /** Returns `null` when absent -- Java's `get` does not distinguish. */
    get(key: K): V | null;
    put(key: K, value: V): V | null;
    containsKey(key: K): boolean;
    remove(key: K): V | null;
    keySet(): Set<K>;
    values(): Collection<V>;
  }

  interface Set<T = unknown> extends Collection<T> {}

  class HashMap<K = unknown, V = unknown> implements Map<K, V> {
    constructor();
    constructor(initialCapacity: number);
    size(): number;
    isEmpty(): boolean;
    get(key: K): V | null;
    put(key: K, value: V): V | null;
    containsKey(key: K): boolean;
    remove(key: K): V | null;
    keySet(): Set<K>;
    values(): Collection<V>;
  }
}

// --- boxed numerics ----------------------------------------------------------
//
// `HashMap<String, Integer>` cannot hold a primitive, so the value type is a
// box. This is Java's cost, not ours: a Java caller writing the same map pays
// it too. Cost 1 in the plan.

declare namespace java.lang {
  /** The boxed-number supertype, which a wildcard bound names. */
  class Number {
    intValue(): number;
    doubleValue(): number;
    longValue(): bigint;
  }

  class Integer extends Number {
    static valueOf(value: number): Integer;
    intValue(): number;
  }
  class Long extends Number {
    static valueOf(value: bigint): Long;
    longValue(): bigint;
  }
  class Double extends Number {
    static valueOf(value: number): Double;
    doubleValue(): number;
  }
  /** The erased supertype. `Object` becomes `unknown`, never `any`. */
  type Object = unknown;
}
