// The shared prelude every generated binding imports.
//
// GENERATED by `nts bind --prelude`. Checked in and drift-tested, for the same
// reason `codegen/llvm/src/signatures.rs` is: a file you can grep beats a file
// you have to run a build to see.

// --- the numeric brands ------------------------------------------------------
//
// A TypeScript `number` is an f64. Java has six numeric widths and they are not
// interchangeable, so the binding needs to say which one a parameter takes --
// otherwise `find(1.5)` and `find(1)` are the same call and one of them is a
// silent truncation.
//
// These are *phantom* brands: `int` is a `number` at runtime and erases to
// nothing. Their whole job is to make two overloads distinguishable to the
// checker. Cost 10a in docs/jvm-interop.md is the measurement behind this, and
// it is why an `int[]` is spelled `Int32Array` below rather than `int[]` -- the
// element type IS the TypeScript type, so a branded array would not narrow.

declare const JVM_WIDTH: unique symbol;

/** Java `int`: a 32-bit signed integer. Truncates a fractional `number`. */
export type int = number & { readonly [JVM_WIDTH]: "int" };
/** Java `short`. */
export type short = number & { readonly [JVM_WIDTH]: "short" };
/** Java `byte`. */
export type byte = number & { readonly [JVM_WIDTH]: "byte" };
/** Java `char`: a UTF-16 code unit, not a `string`. */
export type char = number & { readonly [JVM_WIDTH]: "char" };
/** Java `float`: 32-bit. Passing a `number` here loses precision. */
export type float = number & { readonly [JVM_WIDTH]: "float" };

// Java `double` is exactly `number` and gets no brand -- a brand that is never
// the distinguishing one is noise at every call site.
// Java `long` is `bigint`, because it exceeds 2^53 and `number` would be a lie.
// Java `boolean` is `boolean`. Java `String` is `string`.

// --- the collections that stay Java ------------------------------------------
//
// These are NOT converted. A `java.util.HashMap` handed back by a Java method
// is the same object on both sides, and calling it from TypeScript is an
// `invokeinterface` -- no copy, no wrapper, no marshalling. The cost of
// pretending it were a JS `Map` would be a copy per crossing; see "Java data
// structures stay Java".

export namespace java.util {
  interface Iterator<T> {
    hasNext(): boolean;
    next(): T;
  }

  interface Collection<T> {
    size(): int;
    isEmpty(): boolean;
    contains(o: T): boolean;
    iterator(): Iterator<T>;
    /** Allocates. Prefer `iterator()` in a loop. */
    toArray(): T[];
  }

  interface List<T> extends Collection<T> {
    get(index: int): T;
    set(index: int, element: T): T;
    add(element: T): boolean;
    indexOf(o: T): int;
  }

  interface Map<K, V> {
    size(): int;
    isEmpty(): boolean;
    /** Returns `null` when absent -- Java's `get` does not distinguish. */
    get(key: K): V | null;
    put(key: K, value: V): V | null;
    containsKey(key: K): boolean;
    remove(key: K): V | null;
    keySet(): Set<K>;
    values(): Collection<V>;
  }

  interface Set<T> extends Collection<T> {}

  class HashMap<K, V> implements Map<K, V> {
    constructor();
    constructor(initialCapacity: int);
    size(): int;
    isEmpty(): boolean;
    get(key: K): V | null;
    put(key: K, value: V): V | null;
    containsKey(key: K): boolean;
    remove(key: K): V | null;
    keySet(): Set<K>;
    values(): Collection<V>;
  }
}

// --- boxed numerics ----------------------------------------------------------
//
// `HashMap<String, Integer>` cannot hold a primitive, so the value type is a
// box. This is Java's cost, not ours: a Java caller writing the same map pays
// it too. Cost 1 in the plan.

export namespace java.lang {
  class Integer {
    static valueOf(value: int): Integer;
    intValue(): int;
  }
  class Long {
    static valueOf(value: bigint): Long;
    longValue(): bigint;
  }
  class Double {
    static valueOf(value: number): Double;
    doubleValue(): number;
  }
  /** The erased supertype. `Object` becomes `unknown`, never `any`. */
  type Object = unknown;
}
