// GENERATED by `nts bind`. Do not edit.
//
// The prelude, as a **global namespace**: no top-level import anywhere in
// this file, or it becomes a module and every `java.util.List` in every
// binding stops resolving.

declare namespace java.lang {
  /** java.lang.CharSequence */
  export interface CharSequence {
  }

  /** java.lang.Comparable */
  export interface Comparable<T = unknown> {
  }

  /** java.lang.Double Final: cannot be extended. */
  export class Double {
    doubleValue(): number;
  }

  /** java.lang.Integer Final: cannot be extended. */
  export class Integer {
    intValue(): number;
  }

  /** java.lang.Long Final: cannot be extended. */
  export class Long {
    longValue(): bigint;
  }

  /** java.lang.Number */
  export abstract class Number {
    intValue(): number;
    longValue(): bigint;
    doubleValue(): number;
  }

  /** java.lang.Object */
  export class Object {
  }

  /** java.lang.String Final: cannot be extended. */
  export class String {
  }

}
