// Generated by `nts bind-objc` from the macOS SDK and Swift's symbol graphs. Do not edit: regenerate.
//
// nts bind-objc --module objc:CoreGraphics --framework CoreGraphics --class CGContext --class CGColor --class CGColorSpace --function CGColorSpaceCreateDeviceRGB
/**
 * @ntsFramework CoreGraphics
 * @ntsHeader <CoreGraphics/CoreGraphics.h>
 */
declare module "objc:CoreGraphics" {
  import type { ByValue, CEnum, Fields, Owned, Ptr, Struct } from "c:types";
  import type { CGFloat, Double, Int32, ObjcClass, UInt, UInt32, UInt8 } from "objc:types";

  export type CGAffineTransform = Struct<{ a: Double; b: Double; c: Double; d: Double; tx: Double; ty: Double }, "CGAffineTransform">;

  export type CGPoint = Struct<{ x: Double; y: Double }, "CGPoint">;

  export type CGRect = Struct<{ origin: CGPoint; size: CGSize }, "CGRect">;

  export type CGSize = Struct<{ width: Double; height: Double }, "CGSize">;

  export const enum CGBitmapInfo {
    floatComponents = 256,
    byteOrderDefault = 0,
    byteOrder16Little = 4096,
    byteOrder32Little = 8192,
    byteOrder16Big = 12288,
    byteOrder32Big = 16384,
  }

  export const enum CGBlendMode {
    normal = 0,
    multiply = 1,
    screen = 2,
    overlay = 3,
    darken = 4,
    lighten = 5,
    colorDodge = 6,
    colorBurn = 7,
    softLight = 8,
    hardLight = 9,
    difference = 10,
    exclusion = 11,
    hue = 12,
    saturation = 13,
    color = 14,
    luminosity = 15,
    clear = 16,
    copy = 17,
    sourceIn = 18,
    sourceOut = 19,
    sourceAtop = 20,
    destinationOver = 21,
    destinationIn = 22,
    destinationOut = 23,
    destinationAtop = 24,
    xor = 25,
    plusDarker = 26,
    plusLighter = 27,
  }

  export const enum CGColorRenderingIntent {
    defaultIntent = 0,
    absoluteColorimetric = 1,
    relativeColorimetric = 2,
    perceptual = 3,
    saturation = 4,
  }

  export const enum CGColorSpaceModel {
    unknown = -1,
    monochrome = 0,
    rgb = 1,
    cmyk = 2,
    lab = 3,
    deviceN = 4,
    indexed = 5,
    pattern = 6,
    XYZ = 7,
  }

  export const enum CGImageAlphaInfo {
    none = 0,
    premultipliedLast = 1,
    premultipliedFirst = 2,
    last = 3,
    first = 4,
    noneSkipLast = 5,
    noneSkipFirst = 6,
    alphaOnly = 7,
  }

  export const enum CGInterpolationQuality {
    default = 0,
    none = 1,
    low = 2,
    medium = 4,
    high = 3,
  }

  export const enum CGLineCap {
    butt = 0,
    round = 1,
    square = 2,
  }

  export const enum CGLineJoin {
    miter = 0,
    round = 1,
    bevel = 2,
  }

  export const enum CGPathDrawingMode {
    fill = 0,
    eoFill = 1,
    stroke = 2,
    fillStroke = 3,
    eoFillStroke = 4,
  }

  export const enum CGTextDrawingMode {
    fill = 0,
    stroke = 1,
    fillStroke = 2,
    invisible = 3,
    fillClip = 4,
    strokeClip = 5,
    fillStrokeClip = 6,
    clip = 7,
  }

  export interface CGColorOwnMethods {
    /** @ntsSymbol CGColorGetAlpha */
    CGColorGetAlpha(this: CGColor): CGFloat;
    /** @ntsGet CGColorGetAlpha */
    readonly alpha: CGFloat;
    /** @ntsSymbol CGColorGetColorSpace */
    CGColorGetColorSpace(this: CGColor): CGColorSpace | null;
    /** @ntsGet CGColorGetColorSpace */
    readonly colorSpace: CGColorSpace | null;
    /** @ntsSymbol CGColorCreateCopy */
    copy(this: CGColor): Owned<CGColor> | null;
    /** @ntsSymbol CGColorCreateCopyWithAlpha */
    copy(this: CGColor, labels: { alpha: CGFloat }): Owned<CGColor> | null;
    /** @ntsSymbol CGColorGetNumberOfComponents */
    CGColorGetNumberOfComponents(this: CGColor): UInt;
    /** @ntsGet CGColorGetNumberOfComponents */
    readonly numberOfComponents: UInt;
    // Not bound, each for the reason given:
    //   CGColorGetContentHeadroom: introduced in macOS 26.0
    //   CGColorCreateCopyByMatchingToColorSpace: a `const struct __CFDictionary *`
    //   CGColorCreateWithContentHeadroom: introduced in macOS 26.0
    //   CGColorCreateWithPattern: `CGPattern`, a Core Foundation class this binding does not bind (`--class CGPattern`)
    //   CGColorGetPattern: `CGPattern`, a Core Foundation class this binding does not bind (`--class CGPattern`)
    //   CGColorGetTypeID: a `swift.type.property`, which is not bound yet
  }
  export type CGColor = ObjcClass<"CGColor"> & CGColorOwnMethods;
  /** @ntsSymbol CGColorCreate */
  export function CGColor(labels: { colorSpace: CGColorSpace | null; components: Ptr<CGFloat> | null }): Owned<CGColor>;
  /** @ntsSymbol CGColorCreateGenericCMYK */
  export function CGColor(labels: { genericCMYKCyan: CGFloat; magenta: CGFloat; yellow: CGFloat; black: CGFloat; alpha: CGFloat }): Owned<CGColor>;
  /** @ntsSymbol CGColorCreateGenericGrayGamma2_2 */
  export function CGColor(labels: { genericGrayGamma2_2Gray: CGFloat; alpha: CGFloat }): Owned<CGColor>;
  /** @ntsSymbol CGColorCreateGenericGray */
  export function CGColor(labels: { gray: CGFloat; alpha: CGFloat }): Owned<CGColor>;
  /** @ntsSymbol CGColorCreateGenericRGB */
  export function CGColor(labels: { red: CGFloat; green: CGFloat; blue: CGFloat; alpha: CGFloat }): Owned<CGColor>;
  /** @ntsSymbol CGColorCreateSRGB */
  export function CGColor(labels: { srgbRed: CGFloat; green: CGFloat; blue: CGFloat; alpha: CGFloat }): Owned<CGColor>;

  export interface CGColorSpaceOwnMethods {
    /** @ntsSymbol CGColorSpaceGetBaseColorSpace */
    CGColorSpaceGetBaseColorSpace(this: CGColorSpace): CGColorSpace | null;
    /** @ntsGet CGColorSpaceGetBaseColorSpace */
    readonly baseColorSpace: CGColorSpace | null;
    /** @ntsSymbol CGColorSpaceCopyPropertyList */
    copyPropertyList(this: CGColorSpace): Ptr<unknown> | null;
    /** @ntsSymbol CGColorSpaceIsHDR */
    isHDR(this: CGColorSpace): boolean;
    /** @ntsSymbol CGColorSpaceIsWideGamutRGB */
    CGColorSpaceIsWideGamutRGB(this: CGColorSpace): boolean;
    /** @ntsGet CGColorSpaceIsWideGamutRGB */
    readonly isWideGamutRGB: boolean;
    /** @ntsSymbol CGColorSpaceGetModel */
    CGColorSpaceGetModel(this: CGColorSpace): CEnum<CGColorSpaceModel, Int32>;
    /** @ntsGet CGColorSpaceGetModel */
    readonly model: CEnum<CGColorSpaceModel, Int32>;
    /** @ntsSymbol CGColorSpaceGetNumberOfComponents */
    CGColorSpaceGetNumberOfComponents(this: CGColorSpace): UInt;
    /** @ntsGet CGColorSpaceGetNumberOfComponents */
    readonly numberOfComponents: UInt;
    /** @ntsSymbol CGColorSpaceSupportsOutput */
    CGColorSpaceSupportsOutput(this: CGColorSpace): boolean;
    /** @ntsGet CGColorSpaceSupportsOutput */
    readonly supportsOutput: boolean;
    // Not bound, each for the reason given:
    //   CGColorSpaceCopyICCData: a `const struct __CFData *`
    //   CGColorSpaceCopyICCProfile: deprecated in macOS 10.13
    //   CGColorSpaceCreateICCBased: `CGDataProvider`, a Core Foundation class this binding does not bind (`--class CGDataProvider`)
    //   CGColorSpaceCreateWithICCProfile: deprecated in macOS 10.13
    //   CGColorSpaceCreateWithName: a `const struct __CFString *`
    //   CGColorSpaceCreateWithPlatformColorSpace: deprecated in macOS 12.0
    //   CGColorSpaceCopyName: a `const struct __CFString *`
    //   CGColorSpaceGetTypeID: a `swift.type.property`, which is not bound yet
  }
  export type CGColorSpace = ObjcClass<"CGColorSpace"> & CGColorSpaceOwnMethods;
  /** @ntsSymbol CGColorSpaceCreateCalibratedGray */
  export function CGColorSpace(labels: { calibratedGrayWhitePoint: Ptr<CGFloat>; blackPoint: Ptr<CGFloat> | null; gamma: CGFloat }): Owned<CGColorSpace>;
  /** @ntsSymbol CGColorSpaceCreateCalibratedRGB */
  export function CGColorSpace(labels: { calibratedRGBWhitePoint: Ptr<CGFloat>; blackPoint: Ptr<CGFloat> | null; gamma: Ptr<CGFloat> | null; matrix: Ptr<CGFloat> | null }): Owned<CGColorSpace>;
  /** @ntsSymbol CGColorSpaceCreateWithICCData */
  export function CGColorSpace(labels: { iccData: Ptr<unknown> | null }): Owned<CGColorSpace>;
  /** @ntsSymbol CGColorSpaceCreateIndexed */
  export function CGColorSpace(labels: { indexedBaseSpace: CGColorSpace | null; last: UInt; colorTable: Ptr<UInt8> | null }): Owned<CGColorSpace>;
  /** @ntsSymbol CGColorSpaceCreateLab */
  export function CGColorSpace(labels: { labWhitePoint: Ptr<CGFloat>; blackPoint: Ptr<CGFloat> | null; range: Ptr<CGFloat> | null }): Owned<CGColorSpace>;
  /** @ntsSymbol CGColorSpaceCreatePattern */
  export function CGColorSpace(labels: { patternBaseSpace: CGColorSpace | null }): Owned<CGColorSpace>;
  /** @ntsSymbol CGColorSpaceCreateWithPropertyList */
  export function CGColorSpace(labels: { propertyListPlist: Ptr<unknown> }): Owned<CGColorSpace>;

  export interface CGContextOwnMethods {
    /** @ntsSymbol CGContextAddEllipseInRect */
    addEllipse(this: CGContext, labels: { in: ByValue<CGRect> | Fields<CGRect> }): void;
    /** @ntsSymbol CGContextAddRect */
    addRect(this: CGContext, rect: ByValue<CGRect> | Fields<CGRect>): void;
    /** @ntsSymbol CGBitmapContextGetAlphaInfo */
    CGBitmapContextGetAlphaInfo(this: CGContext): CEnum<CGImageAlphaInfo, UInt32>;
    /** @ntsGet CGBitmapContextGetAlphaInfo */
    readonly alphaInfo: CEnum<CGImageAlphaInfo, UInt32>;
    /** @ntsSymbol CGContextBeginPage */
    beginPage(this: CGContext, labels: { mediaBox: Ptr<CGRect> | null }): void;
    /** @ntsSymbol CGContextBeginPath */
    beginPath(this: CGContext): void;
    /** @ntsSymbol CGBitmapContextGetBitmapInfo */
    CGBitmapContextGetBitmapInfo(this: CGContext): CEnum<CGBitmapInfo | 0, UInt32>;
    /** @ntsGet CGBitmapContextGetBitmapInfo */
    readonly bitmapInfo: CEnum<CGBitmapInfo | 0, UInt32>;
    /** @ntsSymbol CGBitmapContextGetBitsPerComponent */
    CGBitmapContextGetBitsPerComponent(this: CGContext): UInt;
    /** @ntsGet CGBitmapContextGetBitsPerComponent */
    readonly bitsPerComponent: UInt;
    /** @ntsSymbol CGBitmapContextGetBitsPerPixel */
    CGBitmapContextGetBitsPerPixel(this: CGContext): UInt;
    /** @ntsGet CGBitmapContextGetBitsPerPixel */
    readonly bitsPerPixel: UInt;
    /** @ntsSymbol CGContextGetClipBoundingBox */
    CGContextGetClipBoundingBox(this: CGContext): ByValue<CGRect>;
    /** @ntsGet CGContextGetClipBoundingBox */
    readonly boundingBoxOfClipPath: ByValue<CGRect>;
    /** @ntsSymbol CGContextGetPathBoundingBox */
    CGContextGetPathBoundingBox(this: CGContext): ByValue<CGRect>;
    /** @ntsGet CGContextGetPathBoundingBox */
    readonly boundingBoxOfPath: ByValue<CGRect>;
    /** @ntsSymbol CGBitmapContextGetBytesPerRow */
    CGBitmapContextGetBytesPerRow(this: CGContext): UInt;
    /** @ntsGet CGBitmapContextGetBytesPerRow */
    readonly bytesPerRow: UInt;
    /** @ntsSymbol CGContextClearRect */
    clear(this: CGContext, rect: ByValue<CGRect> | Fields<CGRect>): void;
    /** @ntsSymbol CGContextClipToRect */
    clip(this: CGContext, labels: { to: ByValue<CGRect> | Fields<CGRect> }): void;
    /** @ntsSymbol CGPDFContextClose */
    closePDF(this: CGContext): void;
    /** @ntsSymbol CGContextClosePath */
    closePath(this: CGContext): void;
    /** @ntsSymbol CGBitmapContextGetColorSpace */
    CGBitmapContextGetColorSpace(this: CGContext): CGColorSpace | null;
    /** @ntsGet CGBitmapContextGetColorSpace */
    readonly colorSpace: CGColorSpace | null;
    /** @ntsSymbol CGContextConcatCTM */
    concatenate(this: CGContext, transform: ByValue<CGAffineTransform> | Fields<CGAffineTransform>): void;
    /** @ntsSymbol CGContextConvertPointToDeviceSpace */
    convertToDeviceSpace(this: CGContext, point: ByValue<CGPoint> | Fields<CGPoint>): ByValue<CGPoint>;
    /** @ntsSymbol CGContextConvertRectToDeviceSpace */
    convertToDeviceSpace(this: CGContext, rect: ByValue<CGRect> | Fields<CGRect>): ByValue<CGRect>;
    /** @ntsSymbol CGContextConvertSizeToDeviceSpace */
    convertToDeviceSpace(this: CGContext, size: ByValue<CGSize> | Fields<CGSize>): ByValue<CGSize>;
    /** @ntsSymbol CGContextConvertPointToUserSpace */
    convertToUserSpace(this: CGContext, point: ByValue<CGPoint> | Fields<CGPoint>): ByValue<CGPoint>;
    /** @ntsSymbol CGContextConvertRectToUserSpace */
    convertToUserSpace(this: CGContext, rect: ByValue<CGRect> | Fields<CGRect>): ByValue<CGRect>;
    /** @ntsSymbol CGContextConvertSizeToUserSpace */
    convertToUserSpace(this: CGContext, size: ByValue<CGSize> | Fields<CGSize>): ByValue<CGSize>;
    /** @ntsSymbol CGContextGetCTM */
    CGContextGetCTM(this: CGContext): ByValue<CGAffineTransform>;
    /** @ntsGet CGContextGetCTM */
    readonly ctm: ByValue<CGAffineTransform>;
    /** @ntsSymbol CGContextGetPathCurrentPoint */
    CGContextGetPathCurrentPoint(this: CGContext): ByValue<CGPoint>;
    /** @ntsGet CGContextGetPathCurrentPoint */
    readonly currentPointOfPath: ByValue<CGPoint>;
    /** @ntsSymbol CGBitmapContextGetData */
    CGBitmapContextGetData(this: CGContext): Ptr<unknown> | null;
    /** @ntsGet CGBitmapContextGetData */
    readonly data: Ptr<unknown> | null;
    /** @ntsSymbol CGContextDrawPath */
    drawPath(this: CGContext, labels: { using: CEnum<CGPathDrawingMode, Int32> }): void;
    /** @ntsSymbol CGPDFContextEndPage */
    endPDFPage(this: CGContext): void;
    /** @ntsSymbol CGContextEndPage */
    endPage(this: CGContext): void;
    /** @ntsSymbol CGContextEndTransparencyLayer */
    endTransparencyLayer(this: CGContext): void;
    /** @ntsSymbol CGContextFillRect */
    fill(this: CGContext, rect: ByValue<CGRect> | Fields<CGRect>): void;
    /** @ntsSymbol CGContextFillEllipseInRect */
    fillEllipse(this: CGContext, labels: { in: ByValue<CGRect> | Fields<CGRect> }): void;
    /** @ntsSymbol CGContextFlush */
    flush(this: CGContext): void;
    /** @ntsSymbol CGBitmapContextGetHeight */
    CGBitmapContextGetHeight(this: CGContext): UInt;
    /** @ntsGet CGBitmapContextGetHeight */
    readonly height: UInt;
    /** @ntsSymbol CGContextGetInterpolationQuality */
    CGContextGetInterpolationQuality(this: CGContext): CEnum<CGInterpolationQuality, Int32>;
    /** @ntsGet CGContextGetInterpolationQuality */
    readonly interpolationQuality: CEnum<CGInterpolationQuality, Int32>;
    /** @ntsSymbol CGContextIsPathEmpty */
    CGContextIsPathEmpty(this: CGContext): boolean;
    /** @ntsGet CGContextIsPathEmpty */
    readonly isPathEmpty: boolean;
    /** @ntsSymbol CGContextPathContainsPoint */
    pathContains(this: CGContext, point: ByValue<CGPoint> | Fields<CGPoint>, labels: { mode: CEnum<CGPathDrawingMode, Int32> }): boolean;
    /** @ntsSymbol CGContextReplacePathWithStrokedPath */
    replacePathWithStrokedPath(this: CGContext): void;
    /** @ntsSymbol CGContextResetClip */
    resetClip(this: CGContext): void;
    /** @ntsSymbol CGContextRestoreGState */
    restoreGState(this: CGContext): void;
    /** @ntsSymbol CGContextRotateCTM */
    rotate(this: CGContext, labels: { by: CGFloat }): void;
    /** @ntsSymbol CGContextSaveGState */
    saveGState(this: CGContext): void;
    /** @ntsSymbol CGContextScaleCTM */
    scaleBy(this: CGContext, labels: { x: CGFloat; y: CGFloat }): void;
    /** @ntsSymbol CGContextSetAllowsAntialiasing */
    setAllowsAntialiasing(this: CGContext, allowsAntialiasing: boolean): void;
    /** @ntsSymbol CGContextSetAllowsFontSmoothing */
    setAllowsFontSmoothing(this: CGContext, allowsFontSmoothing: boolean): void;
    /** @ntsSymbol CGContextSetAllowsFontSubpixelPositioning */
    setAllowsFontSubpixelPositioning(this: CGContext, allowsFontSubpixelPositioning: boolean): void;
    /** @ntsSymbol CGContextSetAllowsFontSubpixelQuantization */
    setAllowsFontSubpixelQuantization(this: CGContext, allowsFontSubpixelQuantization: boolean): void;
    /** @ntsSymbol CGContextSetAlpha */
    setAlpha(this: CGContext, alpha: CGFloat): void;
    /** @ntsSymbol CGContextSetBlendMode */
    setBlendMode(this: CGContext, mode: CEnum<CGBlendMode, Int32>): void;
    /** @ntsSymbol CGContextSetCharacterSpacing */
    setCharacterSpacing(this: CGContext, spacing: CGFloat): void;
    /** @ntsSymbol CGContextSetFillColor */
    setFillColor(this: CGContext, components: Ptr<CGFloat> | null): void;
    /** @ntsSymbol CGContextSetFillColorWithColor */
    setFillColor(this: CGContext, color: CGColor | null): void;
    /** @ntsSymbol CGContextSetCMYKFillColor */
    setFillColor(this: CGContext, labels: { cyan: CGFloat; magenta: CGFloat; yellow: CGFloat; black: CGFloat; alpha: CGFloat }): void;
    /** @ntsSymbol CGContextSetGrayFillColor */
    setFillColor(this: CGContext, labels: { gray: CGFloat; alpha: CGFloat }): void;
    /** @ntsSymbol CGContextSetRGBFillColor */
    setFillColor(this: CGContext, labels: { red: CGFloat; green: CGFloat; blue: CGFloat; alpha: CGFloat }): void;
    /** @ntsSymbol CGContextSetFillColorSpace */
    setFillColorSpace(this: CGContext, space: CGColorSpace | null): void;
    /** @ntsSymbol CGContextSetFlatness */
    setFlatness(this: CGContext, flatness: CGFloat): void;
    /** @ntsSymbol CGContextSetFontSize */
    setFontSize(this: CGContext, size: CGFloat): void;
    /** @ntsSymbol CGContextSetLineCap */
    setLineCap(this: CGContext, cap: CEnum<CGLineCap, Int32>): void;
    /** @ntsSymbol CGContextSetLineJoin */
    setLineJoin(this: CGContext, join: CEnum<CGLineJoin, Int32>): void;
    /** @ntsSymbol CGContextSetLineWidth */
    setLineWidth(this: CGContext, width: CGFloat): void;
    /** @ntsSymbol CGContextSetMiterLimit */
    setMiterLimit(this: CGContext, limit: CGFloat): void;
    /** @ntsSymbol CGContextSetPatternPhase */
    setPatternPhase(this: CGContext, phase: ByValue<CGSize> | Fields<CGSize>): void;
    /** @ntsSymbol CGContextSetRenderingIntent */
    setRenderingIntent(this: CGContext, intent: CEnum<CGColorRenderingIntent, Int32>): void;
    /** @ntsSymbol CGContextSetShadow */
    setShadow(this: CGContext, labels: { offset: ByValue<CGSize> | Fields<CGSize>; blur: CGFloat }): void;
    /** @ntsSymbol CGContextSetShadowWithColor */
    setShadow(this: CGContext, labels: { offset: ByValue<CGSize> | Fields<CGSize>; blur: CGFloat; color: CGColor | null }): void;
    /** @ntsSymbol CGContextSetShouldAntialias */
    setShouldAntialias(this: CGContext, shouldAntialias: boolean): void;
    /** @ntsSymbol CGContextSetShouldSmoothFonts */
    setShouldSmoothFonts(this: CGContext, shouldSmoothFonts: boolean): void;
    /** @ntsSymbol CGContextSetShouldSubpixelPositionFonts */
    setShouldSubpixelPositionFonts(this: CGContext, shouldSubpixelPositionFonts: boolean): void;
    /** @ntsSymbol CGContextSetShouldSubpixelQuantizeFonts */
    setShouldSubpixelQuantizeFonts(this: CGContext, shouldSubpixelQuantizeFonts: boolean): void;
    /** @ntsSymbol CGContextSetStrokeColor */
    setStrokeColor(this: CGContext, components: Ptr<CGFloat> | null): void;
    /** @ntsSymbol CGContextSetStrokeColorWithColor */
    setStrokeColor(this: CGContext, color: CGColor | null): void;
    /** @ntsSymbol CGContextSetCMYKStrokeColor */
    setStrokeColor(this: CGContext, labels: { cyan: CGFloat; magenta: CGFloat; yellow: CGFloat; black: CGFloat; alpha: CGFloat }): void;
    /** @ntsSymbol CGContextSetGrayStrokeColor */
    setStrokeColor(this: CGContext, labels: { gray: CGFloat; alpha: CGFloat }): void;
    /** @ntsSymbol CGContextSetRGBStrokeColor */
    setStrokeColor(this: CGContext, labels: { red: CGFloat; green: CGFloat; blue: CGFloat; alpha: CGFloat }): void;
    /** @ntsSymbol CGContextSetStrokeColorSpace */
    setStrokeColorSpace(this: CGContext, space: CGColorSpace | null): void;
    /** @ntsSymbol CGContextSetTextDrawingMode */
    setTextDrawingMode(this: CGContext, mode: CEnum<CGTextDrawingMode, Int32>): void;
    /** @ntsSymbol CGContextStrokeRect */
    stroke(this: CGContext, rect: ByValue<CGRect> | Fields<CGRect>): void;
    /** @ntsSymbol CGContextStrokeRectWithWidth */
    stroke(this: CGContext, rect: ByValue<CGRect> | Fields<CGRect>, labels: { width: CGFloat }): void;
    /** @ntsSymbol CGContextStrokeEllipseInRect */
    strokeEllipse(this: CGContext, labels: { in: ByValue<CGRect> | Fields<CGRect> }): void;
    /** @ntsSymbol CGContextStrokePath */
    strokePath(this: CGContext): void;
    /** @ntsSymbol CGContextSynchronize */
    synchronize(this: CGContext): void;
    /** @ntsSymbol CGContextGetTextMatrix */
    CGContextGetTextMatrix(this: CGContext): ByValue<CGAffineTransform>;
    /** @ntsGet CGContextGetTextMatrix */
    readonly textMatrix: ByValue<CGAffineTransform>;
    /** @ntsSymbol CGContextTranslateCTM */
    translateBy(this: CGContext, labels: { x: CGFloat; y: CGFloat }): void;
    /** @ntsSymbol CGContextGetUserSpaceToDeviceSpaceTransform */
    CGContextGetUserSpaceToDeviceSpaceTransform(this: CGContext): ByValue<CGAffineTransform>;
    /** @ntsGet CGContextGetUserSpaceToDeviceSpaceTransform */
    readonly userSpaceToDeviceSpaceTransform: ByValue<CGAffineTransform>;
    /** @ntsSymbol CGBitmapContextGetWidth */
    CGBitmapContextGetWidth(this: CGContext): UInt;
    /** @ntsGet CGBitmapContextGetWidth */
    readonly width: UInt;
    // Not bound, each for the reason given:
    //   CGPDFContextAddDestinationAtPoint: a `const struct __CFString *`
    //   CGPDFContextAddDocumentMetadata: a `const struct __CFData *`
    //   CGContextAddPath: a `const struct CGPath *`
    //   CGPDFContextBeginPage: a `const struct __CFDictionary *`
    //   CGContextBeginTransparencyLayer: a `const struct __CFDictionary *`
    //   CGContextBeginTransparencyLayerWithRect: a `const struct __CFDictionary *`
    //   CGContextClipToMask: `CGImage`, a Core Foundation class this binding does not bind (`--class CGImage`)
    //   CGContextDrawLinearGradient: `CGGradient`, a Core Foundation class this binding does not bind (`--class CGGradient`)
    //   CGContextDrawPDFPage: `CGPDFPage`, a Core Foundation class this binding does not bind (`--class CGPDFPage`)
    //   CGContextDrawRadialGradient: `CGGradient`, a Core Foundation class this binding does not bind (`--class CGGradient`)
    //   CGContextDrawShading: `CGShading`, a Core Foundation class this binding does not bind (`--class CGShading`)
    //   CGPDFContextCreateWithURL: a `const struct __CFURL *`
    //   CGPDFContextCreate: `CGDataConsumer`, a Core Foundation class this binding does not bind (`--class CGDataConsumer`)
    //   CGBitmapContextCreateWithData: a `void (*)(void * _Nullable, void * _Nullable)`
    //   CGBitmapContextCreateImage: `CGImage`, a Core Foundation class this binding does not bind (`--class CGImage`)
    //   CGContextCopyPath: a `const struct CGPath *`
    //   CGPDFContextSetDestinationForRect: a `const struct __CFString *`
    //   CGContextSetEDRTargetHeadroom: introduced in macOS 15.0
    //   CGContextSetFillPattern: `CGPattern`, a Core Foundation class this binding does not bind (`--class CGPattern`)
    //   CGContextSetFont: `CGFont`, a Core Foundation class this binding does not bind (`--class CGFont`)
    //   CGContextSetStrokePattern: `CGPattern`, a Core Foundation class this binding does not bind (`--class CGPattern`)
    //   CGPDFContextSetURLForRect: a `const struct __CFURL *`
    //   CGContextSynchronizeAttributes: introduced in macOS 26.0
    //   CGContextGetTypeID: a `swift.type.property`, which is not bound yet
  }
  export type CGContext = ObjcClass<"CGContext"> & CGContextOwnMethods;
  /** @ntsSymbol CGBitmapContextCreate */
  export function CGContext(labels: { data: Ptr<unknown> | null; width: UInt; height: UInt; bitsPerComponent: UInt; bytesPerRow: UInt; space: CGColorSpace | null; bitmapInfo: CEnum<CGBitmapInfo | 0, UInt32> }): Owned<CGContext>;
  /** @ntsSymbol CGColorSpaceCreateDeviceRGB */
  export function CGColorSpaceCreateDeviceRGB(): Owned<CGColorSpace>;
}
