/* Generated by tooling/chromium/bindgen/generate.py from Blink's IDL at Chromium b510e9d7cd3a2fbd78d0ddc42234103206c5f78d.
Do not edit; regenerate. */
#ifndef NTS_CHROMIUM_DOM_IDL_H_
#define NTS_CHROMIUM_DOM_IDL_H_
#include <stdbool.h>
#include <stdint.h>

#include "nts_string_view.h"

#ifdef __cplusplus
extern "C" {
#endif

/* A DOM exception a member reported: what the program throws, by
 * nts_dom_exception_take_message (dom_abi.h). */
typedef struct NtsDomException NtsDomException;
typedef struct NtsDomEventTarget NtsDomEventTarget;
typedef struct NtsDomNode NtsDomNode;
typedef struct NtsDomElement NtsDomElement;
typedef struct NtsDomCharacterData NtsDomCharacterData;
typedef struct NtsDomText NtsDomText;
typedef struct NtsDomDocument NtsDomDocument;
typedef struct NtsDomDocumentFragment NtsDomDocumentFragment;
typedef struct NtsDomHTMLElement NtsDomHTMLElement;
typedef struct NtsDomHTMLInputElement NtsDomHTMLInputElement;
typedef struct NtsDomHTMLButtonElement NtsDomHTMLButtonElement;
typedef struct NtsDomHTMLAnchorElement NtsDomHTMLAnchorElement;
typedef struct NtsDomEvent NtsDomEvent;
typedef struct NtsDomUIEvent NtsDomUIEvent;
typedef struct NtsDomMouseEvent NtsDomMouseEvent;
typedef struct NtsDomKeyboardEvent NtsDomKeyboardEvent;
typedef struct NtsDomDOMTokenList NtsDomDOMTokenList;
typedef struct NtsDomCSSStyleDeclaration NtsDomCSSStyleDeclaration;
typedef struct NtsDomComment NtsDomComment;
typedef struct NtsDomNodeList NtsDomNodeList;
typedef struct NtsDomHTMLCollection NtsDomHTMLCollection;
typedef struct NtsDomDOMRectReadOnly NtsDomDOMRectReadOnly;
typedef struct NtsDomDOMRect NtsDomDOMRect;

/* Every interface Blink's core component defines, for nts_dom_is: bound or
 * not, since `instanceof` may name any of them. Stable for one Chromium pin
 * and allowlist. */
enum NtsDomInterface {
  NTS_DOM_AbortController = 0,
  NTS_DOM_AbortSignal = 1,
  NTS_DOM_AbstractRange = 2,
  NTS_DOM_Animation = 3,
  NTS_DOM_AnimationEffect = 4,
  NTS_DOM_AnimationEvent = 5,
  NTS_DOM_AnimationPlaybackEvent = 6,
  NTS_DOM_AnimationTimeline = 7,
  NTS_DOM_AnimationTrigger = 8,
  NTS_DOM_Attr = 9,
  NTS_DOM_AudioTrack = 10,
  NTS_DOM_AudioTrackList = 11,
  NTS_DOM_AutofillEvent = 12,
  NTS_DOM_BackForwardCacheRestoration = 13,
  NTS_DOM_BarProp = 14,
  NTS_DOM_BeforeUnloadEvent = 15,
  NTS_DOM_Blob = 16,
  NTS_DOM_ByteLengthQueuingStrategy = 17,
  NTS_DOM_CDATASection = 18,
  NTS_DOM_CSPViolationReportBody = 19,
  NTS_DOM_CSSAnimation = 20,
  NTS_DOM_CSSApplyMixinRule = 21,
  NTS_DOM_CSSColorValue = 22,
  NTS_DOM_CSSConditionRule = 23,
  NTS_DOM_CSSContainerRule = 24,
  NTS_DOM_CSSContentsMixinRule = 25,
  NTS_DOM_CSSCounterStyleRule = 26,
  NTS_DOM_CSSCustomMediaRule = 27,
  NTS_DOM_CSSFontFaceRule = 28,
  NTS_DOM_CSSFontFeatureValuesMap = 29,
  NTS_DOM_CSSFontFeatureValuesRule = 30,
  NTS_DOM_CSSFontPaletteValuesRule = 31,
  NTS_DOM_CSSFunctionDeclarations = 32,
  NTS_DOM_CSSFunctionDescriptors = 33,
  NTS_DOM_CSSFunctionRule = 34,
  NTS_DOM_CSSGroupingRule = 35,
  NTS_DOM_CSSHSL = 36,
  NTS_DOM_CSSHWB = 37,
  NTS_DOM_CSSImageValue = 38,
  NTS_DOM_CSSImportRule = 39,
  NTS_DOM_CSSKeyframeRule = 40,
  NTS_DOM_CSSKeyframesRule = 41,
  NTS_DOM_CSSKeywordValue = 42,
  NTS_DOM_CSSLayerBlockRule = 43,
  NTS_DOM_CSSLayerStatementRule = 44,
  NTS_DOM_CSSLocationRule = 45,
  NTS_DOM_CSSMarginRule = 46,
  NTS_DOM_CSSMathClamp = 47,
  NTS_DOM_CSSMathInvert = 48,
  NTS_DOM_CSSMathMax = 49,
  NTS_DOM_CSSMathMin = 50,
  NTS_DOM_CSSMathNegate = 51,
  NTS_DOM_CSSMathProduct = 52,
  NTS_DOM_CSSMathRandom = 53,
  NTS_DOM_CSSMathSum = 54,
  NTS_DOM_CSSMathValue = 55,
  NTS_DOM_CSSMatrixComponent = 56,
  NTS_DOM_CSSMediaRule = 57,
  NTS_DOM_CSSMixinRule = 58,
  NTS_DOM_CSSNamespaceRule = 59,
  NTS_DOM_CSSNavigationRule = 60,
  NTS_DOM_CSSNestedDeclarations = 61,
  NTS_DOM_CSSNumericArray = 62,
  NTS_DOM_CSSNumericValue = 63,
  NTS_DOM_CSSPageRule = 64,
  NTS_DOM_CSSPerspective = 65,
  NTS_DOM_CSSPositionTryDescriptors = 66,
  NTS_DOM_CSSPositionTryRule = 67,
  NTS_DOM_CSSPositionValue = 68,
  NTS_DOM_CSSPrivateRule = 69,
  NTS_DOM_CSSPropertyRule = 70,
  NTS_DOM_CSSPseudoElement = 71,
  NTS_DOM_CSSRGB = 72,
  NTS_DOM_CSSResultRule = 73,
  NTS_DOM_CSSRotate = 74,
  NTS_DOM_CSSRule = 75,
  NTS_DOM_CSSRuleList = 76,
  NTS_DOM_CSSScale = 77,
  NTS_DOM_CSSScopeRule = 78,
  NTS_DOM_CSSSkew = 79,
  NTS_DOM_CSSSkewX = 80,
  NTS_DOM_CSSSkewY = 81,
  NTS_DOM_CSSStartingStyleRule = 82,
  NTS_DOM_CSSStyleDeclaration = 83,
  NTS_DOM_CSSStyleRule = 84,
  NTS_DOM_CSSStyleSheet = 85,
  NTS_DOM_CSSStyleValue = 86,
  NTS_DOM_CSSSupportsRule = 87,
  NTS_DOM_CSSTransformComponent = 88,
  NTS_DOM_CSSTransformValue = 89,
  NTS_DOM_CSSTransition = 90,
  NTS_DOM_CSSTranslate = 91,
  NTS_DOM_CSSUnitValue = 92,
  NTS_DOM_CSSUnparsedValue = 93,
  NTS_DOM_CSSVariableReferenceValue = 94,
  NTS_DOM_CSSViewTransitionRule = 95,
  NTS_DOM_CallbackFunctionTest = 96,
  NTS_DOM_CanvasPaintEvent = 97,
  NTS_DOM_CaretPosition = 98,
  NTS_DOM_CharacterBoundsUpdateEvent = 99,
  NTS_DOM_CharacterData = 100,
  NTS_DOM_ClipboardEvent = 101,
  NTS_DOM_CloseWatcher = 102,
  NTS_DOM_ColorPagePopupController = 103,
  NTS_DOM_CommandEvent = 104,
  NTS_DOM_Comment = 105,
  NTS_DOM_CompositionEvent = 106,
  NTS_DOM_ConnectionAllowlistViolationReportBody = 107,
  NTS_DOM_ContainerQueryList = 108,
  NTS_DOM_ContentVisibilityAutoStateChangeEvent = 109,
  NTS_DOM_CoopAccessViolationReportBody = 110,
  NTS_DOM_CountQueuingStrategy = 111,
  NTS_DOM_CrashReportContext = 112,
  NTS_DOM_CustomElementRegistry = 113,
  NTS_DOM_CustomEvent = 114,
  NTS_DOM_CustomStateSet = 115,
  NTS_DOM_DOMException = 116,
  NTS_DOM_DOMImplementation = 117,
  NTS_DOM_DOMMatrix = 118,
  NTS_DOM_DOMMatrixReadOnly = 119,
  NTS_DOM_DOMParser = 120,
  NTS_DOM_DOMPoint = 121,
  NTS_DOM_DOMPointReadOnly = 122,
  NTS_DOM_DOMQuad = 123,
  NTS_DOM_DOMRect = 124,
  NTS_DOM_DOMRectList = 125,
  NTS_DOM_DOMRectReadOnly = 126,
  NTS_DOM_DOMStringList = 127,
  NTS_DOM_DOMStringMap = 128,
  NTS_DOM_DOMTokenList = 129,
  NTS_DOM_DataTransfer = 130,
  NTS_DOM_DataTransferItem = 131,
  NTS_DOM_DataTransferItemList = 132,
  NTS_DOM_DedicatedWorkerGlobalScope = 133,
  NTS_DOM_DeprecationReportBody = 134,
  NTS_DOM_DevToolsHost = 135,
  NTS_DOM_DictionaryTest = 136,
  NTS_DOM_Directive = 137,
  NTS_DOM_Document = 138,
  NTS_DOM_DocumentFragment = 139,
  NTS_DOM_DocumentPolicyViolationReportBody = 140,
  NTS_DOM_DocumentTimeline = 141,
  NTS_DOM_DocumentType = 142,
  NTS_DOM_DragEvent = 143,
  NTS_DOM_EditContext = 144,
  NTS_DOM_Element = 145,
  NTS_DOM_ElementBehavior = 146,
  NTS_DOM_ElementImage = 147,
  NTS_DOM_ElementInternals = 148,
  NTS_DOM_ErrorEvent = 149,
  NTS_DOM_Event = 150,
  NTS_DOM_EventCounts = 151,
  NTS_DOM_EventTarget = 152,
  NTS_DOM_EventTrigger = 153,
  NTS_DOM_External = 154,
  NTS_DOM_Fence = 155,
  NTS_DOM_FencedFrameConfig = 156,
  NTS_DOM_FetchLaterResult = 157,
  NTS_DOM_File = 158,
  NTS_DOM_FileList = 159,
  NTS_DOM_FileReader = 160,
  NTS_DOM_FileReaderSync = 161,
  NTS_DOM_FocusEvent = 162,
  NTS_DOM_FontFace = 163,
  NTS_DOM_FontFaceSet = 164,
  NTS_DOM_FontFaceSetLoadEvent = 165,
  NTS_DOM_FormData = 166,
  NTS_DOM_FormDataEvent = 167,
  NTS_DOM_FragmentDirective = 168,
  NTS_DOM_GCObservation = 169,
  NTS_DOM_GarbageCollectedScriptWrappable = 170,
  NTS_DOM_Geolocation = 171,
  NTS_DOM_GeolocationCoordinates = 172,
  NTS_DOM_GeolocationPosition = 173,
  NTS_DOM_GeolocationPositionError = 174,
  NTS_DOM_HTMLAllCollection = 175,
  NTS_DOM_HTMLAnchorElement = 176,
  NTS_DOM_HTMLAreaElement = 177,
  NTS_DOM_HTMLAudioElement = 178,
  NTS_DOM_HTMLBRElement = 179,
  NTS_DOM_HTMLBaseElement = 180,
  NTS_DOM_HTMLBodyElement = 181,
  NTS_DOM_HTMLButtonElement = 182,
  NTS_DOM_HTMLCameraElement = 183,
  NTS_DOM_HTMLCanvasElement = 184,
  NTS_DOM_HTMLCollection = 185,
  NTS_DOM_HTMLCredentialElement = 186,
  NTS_DOM_HTMLDListElement = 187,
  NTS_DOM_HTMLDataElement = 188,
  NTS_DOM_HTMLDataListElement = 189,
  NTS_DOM_HTMLDetailsElement = 190,
  NTS_DOM_HTMLDialogElement = 191,
  NTS_DOM_HTMLDirectoryElement = 192,
  NTS_DOM_HTMLDivElement = 193,
  NTS_DOM_HTMLDocument = 194,
  NTS_DOM_HTMLElement = 195,
  NTS_DOM_HTMLEmbedElement = 196,
  NTS_DOM_HTMLFencedFrameElement = 197,
  NTS_DOM_HTMLFieldSetElement = 198,
  NTS_DOM_HTMLFontElement = 199,
  NTS_DOM_HTMLFormControlsCollection = 200,
  NTS_DOM_HTMLFormElement = 201,
  NTS_DOM_HTMLFrameElement = 202,
  NTS_DOM_HTMLFrameSetElement = 203,
  NTS_DOM_HTMLGeolocationElement = 204,
  NTS_DOM_HTMLHRElement = 205,
  NTS_DOM_HTMLHeadElement = 206,
  NTS_DOM_HTMLHeadingElement = 207,
  NTS_DOM_HTMLHtmlElement = 208,
  NTS_DOM_HTMLIFrameElement = 209,
  NTS_DOM_HTMLImageElement = 210,
  NTS_DOM_HTMLInputElement = 211,
  NTS_DOM_HTMLInstallElement = 212,
  NTS_DOM_HTMLLIElement = 213,
  NTS_DOM_HTMLLabelElement = 214,
  NTS_DOM_HTMLLegendElement = 215,
  NTS_DOM_HTMLLinkElement = 216,
  NTS_DOM_HTMLLoginElement = 217,
  NTS_DOM_HTMLMapElement = 218,
  NTS_DOM_HTMLMarqueeElement = 219,
  NTS_DOM_HTMLMediaElement = 220,
  NTS_DOM_HTMLMenuBarElement = 221,
  NTS_DOM_HTMLMenuElement = 222,
  NTS_DOM_HTMLMenuItemElement = 223,
  NTS_DOM_HTMLMenuListElement = 224,
  NTS_DOM_HTMLMetaElement = 225,
  NTS_DOM_HTMLMeterElement = 226,
  NTS_DOM_HTMLMicrophoneElement = 227,
  NTS_DOM_HTMLModElement = 228,
  NTS_DOM_HTMLOListElement = 229,
  NTS_DOM_HTMLObjectElement = 230,
  NTS_DOM_HTMLOptGroupElement = 231,
  NTS_DOM_HTMLOptionElement = 232,
  NTS_DOM_HTMLOptionsCollection = 233,
  NTS_DOM_HTMLOutputElement = 234,
  NTS_DOM_HTMLParagraphElement = 235,
  NTS_DOM_HTMLParamElement = 236,
  NTS_DOM_HTMLPictureElement = 237,
  NTS_DOM_HTMLPreElement = 238,
  NTS_DOM_HTMLProgressElement = 239,
  NTS_DOM_HTMLQuoteElement = 240,
  NTS_DOM_HTMLScriptElement = 241,
  NTS_DOM_HTMLSelectElement = 242,
  NTS_DOM_HTMLSelectedContentElement = 243,
  NTS_DOM_HTMLSlotElement = 244,
  NTS_DOM_HTMLSourceElement = 245,
  NTS_DOM_HTMLSpanElement = 246,
  NTS_DOM_HTMLStyleElement = 247,
  NTS_DOM_HTMLSubMenuElement = 248,
  NTS_DOM_HTMLSubmitButtonBehavior = 249,
  NTS_DOM_HTMLTableCaptionElement = 250,
  NTS_DOM_HTMLTableCellElement = 251,
  NTS_DOM_HTMLTableColElement = 252,
  NTS_DOM_HTMLTableElement = 253,
  NTS_DOM_HTMLTableRowElement = 254,
  NTS_DOM_HTMLTableSectionElement = 255,
  NTS_DOM_HTMLTemplateElement = 256,
  NTS_DOM_HTMLTextAreaElement = 257,
  NTS_DOM_HTMLTimeElement = 258,
  NTS_DOM_HTMLTitleElement = 259,
  NTS_DOM_HTMLTrackElement = 260,
  NTS_DOM_HTMLUListElement = 261,
  NTS_DOM_HTMLUnknownElement = 262,
  NTS_DOM_HTMLUserMediaElement = 263,
  NTS_DOM_HTMLVideoElement = 264,
  NTS_DOM_HashChangeEvent = 265,
  NTS_DOM_Headers = 266,
  NTS_DOM_Highlight = 267,
  NTS_DOM_HighlightRegistry = 268,
  NTS_DOM_History = 269,
  NTS_DOM_HitTestLayerRect = 270,
  NTS_DOM_HitTestLayerRectList = 271,
  NTS_DOM_IdleDeadline = 272,
  NTS_DOM_ImageBitmap = 273,
  NTS_DOM_ImageData = 274,
  NTS_DOM_InputDeviceCapabilities = 275,
  NTS_DOM_InputEvent = 276,
  NTS_DOM_InspectorOverlayHost = 277,
  NTS_DOM_InstallResultEvent = 278,
  NTS_DOM_IntegrityViolationReportBody = 279,
  NTS_DOM_InteractionContentfulPaint = 280,
  NTS_DOM_InterestEvent = 281,
  NTS_DOM_InternalRuntimeFlags = 282,
  NTS_DOM_InternalSettings = 283,
  NTS_DOM_InternalSettingsGenerated = 284,
  NTS_DOM_Internals = 285,
  NTS_DOM_InternalsUkmRecorder = 286,
  NTS_DOM_IntersectionObserver = 287,
  NTS_DOM_IntersectionObserverEntry = 288,
  NTS_DOM_InterventionReportBody = 289,
  NTS_DOM_IntrinsicSizes = 290,
  NTS_DOM_KeyboardEvent = 291,
  NTS_DOM_KeyframeEffect = 292,
  NTS_DOM_LargestContentfulPaint = 293,
  NTS_DOM_LayoutChild = 294,
  NTS_DOM_LayoutConstraints = 295,
  NTS_DOM_LayoutEdges = 296,
  NTS_DOM_LayoutFragment = 297,
  NTS_DOM_LayoutShift = 298,
  NTS_DOM_LayoutShiftAttribution = 299,
  NTS_DOM_LayoutWorkletGlobalScope = 300,
  NTS_DOM_Location = 301,
  NTS_DOM_MathMLAnchorElement = 302,
  NTS_DOM_MathMLElement = 303,
  NTS_DOM_MediaError = 304,
  NTS_DOM_MediaList = 305,
  NTS_DOM_MediaQueryList = 306,
  NTS_DOM_MediaQueryListEvent = 307,
  NTS_DOM_MemoryInfo = 308,
  NTS_DOM_MessageChannel = 309,
  NTS_DOM_MessageEvent = 310,
  NTS_DOM_MessagePort = 311,
  NTS_DOM_ModelContext = 312,
  NTS_DOM_Mojo = 313,
  NTS_DOM_MojoHandle = 314,
  NTS_DOM_MojoInterfaceInterceptor = 315,
  NTS_DOM_MojoInterfaceRequestEvent = 316,
  NTS_DOM_MojoWatcher = 317,
  NTS_DOM_MouseEvent = 318,
  NTS_DOM_MutationObserver = 319,
  NTS_DOM_MutationRecord = 320,
  NTS_DOM_NADCAttributeTest = 321,
  NTS_DOM_NamedNodeMap = 322,
  NTS_DOM_NavigateEvent = 323,
  NTS_DOM_Navigation = 324,
  NTS_DOM_NavigationActivation = 325,
  NTS_DOM_NavigationCurrentEntryChangeEvent = 326,
  NTS_DOM_NavigationDeferPageSwapController = 327,
  NTS_DOM_NavigationDestination = 328,
  NTS_DOM_NavigationHistoryEntry = 329,
  NTS_DOM_NavigationPrecommitController = 330,
  NTS_DOM_NavigationTransition = 331,
  NTS_DOM_Navigator = 332,
  NTS_DOM_NavigatorUAData = 333,
  NTS_DOM_Node = 334,
  NTS_DOM_NodeIterator = 335,
  NTS_DOM_NodeList = 336,
  NTS_DOM_NodeRange = 337,
  NTS_DOM_NotRestoredReasonDetails = 338,
  NTS_DOM_NotRestoredReasons = 339,
  NTS_DOM_Observable = 340,
  NTS_DOM_OffscreenCanvas = 341,
  NTS_DOM_OpaqueRange = 342,
  NTS_DOM_Origin = 343,
  NTS_DOM_OriginTrialsTest = 344,
  NTS_DOM_OverscrollEvent = 345,
  NTS_DOM_PagePopupController = 346,
  NTS_DOM_PageRevealEvent = 347,
  NTS_DOM_PageSwapEvent = 348,
  NTS_DOM_PageTransitionEvent = 349,
  NTS_DOM_Performance = 350,
  NTS_DOM_PerformanceContainerTiming = 351,
  NTS_DOM_PerformanceElementTiming = 352,
  NTS_DOM_PerformanceEntry = 353,
  NTS_DOM_PerformanceEventTiming = 354,
  NTS_DOM_PerformanceLongAnimationFrameTiming = 355,
  NTS_DOM_PerformanceLongTaskTiming = 356,
  NTS_DOM_PerformanceMark = 357,
  NTS_DOM_PerformanceMarkConditional = 358,
  NTS_DOM_PerformanceMeasure = 359,
  NTS_DOM_PerformanceMeasureConditional = 360,
  NTS_DOM_PerformanceNavigation = 361,
  NTS_DOM_PerformanceNavigationTiming = 362,
  NTS_DOM_PerformanceObserver = 363,
  NTS_DOM_PerformanceObserverEntryList = 364,
  NTS_DOM_PerformancePaintTiming = 365,
  NTS_DOM_PerformanceResourceTiming = 366,
  NTS_DOM_PerformanceScriptTiming = 367,
  NTS_DOM_PerformanceScrollTiming = 368,
  NTS_DOM_PerformanceServerTiming = 369,
  NTS_DOM_PerformanceSoftNavigation = 370,
  NTS_DOM_PerformanceTiming = 371,
  NTS_DOM_PerformanceTimingConfidence = 372,
  NTS_DOM_PermissionsPolicy = 373,
  NTS_DOM_PermissionsPolicyViolationReportBody = 374,
  NTS_DOM_PointerEvent = 375,
  NTS_DOM_PopStateEvent = 376,
  NTS_DOM_PreconnectData = 377,
  NTS_DOM_PreferenceManager = 378,
  NTS_DOM_PreferenceObject = 379,
  NTS_DOM_PreloadData = 380,
  NTS_DOM_ProcessingInstruction = 381,
  NTS_DOM_Profiler = 382,
  NTS_DOM_ProgressEvent = 383,
  NTS_DOM_PromiseRejectionEvent = 384,
  NTS_DOM_QuotaExceededError = 385,
  NTS_DOM_RadioNodeList = 386,
  NTS_DOM_Range = 387,
  NTS_DOM_ReadableByteStreamController = 388,
  NTS_DOM_ReadableStream = 389,
  NTS_DOM_ReadableStreamBYOBReader = 390,
  NTS_DOM_ReadableStreamBYOBRequest = 391,
  NTS_DOM_ReadableStreamDefaultController = 392,
  NTS_DOM_ReadableStreamDefaultReader = 393,
  NTS_DOM_RecordTest = 394,
  NTS_DOM_Report = 395,
  NTS_DOM_ReportBody = 396,
  NTS_DOM_ReportingObserver = 397,
  NTS_DOM_Request = 398,
  NTS_DOM_ResizeObserver = 399,
  NTS_DOM_ResizeObserverEntry = 400,
  NTS_DOM_ResizeObserverSize = 401,
  NTS_DOM_ResourceProgressEvent = 402,
  NTS_DOM_Response = 403,
  NTS_DOM_SVGAElement = 404,
  NTS_DOM_SVGAngle = 405,
  NTS_DOM_SVGAnimateElement = 406,
  NTS_DOM_SVGAnimateMotionElement = 407,
  NTS_DOM_SVGAnimateTransformElement = 408,
  NTS_DOM_SVGAnimatedAngle = 409,
  NTS_DOM_SVGAnimatedBoolean = 410,
  NTS_DOM_SVGAnimatedEnumeration = 411,
  NTS_DOM_SVGAnimatedInteger = 412,
  NTS_DOM_SVGAnimatedLength = 413,
  NTS_DOM_SVGAnimatedLengthList = 414,
  NTS_DOM_SVGAnimatedNumber = 415,
  NTS_DOM_SVGAnimatedNumberList = 416,
  NTS_DOM_SVGAnimatedPreserveAspectRatio = 417,
  NTS_DOM_SVGAnimatedRect = 418,
  NTS_DOM_SVGAnimatedString = 419,
  NTS_DOM_SVGAnimatedTransformList = 420,
  NTS_DOM_SVGAnimationElement = 421,
  NTS_DOM_SVGCircleElement = 422,
  NTS_DOM_SVGClipPathElement = 423,
  NTS_DOM_SVGComponentTransferFunctionElement = 424,
  NTS_DOM_SVGDefsElement = 425,
  NTS_DOM_SVGDescElement = 426,
  NTS_DOM_SVGElement = 427,
  NTS_DOM_SVGEllipseElement = 428,
  NTS_DOM_SVGFEBlendElement = 429,
  NTS_DOM_SVGFEColorMatrixElement = 430,
  NTS_DOM_SVGFEComponentTransferElement = 431,
  NTS_DOM_SVGFECompositeElement = 432,
  NTS_DOM_SVGFEConvolveMatrixElement = 433,
  NTS_DOM_SVGFEDiffuseLightingElement = 434,
  NTS_DOM_SVGFEDisplacementMapElement = 435,
  NTS_DOM_SVGFEDistantLightElement = 436,
  NTS_DOM_SVGFEDropShadowElement = 437,
  NTS_DOM_SVGFEFloodElement = 438,
  NTS_DOM_SVGFEFuncAElement = 439,
  NTS_DOM_SVGFEFuncBElement = 440,
  NTS_DOM_SVGFEFuncGElement = 441,
  NTS_DOM_SVGFEFuncRElement = 442,
  NTS_DOM_SVGFEGaussianBlurElement = 443,
  NTS_DOM_SVGFEImageElement = 444,
  NTS_DOM_SVGFEMergeElement = 445,
  NTS_DOM_SVGFEMergeNodeElement = 446,
  NTS_DOM_SVGFEMorphologyElement = 447,
  NTS_DOM_SVGFEOffsetElement = 448,
  NTS_DOM_SVGFEPointLightElement = 449,
  NTS_DOM_SVGFESpecularLightingElement = 450,
  NTS_DOM_SVGFESpotLightElement = 451,
  NTS_DOM_SVGFETileElement = 452,
  NTS_DOM_SVGFETurbulenceElement = 453,
  NTS_DOM_SVGFilterElement = 454,
  NTS_DOM_SVGForeignObjectElement = 455,
  NTS_DOM_SVGGElement = 456,
  NTS_DOM_SVGGeometryElement = 457,
  NTS_DOM_SVGGradientElement = 458,
  NTS_DOM_SVGGraphicsElement = 459,
  NTS_DOM_SVGImageElement = 460,
  NTS_DOM_SVGLength = 461,
  NTS_DOM_SVGLengthList = 462,
  NTS_DOM_SVGLineElement = 463,
  NTS_DOM_SVGLinearGradientElement = 464,
  NTS_DOM_SVGMPathElement = 465,
  NTS_DOM_SVGMarkerElement = 466,
  NTS_DOM_SVGMaskElement = 467,
  NTS_DOM_SVGMatrix = 468,
  NTS_DOM_SVGMetadataElement = 469,
  NTS_DOM_SVGNumber = 470,
  NTS_DOM_SVGNumberList = 471,
  NTS_DOM_SVGPathElement = 472,
  NTS_DOM_SVGPatternElement = 473,
  NTS_DOM_SVGPoint = 474,
  NTS_DOM_SVGPointList = 475,
  NTS_DOM_SVGPolygonElement = 476,
  NTS_DOM_SVGPolylineElement = 477,
  NTS_DOM_SVGPreserveAspectRatio = 478,
  NTS_DOM_SVGRadialGradientElement = 479,
  NTS_DOM_SVGRect = 480,
  NTS_DOM_SVGRectElement = 481,
  NTS_DOM_SVGSVGElement = 482,
  NTS_DOM_SVGScriptElement = 483,
  NTS_DOM_SVGSetElement = 484,
  NTS_DOM_SVGStopElement = 485,
  NTS_DOM_SVGStringList = 486,
  NTS_DOM_SVGStyleElement = 487,
  NTS_DOM_SVGSwitchElement = 488,
  NTS_DOM_SVGSymbolElement = 489,
  NTS_DOM_SVGTSpanElement = 490,
  NTS_DOM_SVGTextContentElement = 491,
  NTS_DOM_SVGTextElement = 492,
  NTS_DOM_SVGTextPathElement = 493,
  NTS_DOM_SVGTextPositioningElement = 494,
  NTS_DOM_SVGTitleElement = 495,
  NTS_DOM_SVGTransform = 496,
  NTS_DOM_SVGTransformList = 497,
  NTS_DOM_SVGUnitTypes = 498,
  NTS_DOM_SVGUseElement = 499,
  NTS_DOM_SVGViewElement = 500,
  NTS_DOM_Sanitizer = 501,
  NTS_DOM_Scheduler = 502,
  NTS_DOM_Scheduling = 503,
  NTS_DOM_Screen = 504,
  NTS_DOM_ScrollTimeline = 505,
  NTS_DOM_SecurityPolicyViolationEvent = 506,
  NTS_DOM_Selection = 507,
  NTS_DOM_SelectorDirective = 508,
  NTS_DOM_SequenceTest = 509,
  NTS_DOM_ShadowRealmGlobalScope = 510,
  NTS_DOM_ShadowRoot = 511,
  NTS_DOM_SharedWorker = 512,
  NTS_DOM_SharedWorkerGlobalScope = 513,
  NTS_DOM_SnapEvent = 514,
  NTS_DOM_SpeculationData = 515,
  NTS_DOM_SpeculationNavigationData = 516,
  NTS_DOM_StaticRange = 517,
  NTS_DOM_StaticSelection = 518,
  NTS_DOM_StyleMedia = 519,
  NTS_DOM_StylePropertyMap = 520,
  NTS_DOM_StylePropertyMapReadOnly = 521,
  NTS_DOM_StyleSheet = 522,
  NTS_DOM_StyleSheetList = 523,
  NTS_DOM_SubmitEvent = 524,
  NTS_DOM_Subscriber = 525,
  NTS_DOM_TaskAttributionTiming = 526,
  NTS_DOM_TaskController = 527,
  NTS_DOM_TaskPriorityChangeEvent = 528,
  NTS_DOM_TaskSignal = 529,
  NTS_DOM_TestReportBody = 530,
  NTS_DOM_Text = 531,
  NTS_DOM_TextCluster = 532,
  NTS_DOM_TextDirective = 533,
  NTS_DOM_TextEvent = 534,
  NTS_DOM_TextFormat = 535,
  NTS_DOM_TextFormatUpdateEvent = 536,
  NTS_DOM_TextMetrics = 537,
  NTS_DOM_TextTrack = 538,
  NTS_DOM_TextTrackCue = 539,
  NTS_DOM_TextTrackCueList = 540,
  NTS_DOM_TextTrackList = 541,
  NTS_DOM_TextUpdateEvent = 542,
  NTS_DOM_TimeRanges = 543,
  NTS_DOM_TimelineTrigger = 544,
  NTS_DOM_TimelineTriggerRange = 545,
  NTS_DOM_TimelineTriggerRangeList = 546,
  NTS_DOM_ToggleEvent = 547,
  NTS_DOM_Touch = 548,
  NTS_DOM_TouchEvent = 549,
  NTS_DOM_TouchList = 550,
  NTS_DOM_TrackEvent = 551,
  NTS_DOM_TransformStream = 552,
  NTS_DOM_TransformStreamDefaultController = 553,
  NTS_DOM_TransitionEvent = 554,
  NTS_DOM_TreeWalker = 555,
  NTS_DOM_TrustedHTML = 556,
  NTS_DOM_TrustedParserOptions = 557,
  NTS_DOM_TrustedScript = 558,
  NTS_DOM_TrustedScriptURL = 559,
  NTS_DOM_TrustedTypePolicy = 560,
  NTS_DOM_TrustedTypePolicyFactory = 561,
  NTS_DOM_TypeConversions = 562,
  NTS_DOM_UIEvent = 563,
  NTS_DOM_URL = 564,
  NTS_DOM_URLPattern = 565,
  NTS_DOM_URLSearchParams = 566,
  NTS_DOM_UnionTypesTest = 567,
  NTS_DOM_UserActivation = 568,
  NTS_DOM_VTTCue = 569,
  NTS_DOM_VTTRegion = 570,
  NTS_DOM_ValidityState = 571,
  NTS_DOM_VideoTrack = 572,
  NTS_DOM_VideoTrackList = 573,
  NTS_DOM_ViewTimeline = 574,
  NTS_DOM_ViewTransition = 575,
  NTS_DOM_ViewTransitionTypeSet = 576,
  NTS_DOM_Viewport = 577,
  NTS_DOM_VisibilityStateEntry = 578,
  NTS_DOM_VisualViewport = 579,
  NTS_DOM_WebMCPEvent = 580,
  NTS_DOM_WheelEvent = 581,
  NTS_DOM_Window = 582,
  NTS_DOM_WindowProperties = 583,
  NTS_DOM_Worker = 584,
  NTS_DOM_WorkerGlobalScope = 585,
  NTS_DOM_WorkerInternals = 586,
  NTS_DOM_WorkerLocation = 587,
  NTS_DOM_WorkerNavigator = 588,
  NTS_DOM_Worklet = 589,
  NTS_DOM_WorkletGlobalScope = 590,
  NTS_DOM_WritableStream = 591,
  NTS_DOM_WritableStreamDefaultController = 592,
  NTS_DOM_WritableStreamDefaultWriter = 593,
  NTS_DOM_XMLDocument = 594,
  NTS_DOM_XMLHttpRequest = 595,
  NTS_DOM_XMLHttpRequestEventTarget = 596,
  NTS_DOM_XMLHttpRequestUpload = 597,
  NTS_DOM_XMLSerializer = 598,
  NTS_DOM_XPathEvaluator = 599,
  NTS_DOM_XPathExpression = 600,
  NTS_DOM_XPathResult = 601,
  NTS_DOM_XSLTProcessor = 602,
};
/* `object instanceof <interface>`, as V8's binding answers it: whether the
 * object's wrapper type is the interface's or derives from it. NULL is no. */
bool nts_dom_is(const void* object, uint32_t interface_id);

bool nts_dom_EventTarget_dispatchEvent(NtsDomEventTarget* self, NtsDomEvent* event, NtsDomException** error);
NtsDomNode* nts_dom_as_Node(NtsDomEventTarget* target);
double nts_dom_Node_get_nodeType(NtsDomNode* self);
const NtsStringView* nts_dom_Node_get_nodeName(NtsDomNode* self);
const NtsStringView* nts_dom_Node_get_baseURI(NtsDomNode* self);
bool nts_dom_Node_get_isConnected(NtsDomNode* self);
NtsDomDocument* nts_dom_Node_get_ownerDocument(NtsDomNode* self);
NtsDomNode* nts_dom_Node_get_parentNode(NtsDomNode* self);
NtsDomElement* nts_dom_Node_get_parentElement(NtsDomNode* self);
NtsDomNodeList* nts_dom_Node_get_childNodes(NtsDomNode* self);
NtsDomNode* nts_dom_Node_get_firstChild(NtsDomNode* self);
NtsDomNode* nts_dom_Node_get_lastChild(NtsDomNode* self);
NtsDomNode* nts_dom_Node_get_previousSibling(NtsDomNode* self);
NtsDomNode* nts_dom_Node_get_nextSibling(NtsDomNode* self);
const NtsStringView* nts_dom_Node_get_nodeValue(NtsDomNode* self);
void nts_dom_Node_set_nodeValue(NtsDomNode* self, const NtsBorrowedString* value, NtsDomException** error);
const NtsStringView* nts_dom_Node_get_textContent(NtsDomNode* self);
void nts_dom_Node_set_textContent(NtsDomNode* self, const NtsBorrowedString* value, NtsDomException** error);
NtsDomNode* nts_dom_Node_appendChild(NtsDomNode* self, NtsDomNode* node, NtsDomException** error);
NtsDomNode* nts_dom_Node_cloneNode_1(NtsDomNode* self, bool deep, NtsDomException** error);
NtsDomNode* nts_dom_Node_cloneNode_0(NtsDomNode* self, NtsDomException** error);
double nts_dom_Node_compareDocumentPosition(NtsDomNode* self, NtsDomNode* other);
bool nts_dom_Node_contains(NtsDomNode* self, NtsDomNode* other);
bool nts_dom_Node_hasChildNodes(NtsDomNode* self);
NtsDomNode* nts_dom_Node_insertBefore(NtsDomNode* self, NtsDomNode* node, NtsDomNode* child, NtsDomException** error);
bool nts_dom_Node_isDefaultNamespace(NtsDomNode* self, const NtsBorrowedString* namespaceURI);
bool nts_dom_Node_isEqualNode(NtsDomNode* self, NtsDomNode* otherNode);
bool nts_dom_Node_isSameNode(NtsDomNode* self, NtsDomNode* otherNode);
const NtsStringView* nts_dom_Node_lookupNamespaceURI(NtsDomNode* self, const NtsBorrowedString* prefix);
const NtsStringView* nts_dom_Node_lookupPrefix(NtsDomNode* self, const NtsBorrowedString* namespaceURI);
void nts_dom_Node_normalize(NtsDomNode* self);
NtsDomNode* nts_dom_Node_removeChild(NtsDomNode* self, NtsDomNode* child, NtsDomException** error);
NtsDomNode* nts_dom_Node_replaceChild(NtsDomNode* self, NtsDomNode* node, NtsDomNode* child, NtsDomException** error);
NtsDomElement* nts_dom_as_Element(NtsDomNode* node);
const NtsStringView* nts_dom_Element_get_namespaceURI(NtsDomElement* self);
const NtsStringView* nts_dom_Element_get_prefix(NtsDomElement* self);
const NtsStringView* nts_dom_Element_get_localName(NtsDomElement* self);
const NtsStringView* nts_dom_Element_get_tagName(NtsDomElement* self);
const NtsStringView* nts_dom_Element_get_id(NtsDomElement* self);
void nts_dom_Element_set_id(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_className(NtsDomElement* self);
void nts_dom_Element_set_className(NtsDomElement* self, const NtsBorrowedString* value);
NtsDomDOMTokenList* nts_dom_Element_get_classList(NtsDomElement* self);
const NtsStringView* nts_dom_Element_get_slot(NtsDomElement* self);
void nts_dom_Element_set_slot(NtsDomElement* self, const NtsBorrowedString* value);
NtsDomDOMTokenList* nts_dom_Element_get_part(NtsDomElement* self);
const NtsStringView* nts_dom_Element_get_innerHTML(NtsDomElement* self);
void nts_dom_Element_set_innerHTML(NtsDomElement* self, const NtsBorrowedString* value, NtsDomException** error);
const NtsStringView* nts_dom_Element_get_outerHTML(NtsDomElement* self);
void nts_dom_Element_set_outerHTML(NtsDomElement* self, const NtsBorrowedString* value, NtsDomException** error);
double nts_dom_Element_get_scrollTop(NtsDomElement* self);
void nts_dom_Element_set_scrollTop(NtsDomElement* self, double value);
double nts_dom_Element_get_scrollLeft(NtsDomElement* self);
void nts_dom_Element_set_scrollLeft(NtsDomElement* self, double value);
double nts_dom_Element_get_scrollWidth(NtsDomElement* self);
double nts_dom_Element_get_scrollHeight(NtsDomElement* self);
double nts_dom_Element_get_clientTop(NtsDomElement* self);
double nts_dom_Element_get_clientLeft(NtsDomElement* self);
double nts_dom_Element_get_clientWidth(NtsDomElement* self);
double nts_dom_Element_get_clientHeight(NtsDomElement* self);
const NtsStringView* nts_dom_Element_get_elementTiming(NtsDomElement* self);
void nts_dom_Element_set_elementTiming(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_role(NtsDomElement* self);
void nts_dom_Element_set_role(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaAtomic(NtsDomElement* self);
void nts_dom_Element_set_ariaAtomic(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaAutoComplete(NtsDomElement* self);
void nts_dom_Element_set_ariaAutoComplete(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaBusy(NtsDomElement* self);
void nts_dom_Element_set_ariaBusy(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaBrailleLabel(NtsDomElement* self);
void nts_dom_Element_set_ariaBrailleLabel(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaBrailleRoleDescription(NtsDomElement* self);
void nts_dom_Element_set_ariaBrailleRoleDescription(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaChecked(NtsDomElement* self);
void nts_dom_Element_set_ariaChecked(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaColCount(NtsDomElement* self);
void nts_dom_Element_set_ariaColCount(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaColIndex(NtsDomElement* self);
void nts_dom_Element_set_ariaColIndex(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaColSpan(NtsDomElement* self);
void nts_dom_Element_set_ariaColSpan(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaCurrent(NtsDomElement* self);
void nts_dom_Element_set_ariaCurrent(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaDescription(NtsDomElement* self);
void nts_dom_Element_set_ariaDescription(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaDisabled(NtsDomElement* self);
void nts_dom_Element_set_ariaDisabled(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaExpanded(NtsDomElement* self);
void nts_dom_Element_set_ariaExpanded(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaHasPopup(NtsDomElement* self);
void nts_dom_Element_set_ariaHasPopup(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaHidden(NtsDomElement* self);
void nts_dom_Element_set_ariaHidden(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaInvalid(NtsDomElement* self);
void nts_dom_Element_set_ariaInvalid(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaKeyShortcuts(NtsDomElement* self);
void nts_dom_Element_set_ariaKeyShortcuts(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaLabel(NtsDomElement* self);
void nts_dom_Element_set_ariaLabel(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaLevel(NtsDomElement* self);
void nts_dom_Element_set_ariaLevel(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaLive(NtsDomElement* self);
void nts_dom_Element_set_ariaLive(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaModal(NtsDomElement* self);
void nts_dom_Element_set_ariaModal(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaMultiLine(NtsDomElement* self);
void nts_dom_Element_set_ariaMultiLine(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaMultiSelectable(NtsDomElement* self);
void nts_dom_Element_set_ariaMultiSelectable(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaOrientation(NtsDomElement* self);
void nts_dom_Element_set_ariaOrientation(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaPlaceholder(NtsDomElement* self);
void nts_dom_Element_set_ariaPlaceholder(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaPosInSet(NtsDomElement* self);
void nts_dom_Element_set_ariaPosInSet(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaPressed(NtsDomElement* self);
void nts_dom_Element_set_ariaPressed(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaReadOnly(NtsDomElement* self);
void nts_dom_Element_set_ariaReadOnly(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaRelevant(NtsDomElement* self);
void nts_dom_Element_set_ariaRelevant(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaRequired(NtsDomElement* self);
void nts_dom_Element_set_ariaRequired(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaRoleDescription(NtsDomElement* self);
void nts_dom_Element_set_ariaRoleDescription(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaRowCount(NtsDomElement* self);
void nts_dom_Element_set_ariaRowCount(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaRowIndex(NtsDomElement* self);
void nts_dom_Element_set_ariaRowIndex(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaRowSpan(NtsDomElement* self);
void nts_dom_Element_set_ariaRowSpan(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaSelected(NtsDomElement* self);
void nts_dom_Element_set_ariaSelected(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaSetSize(NtsDomElement* self);
void nts_dom_Element_set_ariaSetSize(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaSort(NtsDomElement* self);
void nts_dom_Element_set_ariaSort(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaValueMax(NtsDomElement* self);
void nts_dom_Element_set_ariaValueMax(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaValueMin(NtsDomElement* self);
void nts_dom_Element_set_ariaValueMin(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaValueNow(NtsDomElement* self);
void nts_dom_Element_set_ariaValueNow(NtsDomElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Element_get_ariaValueText(NtsDomElement* self);
void nts_dom_Element_set_ariaValueText(NtsDomElement* self, const NtsBorrowedString* value);
NtsDomElement* nts_dom_Element_get_ariaActiveDescendantElement(NtsDomElement* self);
void nts_dom_Element_set_ariaActiveDescendantElement(NtsDomElement* self, NtsDomElement* value);
NtsDomHTMLCollection* nts_dom_Element_get_children(NtsDomElement* self);
NtsDomElement* nts_dom_Element_get_firstElementChild(NtsDomElement* self);
NtsDomElement* nts_dom_Element_get_lastElementChild(NtsDomElement* self);
double nts_dom_Element_get_childElementCount(NtsDomElement* self);
NtsDomElement* nts_dom_Element_get_previousElementSibling(NtsDomElement* self);
NtsDomElement* nts_dom_Element_get_nextElementSibling(NtsDomElement* self);
NtsDomElement* nts_dom_Element_closest(NtsDomElement* self, const NtsBorrowedString* selectors, NtsDomException** error);
const NtsStringView* nts_dom_Element_getAttribute(NtsDomElement* self, const NtsBorrowedString* name);
const NtsStringView* nts_dom_Element_getAttributeNS(NtsDomElement* self, const NtsBorrowedString* namespaceURI, const NtsBorrowedString* localName);
NtsDomDOMRect* nts_dom_Element_getBoundingClientRect(NtsDomElement* self);
NtsDomHTMLCollection* nts_dom_Element_getElementsByClassName(NtsDomElement* self, const NtsBorrowedString* classNames);
NtsDomHTMLCollection* nts_dom_Element_getElementsByTagName(NtsDomElement* self, const NtsBorrowedString* localName);
NtsDomHTMLCollection* nts_dom_Element_getElementsByTagNameNS(NtsDomElement* self, const NtsBorrowedString* namespaceURI, const NtsBorrowedString* localName);
bool nts_dom_Element_hasAttribute(NtsDomElement* self, const NtsBorrowedString* name);
bool nts_dom_Element_hasAttributeNS(NtsDomElement* self, const NtsBorrowedString* namespaceURI, const NtsBorrowedString* localName);
bool nts_dom_Element_hasAttributes(NtsDomElement* self);
bool nts_dom_Element_hasPointerCapture(NtsDomElement* self, double pointerId);
NtsDomElement* nts_dom_Element_insertAdjacentElement(NtsDomElement* self, const NtsBorrowedString* where, NtsDomElement* element, NtsDomException** error);
void nts_dom_Element_insertAdjacentHTML(NtsDomElement* self, const NtsBorrowedString* position, const NtsBorrowedString* text, NtsDomException** error);
void nts_dom_Element_insertAdjacentText(NtsDomElement* self, const NtsBorrowedString* where, const NtsBorrowedString* data, NtsDomException** error);
bool nts_dom_Element_matches(NtsDomElement* self, const NtsBorrowedString* selectors, NtsDomException** error);
void nts_dom_Element_moveBefore(NtsDomElement* self, NtsDomNode* node, NtsDomNode* child, NtsDomException** error);
NtsDomElement* nts_dom_Element_querySelector(NtsDomElement* self, const NtsBorrowedString* selectors, NtsDomException** error);
NtsDomNodeList* nts_dom_Element_querySelectorAll(NtsDomElement* self, const NtsBorrowedString* selectors, NtsDomException** error);
void nts_dom_Element_releasePointerCapture(NtsDomElement* self, double pointerId, NtsDomException** error);
void nts_dom_Element_remove(NtsDomElement* self, NtsDomException** error);
void nts_dom_Element_removeAttribute(NtsDomElement* self, const NtsBorrowedString* name);
void nts_dom_Element_removeAttributeNS(NtsDomElement* self, const NtsBorrowedString* namespaceURI, const NtsBorrowedString* localName);
void nts_dom_Element_scrollIntoViewIfNeeded_1(NtsDomElement* self, bool centerIfNeeded);
void nts_dom_Element_scrollIntoViewIfNeeded_0(NtsDomElement* self);
void nts_dom_Element_setAttribute(NtsDomElement* self, const NtsBorrowedString* name, const NtsBorrowedString* value, NtsDomException** error);
void nts_dom_Element_setAttributeNS(NtsDomElement* self, const NtsBorrowedString* namespaceURI, const NtsBorrowedString* name, const NtsBorrowedString* value, NtsDomException** error);
void nts_dom_Element_setHTMLUnsafe(NtsDomElement* self, const NtsBorrowedString* html, NtsDomException** error);
void nts_dom_Element_setPointerCapture(NtsDomElement* self, double pointerId, NtsDomException** error);
bool nts_dom_Element_toggleAttribute_2(NtsDomElement* self, const NtsBorrowedString* qualifiedName, bool force, NtsDomException** error);
bool nts_dom_Element_toggleAttribute_1(NtsDomElement* self, const NtsBorrowedString* qualifiedName, NtsDomException** error);
bool nts_dom_Element_webkitMatchesSelector(NtsDomElement* self, const NtsBorrowedString* selectors, NtsDomException** error);
NtsDomCharacterData* nts_dom_as_CharacterData(NtsDomNode* node);
const NtsStringView* nts_dom_CharacterData_get_data(NtsDomCharacterData* self);
void nts_dom_CharacterData_set_data(NtsDomCharacterData* self, const NtsBorrowedString* value);
double nts_dom_CharacterData_get_length(NtsDomCharacterData* self);
NtsDomElement* nts_dom_CharacterData_get_previousElementSibling(NtsDomCharacterData* self);
NtsDomElement* nts_dom_CharacterData_get_nextElementSibling(NtsDomCharacterData* self);
void nts_dom_CharacterData_appendData(NtsDomCharacterData* self, const NtsBorrowedString* data);
void nts_dom_CharacterData_deleteData(NtsDomCharacterData* self, double offset, double count, NtsDomException** error);
void nts_dom_CharacterData_insertData(NtsDomCharacterData* self, double offset, const NtsBorrowedString* data, NtsDomException** error);
void nts_dom_CharacterData_remove(NtsDomCharacterData* self, NtsDomException** error);
void nts_dom_CharacterData_replaceData(NtsDomCharacterData* self, double offset, double count, const NtsBorrowedString* data, NtsDomException** error);
const NtsStringView* nts_dom_CharacterData_substringData(NtsDomCharacterData* self, double offset, double count, NtsDomException** error);
NtsDomText* nts_dom_as_Text(NtsDomNode* node);
const NtsStringView* nts_dom_Text_get_wholeText(NtsDomText* self);
NtsDomText* nts_dom_Text_splitText(NtsDomText* self, double offset, NtsDomException** error);
NtsDomDocument* nts_dom_as_Document(NtsDomNode* node);
const NtsStringView* nts_dom_Document_get_URL(NtsDomDocument* self);
const NtsStringView* nts_dom_Document_get_documentURI(NtsDomDocument* self);
const NtsStringView* nts_dom_Document_get_compatMode(NtsDomDocument* self);
const NtsStringView* nts_dom_Document_get_characterSet(NtsDomDocument* self);
const NtsStringView* nts_dom_Document_get_charset(NtsDomDocument* self);
const NtsStringView* nts_dom_Document_get_inputEncoding(NtsDomDocument* self);
const NtsStringView* nts_dom_Document_get_contentType(NtsDomDocument* self);
NtsDomElement* nts_dom_Document_get_documentElement(NtsDomDocument* self);
const NtsStringView* nts_dom_Document_get_xmlEncoding(NtsDomDocument* self);
const NtsStringView* nts_dom_Document_get_xmlVersion(NtsDomDocument* self);
void nts_dom_Document_set_xmlVersion(NtsDomDocument* self, const NtsBorrowedString* value, NtsDomException** error);
bool nts_dom_Document_get_xmlStandalone(NtsDomDocument* self);
void nts_dom_Document_set_xmlStandalone(NtsDomDocument* self, bool value, NtsDomException** error);
const NtsStringView* nts_dom_Document_get_domain(NtsDomDocument* self);
void nts_dom_Document_set_domain(NtsDomDocument* self, const NtsBorrowedString* value, NtsDomException** error);
const NtsStringView* nts_dom_Document_get_referrer(NtsDomDocument* self);
const NtsStringView* nts_dom_Document_get_cookie(NtsDomDocument* self, NtsDomException** error);
void nts_dom_Document_set_cookie(NtsDomDocument* self, const NtsBorrowedString* value, NtsDomException** error);
const NtsStringView* nts_dom_Document_get_lastModified(NtsDomDocument* self);
const NtsStringView* nts_dom_Document_get_title(NtsDomDocument* self);
void nts_dom_Document_set_title(NtsDomDocument* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Document_get_dir(NtsDomDocument* self);
void nts_dom_Document_set_dir(NtsDomDocument* self, const NtsBorrowedString* value);
NtsDomHTMLElement* nts_dom_Document_get_body(NtsDomDocument* self);
void nts_dom_Document_set_body(NtsDomDocument* self, NtsDomHTMLElement* value, NtsDomException** error);
NtsDomHTMLCollection* nts_dom_Document_get_images(NtsDomDocument* self);
NtsDomHTMLCollection* nts_dom_Document_get_embeds(NtsDomDocument* self);
NtsDomHTMLCollection* nts_dom_Document_get_plugins(NtsDomDocument* self);
NtsDomHTMLCollection* nts_dom_Document_get_links(NtsDomDocument* self);
NtsDomHTMLCollection* nts_dom_Document_get_forms(NtsDomDocument* self);
NtsDomHTMLCollection* nts_dom_Document_get_scripts(NtsDomDocument* self);
const NtsStringView* nts_dom_Document_get_designMode(NtsDomDocument* self);
void nts_dom_Document_set_designMode(NtsDomDocument* self, const NtsBorrowedString* value);
NtsDomHTMLCollection* nts_dom_Document_get_anchors(NtsDomDocument* self);
NtsDomHTMLCollection* nts_dom_Document_get_applets(NtsDomDocument* self);
const NtsStringView* nts_dom_Document_get_fgColor(NtsDomDocument* self);
void nts_dom_Document_set_fgColor(NtsDomDocument* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Document_get_linkColor(NtsDomDocument* self);
void nts_dom_Document_set_linkColor(NtsDomDocument* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Document_get_vlinkColor(NtsDomDocument* self);
void nts_dom_Document_set_vlinkColor(NtsDomDocument* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Document_get_alinkColor(NtsDomDocument* self);
void nts_dom_Document_set_alinkColor(NtsDomDocument* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_Document_get_bgColor(NtsDomDocument* self);
void nts_dom_Document_set_bgColor(NtsDomDocument* self, const NtsBorrowedString* value);
NtsDomElement* nts_dom_Document_get_scrollingElement(NtsDomDocument* self);
bool nts_dom_Document_get_hidden(NtsDomDocument* self);
bool nts_dom_Document_get_wasDiscarded(NtsDomDocument* self);
bool nts_dom_Document_get_prerendering(NtsDomDocument* self);
const NtsStringView* nts_dom_Document_get_webkitVisibilityState(NtsDomDocument* self);
bool nts_dom_Document_get_webkitHidden(NtsDomDocument* self);
bool nts_dom_Document_get_fullscreenEnabled(NtsDomDocument* self);
bool nts_dom_Document_get_fullscreen(NtsDomDocument* self);
bool nts_dom_Document_get_webkitIsFullScreen(NtsDomDocument* self);
NtsDomElement* nts_dom_Document_get_webkitCurrentFullScreenElement(NtsDomDocument* self);
bool nts_dom_Document_get_webkitFullscreenEnabled(NtsDomDocument* self);
NtsDomElement* nts_dom_Document_get_webkitFullscreenElement(NtsDomDocument* self);
NtsDomHTMLCollection* nts_dom_Document_get_children(NtsDomDocument* self);
NtsDomElement* nts_dom_Document_get_firstElementChild(NtsDomDocument* self);
NtsDomElement* nts_dom_Document_get_lastElementChild(NtsDomDocument* self);
double nts_dom_Document_get_childElementCount(NtsDomDocument* self);
NtsDomElement* nts_dom_Document_get_activeElement(NtsDomDocument* self);
NtsDomElement* nts_dom_Document_get_pointerLockElement(NtsDomDocument* self);
NtsDomElement* nts_dom_Document_get_fullscreenElement(NtsDomDocument* self);
NtsDomElement* nts_dom_Document_get_pictureInPictureElement(NtsDomDocument* self);
NtsDomNode* nts_dom_Document_adoptNode(NtsDomDocument* self, NtsDomNode* node, NtsDomException** error);
void nts_dom_Document_captureEvents(NtsDomDocument* self);
void nts_dom_Document_clear(NtsDomDocument* self);
void nts_dom_Document_close(NtsDomDocument* self, NtsDomException** error);
NtsDomComment* nts_dom_Document_createComment(NtsDomDocument* self, const NtsBorrowedString* data);
NtsDomDocumentFragment* nts_dom_Document_createDocumentFragment(NtsDomDocument* self);
NtsDomElement* nts_dom_Document_createElement_1(NtsDomDocument* self, const NtsBorrowedString* localName, NtsDomException** error);
NtsDomElement* nts_dom_Document_createElement_2(NtsDomDocument* self, const NtsBorrowedString* localName, const NtsBorrowedString* options, NtsDomException** error);
NtsDomElement* nts_dom_Document_createElementNS_2(NtsDomDocument* self, const NtsBorrowedString* namespaceURI, const NtsBorrowedString* qualifiedName, NtsDomException** error);
NtsDomElement* nts_dom_Document_createElementNS_3(NtsDomDocument* self, const NtsBorrowedString* namespaceURI, const NtsBorrowedString* qualifiedName, const NtsBorrowedString* options, NtsDomException** error);
NtsDomNode* nts_dom_Document_createNSResolver(NtsDomDocument* self, NtsDomNode* nodeResolver);
NtsDomText* nts_dom_Document_createTextNode(NtsDomDocument* self, const NtsBorrowedString* data);
NtsDomElement* nts_dom_Document_elementFromPoint(NtsDomDocument* self, double x, double y, NtsDomException** error);
bool nts_dom_Document_execCommand(NtsDomDocument* self, const NtsBorrowedString* commandId, bool showUI, const NtsBorrowedString* value, NtsDomException** error);
void nts_dom_Document_exitPointerLock(NtsDomDocument* self);
NtsDomElement* nts_dom_Document_getElementById(NtsDomDocument* self, const NtsBorrowedString* elementId);
NtsDomHTMLCollection* nts_dom_Document_getElementsByClassName(NtsDomDocument* self, const NtsBorrowedString* classNames);
NtsDomNodeList* nts_dom_Document_getElementsByName(NtsDomDocument* self, const NtsBorrowedString* elementName);
NtsDomHTMLCollection* nts_dom_Document_getElementsByTagName(NtsDomDocument* self, const NtsBorrowedString* localName);
NtsDomHTMLCollection* nts_dom_Document_getElementsByTagNameNS(NtsDomDocument* self, const NtsBorrowedString* namespaceURI, const NtsBorrowedString* localName);
bool nts_dom_Document_hasFocus(NtsDomDocument* self);
NtsDomNode* nts_dom_Document_importNode(NtsDomDocument* self, NtsDomNode* node, NtsDomException** error);
void nts_dom_Document_moveBefore(NtsDomDocument* self, NtsDomNode* node, NtsDomNode* child, NtsDomException** error);
NtsDomDocument* nts_dom_Document_open_2(NtsDomDocument* self, const NtsBorrowedString* type, const NtsBorrowedString* replace, NtsDomException** error);
NtsDomDocument* nts_dom_Document_open_1(NtsDomDocument* self, const NtsBorrowedString* type, NtsDomException** error);
NtsDomDocument* nts_dom_Document_open_0(NtsDomDocument* self, NtsDomException** error);
bool nts_dom_Document_queryCommandEnabled(NtsDomDocument* self, const NtsBorrowedString* commandId, NtsDomException** error);
bool nts_dom_Document_queryCommandIndeterm(NtsDomDocument* self, const NtsBorrowedString* commandId, NtsDomException** error);
bool nts_dom_Document_queryCommandState(NtsDomDocument* self, const NtsBorrowedString* commandId, NtsDomException** error);
bool nts_dom_Document_queryCommandSupported(NtsDomDocument* self, const NtsBorrowedString* commandId, NtsDomException** error);
const NtsStringView* nts_dom_Document_queryCommandValue(NtsDomDocument* self, const NtsBorrowedString* commandId, NtsDomException** error);
NtsDomElement* nts_dom_Document_querySelector(NtsDomDocument* self, const NtsBorrowedString* selectors, NtsDomException** error);
NtsDomNodeList* nts_dom_Document_querySelectorAll(NtsDomDocument* self, const NtsBorrowedString* selectors, NtsDomException** error);
void nts_dom_Document_releaseEvents(NtsDomDocument* self);
void nts_dom_Document_webkitCancelFullScreen(NtsDomDocument* self);
void nts_dom_Document_webkitExitFullscreen(NtsDomDocument* self);
void nts_dom_Document_write_3(NtsDomDocument* self, const NtsBorrowedString* text1, const NtsBorrowedString* text2, const NtsBorrowedString* text3, NtsDomException** error);
void nts_dom_Document_write_2(NtsDomDocument* self, const NtsBorrowedString* text1, const NtsBorrowedString* text2, NtsDomException** error);
void nts_dom_Document_write_1(NtsDomDocument* self, const NtsBorrowedString* text1, NtsDomException** error);
void nts_dom_Document_writeln_3(NtsDomDocument* self, const NtsBorrowedString* text1, const NtsBorrowedString* text2, const NtsBorrowedString* text3, NtsDomException** error);
void nts_dom_Document_writeln_2(NtsDomDocument* self, const NtsBorrowedString* text1, const NtsBorrowedString* text2, NtsDomException** error);
void nts_dom_Document_writeln_1(NtsDomDocument* self, const NtsBorrowedString* text1, NtsDomException** error);
NtsDomDocumentFragment* nts_dom_as_DocumentFragment(NtsDomNode* node);
NtsDomHTMLCollection* nts_dom_DocumentFragment_get_children(NtsDomDocumentFragment* self);
NtsDomElement* nts_dom_DocumentFragment_get_firstElementChild(NtsDomDocumentFragment* self);
NtsDomElement* nts_dom_DocumentFragment_get_lastElementChild(NtsDomDocumentFragment* self);
double nts_dom_DocumentFragment_get_childElementCount(NtsDomDocumentFragment* self);
NtsDomElement* nts_dom_DocumentFragment_getElementById(NtsDomDocumentFragment* self, const NtsBorrowedString* elementId);
void nts_dom_DocumentFragment_moveBefore(NtsDomDocumentFragment* self, NtsDomNode* node, NtsDomNode* child, NtsDomException** error);
NtsDomElement* nts_dom_DocumentFragment_querySelector(NtsDomDocumentFragment* self, const NtsBorrowedString* selectors, NtsDomException** error);
NtsDomNodeList* nts_dom_DocumentFragment_querySelectorAll(NtsDomDocumentFragment* self, const NtsBorrowedString* selectors, NtsDomException** error);
NtsDomHTMLElement* nts_dom_as_HTMLElement(NtsDomNode* node);
const NtsStringView* nts_dom_HTMLElement_get_title(NtsDomHTMLElement* self);
void nts_dom_HTMLElement_set_title(NtsDomHTMLElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLElement_get_lang(NtsDomHTMLElement* self);
void nts_dom_HTMLElement_set_lang(NtsDomHTMLElement* self, const NtsBorrowedString* value);
bool nts_dom_HTMLElement_get_translate(NtsDomHTMLElement* self);
void nts_dom_HTMLElement_set_translate(NtsDomHTMLElement* self, bool value);
const NtsStringView* nts_dom_HTMLElement_get_dir(NtsDomHTMLElement* self);
void nts_dom_HTMLElement_set_dir(NtsDomHTMLElement* self, const NtsBorrowedString* value);
void nts_dom_HTMLElement_set_hidden(NtsDomHTMLElement* self, const NtsBorrowedString* value);
bool nts_dom_HTMLElement_get_inert(NtsDomHTMLElement* self);
void nts_dom_HTMLElement_set_inert(NtsDomHTMLElement* self, bool value);
const NtsStringView* nts_dom_HTMLElement_get_accessKey(NtsDomHTMLElement* self);
void nts_dom_HTMLElement_set_accessKey(NtsDomHTMLElement* self, const NtsBorrowedString* value);
bool nts_dom_HTMLElement_get_draggable(NtsDomHTMLElement* self);
void nts_dom_HTMLElement_set_draggable(NtsDomHTMLElement* self, bool value);
bool nts_dom_HTMLElement_get_spellcheck(NtsDomHTMLElement* self);
void nts_dom_HTMLElement_set_spellcheck(NtsDomHTMLElement* self, bool value);
const NtsStringView* nts_dom_HTMLElement_get_autocapitalize(NtsDomHTMLElement* self);
void nts_dom_HTMLElement_set_autocapitalize(NtsDomHTMLElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLElement_get_contentEditable(NtsDomHTMLElement* self);
void nts_dom_HTMLElement_set_contentEditable(NtsDomHTMLElement* self, const NtsBorrowedString* value, NtsDomException** error);
const NtsStringView* nts_dom_HTMLElement_get_enterKeyHint(NtsDomHTMLElement* self);
void nts_dom_HTMLElement_set_enterKeyHint(NtsDomHTMLElement* self, const NtsBorrowedString* value);
bool nts_dom_HTMLElement_get_isContentEditable(NtsDomHTMLElement* self);
const NtsStringView* nts_dom_HTMLElement_get_inputMode(NtsDomHTMLElement* self);
void nts_dom_HTMLElement_set_inputMode(NtsDomHTMLElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLElement_get_virtualKeyboardPolicy(NtsDomHTMLElement* self);
void nts_dom_HTMLElement_set_virtualKeyboardPolicy(NtsDomHTMLElement* self, const NtsBorrowedString* value);
NtsDomElement* nts_dom_HTMLElement_get_offsetParent(NtsDomHTMLElement* self);
double nts_dom_HTMLElement_get_offsetTop(NtsDomHTMLElement* self);
double nts_dom_HTMLElement_get_offsetLeft(NtsDomHTMLElement* self);
double nts_dom_HTMLElement_get_offsetWidth(NtsDomHTMLElement* self);
double nts_dom_HTMLElement_get_offsetHeight(NtsDomHTMLElement* self);
const NtsStringView* nts_dom_HTMLElement_get_popover(NtsDomHTMLElement* self);
void nts_dom_HTMLElement_set_popover(NtsDomHTMLElement* self, const NtsBorrowedString* value);
bool nts_dom_HTMLElement_get_unbounded(NtsDomHTMLElement* self);
void nts_dom_HTMLElement_set_unbounded(NtsDomHTMLElement* self, bool value);
const NtsStringView* nts_dom_HTMLElement_get_innerText(NtsDomHTMLElement* self);
void nts_dom_HTMLElement_set_innerText(NtsDomHTMLElement* self, const NtsBorrowedString* value, NtsDomException** error);
const NtsStringView* nts_dom_HTMLElement_get_outerText(NtsDomHTMLElement* self);
void nts_dom_HTMLElement_set_outerText(NtsDomHTMLElement* self, const NtsBorrowedString* value, NtsDomException** error);
const NtsStringView* nts_dom_HTMLElement_get_writingSuggestions(NtsDomHTMLElement* self);
void nts_dom_HTMLElement_set_writingSuggestions(NtsDomHTMLElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLElement_get_nonce(NtsDomHTMLElement* self);
void nts_dom_HTMLElement_set_nonce(NtsDomHTMLElement* self, const NtsBorrowedString* value);
bool nts_dom_HTMLElement_get_autofocus(NtsDomHTMLElement* self);
void nts_dom_HTMLElement_set_autofocus(NtsDomHTMLElement* self, bool value);
double nts_dom_HTMLElement_get_tabIndex(NtsDomHTMLElement* self);
void nts_dom_HTMLElement_set_tabIndex(NtsDomHTMLElement* self, double value);
NtsDomCSSStyleDeclaration* nts_dom_HTMLElement_get_style(NtsDomHTMLElement* self);
void nts_dom_HTMLElement_blur(NtsDomHTMLElement* self);
void nts_dom_HTMLElement_click(NtsDomHTMLElement* self);
void nts_dom_HTMLElement_hidePopover(NtsDomHTMLElement* self, NtsDomException** error);
void nts_dom_HTMLElement_showPopover(NtsDomHTMLElement* self, NtsDomException** error);
bool nts_dom_HTMLElement_togglePopover(NtsDomHTMLElement* self, NtsDomException** error);
NtsDomHTMLInputElement* nts_dom_as_HTMLInputElement(NtsDomNode* node);
const NtsStringView* nts_dom_HTMLInputElement_get_accept(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_accept(NtsDomHTMLInputElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLInputElement_get_alt(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_alt(NtsDomHTMLInputElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLInputElement_get_autocomplete(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_autocomplete(NtsDomHTMLInputElement* self, const NtsBorrowedString* value);
bool nts_dom_HTMLInputElement_get_defaultChecked(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_defaultChecked(NtsDomHTMLInputElement* self, bool value);
bool nts_dom_HTMLInputElement_get_checked(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_checked(NtsDomHTMLInputElement* self, bool value);
const NtsStringView* nts_dom_HTMLInputElement_get_dirName(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_dirName(NtsDomHTMLInputElement* self, const NtsBorrowedString* value);
bool nts_dom_HTMLInputElement_get_disabled(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_disabled(NtsDomHTMLInputElement* self, bool value);
NtsDomHTMLElement* nts_dom_HTMLInputElement_get_form(NtsDomHTMLInputElement* self);
const NtsStringView* nts_dom_HTMLInputElement_get_formAction(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_formAction(NtsDomHTMLInputElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLInputElement_get_formEnctype(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_formEnctype(NtsDomHTMLInputElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLInputElement_get_formMethod(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_formMethod(NtsDomHTMLInputElement* self, const NtsBorrowedString* value);
bool nts_dom_HTMLInputElement_get_formNoValidate(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_formNoValidate(NtsDomHTMLInputElement* self, bool value);
const NtsStringView* nts_dom_HTMLInputElement_get_formTarget(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_formTarget(NtsDomHTMLInputElement* self, const NtsBorrowedString* value);
double nts_dom_HTMLInputElement_get_height(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_height(NtsDomHTMLInputElement* self, double value);
bool nts_dom_HTMLInputElement_get_indeterminate(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_indeterminate(NtsDomHTMLInputElement* self, bool value);
NtsDomHTMLElement* nts_dom_HTMLInputElement_get_list(NtsDomHTMLInputElement* self);
const NtsStringView* nts_dom_HTMLInputElement_get_max(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_max(NtsDomHTMLInputElement* self, const NtsBorrowedString* value);
double nts_dom_HTMLInputElement_get_maxLength(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_maxLength(NtsDomHTMLInputElement* self, double value, NtsDomException** error);
const NtsStringView* nts_dom_HTMLInputElement_get_min(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_min(NtsDomHTMLInputElement* self, const NtsBorrowedString* value);
double nts_dom_HTMLInputElement_get_minLength(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_minLength(NtsDomHTMLInputElement* self, double value, NtsDomException** error);
bool nts_dom_HTMLInputElement_get_multiple(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_multiple(NtsDomHTMLInputElement* self, bool value);
const NtsStringView* nts_dom_HTMLInputElement_get_name(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_name(NtsDomHTMLInputElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLInputElement_get_pattern(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_pattern(NtsDomHTMLInputElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLInputElement_get_placeholder(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_placeholder(NtsDomHTMLInputElement* self, const NtsBorrowedString* value);
bool nts_dom_HTMLInputElement_get_readOnly(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_readOnly(NtsDomHTMLInputElement* self, bool value);
bool nts_dom_HTMLInputElement_get_required(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_required(NtsDomHTMLInputElement* self, bool value);
double nts_dom_HTMLInputElement_get_size(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_size(NtsDomHTMLInputElement* self, double value, NtsDomException** error);
const NtsStringView* nts_dom_HTMLInputElement_get_src(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_src(NtsDomHTMLInputElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLInputElement_get_step(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_step(NtsDomHTMLInputElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLInputElement_get_type(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_type(NtsDomHTMLInputElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLInputElement_get_defaultValue(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_defaultValue(NtsDomHTMLInputElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLInputElement_get_value(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_value(NtsDomHTMLInputElement* self, const NtsBorrowedString* value, NtsDomException** error);
double nts_dom_HTMLInputElement_get_valueAsNumber(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_valueAsNumber(NtsDomHTMLInputElement* self, double value, NtsDomException** error);
double nts_dom_HTMLInputElement_get_width(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_width(NtsDomHTMLInputElement* self, double value);
bool nts_dom_HTMLInputElement_get_willValidate(NtsDomHTMLInputElement* self);
const NtsStringView* nts_dom_HTMLInputElement_get_validationMessage(NtsDomHTMLInputElement* self);
NtsDomNodeList* nts_dom_HTMLInputElement_get_labels(NtsDomHTMLInputElement* self);
const NtsStringView* nts_dom_HTMLInputElement_get_selectionDirection(NtsDomHTMLInputElement* self, NtsDomException** error);
void nts_dom_HTMLInputElement_set_selectionDirection(NtsDomHTMLInputElement* self, const NtsBorrowedString* value, NtsDomException** error);
const NtsStringView* nts_dom_HTMLInputElement_get_align(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_align(NtsDomHTMLInputElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLInputElement_get_useMap(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_useMap(NtsDomHTMLInputElement* self, const NtsBorrowedString* value);
bool nts_dom_HTMLInputElement_get_webkitdirectory(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_webkitdirectory(NtsDomHTMLInputElement* self, bool value);
bool nts_dom_HTMLInputElement_get_incremental(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_incremental(NtsDomHTMLInputElement* self, bool value);
NtsDomElement* nts_dom_HTMLInputElement_get_popoverTargetElement(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_popoverTargetElement(NtsDomHTMLInputElement* self, NtsDomElement* value);
const NtsStringView* nts_dom_HTMLInputElement_get_popoverTargetAction(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_set_popoverTargetAction(NtsDomHTMLInputElement* self, const NtsBorrowedString* value);
bool nts_dom_HTMLInputElement_checkValidity(NtsDomHTMLInputElement* self);
bool nts_dom_HTMLInputElement_reportValidity(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_select(NtsDomHTMLInputElement* self);
void nts_dom_HTMLInputElement_setCustomValidity(NtsDomHTMLInputElement* self, const NtsBorrowedString* error_);
void nts_dom_HTMLInputElement_setRangeText(NtsDomHTMLInputElement* self, const NtsBorrowedString* replacement, NtsDomException** error);
void nts_dom_HTMLInputElement_setSelectionRange_3(NtsDomHTMLInputElement* self, double start, double end, const NtsBorrowedString* direction, NtsDomException** error);
void nts_dom_HTMLInputElement_setSelectionRange_2(NtsDomHTMLInputElement* self, double start, double end, NtsDomException** error);
void nts_dom_HTMLInputElement_showPicker(NtsDomHTMLInputElement* self, NtsDomException** error);
void nts_dom_HTMLInputElement_stepDown_1(NtsDomHTMLInputElement* self, double n, NtsDomException** error);
void nts_dom_HTMLInputElement_stepDown_0(NtsDomHTMLInputElement* self, NtsDomException** error);
void nts_dom_HTMLInputElement_stepUp_1(NtsDomHTMLInputElement* self, double n, NtsDomException** error);
void nts_dom_HTMLInputElement_stepUp_0(NtsDomHTMLInputElement* self, NtsDomException** error);
NtsDomHTMLButtonElement* nts_dom_as_HTMLButtonElement(NtsDomNode* node);
bool nts_dom_HTMLButtonElement_get_disabled(NtsDomHTMLButtonElement* self);
void nts_dom_HTMLButtonElement_set_disabled(NtsDomHTMLButtonElement* self, bool value);
NtsDomHTMLElement* nts_dom_HTMLButtonElement_get_form(NtsDomHTMLButtonElement* self);
const NtsStringView* nts_dom_HTMLButtonElement_get_formAction(NtsDomHTMLButtonElement* self);
void nts_dom_HTMLButtonElement_set_formAction(NtsDomHTMLButtonElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLButtonElement_get_formEnctype(NtsDomHTMLButtonElement* self);
void nts_dom_HTMLButtonElement_set_formEnctype(NtsDomHTMLButtonElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLButtonElement_get_formMethod(NtsDomHTMLButtonElement* self);
void nts_dom_HTMLButtonElement_set_formMethod(NtsDomHTMLButtonElement* self, const NtsBorrowedString* value);
bool nts_dom_HTMLButtonElement_get_formNoValidate(NtsDomHTMLButtonElement* self);
void nts_dom_HTMLButtonElement_set_formNoValidate(NtsDomHTMLButtonElement* self, bool value);
const NtsStringView* nts_dom_HTMLButtonElement_get_formTarget(NtsDomHTMLButtonElement* self);
void nts_dom_HTMLButtonElement_set_formTarget(NtsDomHTMLButtonElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLButtonElement_get_name(NtsDomHTMLButtonElement* self);
void nts_dom_HTMLButtonElement_set_name(NtsDomHTMLButtonElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLButtonElement_get_type(NtsDomHTMLButtonElement* self);
void nts_dom_HTMLButtonElement_set_type(NtsDomHTMLButtonElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLButtonElement_get_value(NtsDomHTMLButtonElement* self);
void nts_dom_HTMLButtonElement_set_value(NtsDomHTMLButtonElement* self, const NtsBorrowedString* value);
bool nts_dom_HTMLButtonElement_get_willValidate(NtsDomHTMLButtonElement* self);
const NtsStringView* nts_dom_HTMLButtonElement_get_validationMessage(NtsDomHTMLButtonElement* self);
NtsDomNodeList* nts_dom_HTMLButtonElement_get_labels(NtsDomHTMLButtonElement* self);
NtsDomElement* nts_dom_HTMLButtonElement_get_popoverTargetElement(NtsDomHTMLButtonElement* self);
void nts_dom_HTMLButtonElement_set_popoverTargetElement(NtsDomHTMLButtonElement* self, NtsDomElement* value);
const NtsStringView* nts_dom_HTMLButtonElement_get_popoverTargetAction(NtsDomHTMLButtonElement* self);
void nts_dom_HTMLButtonElement_set_popoverTargetAction(NtsDomHTMLButtonElement* self, const NtsBorrowedString* value);
NtsDomElement* nts_dom_HTMLButtonElement_get_commandForElement(NtsDomHTMLButtonElement* self);
void nts_dom_HTMLButtonElement_set_commandForElement(NtsDomHTMLButtonElement* self, NtsDomElement* value);
const NtsStringView* nts_dom_HTMLButtonElement_get_command(NtsDomHTMLButtonElement* self);
void nts_dom_HTMLButtonElement_set_command(NtsDomHTMLButtonElement* self, const NtsBorrowedString* value);
NtsDomElement* nts_dom_HTMLButtonElement_get_interestForElement(NtsDomHTMLButtonElement* self);
void nts_dom_HTMLButtonElement_set_interestForElement(NtsDomHTMLButtonElement* self, NtsDomElement* value);
bool nts_dom_HTMLButtonElement_checkValidity(NtsDomHTMLButtonElement* self);
bool nts_dom_HTMLButtonElement_reportValidity(NtsDomHTMLButtonElement* self);
void nts_dom_HTMLButtonElement_setCustomValidity(NtsDomHTMLButtonElement* self, const NtsBorrowedString* error_);
NtsDomHTMLAnchorElement* nts_dom_as_HTMLAnchorElement(NtsDomNode* node);
const NtsStringView* nts_dom_HTMLAnchorElement_get_download(NtsDomHTMLAnchorElement* self);
void nts_dom_HTMLAnchorElement_set_download(NtsDomHTMLAnchorElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLAnchorElement_get_ping(NtsDomHTMLAnchorElement* self);
void nts_dom_HTMLAnchorElement_set_ping(NtsDomHTMLAnchorElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLAnchorElement_get_rel(NtsDomHTMLAnchorElement* self);
void nts_dom_HTMLAnchorElement_set_rel(NtsDomHTMLAnchorElement* self, const NtsBorrowedString* value);
NtsDomDOMTokenList* nts_dom_HTMLAnchorElement_get_relList(NtsDomHTMLAnchorElement* self);
const NtsStringView* nts_dom_HTMLAnchorElement_get_referrerPolicy(NtsDomHTMLAnchorElement* self);
void nts_dom_HTMLAnchorElement_set_referrerPolicy(NtsDomHTMLAnchorElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLAnchorElement_get_text(NtsDomHTMLAnchorElement* self);
void nts_dom_HTMLAnchorElement_set_text(NtsDomHTMLAnchorElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLAnchorElement_get_coords(NtsDomHTMLAnchorElement* self);
void nts_dom_HTMLAnchorElement_set_coords(NtsDomHTMLAnchorElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLAnchorElement_get_charset(NtsDomHTMLAnchorElement* self);
void nts_dom_HTMLAnchorElement_set_charset(NtsDomHTMLAnchorElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLAnchorElement_get_name(NtsDomHTMLAnchorElement* self);
void nts_dom_HTMLAnchorElement_set_name(NtsDomHTMLAnchorElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLAnchorElement_get_rev(NtsDomHTMLAnchorElement* self);
void nts_dom_HTMLAnchorElement_set_rev(NtsDomHTMLAnchorElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLAnchorElement_get_shape(NtsDomHTMLAnchorElement* self);
void nts_dom_HTMLAnchorElement_set_shape(NtsDomHTMLAnchorElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLAnchorElement_get_attributionSrc(NtsDomHTMLAnchorElement* self);
void nts_dom_HTMLAnchorElement_set_attributionSrc(NtsDomHTMLAnchorElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLAnchorElement_get_target(NtsDomHTMLAnchorElement* self);
void nts_dom_HTMLAnchorElement_set_target(NtsDomHTMLAnchorElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLAnchorElement_get_href(NtsDomHTMLAnchorElement* self);
void nts_dom_HTMLAnchorElement_set_href(NtsDomHTMLAnchorElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLAnchorElement_get_origin(NtsDomHTMLAnchorElement* self);
const NtsStringView* nts_dom_HTMLAnchorElement_get_protocol(NtsDomHTMLAnchorElement* self);
void nts_dom_HTMLAnchorElement_set_protocol(NtsDomHTMLAnchorElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLAnchorElement_get_username(NtsDomHTMLAnchorElement* self);
void nts_dom_HTMLAnchorElement_set_username(NtsDomHTMLAnchorElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLAnchorElement_get_password(NtsDomHTMLAnchorElement* self);
void nts_dom_HTMLAnchorElement_set_password(NtsDomHTMLAnchorElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLAnchorElement_get_host(NtsDomHTMLAnchorElement* self);
void nts_dom_HTMLAnchorElement_set_host(NtsDomHTMLAnchorElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLAnchorElement_get_hostname(NtsDomHTMLAnchorElement* self);
void nts_dom_HTMLAnchorElement_set_hostname(NtsDomHTMLAnchorElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLAnchorElement_get_port(NtsDomHTMLAnchorElement* self);
void nts_dom_HTMLAnchorElement_set_port(NtsDomHTMLAnchorElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLAnchorElement_get_pathname(NtsDomHTMLAnchorElement* self);
void nts_dom_HTMLAnchorElement_set_pathname(NtsDomHTMLAnchorElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLAnchorElement_get_search(NtsDomHTMLAnchorElement* self);
void nts_dom_HTMLAnchorElement_set_search(NtsDomHTMLAnchorElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLAnchorElement_get_hash(NtsDomHTMLAnchorElement* self);
void nts_dom_HTMLAnchorElement_set_hash(NtsDomHTMLAnchorElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLAnchorElement_get_hreflang(NtsDomHTMLAnchorElement* self);
void nts_dom_HTMLAnchorElement_set_hreflang(NtsDomHTMLAnchorElement* self, const NtsBorrowedString* value);
const NtsStringView* nts_dom_HTMLAnchorElement_get_type(NtsDomHTMLAnchorElement* self);
void nts_dom_HTMLAnchorElement_set_type(NtsDomHTMLAnchorElement* self, const NtsBorrowedString* value);
NtsDomElement* nts_dom_HTMLAnchorElement_get_interestForElement(NtsDomHTMLAnchorElement* self);
void nts_dom_HTMLAnchorElement_set_interestForElement(NtsDomHTMLAnchorElement* self, NtsDomElement* value);
const NtsStringView* nts_dom_Event_get_type(NtsDomEvent* self);
NtsDomEventTarget* nts_dom_Event_get_target(NtsDomEvent* self);
NtsDomEventTarget* nts_dom_Event_get_currentTarget(NtsDomEvent* self);
double nts_dom_Event_get_eventPhase(NtsDomEvent* self);
bool nts_dom_Event_get_bubbles(NtsDomEvent* self);
bool nts_dom_Event_get_cancelable(NtsDomEvent* self);
bool nts_dom_Event_get_defaultPrevented(NtsDomEvent* self);
bool nts_dom_Event_get_composed(NtsDomEvent* self);
bool nts_dom_Event_get_isTrusted(NtsDomEvent* self);
NtsDomEventTarget* nts_dom_Event_get_srcElement(NtsDomEvent* self);
void nts_dom_Event_initEvent_3(NtsDomEvent* self, const NtsBorrowedString* type, bool bubbles, bool cancelable);
void nts_dom_Event_initEvent_2(NtsDomEvent* self, const NtsBorrowedString* type, bool bubbles);
void nts_dom_Event_initEvent_1(NtsDomEvent* self, const NtsBorrowedString* type);
void nts_dom_Event_preventDefault(NtsDomEvent* self);
void nts_dom_Event_stopImmediatePropagation(NtsDomEvent* self);
void nts_dom_Event_stopPropagation(NtsDomEvent* self);
NtsDomUIEvent* nts_dom_as_UIEvent(NtsDomEvent* event);
double nts_dom_UIEvent_get_detail(NtsDomUIEvent* self);
double nts_dom_UIEvent_get_which(NtsDomUIEvent* self);
bool nts_dom_UIEvent_get_isTrusted(NtsDomUIEvent* self);
void nts_dom_UIEvent_initUIEvent_3(NtsDomUIEvent* self, const NtsBorrowedString* type, bool bubbles, bool cancelable);
void nts_dom_UIEvent_initUIEvent_2(NtsDomUIEvent* self, const NtsBorrowedString* type, bool bubbles);
void nts_dom_UIEvent_initUIEvent_1(NtsDomUIEvent* self, const NtsBorrowedString* type);
NtsDomMouseEvent* nts_dom_as_MouseEvent(NtsDomEvent* event);
double nts_dom_MouseEvent_get_screenX(NtsDomMouseEvent* self);
double nts_dom_MouseEvent_get_screenY(NtsDomMouseEvent* self);
double nts_dom_MouseEvent_get_clientX(NtsDomMouseEvent* self);
double nts_dom_MouseEvent_get_clientY(NtsDomMouseEvent* self);
bool nts_dom_MouseEvent_get_ctrlKey(NtsDomMouseEvent* self);
bool nts_dom_MouseEvent_get_shiftKey(NtsDomMouseEvent* self);
bool nts_dom_MouseEvent_get_altKey(NtsDomMouseEvent* self);
bool nts_dom_MouseEvent_get_metaKey(NtsDomMouseEvent* self);
double nts_dom_MouseEvent_get_button(NtsDomMouseEvent* self);
double nts_dom_MouseEvent_get_buttons(NtsDomMouseEvent* self);
NtsDomEventTarget* nts_dom_MouseEvent_get_relatedTarget(NtsDomMouseEvent* self);
double nts_dom_MouseEvent_get_pageX(NtsDomMouseEvent* self);
double nts_dom_MouseEvent_get_pageY(NtsDomMouseEvent* self);
double nts_dom_MouseEvent_get_x(NtsDomMouseEvent* self);
double nts_dom_MouseEvent_get_y(NtsDomMouseEvent* self);
double nts_dom_MouseEvent_get_offsetX(NtsDomMouseEvent* self);
double nts_dom_MouseEvent_get_offsetY(NtsDomMouseEvent* self);
double nts_dom_MouseEvent_get_movementX(NtsDomMouseEvent* self);
double nts_dom_MouseEvent_get_movementY(NtsDomMouseEvent* self);
NtsDomNode* nts_dom_MouseEvent_get_fromElement(NtsDomMouseEvent* self);
NtsDomNode* nts_dom_MouseEvent_get_toElement(NtsDomMouseEvent* self);
double nts_dom_MouseEvent_get_layerX(NtsDomMouseEvent* self);
double nts_dom_MouseEvent_get_layerY(NtsDomMouseEvent* self);
bool nts_dom_MouseEvent_get_isTrusted(NtsDomMouseEvent* self);
bool nts_dom_MouseEvent_getModifierState(NtsDomMouseEvent* self, const NtsBorrowedString* keyArg);
NtsDomKeyboardEvent* nts_dom_as_KeyboardEvent(NtsDomEvent* event);
const NtsStringView* nts_dom_KeyboardEvent_get_key(NtsDomKeyboardEvent* self);
const NtsStringView* nts_dom_KeyboardEvent_get_code(NtsDomKeyboardEvent* self);
double nts_dom_KeyboardEvent_get_location(NtsDomKeyboardEvent* self);
bool nts_dom_KeyboardEvent_get_ctrlKey(NtsDomKeyboardEvent* self);
bool nts_dom_KeyboardEvent_get_shiftKey(NtsDomKeyboardEvent* self);
bool nts_dom_KeyboardEvent_get_altKey(NtsDomKeyboardEvent* self);
bool nts_dom_KeyboardEvent_get_metaKey(NtsDomKeyboardEvent* self);
bool nts_dom_KeyboardEvent_get_repeat(NtsDomKeyboardEvent* self);
bool nts_dom_KeyboardEvent_get_isComposing(NtsDomKeyboardEvent* self);
double nts_dom_KeyboardEvent_get_charCode(NtsDomKeyboardEvent* self);
double nts_dom_KeyboardEvent_get_keyCode(NtsDomKeyboardEvent* self);
bool nts_dom_KeyboardEvent_get_isTrusted(NtsDomKeyboardEvent* self);
bool nts_dom_KeyboardEvent_getModifierState(NtsDomKeyboardEvent* self, const NtsBorrowedString* keyArg);
double nts_dom_DOMTokenList_get_length(NtsDomDOMTokenList* self);
const NtsStringView* nts_dom_DOMTokenList_get_value(NtsDomDOMTokenList* self);
void nts_dom_DOMTokenList_set_value(NtsDomDOMTokenList* self, const NtsBorrowedString* value);
void nts_dom_DOMTokenList_add_3(NtsDomDOMTokenList* self, const NtsBorrowedString* tokens1, const NtsBorrowedString* tokens2, const NtsBorrowedString* tokens3, NtsDomException** error);
void nts_dom_DOMTokenList_add_2(NtsDomDOMTokenList* self, const NtsBorrowedString* tokens1, const NtsBorrowedString* tokens2, NtsDomException** error);
void nts_dom_DOMTokenList_add_1(NtsDomDOMTokenList* self, const NtsBorrowedString* tokens1, NtsDomException** error);
bool nts_dom_DOMTokenList_contains(NtsDomDOMTokenList* self, const NtsBorrowedString* token);
const NtsStringView* nts_dom_DOMTokenList_item(NtsDomDOMTokenList* self, double index);
void nts_dom_DOMTokenList_remove_3(NtsDomDOMTokenList* self, const NtsBorrowedString* tokens1, const NtsBorrowedString* tokens2, const NtsBorrowedString* tokens3, NtsDomException** error);
void nts_dom_DOMTokenList_remove_2(NtsDomDOMTokenList* self, const NtsBorrowedString* tokens1, const NtsBorrowedString* tokens2, NtsDomException** error);
void nts_dom_DOMTokenList_remove_1(NtsDomDOMTokenList* self, const NtsBorrowedString* tokens1, NtsDomException** error);
bool nts_dom_DOMTokenList_replace(NtsDomDOMTokenList* self, const NtsBorrowedString* token, const NtsBorrowedString* newToken, NtsDomException** error);
bool nts_dom_DOMTokenList_supports(NtsDomDOMTokenList* self, const NtsBorrowedString* token, NtsDomException** error);
bool nts_dom_DOMTokenList_toggle_2(NtsDomDOMTokenList* self, const NtsBorrowedString* token, bool force, NtsDomException** error);
bool nts_dom_DOMTokenList_toggle_1(NtsDomDOMTokenList* self, const NtsBorrowedString* token, NtsDomException** error);
const NtsStringView* nts_dom_CSSStyleDeclaration_get_cssText(NtsDomCSSStyleDeclaration* self);
void nts_dom_CSSStyleDeclaration_set_cssText(NtsDomCSSStyleDeclaration* self, const NtsBorrowedString* value, NtsDomException** error);
double nts_dom_CSSStyleDeclaration_get_length(NtsDomCSSStyleDeclaration* self);
const NtsStringView* nts_dom_CSSStyleDeclaration_get_cssFloat(NtsDomCSSStyleDeclaration* self);
void nts_dom_CSSStyleDeclaration_set_cssFloat(NtsDomCSSStyleDeclaration* self, const NtsBorrowedString* value, NtsDomException** error);
const NtsStringView* nts_dom_CSSStyleDeclaration_getPropertyPriority(NtsDomCSSStyleDeclaration* self, const NtsBorrowedString* property);
const NtsStringView* nts_dom_CSSStyleDeclaration_getPropertyValue(NtsDomCSSStyleDeclaration* self, const NtsBorrowedString* property);
const NtsStringView* nts_dom_CSSStyleDeclaration_item(NtsDomCSSStyleDeclaration* self, double index);
const NtsStringView* nts_dom_CSSStyleDeclaration_removeProperty(NtsDomCSSStyleDeclaration* self, const NtsBorrowedString* property, NtsDomException** error);
void nts_dom_CSSStyleDeclaration_setProperty_3(NtsDomCSSStyleDeclaration* self, const NtsBorrowedString* property, const NtsBorrowedString* value, const NtsBorrowedString* priority, NtsDomException** error);
void nts_dom_CSSStyleDeclaration_setProperty_2(NtsDomCSSStyleDeclaration* self, const NtsBorrowedString* property, const NtsBorrowedString* value, NtsDomException** error);
NtsDomComment* nts_dom_as_Comment(NtsDomNode* node);
double nts_dom_NodeList_get_length(NtsDomNodeList* self);
NtsDomNode* nts_dom_NodeList_item(NtsDomNodeList* self, double index);
double nts_dom_HTMLCollection_get_length(NtsDomHTMLCollection* self);
NtsDomElement* nts_dom_HTMLCollection_item(NtsDomHTMLCollection* self, double index);
NtsDomElement* nts_dom_HTMLCollection_namedItem(NtsDomHTMLCollection* self, const NtsBorrowedString* name);
double nts_dom_DOMRectReadOnly_get_x(NtsDomDOMRectReadOnly* self);
double nts_dom_DOMRectReadOnly_get_y(NtsDomDOMRectReadOnly* self);
double nts_dom_DOMRectReadOnly_get_width(NtsDomDOMRectReadOnly* self);
double nts_dom_DOMRectReadOnly_get_height(NtsDomDOMRectReadOnly* self);
double nts_dom_DOMRectReadOnly_get_top(NtsDomDOMRectReadOnly* self);
double nts_dom_DOMRectReadOnly_get_right(NtsDomDOMRectReadOnly* self);
double nts_dom_DOMRectReadOnly_get_bottom(NtsDomDOMRectReadOnly* self);
double nts_dom_DOMRectReadOnly_get_left(NtsDomDOMRectReadOnly* self);
NtsDomDOMRect* nts_dom_as_DOMRect(NtsDomDOMRectReadOnly* object);
double nts_dom_DOMRect_get_x(NtsDomDOMRect* self);
void nts_dom_DOMRect_set_x(NtsDomDOMRect* self, double value);
double nts_dom_DOMRect_get_y(NtsDomDOMRect* self);
void nts_dom_DOMRect_set_y(NtsDomDOMRect* self, double value);
double nts_dom_DOMRect_get_width(NtsDomDOMRect* self);
void nts_dom_DOMRect_set_width(NtsDomDOMRect* self, double value);
double nts_dom_DOMRect_get_height(NtsDomDOMRect* self);
void nts_dom_DOMRect_set_height(NtsDomDOMRect* self, double value);

#ifdef __cplusplus
}
#endif
#endif
