[package]
name = "nts-codegen-c"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
nts-diagnostics.workspace = true
nts-core.workspace = true
nts-memory-lowering.workspace = true
nts-debug-lowering.workspace = true

[lints]
workspace = true
